// Copyright (C) 2024-2026 Tristan Stoltz / Luminous Dynamics
// SPDX-License-Identifier: AGPL-3.0-or-later
// Commercial licensing: see COMMERCIAL_LICENSE.md at repository root
//! ZK proof generation for tax bracket membership.
//!
//! # Security Notice
//!
//! Production builds MUST use the `prover` feature for cryptographic guarantees.
//! Dev mode / simulation is ONLY for testing and provides NO security.
//!
//! # Usage
//!
//! ## Production (with `prover` feature):
//! ```rust,ignore
//! use mycelix_zk_tax::{ProductionTaxProver, Jurisdiction, FilingStatus};
//!
//! let prover = ProductionTaxProver::new()?;
//! let proof = prover.prove(85_000, Jurisdiction::US, FilingStatus::Single, 2024)?;
//! // Proof contains real RISC-0 cryptographic proof
//! ```
//!
//! ## Testing (with simulation):
//! ```rust,ignore
//! use mycelix_zk_tax::{SimulationTaxProver, Jurisdiction, FilingStatus};
//!
//! // WARNING: Simulation proofs have NO cryptographic guarantees!
//! let prover = SimulationTaxProver::new_for_testing();
//! let proof = prover.prove(85_000, Jurisdiction::US, FilingStatus::Single, 2024)?;
//! assert!(proof.is_simulation_proof()); // Always true for simulation
//! ```

use crate::brackets::{compute_commitment, find_bracket};
use crate::error::{Error, Result};
use crate::jurisdiction::{FilingStatus, Jurisdiction};
use crate::proof::TaxBracketProof;
use crate::types::{BracketCommitment, TaxBracketWitness, TaxYear};

// =============================================================================
// Simulation Proof Marker (FIND-002 fix)
// =============================================================================

/// Explicit marker for simulation proofs instead of magic bytes.
///
/// This replaces the insecure `[0xDE, 0xAD, 0xBE, 0xEF]` pattern.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct SimulationProofMarker {
    /// Version of the simulation marker format
    pub version: u8,
    /// Explicit warning that this is not a real proof
    pub warning: String,
    /// Timestamp when the simulation was generated
    pub generated_at_ms: u64,
}

impl SimulationProofMarker {
    /// Create a new simulation marker
    pub fn new() -> Self {
        Self {
            version: 1,
            warning: "SIMULATION_ONLY_NO_CRYPTOGRAPHIC_GUARANTEES".to_string(),
            generated_at_ms: std::time::SystemTime::now()
                .duration_since(std::time::UNIX_EPOCH)
                .map(|d| d.as_millis() as u64)
                .unwrap_or(0),
        }
    }

    /// Prefix bytes to identify simulation proofs: "SIMU" in ASCII
    const PREFIX: [u8; 4] = [0x53, 0x49, 0x4D, 0x55];

    /// Serialize the marker to bytes with identifiable prefix
    pub fn to_bytes(&self) -> Vec<u8> {
        let mut bytes = Self::PREFIX.to_vec();
        bytes.extend(bincode::serialize(self).unwrap_or_default());
        bytes
    }

    /// Check if bytes represent a simulation marker
    pub fn is_simulation_bytes(bytes: &[u8]) -> bool {
        // Check for new simulation marker prefix "SIMU"
        if bytes.len() >= 4 && bytes[0..4] == Self::PREFIX {
            return true;
        }
        // Also check for legacy DEADBEEF marker for backwards compatibility
        if bytes == [0xDE, 0xAD, 0xBE, 0xEF] {
            return true;
        }
        false
    }
}

impl Default for SimulationProofMarker {
    fn default() -> Self {
        Self::new()
    }
}

// =============================================================================
// Production Tax Prover (requires prover feature)
// =============================================================================

/// Production-grade tax bracket prover using RISC-0.
///
/// This prover generates real cryptographic proofs that provide
/// actual security guarantees. Requires the `prover` feature.
#[cfg(feature = "prover")]
pub struct ProductionTaxProver;

#[cfg(feature = "prover")]
impl ProductionTaxProver {
    /// Create a new production prover
    pub fn new() -> Result<Self> {
        Ok(Self)
    }

    /// Generate a real ZK proof of tax bracket membership
    pub fn prove(
        &self,
        income: u64,
        jurisdiction: Jurisdiction,
        filing_status: FilingStatus,
        tax_year: TaxYear,
    ) -> Result<TaxBracketProof> {
        let legacy_prover = TaxBracketProver::new();
        legacy_prover.prove(income, jurisdiction, filing_status, tax_year)
    }
}

// =============================================================================
// Simulation Tax Prover (for testing only)
// =============================================================================

/// Simulation prover for TESTING ONLY.
///
/// **SECURITY WARNING**: This prover provides NO cryptographic guarantees!
/// Proofs generated by this prover can be trivially forged.
/// Never use in production - only for development and testing.
pub struct SimulationTaxProver {
    _warning_logged: bool,
}

impl SimulationTaxProver {
    /// Create a simulation prover for testing.
    ///
    /// **WARNING**: Logs a security warning to stderr.
    pub fn new_for_testing() -> Self {
        // Log warning when simulation prover is created
        #[cfg(feature = "std")]
        eprintln!(
            "\n\x1b[1;33m========================================\x1b[0m\n\
             \x1b[1;33m[ZK_TAX_SECURITY_WARNING]\x1b[0m\n\
             Running in SIMULATION mode!\n\
             Proofs provide NO cryptographic guarantees.\n\
             Do NOT use in production.\n\
             \x1b[1;33m========================================\x1b[0m\n"
        );

        Self { _warning_logged: true }
    }

    /// Generate a SIMULATION proof (NO cryptographic guarantees!)
    pub fn prove(
        &self,
        income: u64,
        jurisdiction: Jurisdiction,
        filing_status: FilingStatus,
        tax_year: TaxYear,
    ) -> Result<TaxBracketProof> {
        let legacy_prover = TaxBracketProver::dev_mode();
        legacy_prover.prove(income, jurisdiction, filing_status, tax_year)
    }
}

// =============================================================================
// Legacy TaxBracketProver (kept for API compatibility)
// =============================================================================

/// Prover for generating tax bracket ZK proofs.
///
/// **Deprecated**: Use `ProductionTaxProver` or `SimulationTaxProver` instead.
///
/// # Example
///
/// ```rust,ignore
/// use mycelix_zk_tax::{TaxBracketProver, Jurisdiction, FilingStatus};
///
/// let prover = TaxBracketProver::new();
///
/// let proof = prover.prove(
///     85_000,                      // Private income
///     Jurisdiction::US,
///     FilingStatus::Single,
///     2024,
/// ).unwrap();
///
/// println!("Proved bracket: {}", proof.bracket_index);
/// ```
pub struct TaxBracketProver {
    /// Whether to use dev mode (faster but not cryptographically secure)
    dev_mode: bool,
}

impl Default for TaxBracketProver {
    fn default() -> Self {
        Self::new()
    }
}

impl TaxBracketProver {
    /// Create a new prover instance.
    pub fn new() -> Self {
        Self { dev_mode: false }
    }

    /// Create a prover in development mode (faster, not secure).
    ///
    /// **WARNING**: Use this for testing only - proofs are not cryptographically sound!
    pub fn dev_mode() -> Self {
        // Log warning when dev mode is used
        #[cfg(feature = "std")]
        eprintln!(
            "\x1b[1;33m[ZK_TAX_SECURITY_WARNING]\x1b[0m: Dev mode enabled - \
             proofs provide NO cryptographic guarantees!"
        );

        Self { dev_mode: true }
    }

    /// Check if running in dev mode.
    pub fn is_dev_mode(&self) -> bool {
        self.dev_mode
    }

    /// Generate a ZK proof of tax bracket membership.
    ///
    /// # Arguments
    ///
    /// * `income` - The private gross income (will NOT be revealed)
    /// * `jurisdiction` - Tax jurisdiction (US, UK, etc.)
    /// * `filing_status` - Filing status (Single, MFJ, etc.)
    /// * `tax_year` - Tax year (2024, 2025)
    ///
    /// # Returns
    ///
    /// A `TaxBracketProof` that can be verified by anyone without
    /// learning the actual income.
    pub fn prove(
        &self,
        income: u64,
        jurisdiction: Jurisdiction,
        filing_status: FilingStatus,
        tax_year: TaxYear,
    ) -> Result<TaxBracketProof> {
        // Validate inputs
        if !jurisdiction.is_valid_filing_status(filing_status) {
            let valid = jurisdiction.valid_filing_statuses();
            let valid_strs: Vec<&str> = valid.iter().map(|s| s.name()).collect();
            return Err(Error::invalid_filing_status(
                filing_status.name(),
                jurisdiction.name(),
                &valid_strs,
            ));
        }

        // Find the bracket for this income
        let bracket = find_bracket(income, jurisdiction, tax_year, filing_status)?;

        // Verify income is actually in the bracket
        if !bracket.contains(income) {
            return Err(Error::IncomeOutOfBounds {
                income,
                lower: bracket.lower,
                upper: bracket.upper,
            });
        }

        // Create the witness
        let witness = TaxBracketWitness {
            gross_income: income,
            bracket_lower: bracket.lower,
            bracket_upper: bracket.upper,
            tax_year,
            bracket_index: bracket.index,
            rate_bps: bracket.rate_bps,
        };

        // Generate the proof
        if self.dev_mode {
            self.prove_dev_mode(&witness, jurisdiction, filing_status)
        } else {
            self.prove_real(&witness, jurisdiction, filing_status)
        }
    }

    /// Generate proof in development mode (fast, not secure).
    ///
    /// **WARNING**: These proofs provide NO cryptographic guarantees!
    fn prove_dev_mode(
        &self,
        witness: &TaxBracketWitness,
        jurisdiction: Jurisdiction,
        filing_status: FilingStatus,
    ) -> Result<TaxBracketProof> {
        // In dev mode, we simulate the proof
        let commitment = compute_commitment(
            witness.bracket_lower,
            witness.bracket_upper,
            witness.tax_year,
        );

        // Use explicit simulation marker instead of magic DEADBEEF bytes (FIND-002 fix)
        let simulation_marker = SimulationProofMarker::new();
        let simulation_receipt = simulation_marker.to_bytes();

        // Image ID for simulation (all zeros with "SIMU" prefix for detection)
        let mut simulation_image_id = vec![0x53, 0x49, 0x4D, 0x55]; // "SIMU"
        simulation_image_id.extend(vec![0x00; 28]);

        Ok(TaxBracketProof {
            jurisdiction,
            filing_status,
            tax_year: witness.tax_year,
            bracket_index: witness.bracket_index,
            rate_bps: witness.rate_bps,
            bracket_lower: witness.bracket_lower,
            bracket_upper: witness.bracket_upper,
            commitment,
            receipt_bytes: simulation_receipt,
            image_id: simulation_image_id,
        })
    }

    /// Generate real ZK proof using Risc0.
    #[cfg(feature = "prover")]
    fn prove_real(
        &self,
        witness: &TaxBracketWitness,
        jurisdiction: Jurisdiction,
        filing_status: FilingStatus,
    ) -> Result<TaxBracketProof> {
        use risc0_zkvm::{default_prover, ExecutorEnv};
        use zk_tax_methods::{ZK_TAX_GUEST_ELF, ZK_TAX_GUEST_ID};

        // Create the guest input (must match guest's expected format)
        let guest_input = GuestInput {
            gross_income: witness.gross_income,
            bracket_lower: witness.bracket_lower,
            bracket_upper: witness.bracket_upper,
            tax_year: witness.tax_year,
            bracket_index: witness.bracket_index,
            rate_bps: witness.rate_bps,
        };

        // Build executor environment with the witness
        let env = ExecutorEnv::builder()
            .write(&guest_input)
            .map_err(|e| Error::proof_generation(format!("Failed to write input: {}", e)))?
            .build()
            .map_err(|e| Error::proof_generation(format!("Failed to build env: {}", e)))?;

        // Get the prover and generate proof
        let prover = default_prover();
        let prove_info = prover
            .prove(env, ZK_TAX_GUEST_ELF)
            .map_err(|e| Error::proof_generation(format!("Proving failed: {}", e)))?;

        let receipt = prove_info.receipt;

        // Decode the output from the journal
        let output: GuestOutput = receipt
            .journal
            .decode()
            .map_err(|e| Error::proof_generation(format!("Failed to decode output: {}", e)))?;

        // Verify the output is valid
        if !output.valid {
            return Err(Error::proof_generation_with_context(
                "Proof constraints not satisfied",
                "Tax bracket verification failed",
                "Check that the income falls within the specified bracket bounds",
            ));
        }

        // Serialize the receipt for storage
        let receipt_bytes = bincode::serialize(&receipt)
            .map_err(|e| Error::serialization(e.to_string()))?;

        let image_id_bytes = bincode::serialize(&ZK_TAX_GUEST_ID)
            .map_err(|e| Error::serialization(e.to_string()))?;

        // Convert commitment bytes to our type
        let commitment = BracketCommitment::from_bytes(output.commitment);

        Ok(TaxBracketProof {
            jurisdiction,
            filing_status,
            tax_year: witness.tax_year,
            bracket_index: output.bracket_index,
            rate_bps: output.rate_bps,
            bracket_lower: output.bracket_lower,
            bracket_upper: output.bracket_upper,
            commitment,
            receipt_bytes,
            image_id: image_id_bytes,
        })
    }

    /// Stub for when prover feature is not enabled.
    #[cfg(not(feature = "prover"))]
    fn prove_real(
        &self,
        _witness: &TaxBracketWitness,
        _jurisdiction: Jurisdiction,
        _filing_status: FilingStatus,
    ) -> Result<TaxBracketProof> {
        Err(Error::proof_generation_with_context(
            "Real proof generation requires the 'prover' feature",
            "The prover feature is not enabled in Cargo.toml",
            "Use TaxBracketProver::dev_mode() for testing, or enable the 'prover' feature",
        ))
    }
}

/// Guest input format (must match guest code).
#[derive(serde::Serialize, serde::Deserialize)]
struct GuestInput {
    gross_income: u64,
    bracket_lower: u64,
    bracket_upper: u64,
    tax_year: u32,
    bracket_index: u8,
    rate_bps: u16,
}

/// Guest output format (must match guest code).
#[derive(serde::Serialize, serde::Deserialize)]
struct GuestOutput {
    tax_year: u32,
    bracket_index: u8,
    rate_bps: u16,
    valid: bool,
    commitment: [u8; 32],
    bracket_lower: u64,
    bracket_upper: u64,
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_dev_mode_proof() {
        let prover = TaxBracketProver::dev_mode();
        assert!(prover.is_dev_mode());

        let proof = prover
            .prove(85_000, Jurisdiction::US, FilingStatus::Single, 2024)
            .unwrap();

        assert_eq!(proof.bracket_index, 2);
        assert_eq!(proof.rate_bps, 2200);
        assert_eq!(proof.jurisdiction, Jurisdiction::US);
    }

    #[test]
    fn test_invalid_filing_status() {
        let prover = TaxBracketProver::dev_mode();

        // UK doesn't support Head of Household
        let result = prover.prove(
            50_000,
            Jurisdiction::UK,
            FilingStatus::HeadOfHousehold,
            2024,
        );

        assert!(matches!(result, Err(Error::InvalidFilingStatus { .. })));
    }

    #[test]
    fn test_uk_proof() {
        let prover = TaxBracketProver::dev_mode();

        let proof = prover
            .prove(60_000, Jurisdiction::UK, FilingStatus::Single, 2024)
            .unwrap();

        // 60k GBP is in the higher rate bracket (40%)
        assert_eq!(proof.bracket_index, 2);
        assert_eq!(proof.rate_bps, 4000);
    }
}
