[package]
name = "comms"
version = "0.1.0"
edition = "2024"
description = "Emergency communications coordinator zome"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
hdk = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
comms_integrity = { path = "../integrity" }
