[package]
name = "publication"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "rlib"]
name = "publication"

[dependencies]
getrandom = { workspace = true }
getrandom_03 = { workspace = true }
holochain_serialized_bytes = { workspace = true }
hdk = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
publication_integrity = { path = "../integrity" }
