// Copyright (C) 2024-2026 Tristan Stoltz / Luminous Dynamics
// SPDX-License-Identifier: AGPL-3.0-or-later

//! Machine-checkable Reed-Solomon conventions and golden vectors.
//!
//! Reed-Solomon interoperability requires more than the field size and parity
//! count. The irreducible polynomial, primitive element, first consecutive
//! root, coefficient order, and systematic layout must all agree. This module
//! names every one of those choices and ships fixed vectors generated by an
//! independent reference implementation.

use std::fmt;

use crate::reed_solomon::{
    AES_FIELD_POLYNOMIAL, AES_PRIMITIVE_ELEMENT, ReedSolomonConfig,
};

/// Polynomial coefficient serialization order.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum CoefficientOrder {
    /// Highest-degree coefficient appears first.
    MostSignificantFirst,
}

/// Codeword payload/parity layout.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum CodewordLayout {
    /// The source message is followed by the parity remainder.
    SystematicMessageThenParity,
}

/// Complete public Reed-Solomon interoperability profile.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct ReedSolomonProfile {
    primitive_polynomial: u16,
    primitive_element: u8,
    first_root: u8,
    parity_symbols: usize,
    coefficient_order: CoefficientOrder,
    layout: CodewordLayout,
}

impl ReedSolomonProfile {
    /// Construct the profile implemented by this crate for `config`.
    #[must_use]
    pub const fn aes(config: ReedSolomonConfig) -> Self {
        Self {
            primitive_polynomial: AES_FIELD_POLYNOMIAL,
            primitive_element: config.primitive_element,
            first_root: config.first_root,
            parity_symbols: config.parity_symbols,
            coefficient_order: CoefficientOrder::MostSignificantFirst,
            layout: CodewordLayout::SystematicMessageThenParity,
        }
    }

    #[must_use]
    pub const fn primitive_polynomial(self) -> u16 {
        self.primitive_polynomial
    }

    #[must_use]
    pub const fn primitive_element(self) -> u8 {
        self.primitive_element
    }

    #[must_use]
    pub const fn first_root(self) -> u8 {
        self.first_root
    }

    #[must_use]
    pub const fn parity_symbols(self) -> usize {
        self.parity_symbols
    }

    #[must_use]
    pub const fn coefficient_order(self) -> CoefficientOrder {
        self.coefficient_order
    }

    #[must_use]
    pub const fn layout(self) -> CodewordLayout {
        self.layout
    }

    /// Convert the interoperability profile back into codec configuration.
    #[must_use]
    pub const fn config(self) -> ReedSolomonConfig {
        ReedSolomonConfig {
            parity_symbols: self.parity_symbols,
            primitive_element: self.primitive_element,
            first_root: self.first_root,
        }
    }

    /// Stable, explicit identifier suitable for evidence manifests.
    #[must_use]
    pub fn identifier(self) -> String {
        format!(
            "rs-gf256-p{:03x}-g{:02x}-fcr{:02x}-msb-systematic-nsym{}",
            self.primitive_polynomial,
            self.primitive_element,
            self.first_root,
            self.parity_symbols,
        )
    }
}

impl fmt::Display for ReedSolomonProfile {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(&self.identifier())
    }
}

/// Fixed interoperability fixture.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct ReedSolomonGoldenVector {
    pub name: &'static str,
    pub profile: ReedSolomonProfile,
    pub message: &'static [u8],
    pub generator: &'static [u8],
    pub codeword: &'static [u8],
}

const PROFILE_FCR0_NSYM4: ReedSolomonProfile = ReedSolomonProfile::aes(
    ReedSolomonConfig {
        parity_symbols: 4,
        primitive_element: AES_PRIMITIVE_ELEMENT,
        first_root: 0,
    },
);
const PROFILE_FCR0_NSYM8: ReedSolomonProfile = ReedSolomonProfile::aes(
    ReedSolomonConfig {
        parity_symbols: 8,
        primitive_element: AES_PRIMITIVE_ELEMENT,
        first_root: 0,
    },
);
const PROFILE_FCR1_NSYM8: ReedSolomonProfile = ReedSolomonProfile::aes(
    ReedSolomonConfig {
        parity_symbols: 8,
        primitive_element: AES_PRIMITIVE_ELEMENT,
        first_root: 1,
    },
);
const PROFILE_FCR17_NSYM12: ReedSolomonProfile = ReedSolomonProfile::aes(
    ReedSolomonConfig {
        parity_symbols: 12,
        primitive_element: AES_PRIMITIVE_ELEMENT,
        first_root: 17,
    },
);

/// Independent fixed vectors covering two parity widths and three root offsets.
pub const REED_SOLOMON_GOLDEN_VECTORS: &[ReedSolomonGoldenVector] = &[
    ReedSolomonGoldenVector {
        name: "rs-aes-fcr0-nsym4",
        profile: PROFILE_FCR0_NSYM4,
        message: &[0x12, 0x34, 0x56],
        generator: &[0x01, 0x08, 0x24, 0x78, 0x55],
        codeword: &[0x12, 0x34, 0x56, 0x33, 0xE0, 0xE4, 0x47],
    },
    ReedSolomonGoldenVector {
        name: "rs-aes-fcr0-nsym8",
        profile: PROFILE_FCR0_NSYM8,
        message: b"123456789",
        generator: &[0x01, 0x80, 0x0D, 0x45, 0x24, 0x91, 0xC7, 0xA5, 0x1E],
        codeword: &[
            0x31, 0x32, 0x33, 0x34, 0x35, 0x36, 0x37, 0x38, 0x39, 0x23, 0x53,
            0x53, 0x14, 0x9E, 0x61, 0x20, 0xD9,
        ],
    },
    ReedSolomonGoldenVector {
        name: "rs-aes-fcr1-nsym8",
        profile: PROFILE_FCR1_NSYM8,
        message: &[0x00, 0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08, 0x09],
        generator: &[0x01, 0x9B, 0x39, 0xDE, 0x52, 0xC6, 0x0F, 0x99, 0x37],
        codeword: &[
            0x00, 0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08, 0x09, 0x89,
            0x55, 0x84, 0x36, 0x6C, 0xB2, 0xE2, 0x9D,
        ],
    },
    ReedSolomonGoldenVector {
        name: "rs-aes-fcr17-nsym12",
        profile: PROFILE_FCR17_NSYM12,
        message: &[0xA5, 0x5A, 0x00, 0xFF, 0x11, 0x22, 0x33],
        generator: &[
            0x01, 0xEC, 0x28, 0xC9, 0x43, 0xE1, 0x91, 0xB2, 0xF7, 0x22, 0x05,
            0x98, 0x35,
        ],
        codeword: &[
            0xA5, 0x5A, 0x00, 0xFF, 0x11, 0x22, 0x33, 0x5C, 0x24, 0xA6, 0xBE,
            0x32, 0xD9, 0x37, 0x89, 0xEF, 0x9A, 0x21, 0x54,
        ],
    },
];

#[cfg(test)]
mod tests {
    use super::*;
    use crate::reed_solomon::ReedSolomon;

    #[test]
    fn profile_identifier_names_every_interoperability_choice() {
        assert_eq!(
            PROFILE_FCR0_NSYM4.identifier(),
            "rs-gf256-p11b-g03-fcr00-msb-systematic-nsym4"
        );
    }

    #[test]
    fn every_golden_vector_matches_encoder_generator_and_decoder() {
        for vector in REED_SOLOMON_GOLDEN_VECTORS {
            let codec = ReedSolomon::new(vector.profile.config()).unwrap();
            assert_eq!(codec.generator(), vector.generator, "{}", vector.name);
            assert_eq!(codec.encode(vector.message).unwrap(), vector.codeword, "{}", vector.name);
            assert!(codec.is_valid(vector.codeword).unwrap(), "{}", vector.name);

            let mut corrupted = vector.codeword.to_vec();
            corrupted[vector.codeword.len() / 2] ^= 0xA5;
            let decoded = codec.decode(&corrupted).unwrap();
            assert_eq!(decoded.message, vector.message, "{}", vector.name);
            assert_eq!(decoded.corrected_codeword, vector.codeword, "{}", vector.name);
        }
    }
}
