# Old Waterworks Asset Manifest
#
# This manifest tracks CC0/licensed assets for the Old Waterworks micro-slice.
# Place assets in the sibling directories and reference them here.

[assets]
# Assets
pump_texture = { path = "../materials/pump_rust.jpg", type = "texture" }
