[package]
name = "shelters"
version = "0.1.0"
edition = "2024"
description = "Emergency shelters coordinator zome"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
hdk = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
shelters_integrity = { path = "../integrity" }
