-- Auto-generated by symthaea-lean-bridge::fol_ext_bridge
-- SMT fragment: LIA
-- Mathlib tactic: omega
-- Requires `import Mathlib.Tactic` + a Lake project with Mathlib resolved.
-- See lean-proofs/phase2/README.md for setup.

import Mathlib.Tactic

theorem mathd_numbertheory_136 : (∀ n : ℕ, (((((123) * n) + (17)) = (39500)) → (n = (321)))) := by
  intro n
  try intros
  first
    | (rfl; done)
    | (norm_num; done)
    | (ring; done)
    | (omega; done)
    | (linarith; done)
    | (nlinarith [sq_nonneg n, mul_self_nonneg n, sq_nonneg (n - 1), sq_nonneg (n + 1)]; done)
    | (positivity; done)
    | (nlinarith [sq_nonneg n, mul_self_nonneg n, sq_nonneg (n - 10), sq_nonneg (n - 7), sq_nonneg (n - 5), sq_nonneg (n - 3), sq_nonneg (n - 1), sq_nonneg (n + 1), sq_nonneg (n + 3), sq_nonneg (n + 5), sq_nonneg (n + 7), sq_nonneg (n + 10)]; done)
    | (rcases lt_trichotomy _ _ with h | h | h <;> tauto; done)
    | (rcases le_total _ _ with h | h <;> first | linarith | tauto; done)
    | (tauto; done)
    | (polyrith; done)
