-- Auto-generated by symthaea-lean-bridge::fol_ext_bridge
-- SMT fragment: NIA
-- Mathlib tactic: omega_nat
-- Requires `import Mathlib.Tactic` + a Lake project with Mathlib resolved.
-- See lean-proofs/phase2/README.md for setup.

import Mathlib.Tactic

theorem mathd_numbertheory_48 : (∀ b : ℕ, (((0) < b) → ((((((3) * (b ^ 2)) + ((2) * b)) + (1)) = (57)) → (b = (4))))) := by
  intro b
  try intros
  first
    | (rfl; done)
    | (norm_num; done)
    | (ring; done)
    | (omega; done)
    | (linarith; done)
    | (nlinarith [sq_nonneg b, mul_self_nonneg b, sq_nonneg (b - 1), sq_nonneg (b + 1)]; done)
    | (positivity; done)
    | (nlinarith [sq_nonneg b, mul_self_nonneg b, sq_nonneg (b - 10), sq_nonneg (b - 7), sq_nonneg (b - 5), sq_nonneg (b - 3), sq_nonneg (b - 1), sq_nonneg (b + 1), sq_nonneg (b + 3), sq_nonneg (b + 5), sq_nonneg (b + 7), sq_nonneg (b + 10)]; done)
    | (rcases lt_trichotomy _ _ with h | h | h <;> tauto; done)
    | (rcases le_total _ _ with h | h <;> first | linarith | tauto; done)
    | (tauto; done)
    | (polyrith; done)
