-- Auto-generated by symthaea-lean-bridge::fol_ext_bridge
-- SMT fragment: QF_NRA
-- Mathlib tactic: nlinarith
-- Requires `import Mathlib.Tactic` + a Lake project with Mathlib resolved.
-- See lean-proofs/phase2/README.md for setup.

import Mathlib.Tactic

theorem mathd_algebra_462 : (((((1 : ℝ) / (2 : ℝ)) + ((1 : ℝ) / (3 : ℝ))) * (((1 : ℝ) / (2 : ℝ)) - ((1 : ℝ) / (3 : ℝ)))) = ((5 : ℝ) / (36 : ℝ))) := by
  try intros
  first
    | (rfl; done)
    | (norm_num; done)
    | (ring; done)
    | (omega; done)
    | (linarith; done)
    | (nlinarith [sq_nonneg _, mul_self_nonneg _]; done)
    | (positivity; done)
    | (nlinarith [sq_nonneg _, mul_self_nonneg _]; done)
    | (rcases lt_trichotomy _ _ with h | h | h <;> tauto; done)
    | (rcases le_total _ _ with h | h <;> first | linarith | tauto; done)
    | (tauto; done)
    | (polyrith; done)
