-- Auto-generated by symthaea-lean-bridge::fol_ext_bridge
-- SMT fragment: LRA
-- Mathlib tactic: linarith
-- Requires `import Mathlib.Tactic` + a Lake project with Mathlib resolved.
-- See lean-proofs/phase2/README.md for setup.

import Mathlib.Tactic

theorem mathd_algebra_388 : (∀ x : ℝ, (∀ y : ℝ, (∀ z : ℝ, ((((((3) * x) + ((4) * y)) - ((12) * z)) = (10)) → ((((((-2) * x) - ((3) * y)) + ((9) * z)) = (-4)) → (x = (14))))))) := by
  intro x y z
  try intros
  first
    | (rfl; done)
    | (norm_num; done)
    | (ring; done)
    | (omega; done)
    | (linarith; done)
    | (nlinarith [sq_nonneg x, mul_self_nonneg x, sq_nonneg (x - 1), sq_nonneg (x + 1), sq_nonneg y, mul_self_nonneg y, sq_nonneg (y - 1), sq_nonneg (y + 1), sq_nonneg z, mul_self_nonneg z, sq_nonneg (z - 1), sq_nonneg (z + 1), sq_nonneg (x - y), sq_nonneg (x + y), sq_nonneg (x - z), sq_nonneg (x + z), sq_nonneg (y - z), sq_nonneg (y + z)]; done)
    | (positivity; done)
    | (nlinarith [sq_nonneg x, mul_self_nonneg x, sq_nonneg (x - 10), sq_nonneg (x - 7), sq_nonneg (x - 5), sq_nonneg (x - 3), sq_nonneg (x - 1), sq_nonneg (x + 1), sq_nonneg (x + 3), sq_nonneg (x + 5), sq_nonneg (x + 7), sq_nonneg (x + 10), sq_nonneg y, mul_self_nonneg y, sq_nonneg (y - 10), sq_nonneg (y - 7), sq_nonneg (y - 5), sq_nonneg (y - 3), sq_nonneg (y - 1), sq_nonneg (y + 1), sq_nonneg (y + 3), sq_nonneg (y + 5), sq_nonneg (y + 7), sq_nonneg (y + 10), sq_nonneg z, mul_self_nonneg z, sq_nonneg (z - 10), sq_nonneg (z - 7), sq_nonneg (z - 5), sq_nonneg (z - 3), sq_nonneg (z - 1), sq_nonneg (z + 1), sq_nonneg (z + 3), sq_nonneg (z + 5), sq_nonneg (z + 7), sq_nonneg (z + 10), sq_nonneg (x - y), sq_nonneg (x + y), sq_nonneg (x - z), sq_nonneg (x + z), sq_nonneg (y - z), sq_nonneg (y + z)]; done)
    | (rcases lt_trichotomy x y with h | h | h <;> tauto; done)
    | (rcases le_total _ _ with h | h <;> first | linarith | tauto; done)
    | (tauto; done)
    | (polyrith; done)
