-- Auto-generated by symthaea-lean-bridge::fol_ext_bridge
-- SMT fragment: LRA
-- Mathlib tactic: linarith
-- Requires `import Mathlib.Tactic` + a Lake project with Mathlib resolved.
-- See lean-proofs/phase2/README.md for setup.

import Mathlib.Tactic

theorem mathd_algebra_359 : (∀ y : ℝ, ((((y + (6)) + y) = ((2) * (12))) → (y = (9)))) := by
  intro y
  try intros
  first
    | (rfl; done)
    | (norm_num; done)
    | (ring; done)
    | (omega; done)
    | (linarith; done)
    | (nlinarith [sq_nonneg y, mul_self_nonneg y, sq_nonneg (y - 1), sq_nonneg (y + 1)]; done)
    | (positivity; done)
    | (rcases lt_trichotomy _ _ with h | h | h <;> tauto; done)
    | (rcases le_total _ _ with h | h <;> first | linarith | tauto; done)
    | (tauto; done)
    | (polyrith; done)
