-- Auto-generated by symthaea-lean-bridge::fol_ext_bridge
-- SMT fragment: LRA
-- Mathlib tactic: linarith
-- Requires `import Mathlib.Tactic` + a Lake project with Mathlib resolved.
-- See lean-proofs/phase2/README.md for setup.

import Mathlib.Tactic

theorem mathd_algebra_51 : (∀ a : ℝ, (∀ b : ℝ, (((0) < a) → (((0) < b) → (((a + b) = (35)) → ((a = (((2 : ℝ) / (5 : ℝ)) * b)) → ((b - a) = (15)))))))) := by
  intro a b
  try intros
  first
    | (rfl; done)
    | (norm_num; done)
    | (ring; done)
    | (omega; done)
    | (linarith; done)
    | (nlinarith [sq_nonneg a, mul_self_nonneg a, sq_nonneg (a - 1), sq_nonneg (a + 1), sq_nonneg b, mul_self_nonneg b, sq_nonneg (b - 1), sq_nonneg (b + 1), sq_nonneg (a - b), sq_nonneg (a + b)]; done)
    | (positivity; done)
    | (nlinarith [sq_nonneg a, mul_self_nonneg a, sq_nonneg (a - 10), sq_nonneg (a - 7), sq_nonneg (a - 5), sq_nonneg (a - 3), sq_nonneg (a - 1), sq_nonneg (a + 1), sq_nonneg (a + 3), sq_nonneg (a + 5), sq_nonneg (a + 7), sq_nonneg (a + 10), sq_nonneg b, mul_self_nonneg b, sq_nonneg (b - 10), sq_nonneg (b - 7), sq_nonneg (b - 5), sq_nonneg (b - 3), sq_nonneg (b - 1), sq_nonneg (b + 1), sq_nonneg (b + 3), sq_nonneg (b + 5), sq_nonneg (b + 7), sq_nonneg (b + 10), sq_nonneg (a - b), sq_nonneg (a + b)]; done)
    | (rcases lt_trichotomy a b with h | h | h <;> tauto; done)
    | (rcases le_total _ _ with h | h <;> first | linarith | tauto; done)
    | (tauto; done)
    | (polyrith; done)
