// Copyright (C) 2024-2026 Tristan Stoltz / Luminous Dynamics
// SPDX-License-Identifier: AGPL-3.0-or-later
// Commercial licensing: see COMMERCIAL_LICENSE.md at repository root
//! RISC-0 Guest Methods
//!
//! This module exports the compiled guest ELF and image ID.
//! Generated by risc0_build::embed_methods() during build.

include!(concat!(env!("OUT_DIR"), "/methods.rs"));
