#![deny(unsafe_code)]
//! Price Oracle Integrity Zome
//!
//! On-chain community price discovery for the value anchor system.
//! Community members report real-world prices in TEND units;
//! the oracle computes trimmed-median consensus.
//!
//! Consciousness gating: Citizen+ tier required for reporting
//! (identity >= 0.25, reputation >= 0.1) to prevent sybil attacks.
//!
//! Design principle: The TEND ledger is zero-sum mutual credit and
//! must NOT be polluted with exchange-rate logic. This zome provides
//! an independent price signal that Observatory can optionally consume.

use hdi::prelude::*;

// =============================================================================
// CONSTANTS
// =============================================================================

/// Maximum basket items in a single definition
pub const MAX_BASKET_ITEMS: usize = 50;

/// Maximum reporters per consensus window
pub const MAX_REPORTERS_PER_WINDOW: usize = 200;

/// Consensus window duration (1 week in microseconds)
pub const CONSENSUS_WINDOW_US: i64 = 7 * 24 * 60 * 60 * 1_000_000;

/// Trim percentage for trimmed median (discard top/bottom 10%)
pub const TRIM_PERCENT: f64 = 0.10;

/// Volatility threshold for TEND limit escalation (20% weekly change)
pub const VOLATILITY_ESCALATION_THRESHOLD: f64 = 0.20;

/// Accuracy EMA smoothing factor (0.1 = ~10 reports to converge)
pub const ACCURACY_EMA_ALPHA: f64 = 0.1;

/// Initial accuracy score for new reporters (neutral, full weight)
pub const ACCURACY_INITIAL_SCORE: f64 = 1.0;

/// Minimum weight floor — prevents zero-influence reporters
pub const ACCURACY_MIN_WEIGHT: f64 = 0.05;

/// String length limits
const MAX_ITEM_NAME_LEN: usize = 128;
const MAX_EVIDENCE_LEN: usize = 512;
const MAX_DID_LEN: usize = 256;
const MAX_BASKET_NAME_LEN: usize = 128;

// =============================================================================
// ENTRY TYPES
// =============================================================================

/// A single price report from a community member.
///
/// Reports are anchored by item name for retrieval.
/// Consciousness gating ensures only Citizen+ tier (identity >= 0.25,
/// reputation >= 0.1) can submit — prevents sybil via identity +
/// reputation requirements.
#[hdk_entry_helper]
#[derive(Clone, PartialEq)]
pub struct PriceReport {
    /// Canonical item name (lowercase, e.g., "bread_750g")
    pub item: String,

    /// Price in TEND units (e.g., 0.15 = "15 minutes of labor")
    pub price_tend: f64,

    /// Evidence or source (e.g., "Pick n Pay Roodepoort, 2026-03-14")
    pub evidence: String,

    /// DID of the reporter
    pub reporter_did: String,

    /// When the price was observed
    pub observed_at: Timestamp,

    /// When the report was submitted
    pub reported_at: Timestamp,
}

/// Computed consensus price for an item.
///
/// Generated by `get_consensus_price()` — trimmed median of all
/// reports within the consensus window, discarding top/bottom 10%.
#[hdk_entry_helper]
#[derive(Clone, PartialEq)]
pub struct PriceConsensus {
    /// Canonical item name
    pub item: String,

    /// Trimmed median price in TEND
    pub median_price: f64,

    /// Number of reporters in this consensus
    pub reporter_count: u32,

    /// Standard deviation of reports (spread indicator)
    pub std_dev: f64,

    /// Start of the consensus window
    pub window_start: Timestamp,

    /// When this consensus was computed
    pub computed_at: Timestamp,
}

/// A basket definition — weighted set of items for composite index.
///
/// Represents "what does 1 TEND buy in this community?"
/// Coordinator computes a weighted index from consensus prices.
#[hdk_entry_helper]
#[derive(Clone, PartialEq)]
pub struct BasketDefinition {
    /// Basket name (e.g., "Roodepoort Essential Goods")
    pub name: String,

    /// Items in the basket with weights (must sum to ~1.0)
    pub items: Vec<BasketItemDef>,

    /// DID of the basket creator
    pub creator_did: String,

    /// When the basket was defined
    pub created_at: Timestamp,
}

/// A single item in a basket definition.
#[derive(Serialize, Deserialize, Debug, Clone, PartialEq)]
pub struct BasketItemDef {
    /// Canonical item name (must match PriceReport.item)
    pub item: String,

    /// Weight in the basket (0.0 - 1.0)
    pub weight: f64,
}

/// Per-reporter accuracy score, updated after each consensus round.
///
/// Tracks how close each reporter's submissions are to the eventual
/// consensus median. Accurate reporters gain influence; inaccurate
/// reporters lose it. Updated via EMA:
///   accuracy = (1 - alpha) * old + alpha * (1 - min(|delta|/median, 1))
#[hdk_entry_helper]
#[derive(Clone, PartialEq)]
pub struct ReporterAccuracy {
    /// DID of the reporter
    pub reporter_did: String,

    /// EMA accuracy score (0.0 - 1.0). New reporters start at 1.0.
    pub accuracy_score: f64,

    /// Number of consensus rounds this reporter has participated in
    pub report_count: u32,

    /// When this accuracy was last updated
    pub updated_at: Timestamp,
}

/// Volatility alert — emitted when basket index moves > threshold.
///
/// Used to trigger TEND limit escalation via cross-zome call to
/// tend/update_oracle_state.
#[hdk_entry_helper]
#[derive(Clone, PartialEq)]
pub struct VolatilityAlert {
    /// Basket name this alert refers to
    pub basket_name: String,

    /// Weekly percentage change (e.g., 0.25 = 25% increase)
    pub weekly_change: f64,

    /// Recommended TEND limit tier
    pub recommended_tier: String,

    /// When detected
    pub detected_at: Timestamp,
}

// =============================================================================
// ENTRY + LINK TYPE REGISTRATION
// =============================================================================

#[hdk_entry_types]
#[unit_enum(UnitEntryTypes)]
pub enum EntryTypes {
    PriceReport(PriceReport),
    PriceConsensus(PriceConsensus),
    BasketDefinition(BasketDefinition),
    VolatilityAlert(VolatilityAlert),
    ReporterAccuracy(ReporterAccuracy),
    Anchor(Anchor),
}

/// Anchor entry for DHT path-based lookups.
#[hdk_entry_helper]
#[derive(Clone, PartialEq)]
pub struct Anchor {
    pub anchor: String,
}

#[hdk_link_types]
pub enum LinkTypes {
    /// Item name anchor → PriceReport entries
    ItemToReports,
    /// Item name anchor → latest PriceConsensus
    ItemToConsensus,
    /// Basket anchor → BasketDefinition
    AnchorToBasket,
    /// Reporter DID → their PriceReport entries
    ReporterToReports,
    /// Global anchor → VolatilityAlert entries
    AnchorToAlerts,
    /// Reporter DID anchor → ReporterAccuracy entry
    ReporterToAccuracy,
    /// Generic anchor links
    AnchorLinks,
}

// =============================================================================
// VALIDATION
// =============================================================================

#[hdk_extern]
pub fn genesis_self_check(_data: GenesisSelfCheckData) -> ExternResult<ValidateCallbackResult> {
    Ok(ValidateCallbackResult::Valid)
}

#[hdk_extern]
pub fn validate(op: Op) -> ExternResult<ValidateCallbackResult> {
    match op.flattened::<EntryTypes, LinkTypes>()? {
        FlatOp::StoreEntry(store_entry) => match store_entry {
            OpEntry::CreateEntry { app_entry, .. } => match app_entry {
                EntryTypes::PriceReport(report) => validate_price_report(&report),
                EntryTypes::PriceConsensus(consensus) => validate_consensus(&consensus),
                EntryTypes::BasketDefinition(basket) => validate_basket(&basket),
                EntryTypes::VolatilityAlert(_) => Ok(ValidateCallbackResult::Valid),
                EntryTypes::ReporterAccuracy(acc) => validate_reporter_accuracy(&acc),
                EntryTypes::Anchor(_) => Ok(ValidateCallbackResult::Valid),
            },
            OpEntry::UpdateEntry { app_entry, .. } => match app_entry {
                // Price reports are immutable once submitted
                EntryTypes::PriceReport(_) => Ok(ValidateCallbackResult::Invalid(
                    "Price reports cannot be updated — submit a new report instead".into(),
                )),
                // Consensus entries are replaced, not updated
                EntryTypes::PriceConsensus(consensus) => validate_consensus(&consensus),
                // Baskets can be updated by creator
                EntryTypes::BasketDefinition(basket) => validate_basket(&basket),
                EntryTypes::VolatilityAlert(_) => Ok(ValidateCallbackResult::Valid),
                // Accuracy is mutable — updated after each consensus round
                EntryTypes::ReporterAccuracy(acc) => validate_reporter_accuracy(&acc),
                EntryTypes::Anchor(_) => Ok(ValidateCallbackResult::Invalid(
                    "Anchors cannot be updated".into(),
                )),
            },
            _ => Ok(ValidateCallbackResult::Valid),
        },
        FlatOp::RegisterCreateLink { .. } => Ok(ValidateCallbackResult::Valid),
        FlatOp::RegisterDeleteLink { .. } => Ok(ValidateCallbackResult::Valid),
        FlatOp::StoreRecord(_) => Ok(ValidateCallbackResult::Valid),
        FlatOp::RegisterAgentActivity(_) => Ok(ValidateCallbackResult::Valid),
        FlatOp::RegisterUpdate(_) => Ok(ValidateCallbackResult::Valid),
        FlatOp::RegisterDelete(_) => Ok(ValidateCallbackResult::Valid),
    }
}

fn validate_price_report(report: &PriceReport) -> ExternResult<ValidateCallbackResult> {
    if report.item.is_empty() || report.item.len() > MAX_ITEM_NAME_LEN {
        return Ok(ValidateCallbackResult::Invalid(
            format!("Item name must be 1-{MAX_ITEM_NAME_LEN} characters"),
        ));
    }
    if !report.price_tend.is_finite() || report.price_tend <= 0.0 {
        return Ok(ValidateCallbackResult::Invalid(
            "Price must be a positive finite number".into(),
        ));
    }
    if report.evidence.len() > MAX_EVIDENCE_LEN {
        return Ok(ValidateCallbackResult::Invalid(
            format!("Evidence must be <= {MAX_EVIDENCE_LEN} characters"),
        ));
    }
    if report.reporter_did.is_empty() || report.reporter_did.len() > MAX_DID_LEN {
        return Ok(ValidateCallbackResult::Invalid(
            "Reporter DID is invalid".into(),
        ));
    }
    Ok(ValidateCallbackResult::Valid)
}

fn validate_consensus(consensus: &PriceConsensus) -> ExternResult<ValidateCallbackResult> {
    if consensus.item.is_empty() || consensus.item.len() > MAX_ITEM_NAME_LEN {
        return Ok(ValidateCallbackResult::Invalid(
            "Item name is invalid".into(),
        ));
    }
    if !consensus.median_price.is_finite() || consensus.median_price <= 0.0 {
        return Ok(ValidateCallbackResult::Invalid(
            "Median price must be positive and finite".into(),
        ));
    }
    if consensus.reporter_count == 0 {
        return Ok(ValidateCallbackResult::Invalid(
            "Consensus requires at least 1 reporter".into(),
        ));
    }
    Ok(ValidateCallbackResult::Valid)
}

fn validate_basket(basket: &BasketDefinition) -> ExternResult<ValidateCallbackResult> {
    if basket.name.is_empty() || basket.name.len() > MAX_BASKET_NAME_LEN {
        return Ok(ValidateCallbackResult::Invalid(
            format!("Basket name must be 1-{MAX_BASKET_NAME_LEN} characters"),
        ));
    }
    if basket.items.is_empty() || basket.items.len() > MAX_BASKET_ITEMS {
        return Ok(ValidateCallbackResult::Invalid(
            format!("Basket must have 1-{MAX_BASKET_ITEMS} items"),
        ));
    }
    let total_weight: f64 = basket.items.iter().map(|i| i.weight).sum();
    if !total_weight.is_finite() || (total_weight - 1.0).abs() > 0.05 {
        return Ok(ValidateCallbackResult::Invalid(
            "Basket weights must sum to approximately 1.0 (±0.05)".into(),
        ));
    }
    for item in &basket.items {
        if item.item.is_empty() || item.item.len() > MAX_ITEM_NAME_LEN {
            return Ok(ValidateCallbackResult::Invalid(
                "Basket item name is invalid".into(),
            ));
        }
        if !item.weight.is_finite() || item.weight <= 0.0 || item.weight > 1.0 {
            return Ok(ValidateCallbackResult::Invalid(
                "Basket item weight must be in (0.0, 1.0]".into(),
            ));
        }
    }
    if basket.creator_did.is_empty() || basket.creator_did.len() > MAX_DID_LEN {
        return Ok(ValidateCallbackResult::Invalid(
            "Creator DID is invalid".into(),
        ));
    }
    Ok(ValidateCallbackResult::Valid)
}

fn validate_reporter_accuracy(acc: &ReporterAccuracy) -> ExternResult<ValidateCallbackResult> {
    if acc.reporter_did.is_empty() || acc.reporter_did.len() > MAX_DID_LEN {
        return Ok(ValidateCallbackResult::Invalid(
            "Reporter DID is invalid".into(),
        ));
    }
    if !acc.accuracy_score.is_finite() || acc.accuracy_score < 0.0 || acc.accuracy_score > 1.0 {
        return Ok(ValidateCallbackResult::Invalid(
            "Accuracy score must be a finite number in [0.0, 1.0]".into(),
        ));
    }
    Ok(ValidateCallbackResult::Valid)
}
