// Copyright (C) 2024-2026 Tristan Stoltz / Luminous Dynamics
// SPDX-License-Identifier: AGPL-3.0-or-later
// Commercial licensing: see COMMERCIAL_LICENSE.md at repository root
//! PoGQ Zome - Byzantine Detection with RISC Zero Proofs
//!
//! This zome integrates RISC Zero zkVM proofs for Proof-of-Gradient-Quality (PoGQ)
//! Byzantine detection in federated learning. It provides:
//!
//! 1. **Proof Publishing**: Nodes publish RISC Zero receipts proving correct PoGQ state transitions
//! 2. **Nonce Binding**: Cryptographic binding between proofs and gradients prevents replay attacks
//! 3. **Verification**: Receipt structure + provenance validation (full ZK verification external)
//! 4. **Sybil Weighting**: Quarantined nodes receive zero weight in aggregation
//!
//! **Architecture**: Adapted from Winterfell design for RISC Zero primary backend
//! **Security**: 127-bit (S128) or 191-bit (S192) conjectured security
//! **Provenance**: Blake3 hash commitment over build metadata
//!
//! ## Verification Strategy
//!
//! RISC Zero zkVM cannot compile to WASM (native dependencies). This zome implements:
//! - **Receipt Structure Verification**: Validates bincode-serialized Receipt format
//! - **Provenance Hash Verification**: Blake3 hash of gradient commitments
//! - **Journal Integrity**: Validates decision outputs (quarantine, EMA, rounds)
//! - **External ZK Verification**: Full STARK proof verification delegated to native service
//!
//! ## On-Chain vs Off-Chain Verification
//!
//! ### Verified On-Chain (in WASM)
//!
//! The following verifications are performed directly in this zome:
//!
//! 1. **Receipt Structure Validation**
//!    - Size bounds checking (MIN_RECEIPT_SIZE to MAX_RECEIPT_SIZE)
//!    - Bincode enum variant validation (Composite=0, Succinct=1, Fake=2)
//!    - Cryptographic commitment presence detection
//!    - Journal size estimation
//!
//! 2. **Blake3 Provenance Hash Verification**
//!    - Computes Blake3 hash of gradient data
//!    - Verifies hash matches the provenance claim in the proof entry
//!    - Ensures gradient-to-proof binding integrity
//!
//! 3. **Journal Integrity Validation**
//!    - Quarantine status is binary (0 or 1)
//!    - Round consistency (entry.round == journal.current_round)
//!    - EMA value within bounds (Q16.16 fixed-point)
//!    - Consecutive counter mutual exclusion
//!
//! 4. **Security Profile Validation**
//!    - Profile must be S128 (128) or S192 (192)
//!    - AIR revision non-zero when provenance enabled
//!
//! 5. **Nonce Validation**
//!    - Non-zero nonce requirement
//!    - Replay attack prevention via nonce registry
//!
//! ### Requires Off-Chain Verification (External Service)
//!
//! The following CANNOT be verified in WASM due to RISC Zero's native dependencies:
//!
//! 1. **Full STARK Proof Verification**
//!    - FRI polynomial commitment verification
//!    - Merkle proof validation
//!    - Constraint system satisfaction
//!
//! 2. **Method ID (Image ID) Verification**
//!    - Verify receipt was generated by expected zkVM guest program
//!    - Requires risc0-zkvm native library
//!
//! 3. **Journal Decoding**
//!    - Full deserialization of journal contents
//!    - Type-safe extraction of DecisionJournal fields
//!
//! ### Verification Flow
//!
//! ```text
//! Client                    PoGQ Zome                    External Verifier
//!   |                          |                              |
//!   |-- publish_pogq_proof --->|                              |
//!   |                          |-- validate structure         |
//!   |                          |-- check nonce freshness      |
//!   |                          |-- store in DHT               |
//!   |<-- EntryHash ------------|                              |
//!   |                          |                              |
//!   |-- publish_gradient ----->|                              |
//!   |                          |-- verify nonce binding       |
//!   |                          |-- Blake3 provenance check    |
//!   |<-- EntryHash ------------|                              |
//!   |                          |                              |
//!   |-- verify_pogq_proof ---->|                              |
//!   |                          |-- receipt structure check    |
//!   |                          |-- provenance verification    |
//!   |                          |-- journal integrity check    |
//!   |<-- VerificationStatus ---|                              |
//!   |    (PartiallyVerified)   |                              |
//!   |                          |                              |
//!   |-- request_external_verification ----------------------->|
//!   |                          |                              |-- full STARK verify
//!   |                          |                              |-- method ID check
//!   |<-- ExternalVerificationResponse ------------------------|
//!   |    (FullyVerified or Invalid)                           |
//! ```
//!
//! ## Entry Types
//!
//! - `PoGQProofEntry`: RISC Zero receipt + provenance + decision outputs
//! - `GradientEntry`: Gradient metadata linked to proof via nonce
//!
//! ## Zome Functions
//!
//! - `publish_pogq_proof`: Validate and publish RISC Zero receipt
//! - `verify_pogq_proof`: Receipt structure + journal verification (returns VerificationStatus)
//! - `verify_pogq_proof_with_gradient`: Full on-chain verification including Blake3 provenance
//! - `publish_gradient`: Bind gradient to proof (nonce validation)
//! - `get_round_gradients`: Fetch gradients with quarantine status
//! - `compute_sybil_weighted_aggregate`: Weight gradients by quarantine state

use hdk::prelude::*;
use hdk::hash_path::anchor::anchor;
use serde::{Deserialize, Serialize};

// ============================================================================
// Entry Types
// ============================================================================

/// PoGQ proof entry containing RISC Zero receipt and provenance
#[hdk_entry_helper]
#[derive(Clone, PartialEq)]
pub struct PoGQProofEntry {
    /// Node that generated this proof
    pub node_id: AgentPubKey,

    /// FL training round
    pub round: u64,

    /// Cryptographic nonce for gradient binding
    pub nonce: [u8; 32],

    /// RISC Zero receipt bytes (serialized Receipt object)
    /// Note: Larger than Winterfell proofs (~several MB vs ~221KB)
    pub receipt_bytes: Vec<u8>,

    /// Provenance hash from Blake3(rust_ver, git_commit, timestamp, profile_id, air_rev)
    /// [0,0,0,0] if provenance disabled
    pub prov_hash: [u64; 4],

    /// Security profile: 128 (S128) or 192 (S192)
    pub profile_id: u32,

    /// AIR schema revision (monotonic version)
    pub air_rev: u32,

    /// Decision outputs from DecisionJournal
    pub quarantine_out: u8,  // 0 = healthy, 1 = quarantined
    pub current_round: u64,
    pub ema_t_fp: u64,  // Fixed-point EMA (Q16.16)
    pub consec_viol_t: u32,
    pub consec_clear_t: u32,

    /// Timestamp of proof creation
    pub timestamp: Timestamp,
}

/// Nonce tracking entry to prevent replay attacks
#[hdk_entry_helper]
#[derive(Clone, PartialEq)]
pub struct NonceEntry {
    /// The nonce value (32 bytes)
    pub nonce: [u8; 32],

    /// When this nonce was used
    pub timestamp: Timestamp,

    /// Node that used this nonce
    pub node_id: AgentPubKey,

    /// Round in which this nonce was used
    pub round: u64,
}

/// Gradient entry linked to PoGQ proof
#[hdk_entry_helper]
#[derive(Clone, PartialEq)]
pub struct GradientEntry {
    /// Node that generated this gradient
    pub node_id: AgentPubKey,

    /// FL training round
    pub round: u64,

    /// Nonce - MUST match linked proof nonce (binding)
    pub nonce: [u8; 32],

    /// Hash of gradient tensor (commitment) - Blake3 hash bytes
    pub gradient_commitment: Vec<u8>,

    /// Hybrid quality score x_t used in PoGQ
    pub quality_score: f64,

    /// Link to PoGQProofEntry
    pub pogq_proof_hash: EntryHash,

    /// Timestamp
    pub timestamp: Timestamp,
}

// ============================================================================
// Result Types
// ============================================================================

/// Result of sybil-weighted aggregation
#[derive(Debug, Serialize, Deserialize)]
pub struct SybilWeightedResult {
    /// Aggregated gradient commitment (Blake3 hash bytes)
    pub aggregated_gradient_commitment: Vec<u8>,

    /// Total weight (number of healthy nodes)
    pub total_weight: f64,

    /// Number of quarantined nodes excluded
    pub num_quarantined: usize,

    /// Number of healthy nodes included
    pub num_healthy: usize,
}

/// Verification result (legacy - use VerificationStatus for new code)
#[derive(Debug, Serialize, Deserialize)]
pub struct VerificationResult {
    /// Whether receipt verified successfully
    pub valid: bool,

    /// Quarantine status from journal
    pub quarantine_out: u8,

    /// Provenance hash
    pub prov_hash: [u64; 4],

    /// Error message if verification failed
    pub error: Option<String>,
}

// ============================================================================
// Verification Status Enum
// ============================================================================
//
// This enum represents the verification state of a PoGQ proof, distinguishing
// between what can be verified on-chain (in WASM) and what requires external
// verification (full RISC Zero STARK proof).

/// Verification status for PoGQ proofs
///
/// Represents the level of verification achieved for a proof entry.
/// Full ZK verification is not possible in WASM, so proofs can only
/// reach `PartiallyVerified` status on-chain.
///
/// ## Status Meanings
///
/// - `FullyVerified`: All checks passed including full STARK verification.
///   **Note**: This status is NOT achievable in WASM - it can only be set
///   after external verification by a native RISC Zero verifier.
///
/// - `PartiallyVerified`: Receipt structure valid, provenance hash verified,
///   journal integrity confirmed. Ready for external STARK verification.
///   This is the maximum verification level achievable on-chain.
///
/// - `PendingExternal`: Basic structure valid but awaiting external ZK
///   verification. Use this when provenance cannot be verified (no gradient).
///
/// - `Invalid`: Verification failed with a specific reason. The proof should
///   be rejected and the node potentially flagged for malicious behavior.
///
/// ## Example Usage
///
/// ```rust,ignore
/// let status = verify_pogq_proof(proof_hash)?;
/// match status.status {
///     VerificationStatus::PartiallyVerified => {
///         // Safe to use for aggregation, but schedule external verification
///         schedule_external_verification(proof_hash);
///     }
///     VerificationStatus::Invalid(reason) => {
///         // Reject the proof
///         flag_node_as_suspicious(status.node_id);
///     }
///     _ => {}
/// }
/// ```
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub enum VerificationStatus {
    /// All checks passed including full STARK proof verification.
    /// **NOT achievable in WASM** - requires external native verifier.
    ///
    /// This status indicates:
    /// - Receipt structure valid
    /// - Provenance hash verified (Blake3)
    /// - Journal integrity confirmed
    /// - Full STARK proof verified by external service
    /// - Method ID (image ID) matches expected zkVM guest
    FullyVerified,

    /// Structure and provenance verified on-chain.
    /// Maximum verification level achievable in WASM.
    ///
    /// This status indicates:
    /// - Receipt structure valid (bincode format, variant, commitments)
    /// - Provenance hash verified against gradient data (Blake3)
    /// - Journal integrity confirmed (quarantine, EMA, rounds, counters)
    /// - Security profile valid (S128 or S192)
    /// - Nonce is non-zero
    ///
    /// **Still requires**: External STARK proof verification
    PartiallyVerified,

    /// Needs off-chain ZK verification by external service.
    /// Basic structure checks passed but provenance not verified.
    ///
    /// This status indicates:
    /// - Receipt structure valid
    /// - Journal integrity confirmed
    /// - Provenance could not be verified (no gradient data provided)
    ///
    /// **Still requires**: Blake3 provenance verification + STARK verification
    PendingExternal,

    /// Failed verification with specific reason.
    /// The proof should be rejected.
    ///
    /// Common failure reasons:
    /// - "Receipt too small/large"
    /// - "Invalid receipt variant"
    /// - "Missing cryptographic commitments"
    /// - "Provenance hash mismatch"
    /// - "Journal integrity failure"
    /// - "Invalid security profile"
    Invalid(String),
}

impl VerificationStatus {
    /// Returns true if the proof is at least partially verified
    pub fn is_usable(&self) -> bool {
        matches!(self, VerificationStatus::FullyVerified | VerificationStatus::PartiallyVerified)
    }

    /// Returns true if the proof needs external verification
    pub fn needs_external(&self) -> bool {
        matches!(self, VerificationStatus::PartiallyVerified | VerificationStatus::PendingExternal)
    }

    /// Returns true if the proof is invalid
    pub fn is_invalid(&self) -> bool {
        matches!(self, VerificationStatus::Invalid(_))
    }

    /// Get the error message if invalid
    pub fn error_message(&self) -> Option<&str> {
        match self {
            VerificationStatus::Invalid(msg) => Some(msg),
            _ => None,
        }
    }
}

/// Comprehensive verification result with status enum
///
/// This is the new return type for `verify_pogq_proof()`, providing
/// detailed verification status and metadata.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct VerificationStatusResult {
    /// The verification status
    pub status: VerificationStatus,

    /// Quarantine status from journal (0=healthy, 1=quarantined)
    pub quarantine_out: u8,

    /// Provenance hash from the proof entry
    pub prov_hash: [u64; 4],

    /// Receipt structure verification details
    pub receipt_details: ReceiptVerificationResult,

    /// Whether provenance was verified with Blake3
    pub provenance_verified: bool,

    /// List of checks that passed
    pub passed_checks: Vec<String>,

    /// List of checks that failed (if any)
    pub failed_checks: Vec<String>,

    /// Recommendations for next steps
    pub recommendations: Vec<String>,
}

// ============================================================================
// Entry and Link Type Declarations (HDK 0.4 requirement)
// ============================================================================

/// Entry types for the zome
#[hdk_entry_types]
#[unit_enum(UnitEntryTypes)]
pub enum EntryTypes {
    PoGQProofEntry(PoGQProofEntry),
    NonceEntry(NonceEntry),
    GradientEntry(GradientEntry),
}

/// Link types for the zome
#[hdk_link_types]
pub enum LinkTypes {
    ProofToRound,
    GradientToRound,
    GradientToProof,
    NonceToRegistry,
}

// ============================================================================
// Validation Callbacks (Integrity Zome)
// ============================================================================
//
// These callbacks run on all nodes receiving the entry, providing
// network-wide validation of proof entries.

/// Validate PoGQProofEntry before accepting into DHT
///
/// This runs on all nodes that receive the entry, ensuring:
/// 1. Receipt is non-empty and structurally valid
/// 2. Security profile is valid (S128 or S192)
/// 3. Quarantine status is binary
/// 4. Round consistency
/// 5. Nonce is non-zero
pub fn validate_pogq_proof_entry(entry: &PoGQProofEntry) -> Result<(), String> {
    // 1. Receipt validation
    if entry.receipt_bytes.is_empty() {
        return Err("Receipt bytes cannot be empty".to_string());
    }

    if entry.receipt_bytes.len() < MIN_RECEIPT_SIZE {
        return Err(format!(
            "Receipt too small: {} bytes (minimum: {})",
            entry.receipt_bytes.len(),
            MIN_RECEIPT_SIZE
        ));
    }

    if entry.receipt_bytes.len() > MAX_RECEIPT_SIZE {
        return Err(format!(
            "Receipt too large: {} bytes (maximum: {})",
            entry.receipt_bytes.len(),
            MAX_RECEIPT_SIZE
        ));
    }

    // Validate receipt structure (bincode format)
    let receipt_check = verify_receipt_structure(&entry.receipt_bytes);
    if !receipt_check.structure_valid {
        return Err(format!(
            "Invalid receipt structure: {}",
            receipt_check.error.unwrap_or_else(|| "Unknown".to_string())
        ));
    }

    // 2. Security profile validation
    if entry.profile_id != 128 && entry.profile_id != 192 {
        return Err(format!(
            "Invalid security profile: {}. Must be 128 (S128) or 192 (S192)",
            entry.profile_id
        ));
    }

    // 3. Quarantine status validation
    if entry.quarantine_out > 1 {
        return Err(format!(
            "Invalid quarantine status: {}. Must be 0 or 1",
            entry.quarantine_out
        ));
    }

    // 4. Round consistency
    if entry.round != entry.current_round {
        return Err(format!(
            "Round mismatch: round={} != current_round={}",
            entry.round, entry.current_round
        ));
    }

    // 5. Nonce validation
    if entry.nonce == [0u8; 32] {
        return Err("Nonce cannot be all zeros".to_string());
    }

    // 6. EMA validation
    if entry.ema_t_fp > 10 * 65536 {
        return Err(format!(
            "EMA value out of range: {} (max: {})",
            entry.ema_t_fp, 10 * 65536
        ));
    }

    // 7. Consecutive counters mutual exclusion
    if entry.consec_viol_t > 0 && entry.consec_clear_t > 0 {
        return Err(format!(
            "Invalid state: both consec_viol_t ({}) and consec_clear_t ({}) are non-zero",
            entry.consec_viol_t, entry.consec_clear_t
        ));
    }

    // 8. Provenance validation (structural)
    let prov_is_zero = entry.prov_hash == [0, 0, 0, 0];
    if !prov_is_zero {
        // Check entropy
        if entry.prov_hash.iter().all(|&v| v == entry.prov_hash[0]) {
            return Err("Provenance hash lacks entropy".to_string());
        }

        // AIR revision must be non-zero with provenance enabled
        if entry.air_rev == 0 {
            return Err("AIR revision cannot be zero with enabled provenance".to_string());
        }
    }

    // In release mode, provenance must be enabled
    #[cfg(not(debug_assertions))]
    if prov_is_zero {
        return Err("Zero provenance hash not allowed in production".to_string());
    }

    Ok(())
}

/// Validate GradientEntry before accepting into DHT
pub fn validate_gradient_entry(entry: &GradientEntry) -> Result<(), String> {
    // Gradient commitment must be exactly 32 bytes (Blake3 hash)
    if entry.gradient_commitment.len() != 32 {
        return Err(format!(
            "Invalid gradient commitment size: {} (expected 32 bytes)",
            entry.gradient_commitment.len()
        ));
    }

    // Nonce cannot be all zeros
    if entry.nonce == [0u8; 32] {
        return Err("Gradient nonce cannot be all zeros".to_string());
    }

    // Quality score must be in valid range [0.0, 1.0]
    if entry.quality_score < 0.0 || entry.quality_score > 1.0 {
        return Err(format!(
            "Quality score out of range: {} (must be 0.0-1.0)",
            entry.quality_score
        ));
    }

    Ok(())
}

/// Validate NonceEntry before accepting into DHT
pub fn validate_nonce_entry(entry: &NonceEntry) -> Result<(), String> {
    // Nonce cannot be all zeros
    if entry.nonce == [0u8; 32] {
        return Err("Nonce cannot be all zeros".to_string());
    }

    Ok(())
}

// ============================================================================
// Zome Functions
// ============================================================================

/// Publish PoGQ proof (RISC Zero receipt)
///
/// Validates:
/// 1. Entry structural validation (receipt, profile, journal integrity)
/// 2. Nonce is fresh (not used before)
/// 3. Round matches or advances current round
/// 4. Node hasn't already published for this round
#[hdk_extern]
pub fn publish_pogq_proof(entry: PoGQProofEntry) -> ExternResult<EntryHash> {
    // =========================================================================
    // Stage 1: Entry Validation
    // =========================================================================
    // Run comprehensive validation on the proof entry
    validate_pogq_proof_entry(&entry)
        .map_err(|e| wasm_error!(WasmErrorInner::Guest(e)))?;

    // =========================================================================
    // Stage 2: Nonce Freshness Check
    // =========================================================================
    // Prevent replay attacks by checking nonce hasn't been used
    if is_nonce_used(&entry.nonce)? {
        return Err(wasm_error!(WasmErrorInner::Guest(
            "Nonce has already been used - replay attack prevented".into()
        )));
    }

    // =========================================================================
    // Stage 3: Round Advancement Validation
    // =========================================================================
    // Ensure the proof round is valid (current round or next round only)
    let current_round = get_current_round()?;

    // The new proof's round must be:
    // - Equal to current round (multiple proofs per round allowed)
    // - One greater than current round (advancing to next round)
    // We don't allow skipping rounds or submitting for past rounds
    if entry.round < current_round {
        return Err(wasm_error!(WasmErrorInner::Guest(
            format!(
                "Cannot submit proof for past round: submitted round {} but current round is {}",
                entry.round, current_round
            )
        )));
    }

    if entry.round > current_round + 1 {
        return Err(wasm_error!(WasmErrorInner::Guest(
            format!(
                "Cannot skip rounds: submitted round {} but current round is {} (max allowed: {})",
                entry.round, current_round, current_round + 1
            )
        )));
    }

    // =========================================================================
    // Stage 4: Check Node Hasn't Published This Round
    // =========================================================================
    // Prevent duplicate submissions by the same node for the same round
    if has_node_published_round(&entry.node_id, entry.round)? {
        return Err(wasm_error!(WasmErrorInner::Guest(
            format!(
                "Node {} has already published a proof for round {}",
                entry.node_id, entry.round
            )
        )));
    }

    // Create entry in DHT with EntryTypes wrapper
    create_entry(EntryTypes::PoGQProofEntry(entry.clone()))?;
    let proof_hash = hash_entry(&entry)?;

    // Create anchor for round-based discovery
    let round_anchor = anchor(
        LinkTypes::ProofToRound,
        "pogq_proofs".to_string(),
        format!("round_{}", entry.round),
    )?;

    // Link round to proof
    create_link(
        round_anchor,
        proof_hash.clone(),
        LinkTypes::ProofToRound,
        (),
    )?;

    // ✅ RECORD NONCE - Mark as used to prevent future replay
    let nonce_entry = NonceEntry {
        nonce: entry.nonce,
        timestamp: entry.timestamp,
        node_id: entry.node_id.clone(),
        round: entry.round,
    };
    record_nonce(nonce_entry)?;

    // ✅ RECORD NODE-ROUND - Track that this node has published for this round
    record_node_round(&entry.node_id, entry.round, &proof_hash)?;

    Ok(proof_hash)
}

/// Verify PoGQ proof with receipt structure and provenance validation
///
/// This performs comprehensive verification including:
/// 1. **Receipt Structure**: Validates RISC Zero receipt format (bincode structure)
/// 2. **Provenance Hash**: Validates Blake3 provenance commitment (structural)
/// 3. **Journal Integrity**: Validates decision outputs (quarantine, EMA, rounds)
/// 4. **Security Profile**: Validates S128 or S192 configuration
///
/// **IMPORTANT**: Full STARK proof verification requires external service.
/// RISC Zero zkVM cannot compile to WASM (native system dependencies).
///
/// Returns `VerificationStatusResult` with detailed status and metadata.
/// Without gradient data, returns `PendingExternal` status.
/// Use `verify_pogq_proof_with_gradient()` for full on-chain verification.
#[hdk_extern]
pub fn verify_pogq_proof(proof_hash: EntryHash) -> ExternResult<VerificationStatusResult> {
    // Fetch proof entry
    let maybe_record = get(proof_hash.clone(), GetOptions::default())?;
    let record = maybe_record
        .ok_or(wasm_error!(WasmErrorInner::Guest("Proof not found".into())))?;

    let entry: PoGQProofEntry = record
        .entry()
        .to_app_option()
        .map_err(|e| wasm_error!(WasmErrorInner::Guest(e.to_string())))?
        .ok_or(wasm_error!(WasmErrorInner::Guest("Invalid entry".into())))?;

    // Track verification progress
    let mut passed_checks = Vec::new();
    let mut failed_checks = Vec::new();

    // =========================================================================
    // Stage 1: Receipt Structure Verification
    // =========================================================================
    // Validate the RISC Zero receipt format without full ZK verification

    if entry.receipt_bytes.is_empty() {
        failed_checks.push("Receipt bytes empty".to_string());
        return Ok(VerificationStatusResult {
            status: VerificationStatus::Invalid("Empty receipt bytes".to_string()),
            quarantine_out: entry.quarantine_out,
            prov_hash: entry.prov_hash,
            receipt_details: ReceiptVerificationResult {
                structure_valid: false,
                provenance_valid: false,
                format_version: None,
                journal_size_estimate: None,
                requires_external_verification: true,
                error: Some("Empty receipt bytes".to_string()),
            },
            provenance_verified: false,
            passed_checks,
            failed_checks,
            recommendations: vec!["Provide non-empty receipt bytes".to_string()],
        });
    }

    let receipt_check = verify_receipt_structure(&entry.receipt_bytes);

    if !receipt_check.structure_valid {
        let error_msg = receipt_check.error.clone().unwrap_or_else(|| "Unknown error".to_string());
        failed_checks.push(format!("Receipt structure: {}", error_msg));
        return Ok(VerificationStatusResult {
            status: VerificationStatus::Invalid(format!(
                "Receipt structure invalid: {}",
                error_msg
            )),
            quarantine_out: entry.quarantine_out,
            prov_hash: entry.prov_hash,
            receipt_details: receipt_check,
            provenance_verified: false,
            passed_checks,
            failed_checks,
            recommendations: vec!["Ensure receipt is valid bincode-serialized RISC Zero Receipt".to_string()],
        });
    }
    passed_checks.push("Receipt structure valid".to_string());

    // =========================================================================
    // Stage 2: Security Profile Validation
    // =========================================================================
    // Must be S128 (127-bit) or S192 (191-bit) conjectured security

    if entry.profile_id != 128 && entry.profile_id != 192 {
        failed_checks.push(format!("Invalid security profile: {}", entry.profile_id));
        return Ok(VerificationStatusResult {
            status: VerificationStatus::Invalid(format!(
                "Invalid security profile: {}. Must be 128 (S128) or 192 (S192)",
                entry.profile_id
            )),
            quarantine_out: entry.quarantine_out,
            prov_hash: entry.prov_hash,
            receipt_details: receipt_check,
            provenance_verified: false,
            passed_checks,
            failed_checks,
            recommendations: vec!["Use profile_id 128 (S128) or 192 (S192)".to_string()],
        });
    }
    passed_checks.push(format!("Security profile valid (S{})", entry.profile_id));

    // =========================================================================
    // Stage 3: Provenance Hash Structural Verification
    // =========================================================================
    // Validate Blake3 provenance commitment (structural check in WASM)
    // Note: Full Blake3 verification against gradient requires gradient data

    let prov_is_zero = entry.prov_hash == [0, 0, 0, 0];

    if !prov_is_zero {
        // Provenance enabled - validate structural integrity
        // Check entropy - all same value indicates invalid hash
        if entry.prov_hash.iter().all(|&v| v == entry.prov_hash[0]) {
            failed_checks.push("Provenance hash lacks entropy".to_string());
            return Ok(VerificationStatusResult {
                status: VerificationStatus::Invalid("Provenance hash lacks entropy (uniform values)".to_string()),
                quarantine_out: entry.quarantine_out,
                prov_hash: entry.prov_hash,
                receipt_details: receipt_check,
                provenance_verified: false,
                passed_checks,
                failed_checks,
                recommendations: vec!["Provide valid Blake3 provenance hash".to_string()],
            });
        }

        // Verify AIR revision is within expected range
        if entry.air_rev == 0 {
            failed_checks.push("AIR revision zero with enabled provenance".to_string());
            return Ok(VerificationStatusResult {
                status: VerificationStatus::Invalid("AIR revision cannot be zero with enabled provenance".to_string()),
                quarantine_out: entry.quarantine_out,
                prov_hash: entry.prov_hash,
                receipt_details: receipt_check,
                provenance_verified: false,
                passed_checks,
                failed_checks,
                recommendations: vec!["Set non-zero air_rev when provenance is enabled".to_string()],
            });
        }
        passed_checks.push("Provenance hash structurally valid".to_string());
    } else {
        // Provenance disabled
        #[cfg(debug_assertions)]
        passed_checks.push("Provenance disabled (debug mode)".to_string());
    }

    // In release mode, provenance should be enabled
    #[cfg(not(debug_assertions))]
    if prov_is_zero {
        failed_checks.push("Zero provenance in production".to_string());
        return Ok(VerificationStatusResult {
            status: VerificationStatus::Invalid("Zero provenance hash not allowed in production".to_string()),
            quarantine_out: entry.quarantine_out,
            prov_hash: entry.prov_hash,
            receipt_details: receipt_check,
            provenance_verified: false,
            passed_checks,
            failed_checks,
            recommendations: vec!["Enable provenance in production builds".to_string()],
        });
    }

    // =========================================================================
    // Stage 4: Journal Integrity Validation
    // =========================================================================
    // Validate decision outputs from the zkVM journal

    // 4a. Quarantine status must be binary (0=healthy, 1=quarantined)
    if entry.quarantine_out > 1 {
        failed_checks.push(format!("Invalid quarantine status: {}", entry.quarantine_out));
        return Ok(VerificationStatusResult {
            status: VerificationStatus::Invalid(format!(
                "Invalid quarantine status: {}. Must be 0 (healthy) or 1 (quarantined)",
                entry.quarantine_out
            )),
            quarantine_out: entry.quarantine_out,
            prov_hash: entry.prov_hash,
            receipt_details: receipt_check,
            provenance_verified: false,
            passed_checks,
            failed_checks,
            recommendations: vec!["Use quarantine_out 0 (healthy) or 1 (quarantined)".to_string()],
        });
    }
    passed_checks.push("Quarantine status valid".to_string());

    // 4b. Round consistency - entry round must match journal current_round
    if entry.round != entry.current_round {
        failed_checks.push(format!("Round mismatch: {} != {}", entry.round, entry.current_round));
        return Ok(VerificationStatusResult {
            status: VerificationStatus::Invalid(format!(
                "Round mismatch: entry.round={} != journal.current_round={}",
                entry.round, entry.current_round
            )),
            quarantine_out: entry.quarantine_out,
            prov_hash: entry.prov_hash,
            receipt_details: receipt_check,
            provenance_verified: false,
            passed_checks,
            failed_checks,
            recommendations: vec!["Ensure entry.round matches journal.current_round".to_string()],
        });
    }
    passed_checks.push("Round consistency verified".to_string());

    // 4c. EMA value validation (Q16.16 fixed-point)
    // EMA should be positive and reasonable (0 to ~10 in fixed-point = 0 to 655360)
    if entry.ema_t_fp > 10 * 65536 {
        failed_checks.push(format!("EMA out of range: {}", entry.ema_t_fp));
        return Ok(VerificationStatusResult {
            status: VerificationStatus::Invalid(format!(
                "EMA value out of range: {} (max: {})",
                entry.ema_t_fp, 10 * 65536
            )),
            quarantine_out: entry.quarantine_out,
            prov_hash: entry.prov_hash,
            receipt_details: receipt_check,
            provenance_verified: false,
            passed_checks,
            failed_checks,
            recommendations: vec!["EMA must be in range [0, 655360] (Q16.16 format)".to_string()],
        });
    }
    passed_checks.push("EMA value in range".to_string());

    // 4d. Consecutive violation/clear counters sanity check
    // Both cannot be high simultaneously (mutual exclusion)
    if entry.consec_viol_t > 0 && entry.consec_clear_t > 0 {
        failed_checks.push("Both violation and clear counters non-zero".to_string());
        return Ok(VerificationStatusResult {
            status: VerificationStatus::Invalid(format!(
                "Invalid state: both consec_viol_t ({}) and consec_clear_t ({}) are non-zero",
                entry.consec_viol_t, entry.consec_clear_t
            )),
            quarantine_out: entry.quarantine_out,
            prov_hash: entry.prov_hash,
            receipt_details: receipt_check,
            provenance_verified: false,
            passed_checks,
            failed_checks,
            recommendations: vec!["Only one of consec_viol_t or consec_clear_t can be non-zero".to_string()],
        });
    }
    passed_checks.push("Consecutive counters valid".to_string());

    // =========================================================================
    // Stage 5: Nonce Integrity Check
    // =========================================================================
    // Verify nonce is non-zero (prevents trivial replay)

    if entry.nonce == [0u8; 32] {
        failed_checks.push("Nonce is all zeros".to_string());
        return Ok(VerificationStatusResult {
            status: VerificationStatus::Invalid("Nonce cannot be all zeros".to_string()),
            quarantine_out: entry.quarantine_out,
            prov_hash: entry.prov_hash,
            receipt_details: receipt_check,
            provenance_verified: false,
            passed_checks,
            failed_checks,
            recommendations: vec!["Provide a non-zero nonce for replay protection".to_string()],
        });
    }
    passed_checks.push("Nonce non-zero".to_string());

    // =========================================================================
    // All Structure Validations Passed - Return PendingExternal
    // =========================================================================
    // NOTE: Without gradient data, we cannot verify Blake3 provenance.
    // Use verify_pogq_proof_with_gradient() for full on-chain verification.

    Ok(VerificationStatusResult {
        status: VerificationStatus::PendingExternal,
        quarantine_out: entry.quarantine_out,
        prov_hash: entry.prov_hash,
        receipt_details: receipt_check,
        provenance_verified: false,
        passed_checks,
        failed_checks,
        recommendations: vec![
            "Use verify_pogq_proof_with_gradient() for full on-chain verification".to_string(),
            "Submit to external verifier for full STARK proof verification".to_string(),
        ],
    })
}

/// Input for verification with gradient data
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct VerifyWithGradientInput {
    /// Entry hash of the proof to verify
    pub proof_hash: EntryHash,
    /// Gradient data bytes for Blake3 provenance verification
    pub gradient_data: Vec<u8>,
}

/// Verify PoGQ proof with Blake3 provenance verification against gradient data
///
/// This performs the maximum verification possible on-chain:
/// 1. All checks from `verify_pogq_proof()`
/// 2. Blake3 hash of gradient_data matches provenance claim
///
/// Returns `PartiallyVerified` if all on-chain checks pass.
/// This is the highest verification level achievable in WASM.
///
/// ## Blake3 Provenance Verification
///
/// The provenance hash is computed as:
/// ```text
/// Blake3(gradient_data || round || profile_id || nonce)
/// ```
///
/// This binds the gradient to the proof cryptographically, preventing:
/// - Gradient substitution attacks
/// - Cross-round replay attacks
/// - Profile downgrade attacks
#[hdk_extern]
pub fn verify_pogq_proof_with_gradient(input: VerifyWithGradientInput) -> ExternResult<VerificationStatusResult> {
    // First, run the basic verification
    let mut result = verify_pogq_proof(input.proof_hash.clone())?;

    // If basic verification failed, return immediately
    if result.status.is_invalid() {
        return Ok(result);
    }

    // Fetch proof entry again for Blake3 verification
    let maybe_record = get(input.proof_hash.clone(), GetOptions::default())?;
    let record = maybe_record
        .ok_or(wasm_error!(WasmErrorInner::Guest("Proof not found".into())))?;

    let entry: PoGQProofEntry = record
        .entry()
        .to_app_option()
        .map_err(|e| wasm_error!(WasmErrorInner::Guest(e.to_string())))?
        .ok_or(wasm_error!(WasmErrorInner::Guest("Invalid entry".into())))?;

    // =========================================================================
    // Blake3 Provenance Verification
    // =========================================================================
    // Compute Blake3 hash of gradient data and verify against provenance claim

    let prov_is_zero = entry.prov_hash == [0, 0, 0, 0];

    if !prov_is_zero {
        // Compute expected provenance hash
        let computed_prov = compute_blake3_provenance(
            &input.gradient_data,
            entry.round,
            entry.profile_id,
            &entry.nonce,
        );

        // Compare with stored provenance
        if computed_prov != entry.prov_hash {
            result.failed_checks.push("Blake3 provenance hash mismatch".to_string());
            result.status = VerificationStatus::Invalid(
                "Provenance hash mismatch: Blake3(gradient_data || round || profile_id || nonce) does not match stored prov_hash".to_string()
            );
            result.provenance_verified = false;
            result.recommendations = vec![
                "Verify gradient_data matches the data used during proof generation".to_string(),
                "Ensure round, profile_id, and nonce are consistent".to_string(),
            ];
            return Ok(result);
        }

        result.passed_checks.push("Blake3 provenance verified".to_string());
        result.provenance_verified = true;
    } else {
        // Provenance disabled - still partially verified in debug mode
        #[cfg(debug_assertions)]
        {
            result.passed_checks.push("Provenance disabled (debug mode) - skipping Blake3 check".to_string());
            result.provenance_verified = true; // Vacuously true
        }

        #[cfg(not(debug_assertions))]
        {
            result.failed_checks.push("Zero provenance in production".to_string());
            result.status = VerificationStatus::Invalid("Zero provenance hash not allowed in production".to_string());
            result.provenance_verified = false;
            return Ok(result);
        }
    }

    // =========================================================================
    // All On-Chain Verifications Passed - PartiallyVerified
    // =========================================================================
    // This is the maximum verification level achievable in WASM.

    result.status = VerificationStatus::PartiallyVerified;
    result.recommendations = vec![
        "Proof is partially verified (maximum on-chain level)".to_string(),
        "Submit to external verifier for full STARK proof verification".to_string(),
        "Safe to use for aggregation with appropriate trust level".to_string(),
    ];

    Ok(result)
}

/// Extended verification result with receipt structure details
#[derive(Debug, Serialize, Deserialize)]
pub struct ExtendedVerificationResult {
    /// Full verification status result
    pub result: VerificationStatusResult,

    /// Whether external ZK verification is needed
    pub needs_external_verification: bool,

    /// Estimated proof size category
    pub proof_size_category: String,

    /// Receipt size in bytes
    pub receipt_size_bytes: usize,

    /// Summary of verification outcome
    pub summary: String,
}

/// Perform extended verification with full diagnostics
///
/// This is useful for debugging and provides more detailed
/// information about the verification process.
#[hdk_extern]
pub fn verify_pogq_proof_extended(proof_hash: EntryHash) -> ExternResult<ExtendedVerificationResult> {
    // Fetch proof entry
    let maybe_record = get(proof_hash.clone(), GetOptions::default())?;
    let record = maybe_record
        .ok_or(wasm_error!(WasmErrorInner::Guest("Proof not found".into())))?;

    let entry: PoGQProofEntry = record
        .entry()
        .to_app_option()
        .map_err(|e| wasm_error!(WasmErrorInner::Guest(e.to_string())))?
        .ok_or(wasm_error!(WasmErrorInner::Guest("Invalid entry".into())))?;

    // Perform full verification
    let result = verify_pogq_proof(proof_hash)?;

    // Categorize proof size
    let proof_size_category = match entry.receipt_bytes.len() {
        0..=1024 => "tiny".to_string(),
        1025..=102400 => "small".to_string(),
        102401..=1048576 => "medium".to_string(),
        1048577..=5242880 => "large".to_string(),
        _ => "extra-large".to_string(),
    };

    // Generate summary
    let summary = match &result.status {
        VerificationStatus::FullyVerified =>
            "All verifications passed including external STARK verification".to_string(),
        VerificationStatus::PartiallyVerified =>
            "On-chain verification complete, awaiting external STARK verification".to_string(),
        VerificationStatus::PendingExternal =>
            "Structure valid, needs provenance verification and external STARK verification".to_string(),
        VerificationStatus::Invalid(reason) =>
            format!("Verification failed: {}", reason),
    };

    Ok(ExtendedVerificationResult {
        needs_external_verification: result.status.needs_external(),
        result,
        proof_size_category,
        receipt_size_bytes: entry.receipt_bytes.len(),
        summary,
    })
}

/// Publish gradient with nonce binding to proof
///
/// Validates:
/// 1. Nonce matches an existing PoGQ proof nonce
/// 2. Linked proof exists and is valid
/// 3. Round matches proof round
#[hdk_extern]
pub fn publish_gradient(entry: GradientEntry) -> ExternResult<EntryHash> {
    // Fetch linked proof
    let maybe_proof_record = get(entry.pogq_proof_hash.clone(), GetOptions::default())?;
    let proof_record = maybe_proof_record
        .ok_or(wasm_error!(WasmErrorInner::Guest("PoGQ proof not found".into())))?;

    let proof: PoGQProofEntry = proof_record
        .entry()
        .to_app_option()
        .map_err(|e| wasm_error!(WasmErrorInner::Guest(e.to_string())))?
        .ok_or(wasm_error!(WasmErrorInner::Guest("Invalid proof entry".into())))?;

    // CRITICAL: Nonce binding check
    if entry.nonce != proof.nonce {
        return Err(wasm_error!(WasmErrorInner::Guest(
            "Nonce mismatch - gradient not bound to proof".into()
        )));
    }

    // Validate round matches
    if entry.round != proof.round {
        return Err(wasm_error!(WasmErrorInner::Guest(
            format!("Round mismatch - gradient: {}, proof: {}", entry.round, proof.round)
        )));
    }

    // Verify proof journal before accepting gradient
    let verification = verify_pogq_proof(entry.pogq_proof_hash.clone())?;
    if verification.status.is_invalid() {
        return Err(wasm_error!(WasmErrorInner::Guest(
            format!("Proof verification failed: {:?}", verification.status.error_message())
        )));
    }

    // Create gradient entry with EntryTypes wrapper
    create_entry(EntryTypes::GradientEntry(entry.clone()))?;
    let grad_hash = hash_entry(&entry)?;

    // Create anchor for round-based discovery
    let round_anchor = anchor(
        LinkTypes::GradientToRound,
        "gradients".to_string(),
        format!("round_{}", entry.round),
    )?;

    // Link round to gradient
    create_link(
        round_anchor,
        grad_hash.clone(),
        LinkTypes::GradientToRound,
        (),
    )?;

    // Link gradient to proof
    create_link(
        grad_hash.clone(),
        entry.pogq_proof_hash.clone(),
        LinkTypes::GradientToProof,
        (),
    )?;

    Ok(grad_hash)
}

/// Get all gradients for a round with quarantine status
///
/// Returns list of (GradientEntry, is_quarantined) tuples
#[hdk_extern]
pub fn get_round_gradients(round: u64) -> ExternResult<Vec<(GradientEntry, bool)>> {
    // Get anchor for round
    let round_anchor = anchor(
        LinkTypes::GradientToRound,
        "gradients".to_string(),
        format!("round_{}", round),
    )?;

    // Query links
    let links = get_links(
        GetLinksInputBuilder::try_new(round_anchor, LinkTypes::GradientToRound)?.build()
    )?;

    let mut results = Vec::new();
    for link in links {
        // Convert AnyLinkableHash to EntryHash
        if let Some(grad_hash) = link.target.into_entry_hash() {
            // Fetch gradient entry
            let maybe_grad_record = get(grad_hash, GetOptions::default())?;
            if let Some(grad_record) = maybe_grad_record {
                let grad: GradientEntry = grad_record
                    .entry()
                    .to_app_option()
                    .map_err(|e| wasm_error!(WasmErrorInner::Guest(e.to_string())))?
                    .ok_or(wasm_error!(WasmErrorInner::Guest("Invalid gradient entry".into())))?;

                // Fetch linked proof
                let maybe_proof_record = get(grad.pogq_proof_hash.clone(), GetOptions::default())?;
                if let Some(proof_record) = maybe_proof_record {
                    let proof: PoGQProofEntry = proof_record
                        .entry()
                        .to_app_option()
                        .map_err(|e| wasm_error!(WasmErrorInner::Guest(e.to_string())))?
                        .ok_or(wasm_error!(WasmErrorInner::Guest("Invalid proof entry".into())))?;

                    // Extract quarantine status
                    let is_quarantined = proof.quarantine_out == 1;
                    results.push((grad, is_quarantined));
                }
            }
        }
    }

    Ok(results)
}

/// Compute sybil-weighted aggregate (zero weight for quarantined)
///
/// Returns aggregate metadata (actual gradient aggregation done off-DHT)
#[hdk_extern]
pub fn compute_sybil_weighted_aggregate(round: u64) -> ExternResult<SybilWeightedResult> {
    let entries = get_round_gradients(round)?;

    let mut total_weight = 0.0;
    let mut num_quarantined = 0;
    let mut num_healthy = 0;

    for (_grad_entry, is_quarantined) in &entries {
        if *is_quarantined {
            num_quarantined += 1;
        } else {
            total_weight += 1.0;  // Sybil weight = 1 if healthy, 0 if quarantined
            num_healthy += 1;
        }
    }

    // TODO: Actual gradient aggregation (off-DHT due to size)
    // This zome provides quarantine metadata; aggregation done by FL orchestrator
    let placeholder_hash = vec![0u8; 32];  // Placeholder Blake3 hash

    Ok(SybilWeightedResult {
        aggregated_gradient_commitment: placeholder_hash,
        total_weight,
        num_quarantined,
        num_healthy,
    })
}

// ============================================================================
// Helper Functions
// ============================================================================

/// Check if a nonce has been used before
fn is_nonce_used(nonce: &[u8; 32]) -> ExternResult<bool> {
    // Convert nonce to hex string using standard library
    let nonce_hex = nonce.iter()
        .map(|b| format!("{:02x}", b))
        .collect::<String>();

    // Create anchor for nonce registry
    let nonce_registry = anchor(
        LinkTypes::NonceToRegistry,
        "nonce_registry".to_string(),
        nonce_hex,
    )?;

    // Query for existing nonce entries
    let links = get_links(
        GetLinksInputBuilder::try_new(nonce_registry, LinkTypes::NonceToRegistry)?.build()
    )?;

    Ok(!links.is_empty())
}

/// Record a nonce as used
fn record_nonce(nonce_entry: NonceEntry) -> ExternResult<EntryHash> {
    // Create nonce entry
    create_entry(EntryTypes::NonceEntry(nonce_entry.clone()))?;
    let nonce_hash = hash_entry(&nonce_entry)?;

    // Convert nonce to hex string using standard library
    let nonce_hex = nonce_entry.nonce.iter()
        .map(|b| format!("{:02x}", b))
        .collect::<String>();

    // Create anchor for nonce registry
    let nonce_registry = anchor(
        LinkTypes::NonceToRegistry,
        "nonce_registry".to_string(),
        nonce_hex,
    )?;

    // Link nonce to registry
    create_link(
        nonce_registry,
        nonce_hash.clone(),
        LinkTypes::NonceToRegistry,
        (),
    )?;

    Ok(nonce_hash)
}

/// Get the current training round from the DHT
///
/// The current round is determined by:
/// 1. Looking up the round counter anchor
/// 2. Finding all proofs linked to rounds
/// 3. Returning the highest round number
fn get_current_round() -> ExternResult<u64> {
    // Create anchor for round tracker
    let round_tracker = anchor(
        LinkTypes::ProofToRound,
        "round_tracker".to_string(),
        "current".to_string(),
    )?;

    // Query for round info links
    let links = get_links(
        GetLinksInputBuilder::try_new(round_tracker.clone(), LinkTypes::ProofToRound)?.build()
    )?;

    if links.is_empty() {
        // No rounds recorded yet - start at round 0
        return Ok(0);
    }

    // Find the highest round by fetching all round info entries
    let mut max_round: u64 = 0;

    for link in links {
        if let Some(entry_hash) = link.target.into_entry_hash() {
            if let Some(record) = get(entry_hash, GetOptions::default())? {
                // Try to extract round number from entry
                if let Ok(Some(proof)) = record.entry().to_app_option::<PoGQProofEntry>() {
                    max_round = max_round.max(proof.round);
                }
            }
        }
    }

    Ok(max_round)
}

/// Check if a node has already published a proof for a given round
///
/// This prevents nodes from submitting multiple proofs per round,
/// which could be used to manipulate voting weights or consensus.
fn has_node_published_round(node_id: &AgentPubKey, round: u64) -> ExternResult<bool> {
    // Create anchor for node-round tracking
    let node_round_anchor = anchor(
        LinkTypes::ProofToRound,
        "node_rounds".to_string(),
        format!("{}_{}", node_id, round),
    )?;

    // Query for existing entries
    let links = get_links(
        GetLinksInputBuilder::try_new(node_round_anchor, LinkTypes::ProofToRound)?.build()
    )?;

    Ok(!links.is_empty())
}

/// Record that a node has published for a round
///
/// Called after successful proof publication to prevent duplicates.
fn record_node_round(node_id: &AgentPubKey, round: u64, proof_hash: &EntryHash) -> ExternResult<()> {
    // Create anchor for node-round tracking
    let node_round_anchor = anchor(
        LinkTypes::ProofToRound,
        "node_rounds".to_string(),
        format!("{}_{}", node_id, round),
    )?;

    // Link the proof to the node-round anchor
    create_link(
        node_round_anchor,
        proof_hash.clone(),
        LinkTypes::ProofToRound,
        (),
    )?;

    // Also update the round tracker to reflect the new maximum round
    let round_tracker = anchor(
        LinkTypes::ProofToRound,
        "round_tracker".to_string(),
        "current".to_string(),
    )?;

    create_link(
        round_tracker,
        proof_hash.clone(),
        LinkTypes::ProofToRound,
        (),
    )?;

    Ok(())
}

// ============================================================================
// Receipt Verification Module
// ============================================================================
//
// RISC Zero receipts are serialized using bincode. The Receipt struct contains:
// - inner: InnerReceipt (Composite, Succinct, or Fake variants)
// - journal: Journal (public outputs committed by the guest)
// - metadata: ReceiptMetadata (verifier parameters)
//
// Since we cannot deserialize the full Receipt (requires risc0-zkvm),
// we perform structural validation on the raw bytes.

/// RISC Zero receipt verification result
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ReceiptVerificationResult {
    /// Whether structural validation passed
    pub structure_valid: bool,

    /// Whether provenance hash validation passed
    pub provenance_valid: bool,

    /// Detected receipt format version
    pub format_version: Option<u8>,

    /// Estimated journal size (bytes)
    pub journal_size_estimate: Option<usize>,

    /// Whether full ZK verification is required (always true for production)
    pub requires_external_verification: bool,

    /// Detailed error message if validation failed
    pub error: Option<String>,
}

/// Minimum valid receipt size (bincode header + minimal inner receipt)
/// Based on analysis of RISC Zero 1.0+ receipt structure
const MIN_RECEIPT_SIZE: usize = 64;

/// Maximum valid receipt size (10MB - typical proofs are 2-5MB)
const MAX_RECEIPT_SIZE: usize = 10 * 1024 * 1024;

/// Verify RISC Zero receipt structure without full ZK verification
///
/// This performs the maximum verification possible in WASM:
/// 1. Size bounds check
/// 2. Bincode structure validation
/// 3. Receipt variant detection
/// 4. Journal extraction (if possible)
///
/// **NOTE**: This does NOT verify the STARK proof. Full verification
/// requires an external native service running risc0-zkvm.
pub fn verify_receipt_structure(receipt_bytes: &[u8]) -> ReceiptVerificationResult {
    // 1. Size bounds check
    if receipt_bytes.len() < MIN_RECEIPT_SIZE {
        return ReceiptVerificationResult {
            structure_valid: false,
            provenance_valid: false,
            format_version: None,
            journal_size_estimate: None,
            requires_external_verification: true,
            error: Some(format!(
                "Receipt too small: {} bytes (minimum: {})",
                receipt_bytes.len(),
                MIN_RECEIPT_SIZE
            )),
        };
    }

    if receipt_bytes.len() > MAX_RECEIPT_SIZE {
        return ReceiptVerificationResult {
            structure_valid: false,
            provenance_valid: false,
            format_version: None,
            journal_size_estimate: None,
            requires_external_verification: true,
            error: Some(format!(
                "Receipt too large: {} bytes (maximum: {})",
                receipt_bytes.len(),
                MAX_RECEIPT_SIZE
            )),
        };
    }

    // 2. Bincode structure validation
    // Bincode serializes enum variants as u32 index followed by variant data
    // Receipt inner variants: Composite=0, Succinct=1, Fake=2
    let variant_result = validate_bincode_enum_variant(receipt_bytes);

    let format_version = match &variant_result {
        Ok(v) => Some(*v),
        Err(_) => None,
    };

    if variant_result.is_err() {
        return ReceiptVerificationResult {
            structure_valid: false,
            provenance_valid: false,
            format_version,
            journal_size_estimate: None,
            requires_external_verification: true,
            error: Some(variant_result.unwrap_err()),
        };
    }

    // 3. Estimate journal size from receipt structure
    // Journal is typically near the end of the serialized data
    let journal_size = estimate_journal_size(receipt_bytes);

    // 4. Validate receipt contains expected sections
    // Check for presence of cryptographic commitments (32-byte aligned data)
    let has_commitments = validate_commitment_presence(receipt_bytes);

    if !has_commitments {
        return ReceiptVerificationResult {
            structure_valid: false,
            provenance_valid: false,
            format_version,
            journal_size_estimate: journal_size,
            requires_external_verification: true,
            error: Some("Receipt missing expected cryptographic commitments".to_string()),
        };
    }

    ReceiptVerificationResult {
        structure_valid: true,
        provenance_valid: false, // Set by provenance verification
        format_version,
        journal_size_estimate: journal_size,
        requires_external_verification: true,
        error: None,
    }
}

/// Validate bincode enum variant at start of receipt
///
/// Returns the detected variant index (0=Composite, 1=Succinct, 2=Fake)
fn validate_bincode_enum_variant(bytes: &[u8]) -> Result<u8, String> {
    if bytes.len() < 4 {
        return Err("Insufficient bytes for enum variant".to_string());
    }

    // Bincode uses little-endian u32 for enum variants
    let variant = u32::from_le_bytes([bytes[0], bytes[1], bytes[2], bytes[3]]);

    // Valid InnerReceipt variants: 0 (Composite), 1 (Succinct), 2 (Fake)
    match variant {
        0 => Ok(0), // Composite - multi-segment proof
        1 => Ok(1), // Succinct - compressed proof
        2 => {
            // Fake receipts are only valid in dev mode
            // For production, this should be rejected
            #[cfg(debug_assertions)]
            return Ok(2);
            #[cfg(not(debug_assertions))]
            return Err("Fake receipt variant not allowed in release mode".to_string());
        }
        _ => Err(format!("Invalid receipt variant: {}", variant)),
    }
}

/// Estimate journal size from receipt bytes
///
/// The journal is typically serialized near the end of the receipt.
/// This heuristic looks for the journal length prefix.
fn estimate_journal_size(bytes: &[u8]) -> Option<usize> {
    // Journal struct contains:
    // - bytes: Vec<u8> (length-prefixed in bincode)
    //
    // We scan backwards looking for a plausible length prefix
    // that matches remaining data

    if bytes.len() < 12 {
        return None;
    }

    // Check last 1024 bytes for journal-like structure
    let scan_start = if bytes.len() > 1024 {
        bytes.len() - 1024
    } else {
        8
    };

    for offset in (scan_start..bytes.len().saturating_sub(8)).rev() {
        // Read potential u64 length prefix
        let potential_len = u64::from_le_bytes([
            bytes[offset],
            bytes[offset + 1],
            bytes[offset + 2],
            bytes[offset + 3],
            bytes[offset + 4],
            bytes[offset + 5],
            bytes[offset + 6],
            bytes[offset + 7],
        ]) as usize;

        // Check if this could be a journal length
        // Journal typically contains: gradient_hash (32) + epochs (4) + samples (8) = 44+ bytes
        if potential_len >= 32 && potential_len <= 4096 {
            let remaining = bytes.len() - offset - 8;
            if remaining >= potential_len && remaining <= potential_len + 64 {
                return Some(potential_len);
            }
        }
    }

    None
}

/// Validate presence of cryptographic commitments in receipt
///
/// RISC Zero receipts contain multiple 32-byte cryptographic values:
/// - Merkle roots
/// - Polynomial commitments
/// - Digest values
///
/// We check for 32-byte aligned sequences that look like hashes
fn validate_commitment_presence(bytes: &[u8]) -> bool {
    if bytes.len() < 128 {
        return false;
    }

    // Count sequences that look like cryptographic hashes
    // (high entropy, not all zeros or ones)
    let mut hash_like_count = 0;

    for chunk_start in (32..bytes.len().saturating_sub(32)).step_by(32) {
        let chunk = &bytes[chunk_start..chunk_start + 32];

        if is_hash_like(chunk) {
            hash_like_count += 1;
        }

        // Receipts should contain at least 3 hash-like values
        if hash_like_count >= 3 {
            return true;
        }
    }

    hash_like_count >= 1 // Minimal threshold for small proofs
}

/// Check if a 32-byte slice looks like a cryptographic hash
///
/// Heuristics:
/// - Not all zeros
/// - Not all the same byte
/// - Has reasonable byte distribution
fn is_hash_like(bytes: &[u8]) -> bool {
    if bytes.len() != 32 {
        return false;
    }

    // Check not all zeros
    if bytes.iter().all(|&b| b == 0) {
        return false;
    }

    // Check not all same byte
    let first = bytes[0];
    if bytes.iter().all(|&b| b == first) {
        return false;
    }

    // Check has multiple distinct byte values (entropy indicator)
    let mut seen = [false; 256];
    let mut distinct_count = 0;
    for &b in bytes {
        if !seen[b as usize] {
            seen[b as usize] = true;
            distinct_count += 1;
        }
    }

    // Good hashes typically have 15+ distinct bytes in 32 bytes
    distinct_count >= 8
}

// ============================================================================
// Provenance Verification Module (Blake3)
// ============================================================================
//
// Provenance hashes commit to the proof generation environment:
// - Gradient data (Blake3 hash)
// - FL round number
// - Security profile (S128 or S192)
// - Cryptographic nonce
//
// This ensures proofs can only be verified with matching parameters and
// prevents gradient substitution attacks.
//
// ## Blake3 in WASM
//
// The blake3 crate with `default-features = false` compiles to WASM.
// This allows full cryptographic provenance verification on-chain.

/// Compute Blake3 provenance hash for gradient binding
///
/// The provenance hash binds gradient data to proof metadata:
/// ```text
/// Blake3(gradient_data || round_le_bytes || profile_id_le_bytes || nonce)
/// ```
///
/// This provides:
/// - Gradient authenticity (data wasn't modified)
/// - Round binding (can't use gradient from different round)
/// - Profile binding (can't downgrade security profile)
/// - Replay protection (nonce uniqueness)
///
/// Returns [u64; 4] representation of the 256-bit Blake3 hash.
pub fn compute_blake3_provenance(
    gradient_data: &[u8],
    round: u64,
    profile_id: u32,
    nonce: &[u8; 32],
) -> [u64; 4] {
    let mut hasher = blake3::Hasher::new();

    // Hash gradient data
    hasher.update(gradient_data);

    // Hash round (little-endian u64)
    hasher.update(&round.to_le_bytes());

    // Hash profile_id (little-endian u32)
    hasher.update(&profile_id.to_le_bytes());

    // Hash nonce
    hasher.update(nonce);

    // Finalize and convert to [u64; 4]
    let hash = hasher.finalize();
    let hash_bytes = hash.as_bytes();

    [
        u64::from_le_bytes([
            hash_bytes[0], hash_bytes[1], hash_bytes[2], hash_bytes[3],
            hash_bytes[4], hash_bytes[5], hash_bytes[6], hash_bytes[7],
        ]),
        u64::from_le_bytes([
            hash_bytes[8], hash_bytes[9], hash_bytes[10], hash_bytes[11],
            hash_bytes[12], hash_bytes[13], hash_bytes[14], hash_bytes[15],
        ]),
        u64::from_le_bytes([
            hash_bytes[16], hash_bytes[17], hash_bytes[18], hash_bytes[19],
            hash_bytes[20], hash_bytes[21], hash_bytes[22], hash_bytes[23],
        ]),
        u64::from_le_bytes([
            hash_bytes[24], hash_bytes[25], hash_bytes[26], hash_bytes[27],
            hash_bytes[28], hash_bytes[29], hash_bytes[30], hash_bytes[31],
        ]),
    ]
}

/// Compute Blake3 hash of gradient data only
///
/// Returns 32-byte Blake3 hash as Vec<u8>.
/// Use this for gradient_commitment field in GradientEntry.
pub fn compute_gradient_commitment(gradient_data: &[u8]) -> Vec<u8> {
    let hash = blake3::hash(gradient_data);
    hash.as_bytes().to_vec()
}

/// Verify gradient commitment matches expected Blake3 hash
///
/// Returns true if Blake3(gradient_data) == commitment.
pub fn verify_gradient_commitment(gradient_data: &[u8], commitment: &[u8]) -> bool {
    if commitment.len() != 32 {
        return false;
    }

    let computed = blake3::hash(gradient_data);
    computed.as_bytes() == commitment
}

/// Verify provenance hash against expected gradient commitment
///
/// The provenance hash should commit to:
/// 1. Gradient data hash (Blake3)
/// 2. Model parameters hash
/// 3. Training metadata (epochs, samples, learning rate)
///
/// **Implementation**: Now uses Blake3 for full verification in WASM.
pub fn verify_provenance_hash(
    prov_hash: &[u64; 4],
    gradient_commitment: &[u8],
    _profile_id: u32,
) -> Result<bool, String> {
    // Check if provenance is enabled (non-zero)
    let is_zero = prov_hash.iter().all(|&v| v == 0);

    if is_zero {
        // Provenance disabled - valid for dev mode
        // In production, this should require non-zero provenance
        #[cfg(debug_assertions)]
        return Ok(true);

        #[cfg(not(debug_assertions))]
        return Err("Zero provenance hash not allowed in release mode".to_string());
    }

    // Verify gradient commitment is non-empty
    if gradient_commitment.is_empty() {
        return Err("Gradient commitment is empty".to_string());
    }

    // Verify gradient commitment is valid Blake3 hash size (32 bytes)
    if gradient_commitment.len() != 32 {
        return Err(format!(
            "Invalid gradient commitment size: {} (expected 32)",
            gradient_commitment.len()
        ));
    }

    // Basic entropy check on provenance hash
    if prov_hash.iter().all(|&v| v == prov_hash[0]) {
        return Err("Provenance hash lacks entropy".to_string());
    }

    // Check gradient commitment has sufficient entropy
    if gradient_commitment.iter().all(|&b| b == 0) {
        return Err("Gradient commitment is all zeros".to_string());
    }

    // Structural validation passed
    // Full Blake3 verification done by verify_pogq_proof_with_gradient()
    Ok(true)
}

/// Compute a lightweight provenance commitment (for testing)
///
/// **DEPRECATED**: Use `compute_blake3_provenance()` for production.
/// This function is kept for backwards compatibility with tests.
pub fn compute_simple_provenance(
    gradient_commitment: &[u8],
    round: u64,
    profile_id: u32,
    nonce: &[u8; 32],
) -> [u64; 4] {
    // Use Blake3 for consistency with production
    compute_blake3_provenance(gradient_commitment, round, profile_id, nonce)
}

// ============================================================================
// External Verification Interface
// ============================================================================

/// Marker for proofs that require external ZK verification
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ExternalVerificationRequest {
    /// Entry hash of the proof to verify
    pub proof_hash: EntryHash,

    /// Receipt bytes for external verifier
    pub receipt_bytes: Vec<u8>,

    /// Expected method ID (image ID) - 32 bytes
    pub expected_method_id: Option<Vec<u8>>,

    /// Security profile for verification
    pub profile_id: u32,

    /// Timestamp of request
    pub requested_at: Timestamp,
}

/// Result from external verification service
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ExternalVerificationResponse {
    /// Whether the full ZK proof verified successfully
    pub zk_verified: bool,

    /// Decoded journal contents
    pub journal_data: Option<Vec<u8>>,

    /// Verification timestamp
    pub verified_at: Option<Timestamp>,

    /// Error message if verification failed
    pub error: Option<String>,
}

/// Create external verification request for a proof entry
///
/// This is used to queue proofs for verification by an external
/// native service running risc0-zkvm.
#[hdk_extern]
pub fn create_verification_request(proof_hash: EntryHash) -> ExternResult<ExternalVerificationRequest> {
    let maybe_record = get(proof_hash.clone(), GetOptions::default())?;
    let record = maybe_record
        .ok_or(wasm_error!(WasmErrorInner::Guest("Proof not found".into())))?;

    let entry: PoGQProofEntry = record
        .entry()
        .to_app_option()
        .map_err(|e| wasm_error!(WasmErrorInner::Guest(e.to_string())))?
        .ok_or(wasm_error!(WasmErrorInner::Guest("Invalid entry".into())))?;

    Ok(ExternalVerificationRequest {
        proof_hash,
        receipt_bytes: entry.receipt_bytes,
        expected_method_id: None, // Set by external verifier config
        profile_id: entry.profile_id,
        requested_at: sys_time()?,
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    // ========================================================================
    // Helper Functions for Testing
    // ========================================================================

    /// Create a valid test PoGQProofEntry
    fn create_valid_proof_entry() -> PoGQProofEntry {
        PoGQProofEntry {
            node_id: fake_agent_pub_key(1),
            round: 1,
            nonce: [1u8; 32],
            receipt_bytes: vec![0xde, 0xad, 0xbe, 0xef], // Non-empty receipt
            prov_hash: [12345u64, 67890, 11111, 22222],
            profile_id: 128, // Valid S128 profile
            air_rev: 1,
            quarantine_out: 0, // Healthy
            current_round: 1,  // Matches round
            ema_t_fp: 65536,   // Q16.16 = 1.0
            consec_viol_t: 0,
            consec_clear_t: 5,
            timestamp: Timestamp::from_micros(1000000), // Arbitrary timestamp
        }
    }

    /// Create a fake AgentPubKey for testing
    /// Uses valid AgentPubKey prefix (0x84, 0x20, 0x24) followed by ID bytes
    fn fake_agent_pub_key(id: u8) -> AgentPubKey {
        let mut bytes = vec![0x84, 0x20, 0x24]; // Valid AgentPubKey prefix
        bytes.extend_from_slice(&[id; 36]); // Fill remaining 36 bytes with ID
        AgentPubKey::from_raw_39(bytes).expect("Failed to create test AgentPubKey")
    }

    // ========================================================================
    // Unit Tests: Validation Logic
    // ========================================================================

    #[test]
    fn test_invalid_profile_id_too_low() {
        let mut entry = create_valid_proof_entry();
        entry.profile_id = 64; // Invalid: too low

        // Profile validation happens in publish_pogq_proof and verify_pogq_proof
        // This test documents expected behavior (would need integration test to execute)
        assert!(entry.profile_id != 128 && entry.profile_id != 192);
    }

    #[test]
    fn test_invalid_profile_id_too_high() {
        let mut entry = create_valid_proof_entry();
        entry.profile_id = 256; // Invalid: too high

        assert!(entry.profile_id != 128 && entry.profile_id != 192);
    }

    #[test]
    fn test_valid_profile_id_s128() {
        let entry = create_valid_proof_entry();
        assert_eq!(entry.profile_id, 128);
        assert!(entry.profile_id == 128 || entry.profile_id == 192);
    }

    #[test]
    fn test_valid_profile_id_s192() {
        let mut entry = create_valid_proof_entry();
        entry.profile_id = 192;
        assert!(entry.profile_id == 128 || entry.profile_id == 192);
    }

    #[test]
    fn test_invalid_quarantine_out_too_high() {
        let mut entry = create_valid_proof_entry();
        entry.quarantine_out = 2; // Invalid: must be 0 or 1

        // Verification logic checks quarantine_out <= 1
        assert!(entry.quarantine_out > 1);
    }

    #[test]
    fn test_valid_quarantine_out_healthy() {
        let entry = create_valid_proof_entry();
        assert_eq!(entry.quarantine_out, 0);
        assert!(entry.quarantine_out <= 1);
    }

    #[test]
    fn test_valid_quarantine_out_quarantined() {
        let mut entry = create_valid_proof_entry();
        entry.quarantine_out = 1;
        assert!(entry.quarantine_out <= 1);
    }

    #[test]
    fn test_round_mismatch_detection() {
        let mut entry = create_valid_proof_entry();
        entry.round = 5;
        entry.current_round = 3; // Mismatch!

        // verify_pogq_proof checks entry.round == current_round
        assert_ne!(entry.round, entry.current_round);
    }

    #[test]
    fn test_round_consistency() {
        let entry = create_valid_proof_entry();
        assert_eq!(entry.round, entry.current_round);
    }

    #[test]
    fn test_nonce_binding_mismatch() {
        let proof = create_valid_proof_entry();
        let gradient = GradientEntry {
            node_id: fake_agent_pub_key(1),
            round: 1,
            nonce: [2u8; 32], // Different nonce!
            gradient_commitment: vec![0xaa, 0xbb, 0xcc],
            quality_score: 0.95,
            pogq_proof_hash: EntryHash::from_raw_36([0u8; 36].to_vec()),
            timestamp: Timestamp::from_micros(1000000),
        };

        // publish_gradient checks gradient.nonce == proof.nonce
        assert_ne!(gradient.nonce, proof.nonce);
    }

    #[test]
    fn test_nonce_binding_match() {
        let proof = create_valid_proof_entry();
        let gradient = GradientEntry {
            node_id: fake_agent_pub_key(1),
            round: 1,
            nonce: proof.nonce, // Same nonce
            gradient_commitment: vec![0xaa, 0xbb, 0xcc],
            quality_score: 0.95,
            pogq_proof_hash: EntryHash::from_raw_36([0u8; 36].to_vec()),
            timestamp: Timestamp::from_micros(1000000),
        };

        assert_eq!(gradient.nonce, proof.nonce);
    }

    #[test]
    fn test_empty_receipt_detection() {
        let mut entry = create_valid_proof_entry();
        entry.receipt_bytes = vec![]; // Empty receipt

        // publish_pogq_proof checks !receipt_bytes.is_empty()
        assert!(entry.receipt_bytes.is_empty());
    }

    #[test]
    fn test_non_empty_receipt() {
        let entry = create_valid_proof_entry();
        assert!(!entry.receipt_bytes.is_empty());
    }

    #[test]
    fn test_nonce_uniqueness() {
        let nonce1 = [1u8; 32];
        let nonce2 = [2u8; 32];
        let nonce3 = [1u8; 32]; // Same as nonce1

        // Nonces must be unique to prevent replay attacks
        assert_ne!(nonce1, nonce2);
        assert_eq!(nonce1, nonce3); // Duplicate - should be rejected
    }

    // ========================================================================
    // Receipt Structure Verification Tests
    // ========================================================================

    #[test]
    fn test_receipt_structure_too_small() {
        // Receipt must be at least MIN_RECEIPT_SIZE bytes
        let small_receipt = vec![0u8; 32];
        let result = verify_receipt_structure(&small_receipt);

        assert!(!result.structure_valid);
        assert!(result.error.is_some());
        assert!(result.error.unwrap().contains("too small"));
    }

    #[test]
    fn test_receipt_structure_too_large() {
        // Receipt must be at most MAX_RECEIPT_SIZE bytes
        let large_receipt = vec![0u8; 11 * 1024 * 1024]; // 11MB
        let result = verify_receipt_structure(&large_receipt);

        assert!(!result.structure_valid);
        assert!(result.error.is_some());
        assert!(result.error.unwrap().contains("too large"));
    }

    #[test]
    fn test_receipt_structure_valid_variant_composite() {
        // Create mock receipt with Composite variant (0)
        // and valid structure
        let mut receipt = vec![0u8; 256];
        // Set variant to 0 (Composite) in little-endian
        receipt[0] = 0;
        receipt[1] = 0;
        receipt[2] = 0;
        receipt[3] = 0;

        // Add some hash-like data for commitment validation
        for i in 0..3 {
            let offset = 32 + i * 32;
            for j in 0..32 {
                receipt[offset + j] = ((i * 31 + j * 17) % 256) as u8;
            }
        }

        let result = verify_receipt_structure(&receipt);
        // Should pass basic structure check
        assert!(result.format_version == Some(0));
    }

    #[test]
    fn test_receipt_structure_valid_variant_succinct() {
        // Create mock receipt with Succinct variant (1)
        let mut receipt = vec![0u8; 256];
        // Set variant to 1 (Succinct) in little-endian
        receipt[0] = 1;
        receipt[1] = 0;
        receipt[2] = 0;
        receipt[3] = 0;

        // Add some hash-like data
        for i in 0..3 {
            let offset = 32 + i * 32;
            for j in 0..32 {
                receipt[offset + j] = ((i * 31 + j * 17) % 256) as u8;
            }
        }

        let result = verify_receipt_structure(&receipt);
        assert!(result.format_version == Some(1));
    }

    #[test]
    fn test_receipt_structure_invalid_variant() {
        // Create mock receipt with invalid variant (99)
        let mut receipt = vec![0u8; 256];
        receipt[0] = 99;
        receipt[1] = 0;
        receipt[2] = 0;
        receipt[3] = 0;

        let result = verify_receipt_structure(&receipt);
        assert!(!result.structure_valid);
        assert!(result.error.is_some());
        assert!(result.error.unwrap().contains("Invalid receipt variant"));
    }

    #[test]
    fn test_is_hash_like_all_zeros() {
        let zeros = [0u8; 32];
        assert!(!is_hash_like(&zeros));
    }

    #[test]
    fn test_is_hash_like_all_same() {
        let same = [0xaa; 32];
        assert!(!is_hash_like(&same));
    }

    #[test]
    fn test_is_hash_like_valid_hash() {
        // Create data with high entropy
        let mut hash = [0u8; 32];
        for i in 0..32 {
            hash[i] = (i * 17 + 31) as u8;
        }
        assert!(is_hash_like(&hash));
    }

    // ========================================================================
    // Provenance Verification Tests
    // ========================================================================

    #[test]
    fn test_provenance_zero_hash_debug_mode() {
        let zero_prov = [0u64; 4];
        let gradient = vec![0xaa; 32];

        // In debug mode, zero provenance should be accepted
        let result = verify_provenance_hash(&zero_prov, &gradient, 128);
        #[cfg(debug_assertions)]
        assert!(result.is_ok());
    }

    #[test]
    fn test_provenance_empty_gradient() {
        let prov = [12345u64, 67890, 11111, 22222];
        let empty_gradient: Vec<u8> = vec![];

        let result = verify_provenance_hash(&prov, &empty_gradient, 128);
        assert!(result.is_err());
        assert!(result.unwrap_err().contains("empty"));
    }

    #[test]
    fn test_provenance_wrong_gradient_size() {
        let prov = [12345u64, 67890, 11111, 22222];
        let short_gradient = vec![0xaa; 16]; // Should be 32 bytes

        let result = verify_provenance_hash(&prov, &short_gradient, 128);
        assert!(result.is_err());
        assert!(result.unwrap_err().contains("Invalid gradient commitment size"));
    }

    #[test]
    fn test_provenance_uniform_hash_rejected() {
        let uniform_prov = [12345u64; 4]; // All same value
        let gradient = vec![0xaa; 32];

        let result = verify_provenance_hash(&uniform_prov, &gradient, 128);
        assert!(result.is_err());
        assert!(result.unwrap_err().contains("entropy"));
    }

    #[test]
    fn test_provenance_valid_hash() {
        let valid_prov = [12345u64, 67890, 11111, 22222]; // Different values
        let mut gradient = vec![0u8; 32];
        for i in 0..32 {
            gradient[i] = (i * 17 + 31) as u8;
        }

        let result = verify_provenance_hash(&valid_prov, &gradient, 128);
        assert!(result.is_ok());
    }

    #[test]
    fn test_compute_simple_provenance_deterministic() {
        let gradient = vec![0xab; 32];
        let round = 5u64;
        let profile = 128u32;
        let nonce = [0x12; 32];

        let prov1 = compute_simple_provenance(&gradient, round, profile, &nonce);
        let prov2 = compute_simple_provenance(&gradient, round, profile, &nonce);

        assert_eq!(prov1, prov2);
    }

    #[test]
    fn test_compute_simple_provenance_differs_by_round() {
        let gradient = vec![0xab; 32];
        let nonce = [0x12; 32];

        let prov1 = compute_simple_provenance(&gradient, 1, 128, &nonce);
        let prov2 = compute_simple_provenance(&gradient, 2, 128, &nonce);

        assert_ne!(prov1, prov2);
    }

    #[test]
    fn test_compute_simple_provenance_differs_by_gradient() {
        let gradient1 = vec![0xab; 32];
        let gradient2 = vec![0xcd; 32];
        let nonce = [0x12; 32];

        let prov1 = compute_simple_provenance(&gradient1, 1, 128, &nonce);
        let prov2 = compute_simple_provenance(&gradient2, 1, 128, &nonce);

        assert_ne!(prov1, prov2);
    }

    // ========================================================================
    // Journal Integrity Tests
    // ========================================================================

    #[test]
    fn test_ema_value_in_range() {
        let entry = create_valid_proof_entry();
        // EMA should be 0 to 10 in Q16.16 = 0 to 655360
        assert!(entry.ema_t_fp <= 10 * 65536);
    }

    #[test]
    fn test_ema_value_out_of_range() {
        let mut entry = create_valid_proof_entry();
        entry.ema_t_fp = 11 * 65536; // Out of range

        // This would be caught by verify_pogq_proof
        assert!(entry.ema_t_fp > 10 * 65536);
    }

    #[test]
    fn test_consec_counters_mutual_exclusion() {
        let mut entry = create_valid_proof_entry();

        // Both counters non-zero is invalid
        entry.consec_viol_t = 3;
        entry.consec_clear_t = 2;

        assert!(entry.consec_viol_t > 0 && entry.consec_clear_t > 0);
    }

    #[test]
    fn test_zero_nonce_rejected() {
        let mut entry = create_valid_proof_entry();
        entry.nonce = [0u8; 32];

        // Zero nonce should be rejected
        assert_eq!(entry.nonce, [0u8; 32]);
    }

    // ========================================================================
    // Blake3 Provenance Verification Tests
    // ========================================================================

    #[test]
    fn test_blake3_provenance_deterministic() {
        let gradient = vec![0xab; 64];
        let round = 5u64;
        let profile = 128u32;
        let nonce = [0x12; 32];

        let prov1 = compute_blake3_provenance(&gradient, round, profile, &nonce);
        let prov2 = compute_blake3_provenance(&gradient, round, profile, &nonce);

        assert_eq!(prov1, prov2);
    }

    #[test]
    fn test_blake3_provenance_differs_by_gradient() {
        let gradient1 = vec![0xab; 64];
        let gradient2 = vec![0xcd; 64];
        let nonce = [0x12; 32];

        let prov1 = compute_blake3_provenance(&gradient1, 1, 128, &nonce);
        let prov2 = compute_blake3_provenance(&gradient2, 1, 128, &nonce);

        assert_ne!(prov1, prov2);
    }

    #[test]
    fn test_blake3_provenance_differs_by_round() {
        let gradient = vec![0xab; 64];
        let nonce = [0x12; 32];

        let prov1 = compute_blake3_provenance(&gradient, 1, 128, &nonce);
        let prov2 = compute_blake3_provenance(&gradient, 2, 128, &nonce);

        assert_ne!(prov1, prov2);
    }

    #[test]
    fn test_blake3_provenance_differs_by_profile() {
        let gradient = vec![0xab; 64];
        let nonce = [0x12; 32];

        let prov1 = compute_blake3_provenance(&gradient, 1, 128, &nonce);
        let prov2 = compute_blake3_provenance(&gradient, 1, 192, &nonce);

        assert_ne!(prov1, prov2);
    }

    #[test]
    fn test_blake3_provenance_differs_by_nonce() {
        let gradient = vec![0xab; 64];
        let nonce1 = [0x12; 32];
        let nonce2 = [0x34; 32];

        let prov1 = compute_blake3_provenance(&gradient, 1, 128, &nonce1);
        let prov2 = compute_blake3_provenance(&gradient, 1, 128, &nonce2);

        assert_ne!(prov1, prov2);
    }

    #[test]
    fn test_blake3_provenance_empty_gradient() {
        // Empty gradient should still produce valid hash
        let gradient: Vec<u8> = vec![];
        let nonce = [0x12; 32];

        let prov = compute_blake3_provenance(&gradient, 1, 128, &nonce);

        // Should not be all zeros
        assert!(!prov.iter().all(|&v| v == 0));
    }

    #[test]
    fn test_compute_gradient_commitment() {
        let gradient = vec![0xab; 64];

        let commitment = compute_gradient_commitment(&gradient);

        // Should be 32 bytes (Blake3 output size)
        assert_eq!(commitment.len(), 32);

        // Should not be all zeros
        assert!(!commitment.iter().all(|&b| b == 0));
    }

    #[test]
    fn test_compute_gradient_commitment_deterministic() {
        let gradient = vec![0xab; 64];

        let commitment1 = compute_gradient_commitment(&gradient);
        let commitment2 = compute_gradient_commitment(&gradient);

        assert_eq!(commitment1, commitment2);
    }

    #[test]
    fn test_verify_gradient_commitment_valid() {
        let gradient = vec![0xab; 64];
        let commitment = compute_gradient_commitment(&gradient);

        assert!(verify_gradient_commitment(&gradient, &commitment));
    }

    #[test]
    fn test_verify_gradient_commitment_invalid() {
        let gradient = vec![0xab; 64];
        let wrong_commitment = vec![0xff; 32];

        assert!(!verify_gradient_commitment(&gradient, &wrong_commitment));
    }

    #[test]
    fn test_verify_gradient_commitment_wrong_size() {
        let gradient = vec![0xab; 64];
        let short_commitment = vec![0xab; 16];

        assert!(!verify_gradient_commitment(&gradient, &short_commitment));
    }

    // ========================================================================
    // VerificationStatus Enum Tests
    // ========================================================================

    #[test]
    fn test_verification_status_fully_verified_is_usable() {
        let status = VerificationStatus::FullyVerified;
        assert!(status.is_usable());
        assert!(!status.is_invalid());
        assert!(!status.needs_external());
    }

    #[test]
    fn test_verification_status_partially_verified_is_usable() {
        let status = VerificationStatus::PartiallyVerified;
        assert!(status.is_usable());
        assert!(!status.is_invalid());
        assert!(status.needs_external());
    }

    #[test]
    fn test_verification_status_pending_external_not_usable() {
        let status = VerificationStatus::PendingExternal;
        assert!(!status.is_usable());
        assert!(!status.is_invalid());
        assert!(status.needs_external());
    }

    #[test]
    fn test_verification_status_invalid_not_usable() {
        let status = VerificationStatus::Invalid("Test error".to_string());
        assert!(!status.is_usable());
        assert!(status.is_invalid());
        assert!(!status.needs_external());
    }

    #[test]
    fn test_verification_status_error_message() {
        let status = VerificationStatus::Invalid("Test error message".to_string());
        assert_eq!(status.error_message(), Some("Test error message"));

        let status2 = VerificationStatus::PartiallyVerified;
        assert_eq!(status2.error_message(), None);
    }

    #[test]
    fn test_verification_status_equality() {
        assert_eq!(VerificationStatus::FullyVerified, VerificationStatus::FullyVerified);
        assert_eq!(VerificationStatus::PartiallyVerified, VerificationStatus::PartiallyVerified);
        assert_eq!(VerificationStatus::PendingExternal, VerificationStatus::PendingExternal);
        assert_eq!(
            VerificationStatus::Invalid("error".to_string()),
            VerificationStatus::Invalid("error".to_string())
        );

        // Different errors should not be equal
        assert_ne!(
            VerificationStatus::Invalid("error1".to_string()),
            VerificationStatus::Invalid("error2".to_string())
        );

        // Different variants should not be equal
        assert_ne!(VerificationStatus::FullyVerified, VerificationStatus::PartiallyVerified);
    }

    // ========================================================================
    // Documentation: Integration Test Scenarios
    // ========================================================================
    //
    // The following tests require a Holochain test conductor and should be
    // implemented as integration tests using the Holochain testing framework.
    //
    // ## Required Integration Tests:
    //
    // ### 1. Nonce Replay Attack Prevention
    // ```rust
    // #[test]
    // fn test_nonce_replay_attack_prevented() {
    //     // Setup: Create conductor with pogq_zome
    //     // 1. Publish proof with nonce N
    //     // 2. Attempt to publish second proof with same nonce N
    //     // 3. Assert: Second publish fails with "Nonce has already been used"
    // }
    // ```
    //
    // ### 2. Invalid Profile ID Rejection
    // ```rust
    // #[test]
    // fn test_invalid_profile_id_rejected() {
    //     // Setup: Create conductor
    //     // 1. Create proof with profile_id = 256
    //     // 2. Call publish_pogq_proof(proof)
    //     // 3. Assert: Returns Err("Invalid security profile: 256")
    // }
    // ```
    //
    // ### 3. Invalid Quarantine Status Rejection
    // ```rust
    // #[test]
    // fn test_invalid_quarantine_out_rejected() {
    //     // Setup: Create conductor
    //     // 1. Create proof with quarantine_out = 3
    //     // 2. Publish proof (should succeed - validation in verify)
    //     // 3. Call verify_pogq_proof(proof_hash)
    //     // 4. Assert: Returns VerificationResult { valid: false, error: "Invalid quarantine status: 3" }
    // }
    // ```
    //
    // ### 4. Round Mismatch Rejection
    // ```rust
    // #[test]
    // fn test_round_mismatch_rejected() {
    //     // Setup: Create conductor
    //     // 1. Create proof with round=5, current_round=3
    //     // 2. Publish proof
    //     // 3. Call verify_pogq_proof(proof_hash)
    //     // 4. Assert: Returns VerificationResult { valid: false, error: "Round mismatch" }
    // }
    // ```
    //
    // ### 5. Nonce Binding Validation
    // ```rust
    // #[test]
    // fn test_nonce_binding_enforced() {
    //     // Setup: Create conductor
    //     // 1. Publish proof with nonce N1
    //     // 2. Create gradient with nonce N2 (different)
    //     // 3. Call publish_gradient(gradient)
    //     // 4. Assert: Returns Err("Nonce mismatch - gradient not bound to proof")
    // }
    // ```
    //
    // ### 6. Gradient Round Mismatch
    // ```rust
    // #[test]
    // fn test_gradient_round_mismatch_rejected() {
    //     // Setup: Create conductor
    //     // 1. Publish proof for round 1
    //     // 2. Create gradient for round 2 (but linked to round 1 proof)
    //     // 3. Call publish_gradient(gradient)
    //     // 4. Assert: Returns Err("Round mismatch - gradient: 2, proof: 1")
    // }
    // ```
    //
    // ### 7. Sybil Weighting Calculation
    // ```rust
    // #[test]
    // fn test_sybil_weighting_zero_for_quarantined() {
    //     // Setup: Create conductor
    //     // 1. Publish 3 proofs: 2 healthy (quarantine_out=0), 1 quarantined (quarantine_out=1)
    //     // 2. Publish 3 gradients linked to respective proofs
    //     // 3. Call compute_sybil_weighted_aggregate(round)
    //     // 4. Assert: total_weight = 2.0, num_healthy = 2, num_quarantined = 1
    // }
    // ```
    //
    // ### 8. Empty Receipt Rejection
    // ```rust
    // #[test]
    // fn test_empty_receipt_rejected() {
    //     // Setup: Create conductor
    //     // 1. Create proof with receipt_bytes = vec![]
    //     // 2. Call publish_pogq_proof(proof)
    //     // 3. Assert: Returns Err("Receipt cannot be empty")
    // }
    // ```
    //
    // ### 9. Provenance Hash Validation
    // ```rust
    // #[test]
    // fn test_provenance_hash_accepted() {
    //     // Setup: Create conductor
    //     // 1. Create proof with prov_hash = [0, 0, 0, 0] (disabled)
    //     // 2. Publish and verify - should succeed (M0 accepts disabled provenance)
    //     // 3. Create proof with prov_hash = [12345, 67890, 11111, 22222] (enabled)
    //     // 4. Publish and verify - should succeed (M0 accepts enabled provenance)
    // }
    // ```
    //
    // ### 10. Multi-Node Byzantine Scenario
    // ```rust
    // #[test]
    // fn test_two_node_one_honest_one_byzantine() {
    //     // Setup: Create conductor with 2 nodes
    //     // Node 1 (Honest):
    //     //   - Publishes proof with quarantine_out=0
    //     //   - Publishes gradient with matching nonce
    //     // Node 2 (Byzantine):
    //     //   - Publishes proof with quarantine_out=1
    //     //   - Attempts to publish gradient with different nonce (should fail)
    //     //   - Attempts to reuse Node 1's nonce (should fail)
    //     // Assert:
    //     //   - Node 1 gradient accepted
    //     //   - Node 2 gradient rejected (nonce mismatch)
    //     //   - Node 2 second attempt rejected (nonce replay)
    //     //   - Sybil aggregate: total_weight = 1.0, num_quarantined = 1
    // }
    // ```
    //
    // ## Implementation Notes:
    //
    // Integration tests should be placed in:
    // - `holochain/zomes/pogq_zome/tests/integration.rs` (Rust-based)
    // - `holochain/tests/` (Tryorama-based if using JS/TS)
    //
    // Required setup for integration tests:
    // 1. Test conductor configuration
    // 2. DNA/zome installation
    // 3. Agent creation and setup
    // 4. Test utilities for creating valid entries
    //
    // See `holochain/zomes/gradient_storage/` for reference integration test patterns.
}
