// Copyright (C) 2024-2026 Tristan Stoltz / Luminous Dynamics
// SPDX-License-Identifier: AGPL-3.0-or-later
//! Permit-bound Cartesian hand reference generation.
//!
//! This is a reference contribution, not actuator authority. It maps one freshly
//! spatially-bound end-effector objective into a bounded normalized joint-space
//! correction using the existing solver/full-dynamics hand Jacobian. The result
//! is intended to enter the existing whole-body / inverse-dynamics stack as a
//! nominal contribution; it must still cross dynamics constraints, typed goal
//! authority, final safety projection, and independent HAL enforcement.
//!
//! The module deliberately does not implement object-contact force or grasp
//! retention semantics. Those remain unsupported until explicitly modeled.

use serde::{Deserialize, Serialize};

use crate::full_dynamics::{
    DynamicsComponentSource, FullRigidBodyDynamicsSnapshot, SpatialContactJacobian,
};
use crate::morphology::{HandSide, HumanoidMorphology};
use crate::skill_runtime::HumanoidSkillRequirementRole;
use crate::spatial_goal::HumanoidSpatiallyBoundSkillPermit;
use crate::types::{HumanoidCommand, HumanoidState};
use crate::whole_body_intent::{
    HumanoidWholeBodyMotionIntent, HumanoidWholeBodyObjectiveIR,
};

pub const HUMANOID_CARTESIAN_HAND_REFERENCE_PROFILE_SCHEMA_VERSION: u32 = 1;

/// Qualified/controller-tuned parameters for one exact manipulation subject and
/// hand. There is intentionally no `Default` implementation: dynamics lineage,
/// freshness bounds, gains and correction authority must be selected explicitly.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct HumanoidCartesianHandReferenceProfile {
    pub schema_version: u32,
    pub subject_fingerprint: u64,
    pub morphology: HumanoidMorphology,
    pub hand: HandSide,
    pub dynamics_model_id: String,
    pub expected_jacobian_source: DynamicsComponentSource,
    pub expected_actuator_limit_source: DynamicsComponentSource,
    pub maximum_dynamics_age_s: f64,
    pub maximum_state_age_s: f64,
    /// Minimum confidence attached to the selected hand Jacobian.
    pub minimum_jacobian_confidence: f64,
    /// Damped-least-squares regularization in Jacobian units.
    pub damping_lambda: f64,
    /// Cartesian proportional gain converting position error to desired velocity.
    pub position_gain_per_s: f64,
    /// Joint velocity error -> torque gain, N*m per (rad/s).
    pub velocity_error_gain_nm_per_rad_s: f64,
    /// Maximum absolute normalized correction generated by this reference layer.
    pub maximum_normalized_correction: f32,
}

impl HumanoidCartesianHandReferenceProfile {
    pub fn validate(&self) -> bool {
        self.schema_version == HUMANOID_CARTESIAN_HAND_REFERENCE_PROFILE_SCHEMA_VERSION
            && self.subject_fingerprint != 0
            && !self.dynamics_model_id.trim().is_empty()
            && self.dynamics_model_id == self.dynamics_model_id.trim()
            && self.dynamics_model_id.len() <= 256
            && self.maximum_dynamics_age_s.is_finite()
            && self.maximum_dynamics_age_s > 0.0
            && self.maximum_state_age_s.is_finite()
            && self.maximum_state_age_s > 0.0
            && self.minimum_jacobian_confidence.is_finite()
            && (0.0..=1.0).contains(&self.minimum_jacobian_confidence)
            && self.damping_lambda.is_finite()
            && self.damping_lambda > 0.0
            && self.position_gain_per_s.is_finite()
            && self.position_gain_per_s > 0.0
            && self.velocity_error_gain_nm_per_rad_s.is_finite()
            && self.velocity_error_gain_nm_per_rad_s > 0.0
            && self.maximum_normalized_correction.is_finite()
            && self.maximum_normalized_correction > 0.0
            && self.maximum_normalized_correction <= 1.0
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum HumanoidCartesianHandReferenceFailure {
    InvalidProfile,
    PermitIntentEpochMismatch,
    PermitIntentMorphologyMismatch,
    PermitIntentBackendMismatch,
    SpatialRoleMismatch,
    SpatialGoalMismatch,
    SpatialHandMismatch,
    MissingEndEffectorObjective,
    DuplicateEndEffectorObjective,
    SubjectNotBound,
    InvalidObjective,
    InvalidState,
    StateTimestampInFuture,
    StateStale,
    InvalidDynamics,
    DynamicsMorphologyMismatch,
    DynamicsModelMismatch,
    DynamicsTimestampInFuture,
    DynamicsStale,
    JacobianProvenanceMismatch,
    ActuatorLimitProvenanceMismatch,
    MissingHandJacobian,
    DuplicateHandJacobian,
    JacobianConfidenceTooLow,
    SingularTaskMetric,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct HumanoidCartesianHandReferenceReport {
    pub validation_epoch: u64,
    pub subject_fingerprint: u64,
    pub hand: HandSide,
    pub goal_id: String,
    pub dynamics_model_id: String,
    pub dynamics_age_s: f64,
    pub state_age_s: f64,
    pub jacobian_confidence: f64,
    pub position_error_world_m: [f64; 3],
    pub position_error_norm_m: f64,
    pub desired_cartesian_velocity_world_mps: [f64; 3],
    pub desired_cartesian_speed_mps: f64,
    pub desired_joint_velocity_norm_rad_s: f64,
    pub maximum_normalized_correction_used: f32,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct HumanoidCartesianHandReferenceResult {
    /// Normalized correction only. This is not an actuator-eligible command.
    pub correction: HumanoidCommand,
    pub report: HumanoidCartesianHandReferenceReport,
}

/// Generate a bounded hand reference from one still-live spatial permit and its
/// corresponding whole-body intent.
///
/// The world-space goal is taken from the live spatial permit, not reconstructed
/// from the IR's root-frame audit snapshot. The root-frame target is nevertheless
/// required to exactly match the permit binding so frame/goal substitution fails
/// closed.
pub fn lower_permitted_cartesian_hand_reference(
    bound: &HumanoidSpatiallyBoundSkillPermit<'_>,
    intent: &HumanoidWholeBodyMotionIntent,
    state: &HumanoidState,
    dynamics: &FullRigidBodyDynamicsSnapshot,
    profile: &HumanoidCartesianHandReferenceProfile,
    now_s: f64,
) -> Result<HumanoidCartesianHandReferenceResult, HumanoidCartesianHandReferenceFailure> {
    if !profile.validate() || !now_s.is_finite() || now_s < 0.0 {
        return Err(HumanoidCartesianHandReferenceFailure::InvalidProfile);
    }
    let semantic = bound.semantic();
    if intent.validation_epoch != semantic.epoch() {
        return Err(HumanoidCartesianHandReferenceFailure::PermitIntentEpochMismatch);
    }
    if intent.morphology != semantic.morphology() || profile.morphology != semantic.morphology() {
        return Err(HumanoidCartesianHandReferenceFailure::PermitIntentMorphologyMismatch);
    }
    if intent.backend_profile_id != semantic.backend_profile_id() {
        return Err(HumanoidCartesianHandReferenceFailure::PermitIntentBackendMismatch);
    }
    if bound.role() != HumanoidSkillRequirementRole::Manipulation {
        return Err(HumanoidCartesianHandReferenceFailure::SpatialRoleMismatch);
    }
    let expected_goal_id = intent.spatial_goal_id.as_deref();
    if expected_goal_id != Some(bound.goal().goal_id.as_str()) {
        return Err(HumanoidCartesianHandReferenceFailure::SpatialGoalMismatch);
    }
    if profile.hand != bound.goal().hand {
        return Err(HumanoidCartesianHandReferenceFailure::SpatialHandMismatch);
    }

    let end_effector = intent
        .objectives
        .iter()
        .filter_map(|objective| match objective {
            HumanoidWholeBodyObjectiveIR::EndEffectorTarget {
                hand,
                target_root_m,
                maximum_speed_mps,
            } => Some((*hand, *target_root_m, *maximum_speed_mps)),
            _ => None,
        })
        .collect::<Vec<_>>();
    let (hand, target_root_m, maximum_speed_mps) = match end_effector.as_slice() {
        [] => return Err(HumanoidCartesianHandReferenceFailure::MissingEndEffectorObjective),
        [objective] => *objective,
        _ => return Err(HumanoidCartesianHandReferenceFailure::DuplicateEndEffectorObjective),
    };
    if hand != profile.hand || hand != bound.goal().hand {
        return Err(HumanoidCartesianHandReferenceFailure::SpatialHandMismatch);
    }
    if !same_vec3_bits(target_root_m, bound.target_root_m()) {
        return Err(HumanoidCartesianHandReferenceFailure::SpatialGoalMismatch);
    }
    if !maximum_speed_mps.is_finite() || maximum_speed_mps < 0.0 {
        return Err(HumanoidCartesianHandReferenceFailure::InvalidObjective);
    }
    if !semantic
        .requirements()
        .iter()
        .any(|requirement| requirement.request.subject_fingerprint == profile.subject_fingerprint
            && requirement.role == HumanoidSkillRequirementRole::Manipulation)
    {
        return Err(HumanoidCartesianHandReferenceFailure::SubjectNotBound);
    }

    let n = profile.morphology.num_actuators();
    if state.joint_angles.len() != n
        || state.joint_velocities.len() != n
        || state.extremities.len() < 6
        || !state.root_position.iter().all(|value| value.is_finite())
        || !state.root_quaternion.iter().all(|value| value.is_finite())
        || !state.joint_angles.iter().all(|value| value.is_finite())
        || !state.joint_velocities.iter().all(|value| value.is_finite())
        || !state.extremities.iter().all(|value| value.is_finite())
        || !state.timestamp.is_finite()
        || state.timestamp < 0.0
    {
        return Err(HumanoidCartesianHandReferenceFailure::InvalidState);
    }
    if state.timestamp > now_s {
        return Err(HumanoidCartesianHandReferenceFailure::StateTimestampInFuture);
    }
    let state_age_s = now_s - state.timestamp;
    if state_age_s > profile.maximum_state_age_s {
        return Err(HumanoidCartesianHandReferenceFailure::StateStale);
    }

    if !dynamics.validate() {
        return Err(HumanoidCartesianHandReferenceFailure::InvalidDynamics);
    }
    if dynamics.morphology != profile.morphology {
        return Err(HumanoidCartesianHandReferenceFailure::DynamicsMorphologyMismatch);
    }
    if dynamics.model_id != profile.dynamics_model_id {
        return Err(HumanoidCartesianHandReferenceFailure::DynamicsModelMismatch);
    }
    if dynamics.sampled_at_s > now_s {
        return Err(HumanoidCartesianHandReferenceFailure::DynamicsTimestampInFuture);
    }
    let dynamics_age_s = now_s - dynamics.sampled_at_s;
    if dynamics_age_s > profile.maximum_dynamics_age_s {
        return Err(HumanoidCartesianHandReferenceFailure::DynamicsStale);
    }
    if dynamics.provenance.contact_jacobians != profile.expected_jacobian_source {
        return Err(HumanoidCartesianHandReferenceFailure::JacobianProvenanceMismatch);
    }
    if dynamics.provenance.actuator_limits != profile.expected_actuator_limit_source {
        return Err(HumanoidCartesianHandReferenceFailure::ActuatorLimitProvenanceMismatch);
    }

    let site_id = match hand {
        HandSide::Right => "r_hand_site",
        HandSide::Left => "l_hand_site",
    };
    let matching = dynamics
        .contacts
        .iter()
        .filter(|contact| contact.site_id == site_id)
        .collect::<Vec<_>>();
    let jacobian = match matching.as_slice() {
        [] => return Err(HumanoidCartesianHandReferenceFailure::MissingHandJacobian),
        [jacobian] => *jacobian,
        _ => return Err(HumanoidCartesianHandReferenceFailure::DuplicateHandJacobian),
    };
    if jacobian.confidence < profile.minimum_jacobian_confidence {
        return Err(HumanoidCartesianHandReferenceFailure::JacobianConfidenceTooLow);
    }

    let current_hand_world = hand_world_position(state, hand)
        .ok_or(HumanoidCartesianHandReferenceFailure::InvalidState)?;
    let target_world = bound.goal().target_world_m;
    let position_error_world_m = sub3(target_world, current_hand_world);
    let position_error_norm_m = norm3(position_error_world_m);
    let desired_unbounded = scale3(position_error_world_m, profile.position_gain_per_s);
    let desired_cartesian_velocity_world_mps =
        clamp_norm3(desired_unbounded, maximum_speed_mps);
    let desired_cartesian_speed_mps = norm3(desired_cartesian_velocity_world_mps);

    let desired_joint_velocity = damped_least_squares_joint_velocity(
        jacobian,
        desired_cartesian_velocity_world_mps,
        profile.damping_lambda,
    )
    .ok_or(HumanoidCartesianHandReferenceFailure::SingularTaskMetric)?;
    if desired_joint_velocity.len() != n {
        return Err(HumanoidCartesianHandReferenceFailure::InvalidDynamics);
    }

    let mut correction = HumanoidCommand::zero_for(n);
    let mut maximum_normalized_correction_used = 0.0f32;
    for joint in 0..n {
        let velocity_error = desired_joint_velocity[joint] - state.joint_velocities[joint];
        let torque_nm = profile.velocity_error_gain_nm_per_rad_s * velocity_error;
        let normalized = (torque_nm / dynamics.torque_limits_nm[joint]) as f32;
        let bounded = normalized.clamp(
            -profile.maximum_normalized_correction,
            profile.maximum_normalized_correction,
        );
        maximum_normalized_correction_used =
            maximum_normalized_correction_used.max(bounded.abs());
        correction.torques[joint] = bounded;
    }

    Ok(HumanoidCartesianHandReferenceResult {
        correction,
        report: HumanoidCartesianHandReferenceReport {
            validation_epoch: semantic.epoch(),
            subject_fingerprint: profile.subject_fingerprint,
            hand,
            goal_id: bound.goal().goal_id.clone(),
            dynamics_model_id: dynamics.model_id.clone(),
            dynamics_age_s,
            state_age_s,
            jacobian_confidence: jacobian.confidence,
            position_error_world_m,
            position_error_norm_m,
            desired_cartesian_velocity_world_mps,
            desired_cartesian_speed_mps,
            desired_joint_velocity_norm_rad_s: vector_norm(&desired_joint_velocity),
            maximum_normalized_correction_used,
        },
    })
}

fn hand_world_position(state: &HumanoidState, hand: HandSide) -> Option<[f64; 3]> {
    let start = match hand {
        HandSide::Right => 0,
        HandSide::Left => 3,
    };
    let values = state.extremities.get(start..start + 3)?;
    values.iter().all(|value| value.is_finite()).then_some([
        values[0], values[1], values[2],
    ])
}

/// Damped least-squares inverse `qdot = J^T (J J^T + lambda^2 I)^-1 v`
/// using the translational rows of an actuated 6xN spatial Jacobian.
fn damped_least_squares_joint_velocity(
    jacobian: &SpatialContactJacobian,
    desired_velocity: [f64; 3],
    damping_lambda: f64,
) -> Option<Vec<f64>> {
    if !damping_lambda.is_finite() || damping_lambda <= 0.0 {
        return None;
    }
    let n = jacobian.rows[3].len();
    if n == 0
        || jacobian.rows[4].len() != n
        || jacobian.rows[5].len() != n
        || !desired_velocity.iter().all(|value| value.is_finite())
    {
        return None;
    }
    let j = [&jacobian.rows[3], &jacobian.rows[4], &jacobian.rows[5]];
    let mut metric = [[0.0f64; 3]; 3];
    for row in 0..3 {
        for column in 0..3 {
            metric[row][column] = (0..n).map(|index| j[row][index] * j[column][index]).sum();
        }
        metric[row][row] += damping_lambda * damping_lambda;
    }
    let inverse = inverse3(metric)?;
    let task_dual = mat3_vec(inverse, desired_velocity);
    let mut qdot = vec![0.0; n];
    for joint in 0..n {
        qdot[joint] = j[0][joint] * task_dual[0]
            + j[1][joint] * task_dual[1]
            + j[2][joint] * task_dual[2];
    }
    qdot.iter().all(|value| value.is_finite()).then_some(qdot)
}

fn inverse3(matrix: [[f64; 3]; 3]) -> Option<[[f64; 3]; 3]> {
    if !matrix.iter().flatten().all(|value| value.is_finite()) {
        return None;
    }
    let [a, b, c] = matrix[0];
    let [d, e, f] = matrix[1];
    let [g, h, i] = matrix[2];
    let c00 = e * i - f * h;
    let c01 = -(d * i - f * g);
    let c02 = d * h - e * g;
    let c10 = -(b * i - c * h);
    let c11 = a * i - c * g;
    let c12 = -(a * h - b * g);
    let c20 = b * f - c * e;
    let c21 = -(a * f - c * d);
    let c22 = a * e - b * d;
    let determinant = a * c00 + b * c01 + c * c02;
    let scale = matrix
        .iter()
        .flatten()
        .map(|value| value.abs())
        .fold(1.0f64, f64::max);
    if !determinant.is_finite() || determinant.abs() <= 1e-12 * scale.powi(3) {
        return None;
    }
    let inv_det = determinant.recip();
    // inverse = transpose(cofactor) / det
    Some([
        [c00 * inv_det, c10 * inv_det, c20 * inv_det],
        [c01 * inv_det, c11 * inv_det, c21 * inv_det],
        [c02 * inv_det, c12 * inv_det, c22 * inv_det],
    ])
}

fn mat3_vec(matrix: [[f64; 3]; 3], vector: [f64; 3]) -> [f64; 3] {
    [
        matrix[0][0] * vector[0] + matrix[0][1] * vector[1] + matrix[0][2] * vector[2],
        matrix[1][0] * vector[0] + matrix[1][1] * vector[1] + matrix[1][2] * vector[2],
        matrix[2][0] * vector[0] + matrix[2][1] * vector[1] + matrix[2][2] * vector[2],
    ]
}

fn clamp_norm3(vector: [f64; 3], maximum_norm: f64) -> [f64; 3] {
    if !maximum_norm.is_finite() || maximum_norm <= 0.0 {
        return [0.0; 3];
    }
    let norm = norm3(vector);
    if !norm.is_finite() || norm <= maximum_norm || norm <= 1e-12 {
        vector
    } else {
        scale3(vector, maximum_norm / norm)
    }
}

fn sub3(a: [f64; 3], b: [f64; 3]) -> [f64; 3] {
    [a[0] - b[0], a[1] - b[1], a[2] - b[2]]
}

fn scale3(vector: [f64; 3], scalar: f64) -> [f64; 3] {
    [vector[0] * scalar, vector[1] * scalar, vector[2] * scalar]
}

fn norm3(vector: [f64; 3]) -> f64 {
    (vector[0] * vector[0] + vector[1] * vector[1] + vector[2] * vector[2]).sqrt()
}

fn vector_norm(values: &[f64]) -> f64 {
    values.iter().map(|value| value * value).sum::<f64>().sqrt()
}

fn same_vec3_bits(left: [f64; 3], right: [f64; 3]) -> bool {
    (0..3).all(|axis| left[axis].to_bits() == right[axis].to_bits())
}

#[cfg(test)]
mod tests {
    use super::*;

    fn jacobian(rows: [[f64; 2]; 3]) -> SpatialContactJacobian {
        SpatialContactJacobian {
            site_id: "r_hand_site".into(),
            rows: [
                vec![0.0; 2],
                vec![0.0; 2],
                vec![0.0; 2],
                rows[0].to_vec(),
                rows[1].to_vec(),
                rows[2].to_vec(),
            ],
            confidence: 1.0,
        }
    }

    #[test]
    fn damped_inverse_maps_identity_axes_without_cross_coupling() {
        let j = jacobian([[1.0, 0.0], [0.0, 1.0], [0.0, 0.0]]);
        let qdot = damped_least_squares_joint_velocity(&j, [0.2, -0.1, 0.0], 0.01).unwrap();
        assert!(qdot[0] > 0.19 && qdot[0] < 0.201);
        assert!(qdot[1] < -0.099 && qdot[1] > -0.101);
    }

    #[test]
    fn velocity_reference_is_norm_bounded_without_direction_change() {
        let bounded = clamp_norm3([3.0, 4.0, 0.0], 1.0);
        assert!((norm3(bounded) - 1.0).abs() < 1e-12);
        assert!((bounded[0] / bounded[1] - 0.75).abs() < 1e-12);
    }

    #[test]
    fn positive_damping_keeps_rank_deficient_task_metric_invertible() {
        let j = jacobian([[1.0, 0.0], [0.0, 0.0], [0.0, 0.0]]);
        let qdot = damped_least_squares_joint_velocity(&j, [0.1, 0.1, 0.1], 0.1).unwrap();
        assert!(qdot.iter().all(|value| value.is_finite()));
    }
}
