// Copyright (C) 2024-2026 Tristan Stoltz / Luminous Dynamics
// SPDX-License-Identifier: AGPL-3.0-or-later

//! Humanoid adapter into the shared mathematical configuration-space substrate.
//!
//! The adapter does not introduce a second humanoid state model. It derives
//! ordered bounded-revolute joint factors from [`HumanoidMorphology`]'s existing
//! names/limits and maps [`HumanoidState`]'s existing root pose + joint angles
//! into the generic state-space representation.

use std::fmt;

use symthaea_core::configuration_space::{
    ConfigurationSpaceError, DEFAULT_SO3_NEAR_IDENTITY_DOT_TOLERANCE,
    JointConfigurationSpace, JointSpec, RigidPose3, Se3Space,
};
use symthaea_core::state_space::{ProductSpace, StateSpaceError};

use crate::morphology::HumanoidMorphology;
use crate::types::HumanoidState;

/// Exact mathematical configuration space used by the current humanoid adapter.
pub type HumanoidConfigurationSpace = ProductSpace<Se3Space, JointConfigurationSpace>;

/// State representation corresponding to [`HumanoidConfigurationSpace`].
pub type HumanoidConfigurationState = (RigidPose3, Vec<f64>);

/// Explicit metric/numerical profile for deriving a humanoid configuration space.
#[derive(Clone, Copy, Debug, PartialEq)]
pub struct HumanoidConfigurationMetricProfile {
    /// Weight applied to root translation within `SE(3)`.
    pub translation_weight: f64,
    /// Weight applied to root rotation within `SE(3)`.
    pub rotation_weight: f64,
    /// Weight applied independently to each current actuated hinge coordinate.
    pub joint_weight: f64,
    /// Unit-quaternion validation tolerance.
    pub quaternion_tolerance: f64,
    /// Near-identity quaternion dot-product threshold for SLERP fallback.
    pub near_identity_dot_tolerance: f64,
    /// Fixed-coordinate tolerance reserved for future fixed semantic factors.
    pub fixed_tolerance: f64,
}

impl HumanoidConfigurationMetricProfile {
    /// Named neutral software-reference profile.
    ///
    /// The unit weights are a mathematical benchmark convention only; they do
    /// not assert that one metre and one radian have equivalent physical cost.
    pub const fn reference_v1() -> Self {
        Self {
            translation_weight: 1.0,
            rotation_weight: 1.0,
            joint_weight: 1.0,
            quaternion_tolerance: 1e-10,
            near_identity_dot_tolerance: DEFAULT_SO3_NEAR_IDENTITY_DOT_TOLERANCE,
            fixed_tolerance: 1e-12,
        }
    }
}

/// Construction errors for the humanoid configuration-space adapter.
#[derive(Debug, PartialEq)]
pub enum HumanoidConfigurationSpaceError {
    /// Generic Lie/joint-space profile construction failed.
    Configuration(ConfigurationSpaceError),
    /// Product-space composition failed.
    StateSpace(StateSpaceError),
    /// Morphology name/limit tables disagree structurally.
    MorphologyTableMismatch { names: usize, limits: usize },
}

impl fmt::Display for HumanoidConfigurationSpaceError {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::Configuration(error) => write!(formatter, "{error}"),
            Self::StateSpace(error) => write!(formatter, "{error}"),
            Self::MorphologyTableMismatch { names, limits } => write!(
                formatter,
                "morphology exposes {names} joint names but {limits} joint limits"
            ),
        }
    }
}

impl std::error::Error for HumanoidConfigurationSpaceError {}

impl From<ConfigurationSpaceError> for HumanoidConfigurationSpaceError {
    fn from(error: ConfigurationSpaceError) -> Self {
        Self::Configuration(error)
    }
}

impl From<StateSpaceError> for HumanoidConfigurationSpaceError {
    fn from(error: StateSpaceError) -> Self {
        Self::StateSpace(error)
    }
}

/// Derive the exact root-pose × articulated-joint space for one morphology.
///
/// All currently actuated joints generated by `HumanoidMorphology::to_mjcf()`
/// are bounded hinge coordinates, so they map to bounded revolute factors. If a
/// future morphology adds a prismatic or continuous actuator, this adapter must
/// be extended explicitly rather than inferring topology from a name.
pub fn humanoid_configuration_space(
    morphology: HumanoidMorphology,
    metric: HumanoidConfigurationMetricProfile,
) -> Result<HumanoidConfigurationSpace, HumanoidConfigurationSpaceError> {
    let names = morphology.joint_names();
    let limits = morphology.joint_limits();
    if names.len() != limits.len() {
        return Err(HumanoidConfigurationSpaceError::MorphologyTableMismatch {
            names: names.len(),
            limits: limits.len(),
        });
    }

    let specs = names
        .into_iter()
        .zip(limits)
        .map(|(name, [min, max])| {
            JointSpec::bounded_revolute(name, min, max, metric.joint_weight)
        })
        .collect();

    let root = Se3Space::with_numerical_policy(
        metric.translation_weight,
        metric.rotation_weight,
        metric.quaternion_tolerance,
        metric.near_identity_dot_tolerance,
    )?;
    let joints = JointConfigurationSpace::new(specs, metric.fixed_tolerance)?;

    // Factor-internal metrics already bind the meaningful weights. The outer
    // product uses unit structural weights so it does not introduce a second,
    // hidden scaling layer.
    Ok(ProductSpace::new(root, joints, 1.0, 1.0)?)
}

/// Map an existing humanoid state into the generic configuration representation.
pub fn humanoid_configuration_state(state: &HumanoidState) -> HumanoidConfigurationState {
    (
        RigidPose3 {
            translation: state.root_position,
            rotation: state.root_quaternion,
        },
        state.joint_angles.clone(),
    )
}

#[cfg(test)]
mod tests {
    use super::*;
    use symthaea_core::state_space::{MetricSpace, StateSpace};

    #[test]
    fn dmc21_derives_six_plus_twenty_one_intrinsic_dimensions() {
        let space = humanoid_configuration_space(
            HumanoidMorphology::Dmc21,
            HumanoidConfigurationMetricProfile::reference_v1(),
        )
        .unwrap();
        assert_eq!(space.intrinsic_dimension(), Some(27));
        assert_eq!(space.second().coordinate_count(), 21);
    }

    #[test]
    fn default_humanoid_state_is_valid_configuration() {
        let morphology = HumanoidMorphology::Dmc21;
        let space = humanoid_configuration_space(
            morphology,
            HumanoidConfigurationMetricProfile::reference_v1(),
        )
        .unwrap();
        let state = HumanoidState::default_for(morphology);
        let configuration = humanoid_configuration_state(&state);
        assert!(space.validate_state(&configuration).is_valid());
    }

    #[test]
    fn morphology_limits_are_enforced_without_clipping() {
        let morphology = HumanoidMorphology::Dmc21;
        let space = humanoid_configuration_space(
            morphology,
            HumanoidConfigurationMetricProfile::reference_v1(),
        )
        .unwrap();
        let mut state = HumanoidState::default_for(morphology);
        let upper = morphology.joint_limits()[0][1];
        state.joint_angles[0] = upper + 0.1;
        let configuration = humanoid_configuration_state(&state);
        assert!(!space.validate_state(&configuration).is_valid());
    }

    #[test]
    fn quaternion_double_cover_does_not_create_pose_distance() {
        let morphology = HumanoidMorphology::Dmc21;
        let space = humanoid_configuration_space(
            morphology,
            HumanoidConfigurationMetricProfile::reference_v1(),
        )
        .unwrap();
        let state = HumanoidState::default_for(morphology);
        let a = humanoid_configuration_state(&state);
        let mut b = a.clone();
        for value in &mut b.0.rotation {
            *value = -*value;
        }
        assert!(space.distance(&a, &b).unwrap() <= 1e-12);
    }

    #[test]
    fn morphology_and_numerical_policy_change_exact_profile() {
        let metric = HumanoidConfigurationMetricProfile::reference_v1();
        let dmc = humanoid_configuration_space(HumanoidMorphology::Dmc21, metric).unwrap();
        let extended =
            humanoid_configuration_space(HumanoidMorphology::WithNeckWrist, metric).unwrap();
        assert_ne!(dmc.profile().identity(), extended.profile().identity());

        let mut changed = metric;
        changed.near_identity_dot_tolerance = 1e-9;
        let changed = humanoid_configuration_space(HumanoidMorphology::Dmc21, changed).unwrap();
        assert_ne!(dmc.profile().identity(), changed.profile().identity());
    }
}
