// Copyright (C) 2024-2026 Tristan Stoltz / Luminous Dynamics
// SPDX-License-Identifier: AGPL-3.0-or-later
//! Typed bilateral foot-contact and support geometry.
//!
//! Contact frames are privileged embodiment data. They are deliberately kept
//! separate from the stable policy observation schema so simulators can expose
//! ground-reaction truth while hardware can provide force-plate or foot-sensor
//! estimates without silently changing the learned representation.

use serde::{Deserialize, Serialize};

use crate::types::HumanoidState;

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum ContactSource {
    /// Estimated only from foot height. Useful as an explicit fallback.
    KinematicEstimate,
    /// Produced by the simple simulator's compliant ground-reaction model.
    GroundReactionModel,
    /// Produced by a physical force or pressure sensor.
    ForceSensor,
    /// Produced directly from a rigid-body contact solver wrench.
    SolverWrench,
    /// No trustworthy contact information is available.
    Unavailable,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum BipedSupport {
    Flight,
    Right,
    Left,
    Double,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum ContactQuality {
    Unavailable,
    Stale,
    Kinematic,
    Modeled,
    Measured,
}

#[derive(Debug, Clone, Copy, Serialize, Deserialize)]
pub struct FootContact {
    pub in_contact: bool,
    pub point_world_m: [f64; 3],
    pub force_world_n: [f64; 3],
    pub torque_world_nm: [f64; 3],
    pub center_of_pressure_world_m: [f64; 2],
    pub confidence: f64,
}

impl FootContact {
    pub const fn unavailable() -> Self {
        Self {
            in_contact: false,
            point_world_m: [0.0; 3],
            force_world_n: [0.0; 3],
            torque_world_nm: [0.0; 3],
            center_of_pressure_world_m: [0.0; 2],
            confidence: 0.0,
        }
    }
}

#[derive(Debug, Clone, Copy, Serialize, Deserialize)]
pub struct ContactFrame {
    pub right: FootContact,
    pub left: FootContact,
    pub source: ContactSource,
    pub timestamp: f64,
}

impl ContactFrame {
    pub fn unavailable(timestamp: f64) -> Self {
        Self {
            right: FootContact::unavailable(),
            left: FootContact::unavailable(),
            source: ContactSource::Unavailable,
            timestamp,
        }
    }

    pub fn estimated_from_state(state: &HumanoidState, threshold_m: f64) -> Self {
        let right = foot_from_state(state, 6, threshold_m);
        let left = foot_from_state(state, 9, threshold_m);
        Self {
            right,
            left,
            source: ContactSource::KinematicEstimate,
            timestamp: state.timestamp,
        }
    }

    pub fn from_ground_reaction_forces(
        state: &HumanoidState,
        right_force_n: [f64; 3],
        left_force_n: [f64; 3],
    ) -> Self {
        let mut frame = Self::estimated_from_state(state, 0.05);
        frame.source = ContactSource::GroundReactionModel;
        frame.right.force_world_n = right_force_n;
        frame.left.force_world_n = left_force_n;
        frame.right.torque_world_nm = [0.0; 3];
        frame.left.torque_world_nm = [0.0; 3];
        frame.right.in_contact = right_force_n[2] > 1.0;
        frame.left.in_contact = left_force_n[2] > 1.0;
        frame.right.confidence = 1.0;
        frame.left.confidence = 1.0;
        frame
    }

    /// Construct a frame from solver-derived spatial wrenches. MuJoCo-style
    /// body wrenches are represented as `[torque_xyz, force_xyz]`.
    pub fn from_solver_wrenches(
        state: &HumanoidState,
        right_wrench: [f64; 6],
        left_wrench: [f64; 6],
    ) -> Self {
        let mut frame = Self::estimated_from_state(state, 0.05);
        frame.source = ContactSource::SolverWrench;
        for (foot, wrench) in [
            (&mut frame.right, right_wrench),
            (&mut frame.left, left_wrench),
        ] {
            foot.torque_world_nm = [wrench[0], wrench[1], wrench[2]];
            foot.force_world_n = [wrench[3], wrench[4], wrench[5]];
            foot.in_contact = foot.force_world_n[2] > 1.0;
            foot.confidence = 1.0;
            if foot.force_world_n[2].abs() > 1.0e-6 {
                // CoP from the moment generated by a force acting at the floor:
                // tau_x = r_y * f_z and tau_y = -r_x * f_z.
                let dx = -foot.torque_world_nm[1] / foot.force_world_n[2];
                let dy = foot.torque_world_nm[0] / foot.force_world_n[2];
                foot.center_of_pressure_world_m = [
                    foot.point_world_m[0] + dx.clamp(-0.15, 0.15),
                    foot.point_world_m[1] + dy.clamp(-0.08, 0.08),
                ];
            }
        }
        frame
    }

    pub const fn support(&self) -> BipedSupport {
        match (self.right.in_contact, self.left.in_contact) {
            (false, false) => BipedSupport::Flight,
            (true, false) => BipedSupport::Right,
            (false, true) => BipedSupport::Left,
            (true, true) => BipedSupport::Double,
        }
    }

    pub fn total_normal_force_n(&self) -> f64 {
        self.right.force_world_n[2].max(0.0) + self.left.force_world_n[2].max(0.0)
    }

    pub fn minimum_confidence(&self) -> f64 {
        match self.support() {
            BipedSupport::Flight => self.right.confidence.max(self.left.confidence),
            BipedSupport::Right => self.right.confidence,
            BipedSupport::Left => self.left.confidence,
            BipedSupport::Double => self.right.confidence.min(self.left.confidence),
        }
        .clamp(0.0, 1.0)
    }

    pub fn age_s(&self, now_s: f64) -> f64 {
        if !now_s.is_finite() || !self.timestamp.is_finite() || self.timestamp > now_s {
            return f64::INFINITY;
        }
        now_s - self.timestamp
    }

    pub fn quality_at(&self, now_s: f64, maximum_age_s: f64) -> ContactQuality {
        if self.source == ContactSource::Unavailable {
            return ContactQuality::Unavailable;
        }
        if self.age_s(now_s) > maximum_age_s.max(0.0) {
            return ContactQuality::Stale;
        }
        match self.source {
            ContactSource::Unavailable => ContactQuality::Unavailable,
            ContactSource::KinematicEstimate => ContactQuality::Kinematic,
            ContactSource::GroundReactionModel => ContactQuality::Modeled,
            ContactSource::ForceSensor | ContactSource::SolverWrench => ContactQuality::Measured,
        }
    }

    /// Conservative authority multiplier for recovery and learned residuals.
    /// Unavailable or stale contact truth does not disable all motion, but it
    /// prevents high-authority capture stepping from being treated as certain.
    pub fn control_trust(&self, now_s: f64, maximum_age_s: f64) -> f32 {
        let source_trust = match self.quality_at(now_s, maximum_age_s) {
            ContactQuality::Unavailable => 0.30,
            ContactQuality::Stale => 0.20,
            ContactQuality::Kinematic => 0.55,
            ContactQuality::Modeled => 0.82,
            ContactQuality::Measured => 1.0,
        };
        (source_trust * self.minimum_confidence()).clamp(0.15, 1.0) as f32
    }

    /// Force-weighted center of pressure. Falls back to the geometric support
    /// center when only kinematic contact is available.
    pub fn center_of_pressure_world_m(&self) -> Option<[f64; 2]> {
        let rz = self.right.force_world_n[2].max(0.0);
        let lz = self.left.force_world_n[2].max(0.0);
        let total = rz + lz;
        if total > 1e-6 {
            return Some([
                (rz * self.right.center_of_pressure_world_m[0]
                    + lz * self.left.center_of_pressure_world_m[0])
                    / total,
                (rz * self.right.center_of_pressure_world_m[1]
                    + lz * self.left.center_of_pressure_world_m[1])
                    / total,
            ]);
        }
        match self.support() {
            BipedSupport::Right => Some(self.right.center_of_pressure_world_m),
            BipedSupport::Left => Some(self.left.center_of_pressure_world_m),
            BipedSupport::Double => Some([
                0.5 * (self.right.center_of_pressure_world_m[0]
                    + self.left.center_of_pressure_world_m[0]),
                0.5 * (self.right.center_of_pressure_world_m[1]
                    + self.left.center_of_pressure_world_m[1]),
            ]),
            BipedSupport::Flight => None,
        }
    }

    /// Conservative signed support margin in meters. Positive is inside a
    /// rectangular approximation of the active support polygon.
    pub fn support_margin_m(&self, point_world_m: [f64; 2]) -> f64 {
        let contacts: Vec<[f64; 2]> = [self.right, self.left]
            .into_iter()
            .filter(|foot| foot.in_contact)
            .map(|foot| foot.center_of_pressure_world_m)
            .collect();
        if contacts.is_empty() {
            return f64::NEG_INFINITY;
        }
        let min_x = contacts.iter().map(|p| p[0]).fold(f64::INFINITY, f64::min) - 0.11;
        let max_x = contacts
            .iter()
            .map(|p| p[0])
            .fold(f64::NEG_INFINITY, f64::max)
            + 0.11;
        let min_y = contacts.iter().map(|p| p[1]).fold(f64::INFINITY, f64::min) - 0.055;
        let max_y = contacts
            .iter()
            .map(|p| p[1])
            .fold(f64::NEG_INFINITY, f64::max)
            + 0.055;
        [
            point_world_m[0] - min_x,
            max_x - point_world_m[0],
            point_world_m[1] - min_y,
            max_y - point_world_m[1],
        ]
        .into_iter()
        .fold(f64::INFINITY, f64::min)
    }
}

fn foot_from_state(state: &HumanoidState, offset: usize, threshold_m: f64) -> FootContact {
    let Some(values) = state.extremities.get(offset..offset + 3) else {
        return FootContact::unavailable();
    };
    let point = [values[0], values[1], values[2]];
    let in_contact = point[2].is_finite() && point[2] <= threshold_m;
    FootContact {
        in_contact,
        point_world_m: point,
        force_world_n: [0.0; 3],
        torque_world_nm: [0.0; 3],
        center_of_pressure_world_m: [point[0], point[1]],
        confidence: if in_contact { 0.55 } else { 0.35 },
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn standing_state_has_double_kinematic_support() {
        let mut state = HumanoidState::standing();
        state.extremities[8] = 0.0;
        state.extremities[11] = 0.0;
        let frame = ContactFrame::estimated_from_state(&state, 0.03);
        assert_eq!(frame.support(), BipedSupport::Double);
        assert!(frame.center_of_pressure_world_m().is_some());
    }

    #[test]
    fn stale_contact_truth_reduces_control_trust() {
        let state = HumanoidState::standing();
        let frame = ContactFrame::estimated_from_state(&state, 0.03);
        assert!(frame.control_trust(state.timestamp, 0.05) > frame.control_trust(1.0, 0.05));
        assert_eq!(frame.quality_at(1.0, 0.05), ContactQuality::Stale);
    }

    #[test]
    fn solver_wrench_recovers_center_of_pressure_offset() {
        let mut state = HumanoidState::standing();
        state.extremities[6..9].copy_from_slice(&[0.0, -0.1, 0.0]);
        let frame = ContactFrame::from_solver_wrenches(
            &state,
            [20.0, -40.0, 0.0, 0.0, 0.0, 400.0],
            [0.0; 6],
        );
        assert_eq!(frame.source, ContactSource::SolverWrench);
        assert!(frame.right.center_of_pressure_world_m[0] > 0.0);
        assert!(frame.right.center_of_pressure_world_m[1] > -0.1);
    }

    #[test]
    fn force_weighted_cop_favors_loaded_foot() {
        let mut state = HumanoidState::standing();
        state.extremities[6..9].copy_from_slice(&[0.0, -0.1, 0.0]);
        state.extremities[9..12].copy_from_slice(&[0.0, 0.1, 0.0]);
        let frame =
            ContactFrame::from_ground_reaction_forces(&state, [0.0, 0.0, 700.0], [0.0, 0.0, 100.0]);
        assert!(frame.center_of_pressure_world_m().unwrap()[1] < 0.0);
    }
    #[test]
    fn future_dated_contact_is_not_trusted() {
        let state = HumanoidState::standing();
        let mut frame = ContactFrame::estimated_from_state(&state, 0.05);
        frame.timestamp = state.timestamp + 1.0;
        assert_eq!(
            frame.quality_at(state.timestamp, 0.1),
            ContactQuality::Stale
        );
        assert!(frame.control_trust(state.timestamp, 0.1) <= 0.2);
    }
}
