use symthaea_research_split::{
    AssignedUnit, GroupRef, GroupSeparationPolicy, PartitionRole, ResearchSplitManifest,
    SeparationEvidence, SeparationEvidenceKind, SplitError, SplitUnit, TemporalSeparationPolicy,
};

fn groups(spatial: &str, acquisition: &str) -> Vec<GroupRef> {
    vec![
        GroupRef::new("spatial-block", spatial).unwrap(),
        GroupRef::new("acquisition", acquisition).unwrap(),
    ]
}

fn assigned(
    id: &str,
    time: i64,
    spatial: &str,
    acquisition: &str,
    role: PartitionRole,
) -> AssignedUnit {
    AssignedUnit::new(
        SplitUnit::new(
            id,
            time,
            format!("digest:{id}"),
            groups(spatial, acquisition),
        )
        .unwrap(),
        role,
    )
}

fn eval_disjoint() -> GroupSeparationPolicy {
    GroupSeparationPolicy::EvaluationDisjoint {
        dimensions: vec!["spatial-block".into(), "acquisition".into()],
    }
}

fn valid_manifest() -> ResearchSplitManifest {
    ResearchSplitManifest::new(
        "split-a",
        vec![
            assigned("train-1", 1_000, "s-a", "a-1", PartitionRole::Training),
            assigned(
                "cal-1",
                1_100,
                "s-a",
                "a-1",
                PartitionRole::Calibration,
            ),
            assigned(
                "eval-1",
                2_000,
                "s-b",
                "a-2",
                PartitionRole::Evaluation,
            ),
        ],
        eval_disjoint(),
        TemporalSeparationPolicy::ForwardEvaluation { embargo_ms: 500 },
        vec![SeparationEvidence::new(
            SeparationEvidenceKind::GroupDefinition,
            "spatial-block ids were generated by frozen watershed boundaries",
            "digest:group-definition",
        )
        .unwrap()],
    )
    .unwrap()
}

#[test]
fn valid_split_is_content_addressed_and_summarized() {
    let manifest = valid_manifest();
    manifest.verify_digest().unwrap();
    let summary = manifest.summary();
    assert_eq!(summary.training_count, 1);
    assert_eq!(summary.calibration_count, 1);
    assert_eq!(summary.evaluation_count, 1);
    assert_eq!(summary.latest_development_unix_ms, Some(1_100));
    assert_eq!(summary.earliest_evaluation_unix_ms, Some(2_000));
    assert_eq!(summary.observed_temporal_gap_ms, Some(900));
}

#[test]
fn duplicate_sample_ids_fail_closed() {
    let result = ResearchSplitManifest::new(
        "split",
        vec![
            assigned("same", 1_000, "s-a", "a-1", PartitionRole::Training),
            assigned("same", 2_000, "s-b", "a-2", PartitionRole::Evaluation),
        ],
        eval_disjoint(),
        TemporalSeparationPolicy::None,
        vec![],
    );
    assert!(matches!(result, Err(SplitError::DuplicateSampleId(id)) if id == "same"));
}

#[test]
fn evaluation_cannot_share_spatial_block_with_development() {
    let result = ResearchSplitManifest::new(
        "split",
        vec![
            assigned("train", 1_000, "shared", "a-1", PartitionRole::Training),
            assigned("eval", 2_000, "shared", "a-2", PartitionRole::Evaluation),
        ],
        eval_disjoint(),
        TemporalSeparationPolicy::None,
        vec![],
    );
    assert!(matches!(
        result,
        Err(SplitError::GroupLeakage { dimension, value, .. })
            if dimension == "spatial-block" && value == "shared"
    ));
}

#[test]
fn multiple_dimensions_are_enforced_independently() {
    let result = ResearchSplitManifest::new(
        "split",
        vec![
            assigned("train", 1_000, "s-a", "same-acq", PartitionRole::Training),
            assigned("eval", 2_000, "s-b", "same-acq", PartitionRole::Evaluation),
        ],
        eval_disjoint(),
        TemporalSeparationPolicy::None,
        vec![],
    );
    assert!(matches!(
        result,
        Err(SplitError::GroupLeakage { dimension, value, .. })
            if dimension == "acquisition" && value == "same-acq"
    ));
}

#[test]
fn required_group_dimension_must_exist_on_every_sample() {
    let train = AssignedUnit::new(
        SplitUnit::new(
            "train",
            1_000,
            "digest:train",
            vec![GroupRef::new("spatial-block", "s-a").unwrap()],
        )
        .unwrap(),
        PartitionRole::Training,
    );
    let eval = assigned("eval", 2_000, "s-b", "a-2", PartitionRole::Evaluation);
    let result = ResearchSplitManifest::new(
        "split",
        vec![train, eval],
        eval_disjoint(),
        TemporalSeparationPolicy::None,
        vec![],
    );
    assert!(matches!(
        result,
        Err(SplitError::MissingRequiredGroupDimension { sample_id, dimension })
            if sample_id == "train" && dimension == "acquisition"
    ));
}

#[test]
fn evaluation_disjoint_allows_training_calibration_group_sharing() {
    let manifest = ResearchSplitManifest::new(
        "split",
        vec![
            assigned("train", 1_000, "s-a", "a-1", PartitionRole::Training),
            assigned("cal", 1_100, "s-a", "a-1", PartitionRole::Calibration),
            assigned("eval", 2_000, "s-b", "a-2", PartitionRole::Evaluation),
        ],
        eval_disjoint(),
        TemporalSeparationPolicy::None,
        vec![],
    )
    .unwrap();
    manifest.verify_digest().unwrap();
}

#[test]
fn all_roles_disjoint_rejects_training_calibration_group_sharing() {
    let result = ResearchSplitManifest::new(
        "split",
        vec![
            assigned("train", 1_000, "s-a", "a-1", PartitionRole::Training),
            assigned("cal", 1_100, "s-a", "a-3", PartitionRole::Calibration),
            assigned("eval", 2_000, "s-b", "a-2", PartitionRole::Evaluation),
        ],
        GroupSeparationPolicy::AllRolesDisjoint {
            dimensions: vec!["spatial-block".into()],
        },
        TemporalSeparationPolicy::None,
        vec![],
    );
    assert!(matches!(
        result,
        Err(SplitError::GroupLeakage { first_role: PartitionRole::Training, second_role: PartitionRole::Calibration, .. })
    ));
}

#[test]
fn forward_evaluation_enforces_embargo_from_latest_development_sample() {
    let result = ResearchSplitManifest::new(
        "split",
        vec![
            assigned("train", 1_000, "s-a", "a-1", PartitionRole::Training),
            assigned("cal", 1_500, "s-c", "a-3", PartitionRole::Calibration),
            assigned("eval", 2_000, "s-b", "a-2", PartitionRole::Evaluation),
        ],
        eval_disjoint(),
        TemporalSeparationPolicy::ForwardEvaluation { embargo_ms: 600 },
        vec![],
    );
    assert!(matches!(
        result,
        Err(SplitError::TemporalEmbargoViolation {
            latest_development_unix_ms: 1_500,
            earliest_evaluation_unix_ms: 2_000,
            embargo_ms: 600,
        })
    ));
}

#[test]
fn forward_evaluation_accepts_exact_embargo_boundary() {
    let manifest = ResearchSplitManifest::new(
        "split",
        vec![
            assigned("train", 1_000, "s-a", "a-1", PartitionRole::Training),
            assigned("cal", 1_500, "s-c", "a-3", PartitionRole::Calibration),
            assigned("eval", 2_100, "s-b", "a-2", PartitionRole::Evaluation),
        ],
        eval_disjoint(),
        TemporalSeparationPolicy::ForwardEvaluation { embargo_ms: 600 },
        vec![],
    )
    .unwrap();
    manifest.verify_digest().unwrap();
    assert_eq!(manifest.summary().observed_temporal_gap_ms, Some(600));
}

#[test]
fn temporal_comparison_does_not_overflow_extreme_endpoints() {
    let result = ResearchSplitManifest::new(
        "split",
        vec![assigned(
            "train",
            i64::MAX,
            "s-a",
            "a-1",
            PartitionRole::Training,
        ), assigned(
            "eval",
            i64::MAX,
            "s-b",
            "a-2",
            PartitionRole::Evaluation,
        )],
        eval_disjoint(),
        TemporalSeparationPolicy::ForwardEvaluation {
            embargo_ms: u64::MAX,
        },
        vec![],
    );
    assert!(matches!(result, Err(SplitError::TemporalEmbargoViolation { .. })));
}

#[test]
fn separation_evidence_does_not_override_a_declared_group_violation() {
    let evidence = SeparationEvidence::new(
        SeparationEvidenceKind::SpatialBuffer,
        "external artifact claims the sites are sufficiently separated",
        "digest:buffer-analysis",
    )
    .unwrap();
    let result = ResearchSplitManifest::new(
        "split",
        vec![
            assigned("train", 1_000, "shared", "a-1", PartitionRole::Training),
            assigned("eval", 2_000, "shared", "a-2", PartitionRole::Evaluation),
        ],
        eval_disjoint(),
        TemporalSeparationPolicy::None,
        vec![evidence],
    );
    assert!(matches!(result, Err(SplitError::GroupLeakage { .. })));
}

#[test]
fn post_freeze_mutation_is_detected_even_if_still_semantically_valid() {
    let mut manifest = valid_manifest();
    manifest.separation_evidence[0].statement.push_str("; amended");
    assert!(matches!(
        manifest.verify_digest(),
        Err(SplitError::ManifestDigestMismatch)
    ));
}

#[test]
fn serde_round_trip_preserves_verifiable_manifest() {
    let manifest = valid_manifest();
    let bytes = serde_json::to_vec(&manifest).unwrap();
    let decoded: ResearchSplitManifest = serde_json::from_slice(&bytes).unwrap();
    decoded.verify_digest().unwrap();
}
