-- Auto-generated by symthaea-lean-bridge::fol_ext_bridge
-- SMT fragment: NRA
-- Mathlib tactic: nlinarith
-- Requires `import Mathlib.Tactic` + a Lake project with Mathlib resolved.
-- See lean-proofs/phase2/README.md for setup.

import Mathlib.Tactic

theorem mathd_algebra_107 : (∀ x : ℝ, (∀ y : ℝ, ((((((x ^ 2) + ((8) * x)) + (y ^ 2)) - ((6) * y)) = (0)) → ((((x + (4)) ^ 2) + ((y - (3)) ^ 2)) = ((5) ^ 2))))) := by
  intro x y h0
  first
    | (rfl; done)
    | (norm_num; done)
    | (ring; done)
    | (omega; done)
    | (linarith; done)
    | (nlinarith [sq_nonneg x, mul_self_nonneg x, sq_nonneg (x - 1), sq_nonneg (x + 1), sq_nonneg y, mul_self_nonneg y, sq_nonneg (y - 1), sq_nonneg (y + 1), sq_nonneg (x - y), sq_nonneg (x + y)]; done)
    | (positivity; done)
    | (nlinarith [sq_nonneg x, mul_self_nonneg x, sq_nonneg (x - 10), sq_nonneg (x - 7), sq_nonneg (x - 5), sq_nonneg (x - 3), sq_nonneg (x - 1), sq_nonneg (x + 1), sq_nonneg (x + 3), sq_nonneg (x + 5), sq_nonneg (x + 7), sq_nonneg (x + 10), sq_nonneg y, mul_self_nonneg y, sq_nonneg (y - 10), sq_nonneg (y - 7), sq_nonneg (y - 5), sq_nonneg (y - 3), sq_nonneg (y - 1), sq_nonneg (y + 1), sq_nonneg (y + 3), sq_nonneg (y + 5), sq_nonneg (y + 7), sq_nonneg (y + 10), sq_nonneg (x - y), sq_nonneg (x + y)]; done)
    | (rcases lt_trichotomy x y with h | h | h <;> tauto; done)
    | (rcases le_total _ _ with h | h <;> first | linarith | tauto; done)
    | (tauto; done)
    | (polyrith; done)
