-- Auto-generated by symthaea-lean-bridge::fol_ext_bridge
-- SMT fragment: NIA
-- Mathlib tactic: omega_nat
-- Requires `import Mathlib.Tactic` + a Lake project with Mathlib resolved.
-- See lean-proofs/phase2/README.md for setup.

import Mathlib.Tactic

theorem mathd_numbertheory_326 : (∀ n : ℤ, (((((n - (1)) * n) * (n + (1))) = (720)) → ((n + (1)) = (10)))) := by
  intro n h0
  first
    | (rfl; done)
    | (norm_num; done)
    | (ring; done)
    | (omega; done)
    | (linarith; done)
    | (nlinarith [sq_nonneg n, mul_self_nonneg n, sq_nonneg (n - 1), sq_nonneg (n + 1)]; done)
    | (positivity; done)
    | (nlinarith [sq_nonneg n, mul_self_nonneg n, sq_nonneg (n - 10), sq_nonneg (n - 7), sq_nonneg (n - 5), sq_nonneg (n - 3), sq_nonneg (n - 1), sq_nonneg (n + 1), sq_nonneg (n + 3), sq_nonneg (n + 5), sq_nonneg (n + 7), sq_nonneg (n + 10)]; done)
    | (rcases lt_trichotomy _ _ with h | h | h <;> tauto; done)
    | (rcases le_total _ _ with h | h <;> first | linarith | tauto; done)
    | (tauto; done)
    | (polyrith; done)
