-- Auto-generated by symthaea-lean-bridge::fol_ext_bridge
-- SMT fragment: NRA
-- Mathlib tactic: nlinarith
-- Requires `import Mathlib.Tactic` + a Lake project with Mathlib resolved.
-- See lean-proofs/phase2/README.md for setup.

import Mathlib.Tactic

theorem mathd_algebra_33 : (∀ x : ℝ, (∀ y : ℝ, (∀ z : ℝ, ((¬ (x = (0))) → ((((2) * x) = ((5) * y)) → ((((7) * y) = ((10) * z)) → ((z / x) = ((7 : ℝ) / (25 : ℝ))))))))) := by
  intro x y z h0 h1 h2
  first
    | (rfl; done)
    | (norm_num; done)
    | (ring; done)
    | (omega; done)
    | (linarith; done)
    | (nlinarith [sq_nonneg x, mul_self_nonneg x, sq_nonneg (x - 1), sq_nonneg (x + 1), sq_nonneg y, mul_self_nonneg y, sq_nonneg (y - 1), sq_nonneg (y + 1), sq_nonneg z, mul_self_nonneg z, sq_nonneg (z - 1), sq_nonneg (z + 1), sq_nonneg (x - y), sq_nonneg (x + y), sq_nonneg (x - z), sq_nonneg (x + z), sq_nonneg (y - z), sq_nonneg (y + z)]; done)
    | (positivity; done)
    | (have ne0 := sub_ne_zero.mpr h0; try (field_simp [ne0] at *); first | (linarith; done) | (ring; done) | (norm_num; done) | (nlinarith [sq_nonneg x, mul_self_nonneg x, sq_nonneg (x - 1), sq_nonneg (x + 1), sq_nonneg y, mul_self_nonneg y, sq_nonneg (y - 1), sq_nonneg (y + 1), sq_nonneg z, mul_self_nonneg z, sq_nonneg (z - 1), sq_nonneg (z + 1), sq_nonneg (x - y), sq_nonneg (x + y), sq_nonneg (x - z), sq_nonneg (x + z), sq_nonneg (y - z), sq_nonneg (y + z)]; done); done)
    | (try subst_eqs; try field_simp; first | (norm_num; done) | (ring; done) | (linarith; done) | (nlinarith [sq_nonneg x, mul_self_nonneg x, sq_nonneg (x - 1), sq_nonneg (x + 1), sq_nonneg y, mul_self_nonneg y, sq_nonneg (y - 1), sq_nonneg (y + 1), sq_nonneg z, mul_self_nonneg z, sq_nonneg (z - 1), sq_nonneg (z + 1), sq_nonneg (x - y), sq_nonneg (x + y), sq_nonneg (x - z), sq_nonneg (x + z), sq_nonneg (y - z), sq_nonneg (y + z)]; done); done)
    | (try (field_simp at *); first | (linarith; done) | (ring; done) | (norm_num; done) | (nlinarith [sq_nonneg x, mul_self_nonneg x, sq_nonneg (x - 1), sq_nonneg (x + 1), sq_nonneg y, mul_self_nonneg y, sq_nonneg (y - 1), sq_nonneg (y + 1), sq_nonneg z, mul_self_nonneg z, sq_nonneg (z - 1), sq_nonneg (z + 1), sq_nonneg (x - y), sq_nonneg (x + y), sq_nonneg (x - z), sq_nonneg (x + z), sq_nonneg (y - z), sq_nonneg (y + z)]; done); done)
    | (nlinarith [sq_nonneg x, mul_self_nonneg x, sq_nonneg (x - 10), sq_nonneg (x - 7), sq_nonneg (x - 5), sq_nonneg (x - 3), sq_nonneg (x - 1), sq_nonneg (x + 1), sq_nonneg (x + 3), sq_nonneg (x + 5), sq_nonneg (x + 7), sq_nonneg (x + 10), sq_nonneg y, mul_self_nonneg y, sq_nonneg (y - 10), sq_nonneg (y - 7), sq_nonneg (y - 5), sq_nonneg (y - 3), sq_nonneg (y - 1), sq_nonneg (y + 1), sq_nonneg (y + 3), sq_nonneg (y + 5), sq_nonneg (y + 7), sq_nonneg (y + 10), sq_nonneg z, mul_self_nonneg z, sq_nonneg (z - 10), sq_nonneg (z - 7), sq_nonneg (z - 5), sq_nonneg (z - 3), sq_nonneg (z - 1), sq_nonneg (z + 1), sq_nonneg (z + 3), sq_nonneg (z + 5), sq_nonneg (z + 7), sq_nonneg (z + 10), sq_nonneg (x - y), sq_nonneg (x + y), sq_nonneg (x - z), sq_nonneg (x + z), sq_nonneg (y - z), sq_nonneg (y + z)]; done)
    | (rcases lt_trichotomy x y with h | h | h <;> tauto; done)
    | (rcases le_total _ _ with h | h <;> first | linarith | tauto; done)
    | (tauto; done)
    | (polyrith; done)
