-- Auto-generated by symthaea-lean-bridge::fol_ext_bridge
-- SMT fragment: NRA
-- Mathlib tactic: nlinarith
-- Requires `import Mathlib.Tactic` + a Lake project with Mathlib resolved.
-- See lean-proofs/phase2/README.md for setup.

import Mathlib.Tactic

theorem mathd_algebra_478 : (∀ b : ℝ, (∀ h : ℝ, (∀ v : ℝ, (((((0) < b) ∧ ((0) < h)) ∧ ((0) < v)) → ((v = (((1 : ℝ) / (3 : ℝ)) * (b * h))) → ((b = (30)) → ((h = ((13 : ℝ) / (2 : ℝ))) → (v = (65))))))))) := by
  intro b h v h0 h1 h2 h3
  first
    | (rfl; done)
    | (norm_num; done)
    | (ring; done)
    | (omega; done)
    | (linarith; done)
    | (nlinarith [sq_nonneg b, mul_self_nonneg b, sq_nonneg (b - 1), sq_nonneg (b + 1), sq_nonneg h, mul_self_nonneg h, sq_nonneg (h - 1), sq_nonneg (h + 1), sq_nonneg v, mul_self_nonneg v, sq_nonneg (v - 1), sq_nonneg (v + 1), sq_nonneg (b - h), sq_nonneg (b + h), sq_nonneg (b - v), sq_nonneg (b + v), sq_nonneg (h - v), sq_nonneg (h + v)]; done)
    | (positivity; done)
    | (nlinarith [sq_nonneg b, mul_self_nonneg b, sq_nonneg (b - 10), sq_nonneg (b - 7), sq_nonneg (b - 5), sq_nonneg (b - 3), sq_nonneg (b - 1), sq_nonneg (b + 1), sq_nonneg (b + 3), sq_nonneg (b + 5), sq_nonneg (b + 7), sq_nonneg (b + 10), sq_nonneg h, mul_self_nonneg h, sq_nonneg (h - 10), sq_nonneg (h - 7), sq_nonneg (h - 5), sq_nonneg (h - 3), sq_nonneg (h - 1), sq_nonneg (h + 1), sq_nonneg (h + 3), sq_nonneg (h + 5), sq_nonneg (h + 7), sq_nonneg (h + 10), sq_nonneg v, mul_self_nonneg v, sq_nonneg (v - 10), sq_nonneg (v - 7), sq_nonneg (v - 5), sq_nonneg (v - 3), sq_nonneg (v - 1), sq_nonneg (v + 1), sq_nonneg (v + 3), sq_nonneg (v + 5), sq_nonneg (v + 7), sq_nonneg (v + 10), sq_nonneg (b - h), sq_nonneg (b + h), sq_nonneg (b - v), sq_nonneg (b + v), sq_nonneg (h - v), sq_nonneg (h + v)]; done)
    | (rcases lt_trichotomy b h with h | h | h <;> tauto; done)
    | (rcases le_total _ _ with h | h <;> first | linarith | tauto; done)
    | (tauto; done)
    | (polyrith; done)
