-- Auto-generated by symthaea-lean-bridge::fol_ext_bridge
-- SMT fragment: NRA
-- Mathlib tactic: nlinarith
-- Requires `import Mathlib.Tactic` + a Lake project with Mathlib resolved.
-- See lean-proofs/phase2/README.md for setup.

import Mathlib.Tactic

theorem mathd_algebra_421 : (∀ a : ℝ, (∀ b : ℝ, (∀ c : ℝ, (∀ d : ℝ, ((b = (((a ^ 2) + ((4) * a)) + (6))) → ((b = (((((1 : ℝ) / (2 : ℝ)) * (a ^ 2)) + a) + (6))) → ((d = (((c ^ 2) + ((4) * c)) + (6))) → ((d = (((((1 : ℝ) / (2 : ℝ)) * (c ^ 2)) + c) + (6))) → ((a < c) → ((c - a) = (6))))))))))) := by
  intro a b c d h0 h1 h2 h3 h4
  first
    | (rfl; done)
    | (norm_num; done)
    | (ring; done)
    | (omega; done)
    | (linarith; done)
    | (nlinarith [sq_nonneg a, mul_self_nonneg a, sq_nonneg (a - 1), sq_nonneg (a + 1), sq_nonneg b, mul_self_nonneg b, sq_nonneg (b - 1), sq_nonneg (b + 1), sq_nonneg c, mul_self_nonneg c, sq_nonneg (c - 1), sq_nonneg (c + 1), sq_nonneg d, mul_self_nonneg d, sq_nonneg (d - 1), sq_nonneg (d + 1), sq_nonneg (a - b), sq_nonneg (a + b), sq_nonneg (a - c), sq_nonneg (a + c), sq_nonneg (a - d), sq_nonneg (a + d), sq_nonneg (b - c), sq_nonneg (b + c), sq_nonneg (b - d), sq_nonneg (b + d), sq_nonneg (c - d), sq_nonneg (c + d), sq_nonneg (a*c - b*d), sq_nonneg (a*d - b*c)]; done)
    | (positivity; done)
    | (nlinarith [sq_nonneg a, mul_self_nonneg a, sq_nonneg (a - 10), sq_nonneg (a - 7), sq_nonneg (a - 5), sq_nonneg (a - 3), sq_nonneg (a - 1), sq_nonneg (a + 1), sq_nonneg (a + 3), sq_nonneg (a + 5), sq_nonneg (a + 7), sq_nonneg (a + 10), sq_nonneg b, mul_self_nonneg b, sq_nonneg (b - 10), sq_nonneg (b - 7), sq_nonneg (b - 5), sq_nonneg (b - 3), sq_nonneg (b - 1), sq_nonneg (b + 1), sq_nonneg (b + 3), sq_nonneg (b + 5), sq_nonneg (b + 7), sq_nonneg (b + 10), sq_nonneg c, mul_self_nonneg c, sq_nonneg (c - 10), sq_nonneg (c - 7), sq_nonneg (c - 5), sq_nonneg (c - 3), sq_nonneg (c - 1), sq_nonneg (c + 1), sq_nonneg (c + 3), sq_nonneg (c + 5), sq_nonneg (c + 7), sq_nonneg (c + 10), sq_nonneg d, mul_self_nonneg d, sq_nonneg (d - 10), sq_nonneg (d - 7), sq_nonneg (d - 5), sq_nonneg (d - 3), sq_nonneg (d - 1), sq_nonneg (d + 1), sq_nonneg (d + 3), sq_nonneg (d + 5), sq_nonneg (d + 7), sq_nonneg (d + 10), sq_nonneg (a - b), sq_nonneg (a + b), sq_nonneg (a - c), sq_nonneg (a + c), sq_nonneg (a - d), sq_nonneg (a + d), sq_nonneg (b - c), sq_nonneg (b + c), sq_nonneg (b - d), sq_nonneg (b + d), sq_nonneg (c - d), sq_nonneg (c + d), sq_nonneg (a*c - b*d), sq_nonneg (a*d - b*c)]; done)
    | (rcases lt_trichotomy a b with h | h | h <;> tauto; done)
    | (rcases le_total _ _ with h | h <;> first | linarith | tauto; done)
    | (tauto; done)
    | (polyrith; done)
