-- Auto-generated by symthaea-lean-bridge::fol_ext_bridge
-- SMT fragment: NRA
-- Mathlib tactic: nlinarith
-- Requires `import Mathlib.Tactic` + a Lake project with Mathlib resolved.
-- See lean-proofs/phase2/README.md for setup.

import Mathlib.Tactic

theorem mathd_algebra_234 : (∀ d : ℝ, (((((27 : ℝ) / (125 : ℝ)) * d) = ((9 : ℝ) / (25 : ℝ))) → ((((3 : ℝ) / (5 : ℝ)) * (d ^ 3)) = ((25 : ℝ) / (9 : ℝ))))) := by
  intro d h0
  first
    | (rfl; done)
    | (norm_num; done)
    | (ring; done)
    | (omega; done)
    | (linarith; done)
    | (nlinarith [sq_nonneg d, mul_self_nonneg d, sq_nonneg (d - 1), sq_nonneg (d + 1)]; done)
    | (positivity; done)
    | (nlinarith [sq_nonneg d, mul_self_nonneg d, sq_nonneg (d - 10), sq_nonneg (d - 7), sq_nonneg (d - 5), sq_nonneg (d - 3), sq_nonneg (d - 1), sq_nonneg (d + 1), sq_nonneg (d + 3), sq_nonneg (d + 5), sq_nonneg (d + 7), sq_nonneg (d + 10)]; done)
    | (rcases lt_trichotomy _ _ with h | h | h <;> tauto; done)
    | (rcases le_total _ _ with h | h <;> first | linarith | tauto; done)
    | (tauto; done)
    | (polyrith; done)
