-- Auto-generated by symthaea-lean-bridge::fol_ext_bridge
-- SMT fragment: NRA
-- Mathlib tactic: nlinarith
-- Requires `import Mathlib.Tactic` + a Lake project with Mathlib resolved.
-- See lean-proofs/phase2/README.md for setup.

import Mathlib.Tactic

theorem mathd_algebra_11 : (∀ a : ℝ, (∀ b : ℝ, ((¬ (a = b)) → ((¬ (a = ((2) * b))) → ((((((4) * a) + ((3) * b)) / (a - ((2) * b))) = (5)) → (((a + ((11) * b)) / (a - b)) = (2))))))) := by
  intro a b h0 h1 h2
  first
    | (rfl; done)
    | (norm_num; done)
    | (ring; done)
    | (omega; done)
    | (linarith; done)
    | (nlinarith [sq_nonneg a, mul_self_nonneg a, sq_nonneg (a - 1), sq_nonneg (a + 1), sq_nonneg b, mul_self_nonneg b, sq_nonneg (b - 1), sq_nonneg (b + 1), sq_nonneg (a - b), sq_nonneg (a + b)]; done)
    | (positivity; done)
    | (have ne0 := sub_ne_zero.mpr h0; have ne1 := sub_ne_zero.mpr h1; try (field_simp [ne0, ne1] at *); first | (linarith; done) | (ring; done) | (norm_num; done) | (nlinarith [sq_nonneg a, mul_self_nonneg a, sq_nonneg (a - 1), sq_nonneg (a + 1), sq_nonneg b, mul_self_nonneg b, sq_nonneg (b - 1), sq_nonneg (b + 1), sq_nonneg (a - b), sq_nonneg (a + b)]; done); done)
    | (try subst_eqs; try field_simp; first | (norm_num; done) | (ring; done) | (linarith; done) | (nlinarith [sq_nonneg a, mul_self_nonneg a, sq_nonneg (a - 1), sq_nonneg (a + 1), sq_nonneg b, mul_self_nonneg b, sq_nonneg (b - 1), sq_nonneg (b + 1), sq_nonneg (a - b), sq_nonneg (a + b)]; done); done)
    | (try (field_simp at *); first | (linarith; done) | (ring; done) | (norm_num; done) | (nlinarith [sq_nonneg a, mul_self_nonneg a, sq_nonneg (a - 1), sq_nonneg (a + 1), sq_nonneg b, mul_self_nonneg b, sq_nonneg (b - 1), sq_nonneg (b + 1), sq_nonneg (a - b), sq_nonneg (a + b)]; done); done)
    | (nlinarith [sq_nonneg a, mul_self_nonneg a, sq_nonneg (a - 10), sq_nonneg (a - 7), sq_nonneg (a - 5), sq_nonneg (a - 3), sq_nonneg (a - 1), sq_nonneg (a + 1), sq_nonneg (a + 3), sq_nonneg (a + 5), sq_nonneg (a + 7), sq_nonneg (a + 10), sq_nonneg b, mul_self_nonneg b, sq_nonneg (b - 10), sq_nonneg (b - 7), sq_nonneg (b - 5), sq_nonneg (b - 3), sq_nonneg (b - 1), sq_nonneg (b + 1), sq_nonneg (b + 3), sq_nonneg (b + 5), sq_nonneg (b + 7), sq_nonneg (b + 10), sq_nonneg (a - b), sq_nonneg (a + b)]; done)
    | (rcases lt_trichotomy a b with h | h | h <;> tauto; done)
    | (rcases le_total _ _ with h | h <;> first | linarith | tauto; done)
    | (tauto; done)
    | (polyrith; done)
