// Copyright (C) 2024-2026 Tristan Stoltz / Luminous Dynamics
// SPDX-License-Identifier: AGPL-3.0-or-later
// Commercial licensing: see COMMERCIAL_LICENSE.md at repository root
//! Evidence authority for materials discovery.
//!
//! A materials candidate must never gain scientific authority merely because a
//! heuristic, HDC similarity score, ML model, or atomistic calculation ranks it
//! highly. This module separates *evidence stage* from the canonical Symthaea
//! epistemic coordinate and enforces an ordered evidence chain from hypothesis
//! generation through independent replication.

use serde::{Deserialize, Serialize};
use symthaea_epistemic_types::EpistemicCoordinate;

/// Ordered evidence stages for a materials candidate.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Serialize, Deserialize)]
pub enum MaterialsEvidenceStage {
    /// Generated by a heuristic, analogy, search procedure, or other hypothesis source.
    HeuristicCandidate,
    /// Prior-art and literature search has been performed for the candidate.
    PriorArtChecked,
    /// External materials databases corroborate relevant composition/property context.
    DatabaseCorroborated,
    /// A machine-learning model has screened the candidate within a stated domain.
    MlScreened,
    /// First-principles formation-energy calculations support the candidate.
    DftFormationStable,
    /// Convex-hull analysis supports stability against decomposition.
    ConvexHullScreened,
    /// Phonon or equivalent analysis supports dynamic stability.
    DynamicallyStable,
    /// The material has been physically synthesized.
    ExperimentallySynthesized,
    /// The synthesized material has been characterized for the claimed properties.
    ExperimentallyCharacterized,
    /// The relevant finding has been independently replicated.
    IndependentlyReplicated,
}

impl MaterialsEvidenceStage {
    /// Return the maximum claim authority permitted by this stage.
    pub fn claim_authority(self) -> MaterialsClaimAuthority {
        match self {
            Self::HeuristicCandidate
            | Self::PriorArtChecked
            | Self::DatabaseCorroborated
            | Self::MlScreened => MaterialsClaimAuthority::Candidate,
            Self::DftFormationStable
            | Self::ConvexHullScreened
            | Self::DynamicallyStable => MaterialsClaimAuthority::ComputationallySupported,
            Self::ExperimentallySynthesized => MaterialsClaimAuthority::Synthesized,
            Self::ExperimentallyCharacterized => {
                MaterialsClaimAuthority::ExperimentallyCharacterized
            }
            Self::IndependentlyReplicated => MaterialsClaimAuthority::IndependentlyReplicated,
        }
    }

    /// Return the next stage in the strict evidence ladder, if one exists.
    pub fn next(self) -> Option<Self> {
        match self {
            Self::HeuristicCandidate => Some(Self::PriorArtChecked),
            Self::PriorArtChecked => Some(Self::DatabaseCorroborated),
            Self::DatabaseCorroborated => Some(Self::MlScreened),
            Self::MlScreened => Some(Self::DftFormationStable),
            Self::DftFormationStable => Some(Self::ConvexHullScreened),
            Self::ConvexHullScreened => Some(Self::DynamicallyStable),
            Self::DynamicallyStable => Some(Self::ExperimentallySynthesized),
            Self::ExperimentallySynthesized => Some(Self::ExperimentallyCharacterized),
            Self::ExperimentallyCharacterized => Some(Self::IndependentlyReplicated),
            Self::IndependentlyReplicated => None,
        }
    }
}

/// The strongest wording that a materials evidence stage is allowed to support.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum MaterialsClaimAuthority {
    /// Hypothesis/candidate language only.
    Candidate,
    /// Computational evidence supports the candidate, but no experimental claim is permitted.
    ComputationallySupported,
    /// Physical synthesis has been demonstrated, but the target property is not yet established.
    Synthesized,
    /// Experimental characterization supports the stated property claim.
    ExperimentallyCharacterized,
    /// Independent replication supports the stated property claim.
    IndependentlyReplicated,
}

impl MaterialsClaimAuthority {
    /// Whether this authority permits claiming experimental support.
    pub fn permits_experimental_claim(self) -> bool {
        matches!(
            self,
            Self::ExperimentallyCharacterized | Self::IndependentlyReplicated
        )
    }

    /// Whether this authority permits claiming independent replication.
    pub fn permits_replication_claim(self) -> bool {
        self == Self::IndependentlyReplicated
    }
}

/// Evidence source required to justify a stage transition.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum MaterialsEvidenceKind {
    /// Heuristic, rule-based, HDC, search, or analogy-based candidate generation.
    HeuristicModel,
    /// Literature and patent prior-art search.
    LiteratureSearch,
    /// Materials Project, OQMD, NOMAD, or equivalent external database evidence.
    ExternalDatabase,
    /// Machine-learning screening evidence.
    MachineLearningModel,
    /// First-principles formation-energy calculation.
    DftCalculation,
    /// Convex-hull/decomposition-energy analysis.
    ConvexHullAnalysis,
    /// Phonon or equivalent dynamic-stability calculation.
    PhononCalculation,
    /// Physical synthesis record.
    SynthesisRecord,
    /// Experimental characterization record.
    Characterization,
    /// Independent reproduction or replication record.
    IndependentReplication,
}

impl MaterialsEvidenceKind {
    fn expected_stage(self) -> MaterialsEvidenceStage {
        match self {
            Self::HeuristicModel => MaterialsEvidenceStage::HeuristicCandidate,
            Self::LiteratureSearch => MaterialsEvidenceStage::PriorArtChecked,
            Self::ExternalDatabase => MaterialsEvidenceStage::DatabaseCorroborated,
            Self::MachineLearningModel => MaterialsEvidenceStage::MlScreened,
            Self::DftCalculation => MaterialsEvidenceStage::DftFormationStable,
            Self::ConvexHullAnalysis => MaterialsEvidenceStage::ConvexHullScreened,
            Self::PhononCalculation => MaterialsEvidenceStage::DynamicallyStable,
            Self::SynthesisRecord => MaterialsEvidenceStage::ExperimentallySynthesized,
            Self::Characterization => MaterialsEvidenceStage::ExperimentallyCharacterized,
            Self::IndependentReplication => MaterialsEvidenceStage::IndependentlyReplicated,
        }
    }
}

/// One evidence-bearing step in a candidate's materials discovery lineage.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct MaterialsEvidenceRecord {
    /// Evidence stage established by this record.
    pub stage: MaterialsEvidenceStage,
    /// Kind of evidence supplied.
    pub kind: MaterialsEvidenceKind,
    /// Stable source identifier, calculation ID, DOI, dataset ID, or lab record ID.
    pub source_id: String,
    /// Human-readable method description.
    pub method: String,
    /// Canonical Symthaea epistemic coordinate for this specific evidence item.
    pub epistemic: EpistemicCoordinate,
    /// Optional digest for a reproducibility artifact, input deck, dataset, or raw result bundle.
    pub artifact_digest: Option<String>,
}

impl MaterialsEvidenceRecord {
    /// Validate that the evidence kind actually corresponds to the claimed stage.
    pub fn validate(&self) -> Result<(), MaterialsEvidenceError> {
        let expected = self.kind.expected_stage();
        if self.stage != expected {
            return Err(MaterialsEvidenceError::KindStageMismatch {
                kind: self.kind,
                expected,
                actual: self.stage,
            });
        }
        if self.source_id.trim().is_empty() {
            return Err(MaterialsEvidenceError::EmptySourceId);
        }
        if self.method.trim().is_empty() {
            return Err(MaterialsEvidenceError::EmptyMethod);
        }
        Ok(())
    }
}

/// Append-only evidence chain for a single material candidate.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct MaterialsEvidenceChain {
    /// Stable candidate identifier or canonical composition identifier.
    pub candidate_id: String,
    /// Ordered evidence records.
    pub records: Vec<MaterialsEvidenceRecord>,
}

impl MaterialsEvidenceChain {
    /// Start a chain from a heuristic candidate record.
    pub fn new(
        candidate_id: impl Into<String>,
        initial: MaterialsEvidenceRecord,
    ) -> Result<Self, MaterialsEvidenceError> {
        initial.validate()?;
        if initial.stage != MaterialsEvidenceStage::HeuristicCandidate {
            return Err(MaterialsEvidenceError::MustStartHeuristic {
                actual: initial.stage,
            });
        }
        let candidate_id = candidate_id.into();
        if candidate_id.trim().is_empty() {
            return Err(MaterialsEvidenceError::EmptyCandidateId);
        }
        Ok(Self {
            candidate_id,
            records: vec![initial],
        })
    }

    /// Append exactly the next evidence stage.
    ///
    /// Skipping a stage is rejected so that a DFT or experimental result cannot
    /// silently bypass prior-art, database, or computational qualification gates.
    pub fn append(&mut self, record: MaterialsEvidenceRecord) -> Result<(), MaterialsEvidenceError> {
        record.validate()?;
        let current = self
            .records
            .last()
            .expect("evidence chain is non-empty by construction")
            .stage;
        let expected = current
            .next()
            .ok_or(MaterialsEvidenceError::AlreadyFullyReplicated)?;
        if record.stage != expected {
            return Err(MaterialsEvidenceError::InvalidTransition {
                from: current,
                expected,
                actual: record.stage,
            });
        }
        self.records.push(record);
        Ok(())
    }

    /// Current evidence stage.
    pub fn stage(&self) -> MaterialsEvidenceStage {
        self.records
            .last()
            .expect("evidence chain is non-empty by construction")
            .stage
    }

    /// Maximum materials claim authority currently permitted.
    pub fn claim_authority(&self) -> MaterialsClaimAuthority {
        self.stage().claim_authority()
    }
}

/// Validation failures for the materials evidence lineage.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum MaterialsEvidenceError {
    /// Candidate identifiers must not be empty.
    EmptyCandidateId,
    /// Evidence source identifiers must not be empty.
    EmptySourceId,
    /// Method descriptions must not be empty.
    EmptyMethod,
    /// The evidence kind does not establish the requested stage.
    KindStageMismatch {
        /// Supplied evidence kind.
        kind: MaterialsEvidenceKind,
        /// Stage established by the supplied evidence kind.
        expected: MaterialsEvidenceStage,
        /// Stage claimed by the record.
        actual: MaterialsEvidenceStage,
    },
    /// Every lineage must begin as a heuristic candidate.
    MustStartHeuristic {
        /// Supplied initial stage.
        actual: MaterialsEvidenceStage,
    },
    /// A stage transition attempted to skip or regress the evidence ladder.
    InvalidTransition {
        /// Current stage.
        from: MaterialsEvidenceStage,
        /// Required next stage.
        expected: MaterialsEvidenceStage,
        /// Supplied stage.
        actual: MaterialsEvidenceStage,
    },
    /// The chain is already independently replicated and cannot advance further.
    AlreadyFullyReplicated,
}

#[cfg(test)]
mod tests {
    use super::*;
    use symthaea_epistemic_types::{
        EmpiricalLevel, EpistemicContext, MaterialityLevel, NormativeLevel,
    };

    fn coordinate(empirical: EmpiricalLevel) -> EpistemicCoordinate {
        EpistemicCoordinate {
            empirical,
            normative: NormativeLevel::N0Personal,
            materiality: MaterialityLevel::M1Temporal,
            context: EpistemicContext::Scientific,
        }
    }

    fn record(
        stage: MaterialsEvidenceStage,
        kind: MaterialsEvidenceKind,
        source: &str,
    ) -> MaterialsEvidenceRecord {
        MaterialsEvidenceRecord {
            stage,
            kind,
            source_id: source.to_string(),
            method: "test method".to_string(),
            epistemic: coordinate(EmpiricalLevel::E0Null),
            artifact_digest: None,
        }
    }

    #[test]
    fn heuristic_candidate_never_permits_experimental_claim() {
        let authority = MaterialsEvidenceStage::HeuristicCandidate.claim_authority();
        assert_eq!(authority, MaterialsClaimAuthority::Candidate);
        assert!(!authority.permits_experimental_claim());
    }

    #[test]
    fn dft_stability_is_still_not_experimental_evidence() {
        let authority = MaterialsEvidenceStage::DftFormationStable.claim_authority();
        assert_eq!(authority, MaterialsClaimAuthority::ComputationallySupported);
        assert!(!authority.permits_experimental_claim());
    }

    #[test]
    fn evidence_kind_cannot_impersonate_a_stronger_stage() {
        let bad = record(
            MaterialsEvidenceStage::ExperimentallyCharacterized,
            MaterialsEvidenceKind::DftCalculation,
            "calc:123",
        );
        assert!(matches!(
            bad.validate(),
            Err(MaterialsEvidenceError::KindStageMismatch { .. })
        ));
    }

    #[test]
    fn evidence_chain_rejects_skipped_stages() {
        let initial = record(
            MaterialsEvidenceStage::HeuristicCandidate,
            MaterialsEvidenceKind::HeuristicModel,
            "local:wolverine-v1",
        );
        let mut chain = MaterialsEvidenceChain::new("Ti25Zr25Nb20Ta15Er15", initial).unwrap();
        let skipped = record(
            MaterialsEvidenceStage::DftFormationStable,
            MaterialsEvidenceKind::DftCalculation,
            "dft:001",
        );
        assert!(matches!(
            chain.append(skipped),
            Err(MaterialsEvidenceError::InvalidTransition { .. })
        ));
        assert_eq!(chain.stage(), MaterialsEvidenceStage::HeuristicCandidate);
    }

    #[test]
    fn evidence_chain_advances_only_in_order() {
        let initial = record(
            MaterialsEvidenceStage::HeuristicCandidate,
            MaterialsEvidenceKind::HeuristicModel,
            "local:wolverine-v1",
        );
        let mut chain = MaterialsEvidenceChain::new("Ti25Zr25Nb20Ta15Er15", initial).unwrap();
        chain
            .append(record(
                MaterialsEvidenceStage::PriorArtChecked,
                MaterialsEvidenceKind::LiteratureSearch,
                "search:prior-art-001",
            ))
            .unwrap();
        chain
            .append(record(
                MaterialsEvidenceStage::DatabaseCorroborated,
                MaterialsEvidenceKind::ExternalDatabase,
                "database:mp-oqmd-nomad-001",
            ))
            .unwrap();
        assert_eq!(chain.stage(), MaterialsEvidenceStage::DatabaseCorroborated);
        assert_eq!(chain.claim_authority(), MaterialsClaimAuthority::Candidate);
    }

    #[test]
    fn only_replication_stage_permits_replication_claim() {
        assert!(!MaterialsEvidenceStage::ExperimentallyCharacterized
            .claim_authority()
            .permits_replication_claim());
        assert!(MaterialsEvidenceStage::IndependentlyReplicated
            .claim_authority()
            .permits_replication_claim());
    }
}
