// Copyright (C) 2024-2026 Tristan Stoltz / Luminous Dynamics
// SPDX-License-Identifier: AGPL-3.0-or-later
// Commercial licensing: see COMMERCIAL_LICENSE.md at repository root
use anyhow::{Result, ensure};
use risc0_zkvm::{ExecutorEnv, ProveInfo, VerifierContext, default_prover};
use symthaea_zkproof_core::{
    AccountabilityThresholdInput, AccountabilityThresholdOutput, BalanceProofInput,
    BalanceProofOutput, EvolutionInput, EvolutionOutput,
};

// Re-exported from the methods crate (generated by risc0-build).
// The constant names are derived from the guest binary target name
// ("symthaea-zkproof-guest" → SYMTHAEA_ZKPROOF_GUEST_*).
use symthaea_zkproof_methods::{SYMTHAEA_ZKPROOF_GUEST_ELF, SYMTHAEA_ZKPROOF_GUEST_ID};

/// Stable scheme label for the first SIF computation proof.
pub const SIF_ACCOUNTABILITY_THRESHOLD_SCHEME: &str =
    "symthaea/risc0/sif-u64-threshold-computation/v1";

/// Stable verifier profile exported to the provider-neutral accountability layer.
pub const SIF_ACCOUNTABILITY_THRESHOLD_VERIFIER_PROFILE: &str =
    "symthaea-zkproof/risc0/sif-u64-threshold/v1";

const SIF_PREDICATE_RESULT_DOMAIN: &[u8] = b"symthaea:sif:u64-threshold-result:v1";
const SIF_PROOF_ARTIFACT_DOMAIN: &[u8] = b"symthaea:sif:risc0-proof-artifact:v1";

// ---------------------------------------------------------------------------
// Consciousness attestation prover (tag = 0)
// ---------------------------------------------------------------------------

pub struct EvolutionaryProver;

impl EvolutionaryProver {
    pub fn prove(input: EvolutionInput) -> Result<ProveInfo> {
        let env = ExecutorEnv::builder()
            .write(&0u8)? // tag = 0
            .write(&input)?
            .build()?;

        let prover = default_prover();
        let prove_info = prover.prove(env, SYMTHAEA_ZKPROOF_GUEST_ELF)?;
        Ok(prove_info)
    }

    pub fn verify(prove_info: &ProveInfo) -> Result<EvolutionOutput> {
        prove_info.receipt.verify(SYMTHAEA_ZKPROOF_GUEST_ID)?;
        let output: EvolutionOutput = prove_info.receipt.journal.decode()?;
        Ok(output)
    }
}

// ---------------------------------------------------------------------------
// Balance sufficiency prover (tag = 1)
// ---------------------------------------------------------------------------

/// Proves that a balance is sufficient (>= required minimum) without
/// revealing the actual balance.
///
/// The proof commits to:
/// - `sufficient: bool` (PUBLIC)
/// - `required_minimum: u64` (PUBLIC)
/// - `nonce: u64` (PUBLIC)
///
/// The actual balance is PRIVATE — included in the proof computation
/// but never revealed.
pub struct BalanceProver;

impl BalanceProver {
    /// Generate a ZK proof that `balance >= required_minimum`.
    ///
    /// Returns the proof receipt containing the public outputs.
    /// The actual balance is never revealed.
    pub fn prove(balance: u64, required_minimum: u64, nonce: u64) -> Result<ProveInfo> {
        let env = ExecutorEnv::builder()
            .write(&1u8)? // tag = 1 (balance proof)
            .write(&BalanceProofInput {
                balance,
                required_minimum,
                nonce,
            })?
            .build()?;

        let prover = default_prover();
        let prove_info = prover.prove(env, SYMTHAEA_ZKPROOF_GUEST_ELF)?;
        Ok(prove_info)
    }

    /// Verify a balance proof receipt and decode the public output.
    pub fn verify(prove_info: &ProveInfo) -> Result<BalanceProofOutput> {
        prove_info.receipt.verify(SYMTHAEA_ZKPROOF_GUEST_ID)?;
        let output: BalanceProofOutput = prove_info.receipt.journal.decode()?;
        Ok(output)
    }
}

// ---------------------------------------------------------------------------
// Reciprocal-accountability threshold predicate (tag = 2)
// ---------------------------------------------------------------------------

/// Expected public context for a SIF threshold computation proof.
///
/// This context is supplied by the accountability layer at verification time.
/// A proof that is cryptographically valid but belongs to another receipt/query,
/// policy, threshold, result or operation nonce is rejected.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct AccountabilityThresholdExpectation {
    pub statement_digest: [u8; 32],
    pub query_digest: [u8; 32],
    pub policy_digest: [u8; 32],
    pub result_digest: [u8; 32],
    pub threshold: u64,
    /// Opaque nonce for the exact live operation. In the SIF cross-stack profile,
    /// this is derived by Xenia from its authenticated operation/session plus the
    /// receipt/query commitments.
    pub operation_nonce: [u8; 32],
}

/// Stable, commitment-only metadata exported after a SIF computation proof has
/// passed real (non-dev-mode) RISC Zero verification and exact-context checks.
///
/// This is intentionally provider-neutral metadata rather than an authorization
/// token. `proof_digest` identifies the concrete proof artifact; Mycelix can map
/// the common fields into its `AttestationRole::ComputationProof` reference.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct VerifiedAccountabilityComputationRef {
    pub scheme: &'static str,
    pub statement_digest: [u8; 32],
    pub proof_digest: [u8; 32],
    pub verifier_profile: &'static str,
    pub operation_nonce: [u8; 32],
    pub result_digest: [u8; 32],
}

/// RISC Zero prover/verifier for one minimum-disclosure `u64 >= threshold`
/// computation bound to a reciprocal-accountability statement.
pub struct AccountabilityThresholdProver;

impl AccountabilityThresholdProver {
    /// Generate a proof. `private_value` is consumed only inside the zkVM.
    pub fn prove(input: AccountabilityThresholdInput) -> Result<ProveInfo> {
        validate_public_bindings(
            &input.statement_digest,
            &input.query_digest,
            &input.policy_digest,
            &input.operation_nonce,
        )?;

        let env = ExecutorEnv::builder()
            .write(&2u8)? // tag = 2 (SIF accountability threshold)
            .write(&input)?
            .build()?;

        let prover = default_prover();
        let prove_info = prover.prove(env, SYMTHAEA_ZKPROOF_GUEST_ELF)?;
        Ok(prove_info)
    }

    /// Verify a SIF receipt with dev mode explicitly disabled, then decode its
    /// public journal.
    ///
    /// This deliberately does not inherit `RISC0_DEV_MODE` from the environment.
    /// A fake development receipt must never cross the SIF disclosure boundary as
    /// if it were cryptographic evidence.
    pub fn verify(prove_info: &ProveInfo) -> Result<AccountabilityThresholdOutput> {
        let verifier_context = VerifierContext::default().with_dev_mode(false);
        prove_info
            .receipt
            .verify_with_context(&verifier_context, SYMTHAEA_ZKPROOF_GUEST_ID)?;
        let output: AccountabilityThresholdOutput = prove_info.receipt.journal.decode()?;
        validate_public_bindings(
            &output.statement_digest,
            &output.query_digest,
            &output.policy_digest,
            &output.operation_nonce,
        )?;
        Ok(output)
    }

    /// Verify both the zkVM receipt and every expected SIF public binding.
    ///
    /// The result commitment is recomputed by verifier code from the boolean that
    /// the zkVM actually produced; the prover cannot substitute an unrelated
    /// externally supplied result digest.
    pub fn verify_for_expectation(
        prove_info: &ProveInfo,
        expected: &AccountabilityThresholdExpectation,
    ) -> Result<AccountabilityThresholdOutput> {
        validate_public_bindings(
            &expected.statement_digest,
            &expected.query_digest,
            &expected.policy_digest,
            &expected.operation_nonce,
        )?;
        ensure!(
            expected.result_digest != [0u8; 32],
            "SIF result commitment must not be all-zero"
        );

        let output = Self::verify(prove_info)?;
        ensure!(
            output.statement_digest == expected.statement_digest,
            "SIF proof statement does not match expected receipt commitment"
        );
        ensure!(
            output.query_digest == expected.query_digest,
            "SIF proof query commitment mismatch"
        );
        ensure!(
            output.policy_digest == expected.policy_digest,
            "SIF proof policy commitment mismatch"
        );
        ensure!(
            output.threshold == expected.threshold,
            "SIF proof threshold mismatch"
        );
        ensure!(
            output.operation_nonce == expected.operation_nonce,
            "SIF proof operation nonce mismatch"
        );
        ensure!(
            sif_predicate_result_commitment(output.satisfied) == expected.result_digest,
            "SIF proof result commitment mismatch"
        );
        Ok(output)
    }

    /// Verify an exact SIF proof and export the opaque reference metadata consumed
    /// by the higher accountability layer.
    pub fn verify_to_reference(
        prove_info: &ProveInfo,
        expected: &AccountabilityThresholdExpectation,
    ) -> Result<VerifiedAccountabilityComputationRef> {
        Self::verify_for_expectation(prove_info, expected)?;
        Ok(VerifiedAccountabilityComputationRef {
            scheme: SIF_ACCOUNTABILITY_THRESHOLD_SCHEME,
            statement_digest: expected.statement_digest,
            proof_digest: sif_proof_artifact_digest(prove_info)?,
            verifier_profile: SIF_ACCOUNTABILITY_THRESHOLD_VERIFIER_PROFILE,
            operation_nonce: expected.operation_nonce,
            result_digest: expected.result_digest,
        })
    }
}

/// Canonical result commitment profile for the v1 boolean threshold proof.
///
/// Mycelix can place this 32-byte value directly in its minimum-disclosure
/// `result_digest`; verification then recomputes it from the zkVM's actual public
/// boolean instead of trusting a prover-provided digest.
pub fn sif_predicate_result_commitment(satisfied: bool) -> [u8; 32] {
    let mut hasher = blake3::Hasher::new();
    hasher.update(SIF_PREDICATE_RESULT_DOMAIN);
    hasher.update(&[0]);
    hasher.update(&[u8::from(satisfied)]);
    *hasher.finalize().as_bytes()
}

/// Stable SIF reference digest for the concrete RISC Zero proof artifact.
///
/// The digest is deliberately computed over the Borsh serialization of
/// `Receipt::inner` (the actual cryptographic proof/seal and claim) plus the
/// authenticated journal bytes. Untrusted `ReceiptMetadata` is excluded. This is
/// an SIF artifact identifier, not a replacement for RISC Zero verification.
pub fn sif_proof_artifact_digest(prove_info: &ProveInfo) -> Result<[u8; 32]> {
    let proof_bytes = borsh::to_vec(&prove_info.receipt.inner)?;
    let journal_bytes = &prove_info.receipt.journal.bytes;

    let mut hasher = blake3::Hasher::new();
    hasher.update(SIF_PROOF_ARTIFACT_DOMAIN);
    hasher.update(&[0]);
    hasher.update(SIF_ACCOUNTABILITY_THRESHOLD_SCHEME.as_bytes());
    hasher.update(&[0]);
    hasher.update(&(proof_bytes.len() as u64).to_be_bytes());
    hasher.update(&proof_bytes);
    hasher.update(&(journal_bytes.len() as u64).to_be_bytes());
    hasher.update(journal_bytes);
    Ok(*hasher.finalize().as_bytes())
}

fn validate_public_bindings(
    statement_digest: &[u8; 32],
    query_digest: &[u8; 32],
    policy_digest: &[u8; 32],
    operation_nonce: &[u8; 32],
) -> Result<()> {
    ensure!(
        *statement_digest != [0u8; 32],
        "SIF statement commitment must not be all-zero"
    );
    ensure!(
        *query_digest != [0u8; 32],
        "SIF query commitment must not be all-zero"
    );
    ensure!(
        *policy_digest != [0u8; 32],
        "SIF policy commitment must not be all-zero"
    );
    ensure!(
        *operation_nonce != [0u8; 32],
        "SIF operation nonce must not be all-zero"
    );
    Ok(())
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_balance_proof_sufficient() {
        let prove_info = BalanceProver::prove(1000, 500, 42).unwrap();
        let output = BalanceProver::verify(&prove_info).unwrap();
        assert!(output.sufficient);
        assert_eq!(output.required_minimum, 500);
        assert_eq!(output.nonce, 42);
    }

    #[test]
    fn test_balance_proof_insufficient() {
        let prove_info = BalanceProver::prove(100, 500, 43).unwrap();
        let output = BalanceProver::verify(&prove_info).unwrap();
        assert!(!output.sufficient);
    }

    #[test]
    fn test_balance_proof_exact() {
        let prove_info = BalanceProver::prove(500, 500, 44).unwrap();
        let output = BalanceProver::verify(&prove_info).unwrap();
        assert!(output.sufficient);
    }

    #[test]
    fn test_balance_proof_zero_balance() {
        let prove_info = BalanceProver::prove(0, 0, 99).unwrap();
        let output = BalanceProver::verify(&prove_info).unwrap();
        assert!(output.sufficient);
        assert_eq!(output.required_minimum, 0);
    }

    #[test]
    fn test_balance_proof_max_values() {
        let prove_info = BalanceProver::prove(u64::MAX, u64::MAX, u64::MAX).unwrap();
        let output = BalanceProver::verify(&prove_info).unwrap();
        assert!(output.sufficient);
    }

    #[test]
    fn test_consciousness_attestation_still_works() {
        let input = EvolutionInput {
            episodes: vec![vec![0.0, 1.0]],
            tau_scale: 2.0,
            threshold: 0.5,
        };
        let prove_info = EvolutionaryProver::prove(input).unwrap();
        let output = EvolutionaryProver::verify(&prove_info).unwrap();
        assert!((output.average_phi - 1.0).abs() < 1e-6);
        assert_eq!(output.episode_count, 1);
    }

    fn sif_fixture() -> (ProveInfo, AccountabilityThresholdExpectation) {
        let statement_digest = [10u8; 32];
        let query_digest = [11u8; 32];
        let policy_digest = [12u8; 32];
        let operation_nonce = [13u8; 32];
        let prove_info = AccountabilityThresholdProver::prove(AccountabilityThresholdInput {
            private_value: 750,
            threshold: 500,
            statement_digest,
            query_digest,
            policy_digest,
            operation_nonce,
        })
        .unwrap();

        let expected = AccountabilityThresholdExpectation {
            statement_digest,
            query_digest,
            policy_digest,
            result_digest: sif_predicate_result_commitment(true),
            threshold: 500,
            operation_nonce,
        };
        (prove_info, expected)
    }

    #[test]
    fn test_sif_threshold_proof_binds_exact_accountability_context() {
        let (prove_info, expected) = sif_fixture();
        let output = AccountabilityThresholdProver::verify_for_expectation(&prove_info, &expected)
            .unwrap();
        assert!(output.satisfied);

        let mut replayed = expected.clone();
        replayed.statement_digest = [99u8; 32];
        assert!(
            AccountabilityThresholdProver::verify_for_expectation(&prove_info, &replayed).is_err()
        );
    }

    #[test]
    fn test_sif_threshold_proof_rejects_wrong_live_operation_nonce() {
        let (prove_info, mut expected) = sif_fixture();
        expected.operation_nonce = [77u8; 32];
        assert!(
            AccountabilityThresholdProver::verify_for_expectation(&prove_info, &expected).is_err()
        );
    }

    #[test]
    fn test_sif_verified_reference_identifies_real_proof_artifact() {
        let (prove_info, expected) = sif_fixture();
        let verified = AccountabilityThresholdProver::verify_to_reference(&prove_info, &expected)
            .unwrap();
        assert_eq!(verified.scheme, SIF_ACCOUNTABILITY_THRESHOLD_SCHEME);
        assert_eq!(verified.statement_digest, expected.statement_digest);
        assert_eq!(verified.operation_nonce, expected.operation_nonce);
        assert_eq!(verified.result_digest, expected.result_digest);
        assert_ne!(verified.proof_digest, [0u8; 32]);
        assert_eq!(
            verified.proof_digest,
            sif_proof_artifact_digest(&prove_info).unwrap()
        );
    }

    #[test]
    fn test_sif_result_commitment_distinguishes_boolean_outcomes() {
        assert_ne!(
            sif_predicate_result_commitment(true),
            sif_predicate_result_commitment(false)
        );
    }
}
