// Copyright (C) 2024-2026 Tristan Stoltz / Luminous Dynamics
// SPDX-License-Identifier: AGPL-3.0-or-later
// Commercial licensing: see COMMERCIAL_LICENSE.md at repository root
use anyhow::Result;
use risc0_zkvm::{ExecutorEnv, ProveInfo, default_prover};
use symthaea_zkproof_core::{
    BalanceProofInput, BalanceProofOutput, EvolutionInput, EvolutionOutput,
};

// Re-exported from the methods crate (generated by risc0-build).
// The constant names are derived from the guest binary target name
// ("symthaea-zkproof-guest" → SYMTHAEA_ZKPROOF_GUEST_*).
use symthaea_zkproof_methods::{SYMTHAEA_ZKPROOF_GUEST_ELF, SYMTHAEA_ZKPROOF_GUEST_ID};

// ---------------------------------------------------------------------------
// Consciousness attestation prover (tag = 0)
// ---------------------------------------------------------------------------

pub struct EvolutionaryProver;

impl EvolutionaryProver {
    pub fn prove(input: EvolutionInput) -> Result<ProveInfo> {
        let env = ExecutorEnv::builder()
            .write(&0u8)? // tag = 0
            .write(&input)?
            .build()?;

        let prover = default_prover();
        let prove_info = prover.prove(env, SYMTHAEA_ZKPROOF_GUEST_ELF)?;
        Ok(prove_info)
    }

    pub fn verify(prove_info: &ProveInfo) -> Result<EvolutionOutput> {
        prove_info.receipt.verify(SYMTHAEA_ZKPROOF_GUEST_ID)?;
        let output: EvolutionOutput = prove_info.receipt.journal.decode()?;
        Ok(output)
    }
}

// ---------------------------------------------------------------------------
// Balance sufficiency prover (tag = 1)
// ---------------------------------------------------------------------------

/// Proves that a balance is sufficient (>= required minimum) without
/// revealing the actual balance.
///
/// The proof commits to:
/// - `sufficient: bool` (PUBLIC)
/// - `required_minimum: u64` (PUBLIC)
/// - `nonce: u64` (PUBLIC)
///
/// The actual balance is PRIVATE — included in the proof computation
/// but never revealed.
pub struct BalanceProver;

impl BalanceProver {
    /// Generate a ZK proof that `balance >= required_minimum`.
    ///
    /// Returns the proof receipt containing the public outputs.
    /// The actual balance is never revealed.
    pub fn prove(balance: u64, required_minimum: u64, nonce: u64) -> Result<ProveInfo> {
        let env = ExecutorEnv::builder()
            .write(&1u8)? // tag = 1 (balance proof)
            .write(&BalanceProofInput {
                balance,
                required_minimum,
                nonce,
            })?
            .build()?;

        let prover = default_prover();
        let prove_info = prover.prove(env, SYMTHAEA_ZKPROOF_GUEST_ELF)?;
        Ok(prove_info)
    }

    /// Verify a balance proof receipt and decode the public output.
    pub fn verify(prove_info: &ProveInfo) -> Result<BalanceProofOutput> {
        prove_info.receipt.verify(SYMTHAEA_ZKPROOF_GUEST_ID)?;
        let output: BalanceProofOutput = prove_info.receipt.journal.decode()?;
        Ok(output)
    }
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_balance_proof_sufficient() {
        let prove_info = BalanceProver::prove(1000, 500, 42).unwrap();
        let output = BalanceProver::verify(&prove_info).unwrap();
        assert!(output.sufficient);
        assert_eq!(output.required_minimum, 500);
        assert_eq!(output.nonce, 42);
    }

    #[test]
    fn test_balance_proof_insufficient() {
        let prove_info = BalanceProver::prove(100, 500, 43).unwrap();
        let output = BalanceProver::verify(&prove_info).unwrap();
        assert!(!output.sufficient);
    }

    #[test]
    fn test_balance_proof_exact() {
        let prove_info = BalanceProver::prove(500, 500, 44).unwrap();
        let output = BalanceProver::verify(&prove_info).unwrap();
        assert!(output.sufficient);
    }

    #[test]
    fn test_balance_proof_zero_balance() {
        let prove_info = BalanceProver::prove(0, 0, 99).unwrap();
        let output = BalanceProver::verify(&prove_info).unwrap();
        assert!(output.sufficient);
        assert_eq!(output.required_minimum, 0);
    }

    #[test]
    fn test_balance_proof_max_values() {
        let prove_info = BalanceProver::prove(u64::MAX, u64::MAX, u64::MAX).unwrap();
        let output = BalanceProver::verify(&prove_info).unwrap();
        assert!(output.sufficient);
    }

    #[test]
    fn test_consciousness_attestation_still_works() {
        let input = EvolutionInput {
            episodes: vec![vec![0.0, 1.0]],
            tau_scale: 2.0,
            threshold: 0.5,
        };
        let prove_info = EvolutionaryProver::prove(input).unwrap();
        let output = EvolutionaryProver::verify(&prove_info).unwrap();
        assert!((output.average_phi - 1.0).abs() < 1e-6);
        assert_eq!(output.episode_count, 1);
    }
}
