#!/usr/bin/env python3
"""
Render the two primary figures for the IWAI paper on Φ-gated motor authority.

Figure 1 — Φ trace over time
    Source: ../data/phi_trace_40s.csv (generated by
            `MANIP_BENCH_PHI_TRACE=1 MANIP_BENCH_PHI_TRIALS=1 cargo run
             --release --example manipulator_benchmark`)
    Shows Φ oscillating in the narrow empirical band [0.099, 0.145]
    with SafetyTier default thresholds (Green > 0.6, etc.) overlaid
    — demonstrating why the default mapping pins the arm at a single tier.

Figure 2 — S_p sweep bar chart
    Source: ../data/sp_sweep_results.csv
    Shows ISO cycles/100s collapsing from 7.00 to 0.00 across the
    sweep, vs Φ-SprintFloor's flat 1.00 — the graceful-degradation
    headline result.

Usage (from inside `symtropy/papers/phi-gated-safety/figures/`):

    nix-shell -p 'python3.withPackages (ps: [ps.matplotlib ps.numpy])' \
      --run "python3 render_figures.py"

Output: figure1_phi_trace.png, figure2_sp_sweep.png in the same directory.
"""

import csv
from pathlib import Path
import matplotlib
matplotlib.use("Agg")  # headless
import matplotlib.pyplot as plt
import numpy as np


HERE = Path(__file__).parent
DATA_DIR = HERE.parent / "data"


# ── Figure 1: Φ trace over time ───────────────────────────────────────

def render_phi_trace():
    trace_path = DATA_DIR / "phi_trace_40s.csv"
    ts, dists, pes, dangers, phis, gains = [], [], [], [], [], []
    with open(trace_path) as f:
        for line in f:
            if not line.startswith("TRACE,"):
                continue
            # TRACE,t,human_dist,pe,danger,phi,gain
            parts = line.strip().split(",")
            ts.append(float(parts[1]))
            dists.append(float(parts[2]))
            pes.append(float(parts[3]))
            dangers.append(float(parts[4]))
            phis.append(float(parts[5]))
            gains.append(float(parts[6]))

    fig, (ax_phi, ax_ctx) = plt.subplots(
        2, 1, figsize=(9, 5), sharex=True, gridspec_kw={"height_ratios": [3, 1]}
    )

    # Top: Φ over time with SafetyTier defaults overlaid
    ax_phi.plot(ts, phis, color="#1f6ead", linewidth=1.2, label=r"$\Phi$ (actual)")
    for threshold, label, color in [
        (0.6, "Green  (gain=1.0)", "#2ecc71"),
        (0.3, "Yellow (gain=0.6)", "#f1c40f"),
        (0.1, "Orange (gain=0.3)", "#e67e22"),
    ]:
        ax_phi.axhline(threshold, color=color, linestyle="--", linewidth=0.9, alpha=0.8)
        ax_phi.text(
            ts[-1] * 1.01, threshold, label,
            va="center", fontsize=8, color=color,
        )

    # Empirical band shaded
    phi_lo, phi_hi = min(phis), max(phis)
    ax_phi.axhspan(phi_lo, phi_hi, alpha=0.15, color="#1f6ead",
                   label=f"empirical band [{phi_lo:.3f}, {phi_hi:.3f}]")
    # Sprint threshold the recalibrated mapping uses
    ax_phi.axhline(
        0.125, color="#8e44ad", linewidth=1.5, linestyle=":",
        label="SprintFloor threshold (0.125, post-FEP-wiring)"
    )

    ax_phi.set_ylabel(r"$\Phi$")
    ax_phi.set_ylim(0, 0.7)
    ax_phi.set_title(
        r"Figure 1 — $\Phi$ stays in a narrow empirical band; "
        r"default SafetyTier thresholds never fire"
    )
    ax_phi.legend(loc="upper right", fontsize=8, framealpha=0.85)
    ax_phi.grid(alpha=0.3)

    # Bottom: context signals (human distance normalized, PE)
    ax_ctx.plot(ts, dists, color="#34495e", linewidth=0.9, label="human distance (m)")
    ax_ctx.plot(ts, [p * 10 for p in pes],
                color="#c0392b", linewidth=0.8, alpha=0.6, label="HDC PE × 10")
    ax_ctx.set_xlabel("time (s)")
    ax_ctx.set_ylabel("context")
    ax_ctx.legend(loc="upper right", fontsize=7, framealpha=0.8)
    ax_ctx.grid(alpha=0.3)

    fig.tight_layout()
    out = HERE / "figure1_phi_trace.png"
    fig.savefig(out, dpi=150)
    plt.close(fig)
    print(f"wrote {out} ({len(ts)} samples, Φ ∈ [{phi_lo:.3f}, {phi_hi:.3f}])")


# ── Figure 2: S_p sweep bar chart ─────────────────────────────────────

def render_sp_sweep():
    sweep_path = DATA_DIR / "sp_sweep_results.csv"
    rows = []
    with open(sweep_path) as f:
        reader = csv.DictReader(f)
        for row in reader:
            rows.append(row)

    sp_labels = [row["sp_m"] for row in rows]
    iso_means = [float(row["iso_cycles_mean"]) for row in rows]
    iso_stds = [float(row["iso_cycles_std"]) for row in rows]
    phi_means = [float(row["phi_sprintfloor_cycles_mean"]) for row in rows]
    phi_stds = [float(row["phi_sprintfloor_cycles_std"]) for row in rows]

    x = np.arange(len(sp_labels))
    width = 0.40

    fig, ax = plt.subplots(figsize=(9, 4.5))
    b1 = ax.bar(x - width / 2, iso_means, width, yerr=iso_stds,
                label="ISO/TS 15066 SSM", color="#e74c3c", capsize=3)
    b2 = ax.bar(x + width / 2, phi_means, width, yerr=phi_stds,
                label=r"$\Phi$-SprintFloor", color="#1f6ead", capsize=3)

    ax.set_xlabel(r"ISO protective distance $S_p$ (m)")
    ax.set_ylabel("cycles per 100 s (N=30 ISO, N=10 Φ, mean ± std)")
    ax.set_xticks(x)
    ax.set_xticklabels(sp_labels)
    ax.set_title(
        r"Figure 2 — ISO collapses 7→0 across $S_p$ sweep; "
        r"$\Phi$-SprintFloor holds ~0.8 cycles/100s (post-FEP-wiring)"
    )
    ax.legend(loc="upper right", fontsize=9)
    ax.grid(axis="y", alpha=0.3)

    # Annotate the crossover
    # S_p = 2.5m: Φ (0.80) wins over ISO (0.47) — N=30 post-FEP-wiring
    crossover_idx = sp_labels.index("2.50")
    ax.annotate(
        "Φ wins +71 %\n(crossover)",
        xy=(crossover_idx + width / 2, phi_means[crossover_idx]),
        xytext=(crossover_idx + 0.8, 4.0),
        fontsize=9,
        ha="left",
        arrowprops=dict(arrowstyle="->", color="#1f6ead", lw=1.2),
        color="#1f6ead",
    )
    # S_p = 3.0m: ISO catastrophic
    cat_idx = sp_labels.index("3.00")
    ax.annotate(
        "ISO catastrophic\n(0 cycles)",
        xy=(cat_idx - width / 2, 0.1),
        xytext=(cat_idx - 2.0, 3.0),
        fontsize=9,
        ha="left",
        arrowprops=dict(arrowstyle="->", color="#e74c3c", lw=1.2),
        color="#e74c3c",
    )

    fig.tight_layout()
    out = HERE / "figure2_sp_sweep.png"
    fig.savefig(out, dpi=150)
    plt.close(fig)
    print(f"wrote {out} ({len(rows)} S_p points)")


# ── Figure 3: Cross-platform flight benchmark (paired tier-vs-sprint) ─

def render_flight_benchmark():
    csv_path = DATA_DIR / "flight_benchmark_n30.csv"
    if not csv_path.exists():
        print(f"skipping figure3: {csv_path} not found — "
              "regenerate via `cargo run -p symthaea-flight --example "
              "flight_benchmark --release` with FB_CSV=…")
        return
    tier_means, sprint_means = [], []
    tier_red, sprint_red = [], []
    with open(csv_path) as f:
        reader = csv.DictReader(f)
        for row in reader:
            if row["policy"] == "tier":
                tier_means.append(float(row["mean_thrust"]))
                tier_red.append(float(row["red_fraction"]))
            else:
                sprint_means.append(float(row["mean_thrust"]))
                sprint_red.append(float(row["red_fraction"]))

    n = min(len(tier_means), len(sprint_means))
    tier_m = np.mean(tier_means)
    tier_s = np.std(tier_means, ddof=1)
    sprint_m = np.mean(sprint_means)
    sprint_s = np.std(sprint_means, ddof=1)

    paired = [100.0 * (s - t) / t if t > 1e-9 else 0.0
              for t, s in zip(tier_means, sprint_means)]
    adv_m = float(np.mean(paired))
    adv_s = float(np.std(paired, ddof=1))
    ci_half = 1.96 * adv_s / np.sqrt(n)

    fig, (ax_thr, ax_red) = plt.subplots(
        1, 2, figsize=(10, 4.5), gridspec_kw={"width_ratios": [3, 2]}
    )

    # Left panel: paired means with error bars
    x = np.array([0, 1])
    means = [tier_m, sprint_m]
    stds = [tier_s, sprint_s]
    bars = ax_thr.bar(
        x,
        means,
        yerr=stds,
        width=0.55,
        color=["#e74c3c", "#1f6ead"],
        capsize=6,
    )
    ax_thr.set_xticks(x)
    ax_thr.set_xticklabels(["tier-gate\n(4-tier)", r"sprint-floor\n(2-level)"])
    ax_thr.set_ylabel("mean thrust per frame (Newtons)")
    ax_thr.set_title(
        r"Figure 3 — Flight platform reproduces the headline: "
        rf"sprint-floor wins +{adv_m:.1f} % (N={n}, 95 % CI "
        rf"[+{adv_m-ci_half:.1f}, +{adv_m+ci_half:.1f}])",
        fontsize=10,
    )
    ax_thr.grid(axis="y", alpha=0.3)
    # Annotate bars with values
    for bar, mean in zip(bars, means):
        ax_thr.text(
            bar.get_x() + bar.get_width() / 2,
            mean + 0.005,
            f"{mean:.3f}",
            ha="center",
            va="bottom",
            fontsize=9,
        )

    # Right panel: red-frame fraction
    ax_red.bar(
        x,
        [np.mean(tier_red), np.mean(sprint_red)],
        width=0.55,
        color=["#e74c3c", "#1f6ead"],
    )
    ax_red.set_xticks(x)
    ax_red.set_xticklabels(["tier-gate", "sprint-floor"])
    ax_red.set_ylabel("red-frame fraction")
    ax_red.set_title(
        "Red-frame fraction\n(gain≈0, lower is better)", fontsize=10
    )
    ax_red.set_ylim(0, 1)
    ax_red.grid(axis="y", alpha=0.3)
    for i, v in enumerate([np.mean(tier_red), np.mean(sprint_red)]):
        ax_red.text(i, v + 0.02, f"{v:.2f}", ha="center", va="bottom",
                    fontsize=9)

    fig.tight_layout()
    out = HERE / "figure3_flight_benchmark.png"
    fig.savefig(out, dpi=150)
    plt.close(fig)
    print(f"wrote {out} (N={n}, sprint-floor advantage +{adv_m:.1f} %)")


# ── Figure 4: Structural Φ-invariance across platforms ───────────────

def render_phi_trace_multi():
    """Overlay Φ traces captured by `phi_trace.rs` across six platforms.

    The lines will lie on top of each other because the `RoboticAgent::tick`
    implementation computes `ConsciousnessInputs` purely from `danger_level`
    — the observation vector and platform type don't enter the
    consciousness computation. Visualizing the overlap makes the §8
    structural-transferability argument concrete.
    """
    trace_dir = DATA_DIR / "phi_trace_multi"
    if not trace_dir.exists():
        print(f"skipping figure4: {trace_dir} not found — "
              "regenerate via `PT_CSV=… cargo run -p symtropy-robotics-"
              "bridge --example phi_trace --release` per platform")
        return

    platforms = ["quadrotor", "vehicle", "humanoid", "manipulator",
                 "auv", "helicopter"]
    data = {}
    for p in platforms:
        csv_path = trace_dir / f"{p}.csv"
        if not csv_path.exists():
            continue
        ts, phis = [], []
        with open(csv_path) as f:
            reader = csv.DictReader(f)
            for row in reader:
                ts.append(int(row["step"]))
                phis.append(float(row["phi"]))
        data[p] = (np.array(ts), np.array(phis))

    if not data:
        print("skipping figure4: no trace CSVs found")
        return

    fig, (ax_time, ax_hist) = plt.subplots(
        1, 2, figsize=(11, 4.2), gridspec_kw={"width_ratios": [3, 1]}
    )

    colors = {
        "quadrotor": "#1f6ead",
        "vehicle": "#c0392b",
        "humanoid": "#27ae60",
        "manipulator": "#8e44ad",
        "auv": "#16a085",
        "helicopter": "#f39c12",
    }

    # Time-series panel — first 200 ticks for legibility
    show_to = 200
    for p, (ts, phis) in data.items():
        mask = ts < show_to
        ax_time.plot(ts[mask], phis[mask],
                     color=colors.get(p, "#555"),
                     linewidth=0.9, alpha=0.75, label=p)
    # Threshold line
    ax_time.axhline(0.125, color="#2c3e50", linestyle="--",
                    linewidth=1.1, alpha=0.85,
                    label="SPRINT_THRESHOLD = 0.125 (post-FEP-wiring)")
    # Post-FEP-wiring empirical band
    ax_time.axhspan(0.088, 0.133, color="#1f6ead", alpha=0.08)
    ax_time.set_xlabel("tick")
    ax_time.set_ylabel(r"$\Phi$ (consciousness-inspired scalar)")
    ax_time.set_ylim(0.08, 0.16)
    ax_time.set_title(
        r"Figure 4 — Post-FEP-wiring $\Phi$ traces diverge by observation "
        r"dim: humanoid (dim=2) lowest, dim=4 platforms clustered top",
        fontsize=10,
    )
    ax_time.legend(loc="lower right", fontsize=7, framealpha=0.88, ncol=2)
    ax_time.grid(alpha=0.25)

    # Histogram panel — distribution of Φ across the full 1000 ticks
    for p, (_, phis) in data.items():
        ax_hist.hist(phis, bins=30, alpha=0.35,
                     color=colors.get(p, "#555"), label=p,
                     orientation="horizontal")
    ax_hist.axhline(0.125, color="#2c3e50", linestyle="--", linewidth=1.1)
    ax_hist.axhspan(0.088, 0.133, color="#1f6ead", alpha=0.08)
    ax_hist.set_xlabel("count")
    ax_hist.set_ylim(0.08, 0.16)
    ax_hist.set_title("distribution (1000 ticks)", fontsize=10)
    ax_hist.grid(alpha=0.25)

    fig.tight_layout()
    out = HERE / "figure4_phi_invariance.png"
    fig.savefig(out, dpi=150)
    plt.close(fig)
    print(f"wrote {out} ({len(data)} platforms)")


if __name__ == "__main__":
    render_phi_trace()
    render_sp_sweep()
    render_flight_benchmark()
    render_phi_trace_multi()
    print("\nAll figures rendered. Files:")
    for p in sorted(HERE.glob("figure*.png")):
        print(f"  {p}  ({p.stat().st_size // 1024} KB)")
