[package]
name = "legacy_memorial"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]
name = "legacy_memorial"

[dependencies]
hdk = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
holochain_serialized_bytes = { workspace = true }
legacy_memorial_integrity = { path = "../integrity" }
legacy-types = { workspace = true }
