// Copyright (C) 2024-2026 Tristan Stoltz / Luminous Dynamics
// SPDX-License-Identifier: AGPL-3.0-or-later
// Commercial licensing: see COMMERCIAL_LICENSE.md at repository root

//! Canonical neural-evidence provenance types for Symthaea.
//!
//! This module separates synthetic fixtures, simulated model state, external
//! neural-surrogate predictions, and observed neural measurements. Structural
//! validation proves that an artifact's declared authority and coordinate
//! lineage are internally consistent; it does not prove that external metadata
//! is truthful.
//!
//! Three boundaries are deliberate:
//!
//! - raw [`EvidenceAuthority`] values grant no evidence use;
//! - a [`NeuralObservation`] must pass provenance validation before it exists;
//! - a downstream scientific consumer can require [`AdmittedNeuralEvidence`],
//!   a non-deserializable capability earned for one explicit [`EvidenceUse`].
//!
//! Spatial coordinate changes are valid only through an explicit, versioned,
//! digest-bound transform chain from native coordinates to payload coordinates.

use serde::{Deserialize, Deserializer, Serialize};

/// Current serialized schema version for [`NeuralEvidenceProvenance`].
pub const NEURAL_EVIDENCE_SCHEMA_VERSION: u16 = 1;

/// Evidential authority claimed by a neural representation.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum EvidenceAuthority {
    /// Data generated only as a software/test fixture.
    SyntheticFixture,
    /// State generated by Symthaea or another explicit simulation.
    SimulatedModel,
    /// Prediction from an external model trained to predict neural data.
    ExternalSurrogate,
    /// Neural data measured from a participant or organism.
    EmpiricalObserved,
}

impl EvidenceAuthority {
    pub const fn is_empirical_observation(self) -> bool {
        matches!(self, Self::EmpiricalObserved)
    }

    pub const fn is_external_surrogate(self) -> bool {
        matches!(self, Self::ExternalSurrogate)
    }

    const fn requires_model_identity(self) -> bool {
        matches!(
            self,
            Self::SyntheticFixture | Self::SimulatedModel | Self::ExternalSurrogate
        )
    }

    const fn requires_modality(self) -> bool {
        matches!(self, Self::ExternalSurrogate | Self::EmpiricalObserved)
    }

    const fn requires_source_digest(self) -> bool {
        matches!(self, Self::ExternalSurrogate | Self::EmpiricalObserved)
    }
}

/// Intended use of an admitted neural-evidence artifact.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum EvidenceUse {
    SoftwareQualification,
    ModelBehavior,
    SurrogateAlignment,
    EmpiricalNeuralAnalysis,
    ConsciousnessInference,
}

/// Neural recording or prediction modality.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum NeuralModality {
    Fmri,
    Eeg,
    Meg,
    Ieeg,
    TmsEeg,
}

/// Spatial coordinate system in which neural values live.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum CoordinateSystem {
    #[serde(rename = "symthaea12")]
    Symthaea12,
    #[serde(rename = "fsaverage5")]
    FsAverage5,
    /// Human Connectome Project MMP1.0 / Glasser 360-parcel atlas.
    /// `hcp_mmp1` is accepted as a historical/descriptive wire alias.
    #[serde(rename = "glasser360", alias = "hcp_mmp1")]
    Glasser360,
    #[serde(rename = "desikan_killiany68")]
    DesikanKilliany68,
    #[serde(rename = "schaefer100")]
    Schaefer100,
    #[serde(rename = "sensor_space")]
    SensorSpace,
}

/// Temporal reduction applied independently of spatial transforms.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum TemporalAggregation {
    #[serde(rename = "native")]
    Native,
    #[serde(rename = "temporal_mean")]
    TemporalMean,
}

/// One declared spatial coordinate transformation.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct CoordinateTransformProvenance {
    pub from: CoordinateSystem,
    pub to: CoordinateSystem,
    pub transform_id: String,
    pub transform_version: String,
    /// Digest of the atlas/mapping artifact: `sha256:<64 hex>` or `blake3:<64 hex>`.
    pub source_digest: String,
}

impl CoordinateTransformProvenance {
    pub fn validate(self) -> Result<ValidatedCoordinateTransform, ProvenanceError> {
        validate_transform(&self)?;
        Ok(ValidatedCoordinateTransform(self))
    }
}

/// Coordinate transform whose endpoints, identity, version, and digest validate.
#[derive(Debug, Clone, PartialEq, Eq, Serialize)]
#[serde(transparent)]
pub struct ValidatedCoordinateTransform(CoordinateTransformProvenance);

impl ValidatedCoordinateTransform {
    pub const fn from(&self) -> CoordinateSystem {
        self.0.from
    }

    pub const fn to(&self) -> CoordinateSystem {
        self.0.to
    }

    pub fn as_raw(&self) -> &CoordinateTransformProvenance {
        &self.0
    }
}

impl<'de> Deserialize<'de> for ValidatedCoordinateTransform {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: Deserializer<'de>,
    {
        CoordinateTransformProvenance::deserialize(deserializer)?
            .validate()
            .map_err(serde::de::Error::custom)
    }
}

/// Raw provenance envelope before validation.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct NeuralEvidenceProvenance {
    pub schema_version: u16,
    pub authority: EvidenceAuthority,
    pub modality: Option<NeuralModality>,
    /// Human-readable producer/source identity.
    pub source: String,
    /// Generator/model identity for synthetic, simulated, and surrogate evidence.
    pub model: Option<String>,
    /// Generator/model revision required whenever `model` is authoritative.
    pub model_version: Option<String>,
    /// Dataset identity required for observed empirical evidence.
    pub dataset: Option<String>,
    pub subject_id: Option<String>,
    pub stimulus_id: Option<String>,
    /// Coordinate system of the native source representation.
    pub native_coordinate_system: CoordinateSystem,
    /// Coordinate system of the current payload.
    pub coordinate_system: CoordinateSystem,
    /// Ordered spatial lineage from native to current coordinates.
    #[serde(default)]
    pub coordinate_transforms: Vec<CoordinateTransformProvenance>,
    /// Temporal reduction, orthogonal to spatial coordinate lineage.
    pub temporal_aggregation: TemporalAggregation,
    /// Digest of the source data/model output when required by authority.
    pub source_digest: Option<String>,
}

impl NeuralEvidenceProvenance {
    pub fn validate(self) -> Result<ValidatedProvenance, ProvenanceError> {
        ValidatedProvenance::try_from(self)
    }
}

/// Provenance that passed authority, metadata, digest, and coordinate-lineage checks.
#[derive(Debug, Clone, PartialEq, Eq, Serialize)]
#[serde(transparent)]
pub struct ValidatedProvenance(NeuralEvidenceProvenance);

impl ValidatedProvenance {
    pub const fn authority(&self) -> EvidenceAuthority {
        self.0.authority
    }

    pub const fn modality(&self) -> Option<NeuralModality> {
        self.0.modality
    }

    pub const fn native_coordinate_system(&self) -> CoordinateSystem {
        self.0.native_coordinate_system
    }

    pub const fn coordinate_system(&self) -> CoordinateSystem {
        self.0.coordinate_system
    }

    pub fn coordinate_transforms(&self) -> &[CoordinateTransformProvenance] {
        &self.0.coordinate_transforms
    }

    pub fn as_raw(&self) -> &NeuralEvidenceProvenance {
        &self.0
    }

    const fn permits(&self, use_case: EvidenceUse) -> bool {
        match (self.0.authority, use_case) {
            (_, EvidenceUse::SoftwareQualification) => true,
            (EvidenceAuthority::SimulatedModel, EvidenceUse::ModelBehavior) => true,
            (EvidenceAuthority::ExternalSurrogate, EvidenceUse::SurrogateAlignment) => true,
            (EvidenceAuthority::EmpiricalObserved, EvidenceUse::EmpiricalNeuralAnalysis) => true,
            (_, EvidenceUse::ConsciousnessInference) => false,
            _ => false,
        }
    }
}

impl TryFrom<NeuralEvidenceProvenance> for ValidatedProvenance {
    type Error = ProvenanceError;

    fn try_from(value: NeuralEvidenceProvenance) -> Result<Self, Self::Error> {
        if value.schema_version != NEURAL_EVIDENCE_SCHEMA_VERSION {
            return Err(ProvenanceError::UnsupportedSchemaVersion {
                found: value.schema_version,
            });
        }
        if value.source.trim().is_empty() {
            return Err(ProvenanceError::MissingSource);
        }

        if value.authority.requires_model_identity() {
            require_nonempty(
                value.model.as_deref(),
                ProvenanceError::MissingModel {
                    authority: value.authority,
                },
            )?;
            require_nonempty(
                value.model_version.as_deref(),
                ProvenanceError::MissingModelVersion {
                    authority: value.authority,
                },
            )?;
        }

        if value.authority.requires_modality() && value.modality.is_none() {
            return Err(ProvenanceError::MissingModality {
                authority: value.authority,
            });
        }

        if value.authority == EvidenceAuthority::EmpiricalObserved {
            require_nonempty(value.dataset.as_deref(), ProvenanceError::MissingDataset)?;
        }

        match value.source_digest.as_deref() {
            Some(digest) => validate_digest(digest)?,
            None if value.authority.requires_source_digest() => {
                return Err(ProvenanceError::MissingSourceDigest {
                    authority: value.authority,
                });
            }
            None => {}
        }

        validate_coordinate_chain(&value)?;
        Ok(Self(value))
    }
}

impl<'de> Deserialize<'de> for ValidatedProvenance {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: Deserializer<'de>,
    {
        NeuralEvidenceProvenance::deserialize(deserializer)?
            .validate()
            .map_err(serde::de::Error::custom)
    }
}

/// Neural data paired with validated provenance.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct NeuralObservation<T> {
    data: T,
    provenance: ValidatedProvenance,
}

impl<T> NeuralObservation<T> {
    pub fn new(data: T, provenance: NeuralEvidenceProvenance) -> Result<Self, ProvenanceError> {
        Ok(Self {
            data,
            provenance: provenance.validate()?,
        })
    }

    pub fn data(&self) -> &T {
        &self.data
    }

    pub fn provenance(&self) -> &ValidatedProvenance {
        &self.provenance
    }

    /// Consume this validated observation and earn a capability for one evidence use.
    ///
    /// The returned capability intentionally does not implement `Deserialize`;
    /// persisted data must be validated and admitted again after loading.
    pub fn authorize(
        self,
        use_case: EvidenceUse,
    ) -> Result<AdmittedNeuralEvidence<T>, EvidenceAdmissionError> {
        if self.provenance.permits(use_case) {
            Ok(AdmittedNeuralEvidence {
                observation: self,
                use_case,
            })
        } else {
            Err(EvidenceAdmissionError {
                authority: self.provenance.authority(),
                requested_use: use_case,
            })
        }
    }

    pub fn into_parts(self) -> (T, ValidatedProvenance) {
        (self.data, self.provenance)
    }
}

/// Capability proving that a validated observation was admitted for one use.
///
/// There is no public constructor and no `Deserialize` implementation. A caller
/// must obtain this through [`NeuralObservation::authorize`] each time data crosses
/// a persistence or trust boundary.
#[derive(Debug, Clone, PartialEq)]
pub struct AdmittedNeuralEvidence<T> {
    observation: NeuralObservation<T>,
    use_case: EvidenceUse,
}

impl<T> AdmittedNeuralEvidence<T> {
    pub const fn use_case(&self) -> EvidenceUse {
        self.use_case
    }

    pub fn data(&self) -> &T {
        self.observation.data()
    }

    pub fn provenance(&self) -> &ValidatedProvenance {
        self.observation.provenance()
    }

    pub fn into_observation(self) -> NeuralObservation<T> {
        self.observation
    }
}

/// A validated observation was not authorized for the requested scientific use.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct EvidenceAdmissionError {
    pub authority: EvidenceAuthority,
    pub requested_use: EvidenceUse,
}

impl std::fmt::Display for EvidenceAdmissionError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(
            f,
            "{:?} neural evidence is not admitted for {:?}",
            self.authority, self.requested_use
        )
    }
}

impl std::error::Error for EvidenceAdmissionError {}

fn require_nonempty(value: Option<&str>, error: ProvenanceError) -> Result<(), ProvenanceError> {
    if value.is_none_or(|v| v.trim().is_empty()) {
        Err(error)
    } else {
        Ok(())
    }
}

fn validate_coordinate_chain(value: &NeuralEvidenceProvenance) -> Result<(), ProvenanceError> {
    let mut current = value.native_coordinate_system;
    for (index, transform) in value.coordinate_transforms.iter().enumerate() {
        validate_transform(transform)?;
        if transform.from != current {
            return Err(ProvenanceError::TransformChainSourceMismatch {
                index,
                expected: current,
                found: transform.from,
            });
        }
        current = transform.to;
    }
    if current != value.coordinate_system {
        return Err(ProvenanceError::TransformChainTargetMismatch {
            expected: value.coordinate_system,
            found: current,
        });
    }
    Ok(())
}

fn validate_transform(transform: &CoordinateTransformProvenance) -> Result<(), ProvenanceError> {
    if transform.from == transform.to {
        return Err(ProvenanceError::IdentityCoordinateTransform);
    }
    if transform.transform_id.trim().is_empty() {
        return Err(ProvenanceError::MissingTransformId);
    }
    if transform.transform_version.trim().is_empty() {
        return Err(ProvenanceError::MissingTransformVersion);
    }
    validate_digest(&transform.source_digest)
}

fn validate_digest(digest: &str) -> Result<(), ProvenanceError> {
    let Some((algorithm, hex)) = digest.split_once(':') else {
        return Err(ProvenanceError::MalformedDigest);
    };
    if !matches!(algorithm, "sha256" | "blake3")
        || hex.len() != 64
        || !hex.bytes().all(|byte| byte.is_ascii_hexdigit())
    {
        return Err(ProvenanceError::MalformedDigest);
    }
    Ok(())
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum ProvenanceError {
    UnsupportedSchemaVersion {
        found: u16,
    },
    MissingSource,
    MissingModel {
        authority: EvidenceAuthority,
    },
    MissingModelVersion {
        authority: EvidenceAuthority,
    },
    MissingDataset,
    MissingModality {
        authority: EvidenceAuthority,
    },
    MissingSourceDigest {
        authority: EvidenceAuthority,
    },
    MalformedDigest,
    IdentityCoordinateTransform,
    MissingTransformId,
    MissingTransformVersion,
    TransformChainSourceMismatch {
        index: usize,
        expected: CoordinateSystem,
        found: CoordinateSystem,
    },
    TransformChainTargetMismatch {
        expected: CoordinateSystem,
        found: CoordinateSystem,
    },
}

impl std::fmt::Display for ProvenanceError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::UnsupportedSchemaVersion { found } => write!(
                f,
                "unsupported neural evidence schema version {found}; expected {NEURAL_EVIDENCE_SCHEMA_VERSION}"
            ),
            Self::MissingSource => f.write_str("neural evidence source must be explicit"),
            Self::MissingModel { authority } => {
                write!(f, "{authority:?} evidence requires an explicit model identifier")
            }
            Self::MissingModelVersion { authority } => {
                write!(f, "{authority:?} evidence requires an explicit model version")
            }
            Self::MissingDataset => {
                f.write_str("empirical observed evidence requires an explicit dataset identifier")
            }
            Self::MissingModality { authority } => {
                write!(f, "{authority:?} evidence requires an explicit neural modality")
            }
            Self::MissingSourceDigest { authority } => {
                write!(f, "{authority:?} evidence requires an immutable source digest")
            }
            Self::MalformedDigest => {
                f.write_str("digest must be sha256:<64 hex> or blake3:<64 hex>")
            }
            Self::IdentityCoordinateTransform => {
                f.write_str("coordinate transforms must change coordinate systems")
            }
            Self::MissingTransformId => f.write_str("coordinate transform id must be explicit"),
            Self::MissingTransformVersion => {
                f.write_str("coordinate transform version must be explicit")
            }
            Self::TransformChainSourceMismatch {
                index,
                expected,
                found,
            } => write!(
                f,
                "coordinate transform {index} expected input {expected:?}, found {found:?}"
            ),
            Self::TransformChainTargetMismatch { expected, found } => write!(
                f,
                "coordinate transform chain ended at {found:?}, expected {expected:?}"
            ),
        }
    }
}

impl std::error::Error for ProvenanceError {}

#[cfg(test)]
mod tests {
    use super::*;

    const SHA_A: &str =
        "sha256:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa";
    const SHA_B: &str =
        "sha256:bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb";
    const BLAKE_C: &str =
        "blake3:cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc";

    fn fixture() -> NeuralEvidenceProvenance {
        NeuralEvidenceProvenance {
            schema_version: NEURAL_EVIDENCE_SCHEMA_VERSION,
            authority: EvidenceAuthority::SyntheticFixture,
            modality: Some(NeuralModality::Fmri),
            source: "unit-test".into(),
            model: Some("symthaea-neural-fixture".into()),
            model_version: Some("1".into()),
            dataset: None,
            subject_id: None,
            stimulus_id: Some("fixture-01".into()),
            native_coordinate_system: CoordinateSystem::Symthaea12,
            coordinate_system: CoordinateSystem::Symthaea12,
            coordinate_transforms: vec![],
            temporal_aggregation: TemporalAggregation::Native,
            source_digest: None,
        }
    }

    fn simulated() -> NeuralEvidenceProvenance {
        NeuralEvidenceProvenance {
            authority: EvidenceAuthority::SimulatedModel,
            source: "Symthaea".into(),
            model: Some("cognitive-loop-cortical-map".into()),
            model_version: Some("git:2a8b8fd".into()),
            modality: None,
            ..fixture()
        }
    }

    fn surrogate() -> NeuralEvidenceProvenance {
        NeuralEvidenceProvenance {
            authority: EvidenceAuthority::ExternalSurrogate,
            source: "TRIBE v2".into(),
            model: Some("facebook/tribev2".into()),
            model_version: Some("released-api-v2".into()),
            modality: Some(NeuralModality::Fmri),
            native_coordinate_system: CoordinateSystem::FsAverage5,
            coordinate_system: CoordinateSystem::FsAverage5,
            temporal_aggregation: TemporalAggregation::TemporalMean,
            source_digest: Some(SHA_B.into()),
            ..fixture()
        }
    }

    fn empirical() -> NeuralEvidenceProvenance {
        NeuralEvidenceProvenance {
            authority: EvidenceAuthority::EmpiricalObserved,
            source: "Natural Scenes Dataset".into(),
            model: None,
            model_version: None,
            modality: Some(NeuralModality::Fmri),
            dataset: Some("NSD".into()),
            subject_id: Some("subj01".into()),
            native_coordinate_system: CoordinateSystem::FsAverage5,
            coordinate_system: CoordinateSystem::FsAverage5,
            source_digest: Some(BLAKE_C.into()),
            ..fixture()
        }
    }

    fn two_hop_chain() -> Vec<CoordinateTransformProvenance> {
        vec![
            CoordinateTransformProvenance {
                from: CoordinateSystem::FsAverage5,
                to: CoordinateSystem::Glasser360,
                transform_id: "fsaverage5-to-glasser360".into(),
                transform_version: "1".into(),
                source_digest: SHA_A.into(),
            },
            CoordinateTransformProvenance {
                from: CoordinateSystem::Glasser360,
                to: CoordinateSystem::Symthaea12,
                transform_id: "glasser360-to-symthaea12".into(),
                transform_version: "1".into(),
                source_digest: SHA_B.into(),
            },
        ]
    }

    #[test]
    fn admission_capability_enforces_use_boundary() {
        let fixture_observation = NeuralObservation::new(vec![0.0_f32], fixture()).unwrap();
        let admitted = fixture_observation
            .authorize(EvidenceUse::SoftwareQualification)
            .unwrap();
        assert_eq!(admitted.use_case(), EvidenceUse::SoftwareQualification);

        let simulated_observation = NeuralObservation::new(vec![0.0_f32], simulated()).unwrap();
        assert!(
            simulated_observation
                .authorize(EvidenceUse::ModelBehavior)
                .is_ok()
        );

        let surrogate_observation = NeuralObservation::new(vec![0.0_f32], surrogate()).unwrap();
        assert!(
            surrogate_observation
                .authorize(EvidenceUse::SurrogateAlignment)
                .is_ok()
        );

        let empirical_observation = NeuralObservation::new(vec![0.0_f32], empirical()).unwrap();
        assert!(
            empirical_observation
                .authorize(EvidenceUse::EmpiricalNeuralAnalysis)
                .is_ok()
        );
    }

    #[test]
    fn admission_rejects_authority_laundering_and_consciousness_inference() {
        let surrogate_observation = NeuralObservation::new(vec![0.0_f32], surrogate()).unwrap();
        let err = surrogate_observation
            .authorize(EvidenceUse::EmpiricalNeuralAnalysis)
            .unwrap_err();
        assert_eq!(err.authority, EvidenceAuthority::ExternalSurrogate);

        for raw in [fixture(), simulated(), surrogate(), empirical()] {
            let observation = NeuralObservation::new(vec![0.0_f32], raw).unwrap();
            assert!(
                observation
                    .authorize(EvidenceUse::ConsciousnessInference)
                    .is_err()
            );
        }
    }

    #[test]
    fn authority_specific_metadata_fails_closed() {
        let mut p = fixture();
        p.model = None;
        assert_eq!(
            p.validate(),
            Err(ProvenanceError::MissingModel {
                authority: EvidenceAuthority::SyntheticFixture
            })
        );

        let mut p = simulated();
        p.model_version = None;
        assert_eq!(
            p.validate(),
            Err(ProvenanceError::MissingModelVersion {
                authority: EvidenceAuthority::SimulatedModel
            })
        );

        let mut p = surrogate();
        p.modality = None;
        assert_eq!(
            p.validate(),
            Err(ProvenanceError::MissingModality {
                authority: EvidenceAuthority::ExternalSurrogate
            })
        );

        let mut p = empirical();
        p.dataset = None;
        assert_eq!(p.validate(), Err(ProvenanceError::MissingDataset));
    }

    #[test]
    fn surrogate_and_empirical_require_source_digests() {
        let mut p = surrogate();
        p.source_digest = None;
        assert_eq!(
            p.validate(),
            Err(ProvenanceError::MissingSourceDigest {
                authority: EvidenceAuthority::ExternalSurrogate
            })
        );

        let mut p = empirical();
        p.source_digest = None;
        assert_eq!(
            p.validate(),
            Err(ProvenanceError::MissingSourceDigest {
                authority: EvidenceAuthority::EmpiricalObserved
            })
        );
    }

    #[test]
    fn schema_and_digest_validation_are_closed_world() {
        let mut p = empirical();
        p.schema_version += 1;
        assert_eq!(
            p.validate(),
            Err(ProvenanceError::UnsupportedSchemaVersion { found: 2 })
        );

        for bad in [
            "sha256:abc",
            "sha512:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
            "sha256:zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz",
        ] {
            let mut p = empirical();
            p.source_digest = Some(bad.into());
            assert_eq!(p.validate(), Err(ProvenanceError::MalformedDigest));
        }
    }

    #[test]
    fn temporal_aggregation_is_not_a_spatial_transform() {
        let p = surrogate().validate().unwrap();
        assert_eq!(p.native_coordinate_system(), CoordinateSystem::FsAverage5);
        assert_eq!(p.coordinate_system(), CoordinateSystem::FsAverage5);
        assert!(p.coordinate_transforms().is_empty());
        assert_eq!(p.as_raw().temporal_aggregation, TemporalAggregation::TemporalMean);
    }

    #[test]
    fn coordinate_relabel_without_lineage_fails() {
        let mut p = surrogate();
        p.coordinate_system = CoordinateSystem::Glasser360;
        assert_eq!(
            p.validate(),
            Err(ProvenanceError::TransformChainTargetMismatch {
                expected: CoordinateSystem::Glasser360,
                found: CoordinateSystem::FsAverage5
            })
        );
    }

    #[test]
    fn valid_multi_hop_coordinate_lineage_survives_roundtrip() {
        let mut p = surrogate();
        p.coordinate_system = CoordinateSystem::Symthaea12;
        p.coordinate_transforms = two_hop_chain();
        let observation = NeuralObservation::new(vec![0.1_f32, 0.2, 0.3], p).unwrap();
        let json = serde_json::to_string(&observation).unwrap();
        let restored: NeuralObservation<Vec<f32>> = serde_json::from_str(&json).unwrap();

        assert_eq!(restored.provenance().authority(), EvidenceAuthority::ExternalSurrogate);
        assert_eq!(restored.provenance().native_coordinate_system(), CoordinateSystem::FsAverage5);
        assert_eq!(restored.provenance().coordinate_system(), CoordinateSystem::Symthaea12);
        assert_eq!(restored.provenance().coordinate_transforms().len(), 2);
    }

    #[test]
    fn broken_coordinate_chain_fails() {
        let mut p = surrogate();
        p.coordinate_system = CoordinateSystem::Symthaea12;
        let mut chain = two_hop_chain();
        chain[1].from = CoordinateSystem::DesikanKilliany68;
        p.coordinate_transforms = chain;
        assert_eq!(
            p.validate(),
            Err(ProvenanceError::TransformChainSourceMismatch {
                index: 1,
                expected: CoordinateSystem::Glasser360,
                found: CoordinateSystem::DesikanKilliany68
            })
        );
    }

    #[test]
    fn transforms_validate_identity_version_digest_and_deserialization() {
        let valid = CoordinateTransformProvenance {
            from: CoordinateSystem::FsAverage5,
            to: CoordinateSystem::Glasser360,
            transform_id: "fsaverage5-to-glasser360".into(),
            transform_version: "1".into(),
            source_digest: SHA_A.into(),
        };
        let checked = valid.clone().validate().unwrap();
        assert_eq!(checked.from(), CoordinateSystem::FsAverage5);
        assert_eq!(checked.to(), CoordinateSystem::Glasser360);

        let bad = CoordinateTransformProvenance {
            to: CoordinateSystem::FsAverage5,
            ..valid
        };
        let json = serde_json::to_string(&bad).unwrap();
        assert!(serde_json::from_str::<ValidatedCoordinateTransform>(&json).is_err());
    }

    #[test]
    fn validated_provenance_revalidates_on_deserialization() {
        let mut raw = surrogate();
        raw.coordinate_system = CoordinateSystem::Glasser360;
        let json = serde_json::to_string(&raw).unwrap();
        assert!(serde_json::from_str::<ValidatedProvenance>(&json).is_err());
    }

    #[test]
    fn hcp_mmp1_is_only_a_wire_alias_for_glasser360() {
        let parsed: CoordinateSystem = serde_json::from_str("\"hcp_mmp1\"").unwrap();
        assert_eq!(parsed, CoordinateSystem::Glasser360);
        assert_eq!(serde_json::to_string(&parsed).unwrap(), "\"glasser360\"");
    }

    #[test]
    fn unknown_provenance_fields_are_rejected() {
        let json = serde_json::to_value(surrogate()).unwrap();
        let mut object = json.as_object().unwrap().clone();
        object.insert("unreviewed_field".into(), serde_json::json!(true));
        assert!(
            serde_json::from_value::<NeuralEvidenceProvenance>(serde_json::Value::Object(object))
                .is_err()
        );
    }

    #[test]
    fn modality_wire_name_is_stable() {
        assert_eq!(
            serde_json::to_string(&NeuralModality::TmsEeg).unwrap(),
            "\"tms_eeg\""
        );
    }
}
