//! Prometheus Metrics for Proof Operations
//!
//! Comprehensive metrics collection for monitoring zkSTARK proof generation
//! and verification performance.
//!
//! ## Metrics Overview
//!
//! | Metric | Type | Description |
//! |--------|------|-------------|
//! | `proof_generation_total` | Counter | Total proofs generated |
//! | `proof_generation_duration_seconds` | Histogram | Proof generation time |
//! | `proof_verification_total` | Counter | Total proofs verified |
//! | `proof_verification_duration_seconds` | Histogram | Verification time |
//! | `proof_size_bytes` | Histogram | Proof sizes in bytes |
//! | `batch_verification_total` | Counter | Total batch verifications |
//! | `batch_verification_size` | Histogram | Batch sizes |
//! | `gpu_operations_total` | Counter | GPU operations performed |
//! | `cache_hits_total` | Counter | Cache hits |
//! | `cache_misses_total` | Counter | Cache misses |
//!
//! ## Usage
//!
//! ```rust,ignore
//! use fl_aggregator::proofs::metrics::{ProofMetrics, METRICS};
//!
//! // Record a proof generation
//! METRICS.record_generation(ProofType::Range, 0.05, 15000);
//!
//! // Record a verification
//! METRICS.record_verification(ProofType::Range, true, 0.01);
//!
//! // Get metrics for Prometheus scraping
//! let output = METRICS.gather();
//! ```
//!
//! ## Integration with HTTP Server
//!
//! ```rust,ignore
//! use axum::{Router, routing::get};
//! use fl_aggregator::proofs::metrics::METRICS;
//!
//! async fn metrics_handler() -> String {
//!     METRICS.gather()
//! }
//!
//! let app = Router::new().route("/metrics", get(metrics_handler));
//! ```

use std::time::Instant;

use prometheus::{
    Encoder, GaugeVec, Histogram, HistogramOpts, HistogramVec,
    IntCounter, IntCounterVec, IntGauge, IntGaugeVec, Opts, Registry, TextEncoder,
};

use crate::proofs::ProofType;

/// Global metrics instance
pub static METRICS: once_cell::sync::Lazy<ProofMetrics> =
    once_cell::sync::Lazy::new(ProofMetrics::new);

/// Comprehensive metrics for proof operations
pub struct ProofMetrics {
    registry: Registry,

    // Generation metrics
    generation_total: IntCounterVec,
    generation_duration: HistogramVec,
    generation_errors: IntCounterVec,
    generation_in_progress: IntGaugeVec,

    // Verification metrics
    verification_total: IntCounterVec,
    verification_duration: HistogramVec,
    verification_success: IntCounterVec,
    verification_failures: IntCounterVec,

    // Size metrics
    proof_size_bytes: HistogramVec,
    compressed_size_bytes: HistogramVec,
    compression_ratio: GaugeVec,

    // Batch metrics
    batch_total: IntCounter,
    batch_size: Histogram,
    batch_duration: Histogram,
    batch_valid_count: Histogram,

    // GPU metrics
    gpu_operations: IntCounterVec,
    gpu_duration: HistogramVec,
    gpu_memory_bytes: IntGauge,
    gpu_available: IntGauge,

    // Cache metrics
    cache_hits: IntCounterVec,
    cache_misses: IntCounterVec,
    cache_size: IntGauge,
    cache_evictions: IntCounter,

    // Recursive/Aggregate metrics
    recursive_proofs_created: IntCounter,
    recursive_batch_size: Histogram,
    aggregate_proofs_created: IntCounter,

    // Anchoring metrics
    anchoring_total: IntCounterVec,
    anchoring_duration: HistogramVec,
    anchoring_pending: IntGauge,

    // System metrics
    active_verifiers: IntGauge,
    queue_depth: IntGauge,
    last_generation_timestamp: IntGauge,
    last_verification_timestamp: IntGauge,
}

impl ProofMetrics {
    /// Create a new metrics instance
    pub fn new() -> Self {
        let registry = Registry::new();

        // Generation metrics
        let generation_total = IntCounterVec::new(
            Opts::new("proof_generation_total", "Total proofs generated by type"),
            &["proof_type"],
        )
        .unwrap();
        registry.register(Box::new(generation_total.clone())).unwrap();

        let generation_duration = HistogramVec::new(
            HistogramOpts::new(
                "proof_generation_duration_seconds",
                "Proof generation duration in seconds",
            )
            .buckets(vec![0.01, 0.05, 0.1, 0.25, 0.5, 1.0, 2.5, 5.0, 10.0]),
            &["proof_type"],
        )
        .unwrap();
        registry.register(Box::new(generation_duration.clone())).unwrap();

        let generation_errors = IntCounterVec::new(
            Opts::new("proof_generation_errors_total", "Proof generation errors"),
            &["proof_type", "error_type"],
        )
        .unwrap();
        registry.register(Box::new(generation_errors.clone())).unwrap();

        let generation_in_progress = IntGaugeVec::new(
            Opts::new("proof_generation_in_progress", "Proofs currently being generated"),
            &["proof_type"],
        )
        .unwrap();
        registry.register(Box::new(generation_in_progress.clone())).unwrap();

        // Verification metrics
        let verification_total = IntCounterVec::new(
            Opts::new("proof_verification_total", "Total proofs verified by type"),
            &["proof_type"],
        )
        .unwrap();
        registry.register(Box::new(verification_total.clone())).unwrap();

        let verification_duration = HistogramVec::new(
            HistogramOpts::new(
                "proof_verification_duration_seconds",
                "Proof verification duration in seconds",
            )
            .buckets(vec![0.001, 0.005, 0.01, 0.025, 0.05, 0.1, 0.25, 0.5]),
            &["proof_type"],
        )
        .unwrap();
        registry.register(Box::new(verification_duration.clone())).unwrap();

        let verification_success = IntCounterVec::new(
            Opts::new("proof_verification_success_total", "Successful verifications"),
            &["proof_type"],
        )
        .unwrap();
        registry.register(Box::new(verification_success.clone())).unwrap();

        let verification_failures = IntCounterVec::new(
            Opts::new("proof_verification_failures_total", "Failed verifications"),
            &["proof_type", "reason"],
        )
        .unwrap();
        registry.register(Box::new(verification_failures.clone())).unwrap();

        // Size metrics
        let proof_size_bytes = HistogramVec::new(
            HistogramOpts::new("proof_size_bytes", "Proof sizes in bytes")
                .buckets(vec![1000.0, 5000.0, 10000.0, 25000.0, 50000.0, 100000.0, 250000.0]),
            &["proof_type"],
        )
        .unwrap();
        registry.register(Box::new(proof_size_bytes.clone())).unwrap();

        let compressed_size_bytes = HistogramVec::new(
            HistogramOpts::new("proof_compressed_size_bytes", "Compressed proof sizes")
                .buckets(vec![500.0, 2500.0, 5000.0, 12500.0, 25000.0, 50000.0, 125000.0]),
            &["proof_type"],
        )
        .unwrap();
        registry.register(Box::new(compressed_size_bytes.clone())).unwrap();

        let compression_ratio = GaugeVec::new(
            Opts::new("proof_compression_ratio", "Compression ratio (original/compressed)"),
            &["proof_type"],
        )
        .unwrap();
        registry.register(Box::new(compression_ratio.clone())).unwrap();

        // Batch metrics
        let batch_total = IntCounter::new("batch_verification_total", "Total batch verifications")
            .unwrap();
        registry.register(Box::new(batch_total.clone())).unwrap();

        let batch_size = Histogram::with_opts(
            HistogramOpts::new("batch_verification_size", "Batch sizes")
                .buckets(vec![1.0, 5.0, 10.0, 25.0, 50.0, 100.0, 250.0, 500.0]),
        )
        .unwrap();
        registry.register(Box::new(batch_size.clone())).unwrap();

        let batch_duration = Histogram::with_opts(
            HistogramOpts::new("batch_verification_duration_seconds", "Batch verification time")
                .buckets(vec![0.1, 0.25, 0.5, 1.0, 2.5, 5.0, 10.0]),
        )
        .unwrap();
        registry.register(Box::new(batch_duration.clone())).unwrap();

        let batch_valid_count = Histogram::with_opts(
            HistogramOpts::new("batch_valid_count", "Number of valid proofs per batch")
                .buckets(vec![0.0, 1.0, 5.0, 10.0, 25.0, 50.0, 100.0]),
        )
        .unwrap();
        registry.register(Box::new(batch_valid_count.clone())).unwrap();

        // GPU metrics
        let gpu_operations = IntCounterVec::new(
            Opts::new("gpu_operations_total", "GPU operations by type"),
            &["operation"],
        )
        .unwrap();
        registry.register(Box::new(gpu_operations.clone())).unwrap();

        let gpu_duration = HistogramVec::new(
            HistogramOpts::new("gpu_operation_duration_seconds", "GPU operation duration")
                .buckets(vec![0.001, 0.005, 0.01, 0.025, 0.05, 0.1, 0.25]),
            &["operation"],
        )
        .unwrap();
        registry.register(Box::new(gpu_duration.clone())).unwrap();

        let gpu_memory_bytes = IntGauge::new("gpu_memory_used_bytes", "GPU memory usage").unwrap();
        registry.register(Box::new(gpu_memory_bytes.clone())).unwrap();

        let gpu_available = IntGauge::new("gpu_available", "Whether GPU is available (1/0)").unwrap();
        registry.register(Box::new(gpu_available.clone())).unwrap();

        // Cache metrics
        let cache_hits = IntCounterVec::new(
            Opts::new("proof_cache_hits_total", "Cache hits by type"),
            &["proof_type"],
        )
        .unwrap();
        registry.register(Box::new(cache_hits.clone())).unwrap();

        let cache_misses = IntCounterVec::new(
            Opts::new("proof_cache_misses_total", "Cache misses by type"),
            &["proof_type"],
        )
        .unwrap();
        registry.register(Box::new(cache_misses.clone())).unwrap();

        let cache_size = IntGauge::new("proof_cache_size", "Current cache size").unwrap();
        registry.register(Box::new(cache_size.clone())).unwrap();

        let cache_evictions =
            IntCounter::new("proof_cache_evictions_total", "Cache evictions").unwrap();
        registry.register(Box::new(cache_evictions.clone())).unwrap();

        // Recursive/Aggregate metrics
        let recursive_proofs_created =
            IntCounter::new("recursive_proofs_created_total", "Recursive proofs created").unwrap();
        registry.register(Box::new(recursive_proofs_created.clone())).unwrap();

        let recursive_batch_size = Histogram::with_opts(
            HistogramOpts::new("recursive_batch_size", "Proofs per recursive batch")
                .buckets(vec![2.0, 5.0, 10.0, 25.0, 50.0, 100.0]),
        )
        .unwrap();
        registry.register(Box::new(recursive_batch_size.clone())).unwrap();

        let aggregate_proofs_created =
            IntCounter::new("aggregate_proofs_created_total", "Aggregate proofs created").unwrap();
        registry.register(Box::new(aggregate_proofs_created.clone())).unwrap();

        // Anchoring metrics
        let anchoring_total = IntCounterVec::new(
            Opts::new("proof_anchoring_total", "Proof anchoring operations"),
            &["chain"],
        )
        .unwrap();
        registry.register(Box::new(anchoring_total.clone())).unwrap();

        let anchoring_duration = HistogramVec::new(
            HistogramOpts::new("proof_anchoring_duration_seconds", "Anchoring duration")
                .buckets(vec![1.0, 5.0, 10.0, 30.0, 60.0, 120.0, 300.0]),
            &["chain"],
        )
        .unwrap();
        registry.register(Box::new(anchoring_duration.clone())).unwrap();

        let anchoring_pending = IntGauge::new("proof_anchoring_pending", "Pending anchors").unwrap();
        registry.register(Box::new(anchoring_pending.clone())).unwrap();

        // System metrics
        let active_verifiers =
            IntGauge::new("proof_active_verifiers", "Active verifier instances").unwrap();
        registry.register(Box::new(active_verifiers.clone())).unwrap();

        let queue_depth = IntGauge::new("proof_queue_depth", "Verification queue depth").unwrap();
        registry.register(Box::new(queue_depth.clone())).unwrap();

        let last_generation_timestamp = IntGauge::new(
            "proof_last_generation_timestamp",
            "Timestamp of last proof generation",
        )
        .unwrap();
        registry.register(Box::new(last_generation_timestamp.clone())).unwrap();

        let last_verification_timestamp = IntGauge::new(
            "proof_last_verification_timestamp",
            "Timestamp of last verification",
        )
        .unwrap();
        registry.register(Box::new(last_verification_timestamp.clone())).unwrap();

        Self {
            registry,
            generation_total,
            generation_duration,
            generation_errors,
            generation_in_progress,
            verification_total,
            verification_duration,
            verification_success,
            verification_failures,
            proof_size_bytes,
            compressed_size_bytes,
            compression_ratio,
            batch_total,
            batch_size,
            batch_duration,
            batch_valid_count,
            gpu_operations,
            gpu_duration,
            gpu_memory_bytes,
            gpu_available,
            cache_hits,
            cache_misses,
            cache_size,
            cache_evictions,
            recursive_proofs_created,
            recursive_batch_size,
            aggregate_proofs_created,
            anchoring_total,
            anchoring_duration,
            anchoring_pending,
            active_verifiers,
            queue_depth,
            last_generation_timestamp,
            last_verification_timestamp,
        }
    }

    // ========================================================================
    // Generation Metrics
    // ========================================================================

    /// Record a proof generation
    pub fn record_generation(&self, proof_type: ProofType, duration_secs: f64, size_bytes: usize) {
        let type_str = proof_type_str(proof_type);
        self.generation_total.with_label_values(&[type_str]).inc();
        self.generation_duration
            .with_label_values(&[type_str])
            .observe(duration_secs);
        self.proof_size_bytes
            .with_label_values(&[type_str])
            .observe(size_bytes as f64);
        self.last_generation_timestamp
            .set(chrono::Utc::now().timestamp());
    }

    /// Record a proof generation error
    pub fn record_generation_error(&self, proof_type: ProofType, error_type: &str) {
        self.generation_errors
            .with_label_values(&[proof_type_str(proof_type), error_type])
            .inc();
    }

    /// Mark generation in progress
    pub fn generation_started(&self, proof_type: ProofType) {
        self.generation_in_progress
            .with_label_values(&[proof_type_str(proof_type)])
            .inc();
    }

    /// Mark generation complete
    pub fn generation_completed(&self, proof_type: ProofType) {
        self.generation_in_progress
            .with_label_values(&[proof_type_str(proof_type)])
            .dec();
    }

    /// Create a timer for proof generation
    pub fn generation_timer(&self, proof_type: ProofType) -> GenerationTimer<'_> {
        self.generation_started(proof_type);
        GenerationTimer {
            start: Instant::now(),
            proof_type,
            metrics: self,
        }
    }

    // ========================================================================
    // Verification Metrics
    // ========================================================================

    /// Record a proof verification
    pub fn record_verification(&self, proof_type: ProofType, success: bool, duration_secs: f64) {
        let type_str = proof_type_str(proof_type);
        self.verification_total.with_label_values(&[type_str]).inc();
        self.verification_duration
            .with_label_values(&[type_str])
            .observe(duration_secs);

        if success {
            self.verification_success.with_label_values(&[type_str]).inc();
        }
        self.last_verification_timestamp
            .set(chrono::Utc::now().timestamp());
    }

    /// Record a verification failure with reason
    pub fn record_verification_failure(&self, proof_type: ProofType, reason: &str) {
        self.verification_failures
            .with_label_values(&[proof_type_str(proof_type), reason])
            .inc();
    }

    /// Create a timer for verification
    pub fn verification_timer(&self, proof_type: ProofType) -> VerificationTimer<'_> {
        VerificationTimer {
            start: Instant::now(),
            proof_type,
            metrics: self,
        }
    }

    // ========================================================================
    // Size Metrics
    // ========================================================================

    /// Record compressed proof size
    pub fn record_compression(
        &self,
        proof_type: ProofType,
        original_size: usize,
        compressed_size: usize,
    ) {
        let type_str = proof_type_str(proof_type);
        self.compressed_size_bytes
            .with_label_values(&[type_str])
            .observe(compressed_size as f64);

        if compressed_size > 0 {
            let ratio = original_size as f64 / compressed_size as f64;
            self.compression_ratio
                .with_label_values(&[type_str])
                .set(ratio);
        }
    }

    // ========================================================================
    // Batch Metrics
    // ========================================================================

    /// Record a batch verification
    pub fn record_batch(&self, batch_size: usize, valid_count: usize, duration_secs: f64) {
        self.batch_total.inc();
        self.batch_size.observe(batch_size as f64);
        self.batch_duration.observe(duration_secs);
        self.batch_valid_count.observe(valid_count as f64);
    }

    // ========================================================================
    // GPU Metrics
    // ========================================================================

    /// Record a GPU operation
    pub fn record_gpu_operation(&self, operation: &str, duration_secs: f64) {
        self.gpu_operations.with_label_values(&[operation]).inc();
        self.gpu_duration
            .with_label_values(&[operation])
            .observe(duration_secs);
    }

    /// Update GPU memory usage
    pub fn set_gpu_memory(&self, bytes: i64) {
        self.gpu_memory_bytes.set(bytes);
    }

    /// Set GPU availability
    pub fn set_gpu_available(&self, available: bool) {
        self.gpu_available.set(if available { 1 } else { 0 });
    }

    // ========================================================================
    // Cache Metrics
    // ========================================================================

    /// Record a cache hit
    pub fn record_cache_hit(&self, proof_type: ProofType) {
        self.cache_hits
            .with_label_values(&[proof_type_str(proof_type)])
            .inc();
    }

    /// Record a cache miss
    pub fn record_cache_miss(&self, proof_type: ProofType) {
        self.cache_misses
            .with_label_values(&[proof_type_str(proof_type)])
            .inc();
    }

    /// Update cache size
    pub fn set_cache_size(&self, size: i64) {
        self.cache_size.set(size);
    }

    /// Record cache eviction
    pub fn record_cache_eviction(&self) {
        self.cache_evictions.inc();
    }

    // ========================================================================
    // Recursive/Aggregate Metrics
    // ========================================================================

    /// Record recursive proof creation
    pub fn record_recursive_proof(&self, batch_size: usize) {
        self.recursive_proofs_created.inc();
        self.recursive_batch_size.observe(batch_size as f64);
    }

    /// Record aggregate proof creation
    pub fn record_aggregate_proof(&self) {
        self.aggregate_proofs_created.inc();
    }

    // ========================================================================
    // Anchoring Metrics
    // ========================================================================

    /// Record an anchoring operation
    pub fn record_anchoring(&self, chain: &str, duration_secs: f64) {
        self.anchoring_total.with_label_values(&[chain]).inc();
        self.anchoring_duration
            .with_label_values(&[chain])
            .observe(duration_secs);
    }

    /// Update pending anchors count
    pub fn set_pending_anchors(&self, count: i64) {
        self.anchoring_pending.set(count);
    }

    // ========================================================================
    // System Metrics
    // ========================================================================

    /// Update active verifiers count
    pub fn set_active_verifiers(&self, count: i64) {
        self.active_verifiers.set(count);
    }

    /// Update queue depth
    pub fn set_queue_depth(&self, depth: i64) {
        self.queue_depth.set(depth);
    }

    // ========================================================================
    // Output
    // ========================================================================

    /// Gather all metrics in Prometheus text format
    pub fn gather(&self) -> String {
        let encoder = TextEncoder::new();
        let metric_families = self.registry.gather();
        let mut buffer = Vec::new();
        encoder.encode(&metric_families, &mut buffer).unwrap();
        String::from_utf8(buffer).unwrap()
    }

    /// Get the registry for custom integrations
    pub fn registry(&self) -> &Registry {
        &self.registry
    }

    /// Get a snapshot of key metrics
    pub fn snapshot(&self) -> MetricsSnapshot {
        MetricsSnapshot {
            total_generations: self.generation_total.with_label_values(&["Range"]).get()
                + self.generation_total.with_label_values(&["GradientIntegrity"]).get()
                + self.generation_total.with_label_values(&["IdentityAssurance"]).get()
                + self.generation_total.with_label_values(&["VoteEligibility"]).get()
                + self.generation_total.with_label_values(&["Membership"]).get(),
            total_verifications: self.verification_total.with_label_values(&["Range"]).get()
                + self.verification_total.with_label_values(&["GradientIntegrity"]).get()
                + self.verification_total.with_label_values(&["IdentityAssurance"]).get()
                + self.verification_total.with_label_values(&["VoteEligibility"]).get()
                + self.verification_total.with_label_values(&["Membership"]).get(),
            cache_size: self.cache_size.get(),
            gpu_available: self.gpu_available.get() == 1,
            active_verifiers: self.active_verifiers.get(),
        }
    }
}

impl Default for ProofMetrics {
    fn default() -> Self {
        Self::new()
    }
}

/// Metrics snapshot for quick overview
#[derive(Debug, Clone)]
pub struct MetricsSnapshot {
    pub total_generations: u64,
    pub total_verifications: u64,
    pub cache_size: i64,
    pub gpu_available: bool,
    pub active_verifiers: i64,
}

/// Timer for proof generation that auto-records on drop
pub struct GenerationTimer<'a> {
    start: Instant,
    proof_type: ProofType,
    metrics: &'a ProofMetrics,
}

impl<'a> GenerationTimer<'a> {
    /// Complete the timer and record metrics
    pub fn complete(self, size_bytes: usize) {
        let duration = self.start.elapsed().as_secs_f64();
        self.metrics
            .record_generation(self.proof_type, duration, size_bytes);
        // Don't run drop since we recorded manually
        std::mem::forget(self);
    }

    /// Cancel the timer (on error)
    pub fn cancel(self, error_type: &str) {
        self.metrics.generation_completed(self.proof_type);
        self.metrics
            .record_generation_error(self.proof_type, error_type);
        std::mem::forget(self);
    }
}

impl<'a> Drop for GenerationTimer<'a> {
    fn drop(&mut self) {
        self.metrics.generation_completed(self.proof_type);
    }
}

/// Timer for proof verification
pub struct VerificationTimer<'a> {
    start: Instant,
    proof_type: ProofType,
    metrics: &'a ProofMetrics,
}

impl<'a> VerificationTimer<'a> {
    /// Complete with success status
    pub fn complete(self, success: bool) {
        let duration = self.start.elapsed().as_secs_f64();
        self.metrics
            .record_verification(self.proof_type, success, duration);
    }

    /// Complete with failure reason
    pub fn fail(self, reason: &str) {
        let duration = self.start.elapsed().as_secs_f64();
        self.metrics
            .record_verification(self.proof_type, false, duration);
        self.metrics
            .record_verification_failure(self.proof_type, reason);
    }
}

/// Convert ProofType to string label
fn proof_type_str(proof_type: ProofType) -> &'static str {
    match proof_type {
        ProofType::Range => "Range",
        ProofType::GradientIntegrity => "GradientIntegrity",
        ProofType::IdentityAssurance => "IdentityAssurance",
        ProofType::VoteEligibility => "VoteEligibility",
        ProofType::Membership => "Membership",
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_metrics_creation() {
        let metrics = ProofMetrics::new();
        // Record at least one metric so prometheus outputs the metric families
        metrics.record_generation(ProofType::Range, 0.01, 1000);
        metrics.record_verification(ProofType::Range, true, 0.001);

        let output = metrics.gather();
        // Prometheus outputs TYPE declarations and metric values
        assert!(output.contains("proof_generation_total"));
        assert!(output.contains("proof_verification_total"));
    }

    #[test]
    fn test_record_generation() {
        let metrics = ProofMetrics::new();
        metrics.record_generation(ProofType::Range, 0.05, 15000);

        let snapshot = metrics.snapshot();
        assert_eq!(snapshot.total_generations, 1);
    }

    #[test]
    fn test_record_verification() {
        let metrics = ProofMetrics::new();
        metrics.record_verification(ProofType::Range, true, 0.01);
        metrics.record_verification(ProofType::Range, false, 0.02);

        let snapshot = metrics.snapshot();
        assert_eq!(snapshot.total_verifications, 2);
    }

    #[test]
    fn test_record_batch() {
        let metrics = ProofMetrics::new();
        metrics.record_batch(10, 8, 0.5);

        let output = metrics.gather();
        assert!(output.contains("batch_verification_total 1"));
    }

    #[test]
    fn test_cache_metrics() {
        let metrics = ProofMetrics::new();
        metrics.record_cache_hit(ProofType::Range);
        metrics.record_cache_miss(ProofType::Range);
        metrics.set_cache_size(100);

        let snapshot = metrics.snapshot();
        assert_eq!(snapshot.cache_size, 100);
    }

    #[test]
    fn test_gpu_metrics() {
        let metrics = ProofMetrics::new();
        metrics.set_gpu_available(true);
        metrics.record_gpu_operation("ntt", 0.001);
        metrics.set_gpu_memory(1024 * 1024);

        let snapshot = metrics.snapshot();
        assert!(snapshot.gpu_available);
    }

    #[test]
    fn test_generation_timer() {
        let metrics = ProofMetrics::new();
        {
            let timer = metrics.generation_timer(ProofType::Range);
            std::thread::sleep(std::time::Duration::from_millis(10));
            timer.complete(15000);
        }

        let snapshot = metrics.snapshot();
        assert_eq!(snapshot.total_generations, 1);
    }

    #[test]
    fn test_verification_timer() {
        let metrics = ProofMetrics::new();
        {
            let timer = metrics.verification_timer(ProofType::GradientIntegrity);
            std::thread::sleep(std::time::Duration::from_millis(5));
            timer.complete(true);
        }

        let snapshot = metrics.snapshot();
        assert_eq!(snapshot.total_verifications, 1);
    }

    #[test]
    fn test_recursive_metrics() {
        let metrics = ProofMetrics::new();
        metrics.record_recursive_proof(25);
        metrics.record_aggregate_proof();

        let output = metrics.gather();
        assert!(output.contains("recursive_proofs_created_total 1"));
        assert!(output.contains("aggregate_proofs_created_total 1"));
    }

    #[test]
    fn test_anchoring_metrics() {
        let metrics = ProofMetrics::new();
        metrics.record_anchoring("bitcoin", 30.0);
        metrics.record_anchoring("ethereum", 15.0);
        metrics.set_pending_anchors(5);

        let output = metrics.gather();
        assert!(output.contains("proof_anchoring_total"));
    }

    #[test]
    fn test_compression_metrics() {
        let metrics = ProofMetrics::new();
        metrics.record_compression(ProofType::Range, 15000, 8000);

        let output = metrics.gather();
        assert!(output.contains("proof_compressed_size_bytes"));
        assert!(output.contains("proof_compression_ratio"));
    }

    #[test]
    fn test_metrics_snapshot() {
        let metrics = ProofMetrics::new();
        metrics.record_generation(ProofType::Range, 0.05, 15000);
        metrics.record_verification(ProofType::GradientIntegrity, true, 0.01);
        metrics.set_gpu_available(true);
        metrics.set_cache_size(50);
        metrics.set_active_verifiers(3);

        let snapshot = metrics.snapshot();
        assert_eq!(snapshot.total_generations, 1);
        assert_eq!(snapshot.total_verifications, 1);
        assert!(snapshot.gpu_available);
        assert_eq!(snapshot.cache_size, 50);
        assert_eq!(snapshot.active_verifiers, 3);
    }

    #[test]
    fn test_error_metrics() {
        let metrics = ProofMetrics::new();
        metrics.record_generation_error(ProofType::Range, "constraint_violation");
        metrics.record_verification_failure(ProofType::Range, "invalid_commitment");

        let output = metrics.gather();
        assert!(output.contains("proof_generation_errors_total"));
        assert!(output.contains("proof_verification_failures_total"));
    }
}
