#!/usr/bin/env python3
from __future__ import annotations
import argparse, hashlib, json, pathlib, re, tempfile
from typing import Any
FILES={"predicate":"predicate-contract-receipt.json","execution":"execution-v3-receipt.json","seal":"observation-seal-v3.json","comparison":"comparison-only-qualification-receipt.json","manifest":"qualification-input-manifest.json","assembly":"qualification-assembly-receipt.json","qualification":"qualification-only.json"}
SHA256_RE=re.compile(r'^[0-9a-f]{64}$'); ARTIFACT_DIGEST_RE=re.compile(r'^sha256:[0-9a-f]{64}$')
FORBIDDEN_KEYS={"predicates","threshold_table","observed","expected"}; ALLOWED_FAILED_IDS=[f"REL005A-P{i:03d}" for i in range(1,42)]
EXPECTED={"predicate_head":"43bf1d588447f602ce0f1549986bb558a839762c","execution_head":"6931639e53060809f9d459196a329c4fe983be7b","frozen_subject":"7f5826675b44dd0d3f702f62bc9818f7990e4a01","frozen_test_blob":"787ea051ae0bf8e5667b6925481afd46c15d0bc4","observation_sha256":"e271a5c2e6b51fda15cd6c3209e52859296f44ecd790b9c5e72f769d4aec1c4d","seal_chain_sha256":"a3a288caa9221ec5859b5ac81fcc55f61b4ff43d5e52ad096021c99ea6bf31ab","assembly_head":"3dc01663ff8b2f9f6eb0568f8649ccdd999ddf29","comparison_head":"a47efccf80fa66bacbdfa9930f59c8439be7ee38","comparison_run_id":35349750595,"projection_head":"07af7c4bdfdda377aa8175efe7a3233ce90e889e","projection_run_id":35324485955}
def require(c,m):
    if not c: raise ValueError(m)
def no_dupes(pairs):
    out={}
    for k,v in pairs: require(k not in out,f'duplicate JSON key: {k}'); out[k]=v
    return out
def load(p):
    v=json.loads(p.read_text(),object_pairs_hook=no_dupes); require(isinstance(v,dict),f'{p.name}: expected JSON object'); return v
def sha256(p): return hashlib.sha256(p.read_bytes()).hexdigest()
def walk_keys(v):
    r=set()
    if isinstance(v,dict):
        for k,c in v.items(): r.add(k); r |= walk_keys(c)
    elif isinstance(v,list):
        for c in v: r |= walk_keys(c)
    return r
def claims_exact(v,e,label): require(v.get('claims')==e,f'{label} claims mismatch')
def inspect(root):
    require(root.is_dir(),'evidence root missing')
    rel={p.relative_to(root).as_posix() for p in root.rglob('*') if p.is_file()}; require(rel==set(FILES.values()),f'seven-file census mismatch: {sorted(rel)}')
    v={k:load(root/n) for k,n in FILES.items()}; p,e,s,c,m,a,q=[v[k] for k in ('predicate','execution','seal','comparison','manifest','assembly','qualification')]
    for label,val in v.items():
        leaked=FORBIDDEN_KEYS & walk_keys(val); require(not leaked,f'{label}: forbidden detailed keys leaked: {sorted(leaked)}')
    fc={'observation_sealed':False,'comparison_only_adjudicated':False,'rel_005a_qualified':False,'scientific_pass':False,'scientific_fail':False}
    require(p.get('schema')=='symthaea.rel.predicate-contract-static-receipt.v1' and p.get('authority')=='PredicateContractOnly','predicate identity'); require(p.get('subject_head')==EXPECTED['predicate_head'],'predicate head'); require(p.get('predicate_count')==41 and p.get('source_grounded') is True and p.get('predicate_contract_static_valid') is True,'predicate validity'); require(p.get('frozen_scientific_subject')==EXPECTED['frozen_subject'] and p.get('frozen_test_blob')==EXPECTED['frozen_test_blob'],'predicate frozen identity'); claims_exact(p,fc,'predicate')
    require(e.get('schema')=='symthaea.rel.execution-only-receipt.v3' and e.get('authority')=='ExecutionOnly','execution identity'); require(e.get('subject_head')==EXPECTED['execution_head'] and e.get('predicate_contract_parent')==EXPECTED['predicate_head'],'execution subject'); require(e.get('frozen_scientific_subject')==EXPECTED['frozen_subject'] and e.get('frozen_test_blob')==EXPECTED['frozen_test_blob'],'execution frozen identity'); require(e.get('result')=='EXECUTION_OK' and str(e.get('measurement_exit_code'))=='0' and e.get('observation_present') is True,'execution admissibility'); require(e.get('observation_sha256')==EXPECTED['observation_sha256'],'execution observation'); claims_exact(e,fc,'execution')
    sc=dict(fc); sc['observation_sealed']=True
    require(s.get('schema')=='symthaea.rel.observation-seal.v3' and s.get('authority')=='ObservationSeal','seal identity'); require(s.get('observation_status')=='sealed' and s.get('adjudication')=='not_run' and s.get('scientific_result')=='not_run','seal boundary'); require(s.get('execution_subject_head')==EXPECTED['execution_head'] and s.get('predicate_contract_head')==EXPECTED['predicate_head'],'seal subject'); require(s.get('frozen_scientific_subject')==EXPECTED['frozen_subject'] and s.get('frozen_test_blob')==EXPECTED['frozen_test_blob'],'seal frozen identity'); require(s.get('observation_sha256')==EXPECTED['observation_sha256'] and s.get('chain_commitment_sha256')==EXPECTED['seal_chain_sha256'],'seal commitments'); claims_exact(s,sc,'seal')
    cc={'comparison_only_adjudicated':True,'rel_005a_qualified':False,'scientific_pass':False,'scientific_fail':False}
    require(c.get('schema')=='symthaea.rel.comparison-only-qualification-receipt.v1' and c.get('authority')=='ComparisonOnly','comparison identity'); require(c.get('predicate_contract_head')==EXPECTED['predicate_head'] and c.get('execution_subject_head')==EXPECTED['execution_head'],'comparison subjects'); require(c.get('frozen_scientific_subject')==EXPECTED['frozen_subject'] and c.get('frozen_test_blob')==EXPECTED['frozen_test_blob'],'comparison frozen identity'); require(c.get('observation_sha256')==EXPECTED['observation_sha256'] and c.get('seal_chain_commitment_sha256')==EXPECTED['seal_chain_sha256'],'comparison commitments'); require(c.get('predicate_count')==41,'comparison count')
    passed,failed,ids=c.get('passed_count'),c.get('failed_count'),c.get('failed_predicate_ids'); require(type(passed) is int and type(failed) is int and isinstance(ids,list),'comparison count types'); require(passed+failed==41 and failed==len(ids),'comparison counts'); require(len(ids)==len(set(ids)) and all(x in ALLOWED_FAILED_IDS for x in ids),'comparison failed IDs'); require(ids==sorted(ids,key=ALLOWED_FAILED_IDS.index),'comparison failed IDs order'); result=c.get('comparison_result'); require(result in {'ALL_PREDICATES_PASS','PREDICATE_FAILURES'},'comparison result'); require((result!='ALL_PREDICATES_PASS') or (passed==41 and failed==0 and ids==[]),'all-pass counts'); require((result!='PREDICATE_FAILURES') or failed>0,'predicate-failure counts'); require(isinstance(c.get('full_comparison_sha256'),str) and SHA256_RE.fullmatch(c['full_comparison_sha256']),'full comparison hash'); claims_exact(c,cc,'comparison')
    require(m.get('schema')=='symthaea.rel.qualification-input-manifest.v2' and m.get('authority')=='EvidenceProjectionOnly','manifest identity'); require(m.get('predicate_contract_head')==EXPECTED['predicate_head'] and m.get('execution_subject_head')==EXPECTED['execution_head'],'manifest subjects'); require(m.get('observation_sha256')==EXPECTED['observation_sha256'] and m.get('seal_chain_commitment_sha256')==EXPECTED['seal_chain_sha256'],'manifest commitments'); require(m.get('comparison_result')==result,'manifest result'); require(m.get('raw_observation_included') is False and m.get('raw_execution_logs_included') is False and m.get('detailed_predicate_values_included') is False,'manifest leakage flags')
    names=[FILES[x] for x in ('predicate','execution','seal','comparison')]; entries=m.get('files'); require(isinstance(entries,list) and [x.get('basename') for x in entries]==names,'manifest census/order')
    for entry in entries:
        path=root/entry['basename']; require(entry.get('byte_length')==path.stat().st_size,f'{path.name}: byte length'); require(entry.get('sha256')==sha256(path),f'{path.name}: hash')
    ac={'receipt_extraction_performed':True,'projection_performed':True,'projection_raw_observation_visibility':False,'projection_execution_log_visibility':False,'source_extraction_raw_observation_output':False,'source_extraction_execution_log_output':False,'qualification_completed':False,'rel_005a_qualified':False,'scientific_pass':False,'scientific_fail':False}
    require(a.get('schema')=='symthaea.rel.qualification-assembly-receipt.v3' and a.get('authority')=='QualificationAssemblyOnly','assembly identity'); require(a.get('assembly_contract_head')==EXPECTED['assembly_head'],'assembly head'); require(a.get('comparison_subject_head')==EXPECTED['comparison_head'] and a.get('comparison_source_run_id')==EXPECTED['comparison_run_id'],'assembly comparison provenance'); require(a.get('projection_contract_head')==EXPECTED['projection_head'] and a.get('projection_contract_run_id')==EXPECTED['projection_run_id'],'assembly projection provenance'); require(a.get('full_comparison_sha256')==c['full_comparison_sha256'],'assembly comparison hash'); require(a.get('transport_identity_scientific_authority') is False and a.get('inner_content_commitments_verified') is True,'assembly semantics')
    for prefix in ('comparison','projection_contract'):
        require(type(a.get(f'{prefix}_source_job_id')) is int and a[f'{prefix}_source_job_id']>0,f'{prefix} job id'); require(type(a.get(f'{prefix}_artifact_id')) is int and a[f'{prefix}_artifact_id']>0,f'{prefix} artifact id'); require(isinstance(a.get(f'{prefix}_artifact_digest'),str) and ARTIFACT_DIGEST_RE.fullmatch(a[f'{prefix}_artifact_digest']),f'{prefix} artifact digest')
    claims_exact(a,ac,'assembly')
    require(q.get('schema')=='symthaea.rel.qualification-only.v1' and q.get('authority')=='QualificationOnly','qualification identity')
    expected_q={'predicate_contract_head':EXPECTED['predicate_head'],'execution_subject_head':EXPECTED['execution_head'],'frozen_scientific_subject':EXPECTED['frozen_subject'],'frozen_test_blob':EXPECTED['frozen_test_blob'],'predicate_count':41,'comparison_result':result,'passed_count':passed,'failed_count':failed,'failed_predicate_ids':ids}
    for k,val in expected_q.items(): require(q.get(k)==val,f'qualification {k} mismatch')
    require(q.get('qualification_completed') is True,'qualification incomplete'); sp=q.get('scientific_pass') is True; sf=q.get('scientific_fail') is True; require(sp ^ sf,'pass/fail not XOR')
    if result=='ALL_PREDICATES_PASS': require(q.get('rel_005a_qualified') is True and sp and not sf,'all-pass qualification mapping')
    else: require(q.get('rel_005a_qualified') is False and not sp and sf,'failure qualification mapping')
    return {'schema':'symthaea.rel.qualification-evidence-inspection.v1','authority':'OfflineQualificationEvidenceInspectionOnly','relation':'REL-005A','file_count':7,'qualification_output_valid':True,'manifest_hashes_verified':True,'metric_leakage_absent':True,'authority_chain_consistent':True,'qualification_mapping_consistent':True,'represented_comparison_result':result,'represented_scientific_result':'SCIENTIFIC_PASS' if sp else 'SCIENTIFIC_FAIL','scientific_authority_source':'QualificationOnly','overall_workflow_conclusion_is_scientific_authority':False,'publication_attestation_is_scientific_authority':False,'claims':{'qualification_completed':False,'rel_005a_qualified':False,'scientific_pass':False,'scientific_fail':False}}
def write_json(p,v): p.write_text(json.dumps(v,indent=2,sort_keys=True)+'\n')
def synthetic(root,result):
    ids=[] if result=='ALL_PREDICATES_PASS' else ['REL005A-P041']; failed=len(ids); fc={'observation_sealed':False,'comparison_only_adjudicated':False,'rel_005a_qualified':False,'scientific_pass':False,'scientific_fail':False}; p={'schema':'symthaea.rel.predicate-contract-static-receipt.v1','authority':'PredicateContractOnly','subject_head':EXPECTED['predicate_head'],'predicate_count':41,'source_grounded':True,'predicate_contract_static_valid':True,'frozen_scientific_subject':EXPECTED['frozen_subject'],'frozen_test_blob':EXPECTED['frozen_test_blob'],'claims':fc}; e={'schema':'symthaea.rel.execution-only-receipt.v3','authority':'ExecutionOnly','subject_head':EXPECTED['execution_head'],'predicate_contract_parent':EXPECTED['predicate_head'],'frozen_scientific_subject':EXPECTED['frozen_subject'],'frozen_test_blob':EXPECTED['frozen_test_blob'],'result':'EXECUTION_OK','measurement_exit_code':'0','observation_present':True,'observation_sha256':EXPECTED['observation_sha256'],'claims':fc}; sc=dict(fc); sc['observation_sealed']=True; s={'schema':'symthaea.rel.observation-seal.v3','authority':'ObservationSeal','observation_status':'sealed','adjudication':'not_run','scientific_result':'not_run','execution_subject_head':EXPECTED['execution_head'],'predicate_contract_head':EXPECTED['predicate_head'],'frozen_scientific_subject':EXPECTED['frozen_subject'],'frozen_test_blob':EXPECTED['frozen_test_blob'],'observation_sha256':EXPECTED['observation_sha256'],'chain_commitment_sha256':EXPECTED['seal_chain_sha256'],'claims':sc}; cc={'comparison_only_adjudicated':True,'rel_005a_qualified':False,'scientific_pass':False,'scientific_fail':False}; c={'schema':'symthaea.rel.comparison-only-qualification-receipt.v1','authority':'ComparisonOnly','predicate_contract_head':EXPECTED['predicate_head'],'execution_subject_head':EXPECTED['execution_head'],'frozen_scientific_subject':EXPECTED['frozen_subject'],'frozen_test_blob':EXPECTED['frozen_test_blob'],'observation_sha256':EXPECTED['observation_sha256'],'seal_chain_commitment_sha256':EXPECTED['seal_chain_sha256'],'predicate_count':41,'passed_count':41-failed,'failed_count':failed,'failed_predicate_ids':ids,'comparison_result':result,'claims':cc,'full_comparison_sha256':'55'*32}; root.mkdir(parents=True,exist_ok=True)
    for key,obj in (('predicate',p),('execution',e),('seal',s),('comparison',c)): write_json(root/FILES[key],obj)
    entries=[]
    for key in ('predicate','execution','seal','comparison'):
        path=root/FILES[key]; entries.append({'basename':path.name,'byte_length':path.stat().st_size,'sha256':sha256(path)})
    m={'schema':'symthaea.rel.qualification-input-manifest.v2','authority':'EvidenceProjectionOnly','predicate_contract_head':EXPECTED['predicate_head'],'execution_subject_head':EXPECTED['execution_head'],'observation_sha256':EXPECTED['observation_sha256'],'seal_chain_commitment_sha256':EXPECTED['seal_chain_sha256'],'comparison_result':result,'raw_observation_included':False,'raw_execution_logs_included':False,'detailed_predicate_values_included':False,'files':entries}; write_json(root/FILES['manifest'],m)
    ac={'receipt_extraction_performed':True,'projection_performed':True,'projection_raw_observation_visibility':False,'projection_execution_log_visibility':False,'source_extraction_raw_observation_output':False,'source_extraction_execution_log_output':False,'qualification_completed':False,'rel_005a_qualified':False,'scientific_pass':False,'scientific_fail':False}; a={'schema':'symthaea.rel.qualification-assembly-receipt.v3','authority':'QualificationAssemblyOnly','assembly_contract_head':EXPECTED['assembly_head'],'comparison_subject_head':EXPECTED['comparison_head'],'comparison_source_run_id':EXPECTED['comparison_run_id'],'comparison_source_job_id':1,'comparison_artifact_id':1,'comparison_artifact_name':'x','comparison_artifact_digest':'sha256:'+'11'*32,'full_comparison_sha256':c['full_comparison_sha256'],'projection_contract_head':EXPECTED['projection_head'],'projection_contract_run_id':EXPECTED['projection_run_id'],'projection_contract_source_job_id':2,'projection_contract_artifact_id':2,'projection_contract_artifact_name':'y','projection_contract_artifact_digest':'sha256:'+'22'*32,'projection_contract_receipt_sha256':'33'*32,'predicate_source_run_id':1,'predicate_artifact_id':1,'predicate_artifact_digest':'sha256:'+'44'*32,'seal_source_run_id':1,'seal_source_job_id':1,'seal_artifact_id':1,'seal_artifact_digest':'sha256:'+'66'*32,'predicate_receipt_sha256':'77'*32,'execution_receipt_sha256':'88'*32,'seal_receipt_sha256':'99'*32,'authority_extraction_receipt_sha256':'aa'*32,'sealed_manifest_replay_receipt_sha256':'bb'*32,'transport_identity_scientific_authority':False,'inner_content_commitments_verified':True,'claims':ac}; write_json(root/FILES['assembly'],a); q={'schema':'symthaea.rel.qualification-only.v1','authority':'QualificationOnly','predicate_contract_head':EXPECTED['predicate_head'],'execution_subject_head':EXPECTED['execution_head'],'frozen_scientific_subject':EXPECTED['frozen_subject'],'frozen_test_blob':EXPECTED['frozen_test_blob'],'predicate_count':41,'comparison_result':result,'passed_count':41-failed,'failed_count':failed,'failed_predicate_ids':ids,'qualification_completed':True,'rel_005a_qualified':result=='ALL_PREDICATES_PASS','scientific_pass':result=='ALL_PREDICATES_PASS','scientific_fail':result=='PREDICATE_FAILURES'}; write_json(root/FILES['qualification'],q)
def self_test():
    rejected={}
    with tempfile.TemporaryDirectory() as td:
        base=pathlib.Path(td)
        for r in ('ALL_PREDICATES_PASS','PREDICATE_FAILURES'): root=base/r; synthetic(root,r); inspect(root)
        root=base/'metric'; synthetic(root,'ALL_PREDICATES_PASS'); c=load(root/FILES['comparison']); c['observed']=123; write_json(root/FILES['comparison'],c)
        try: inspect(root)
        except ValueError: rejected['metric_leakage']=True
        else: rejected['metric_leakage']=False
        root=base/'mapping'; synthetic(root,'ALL_PREDICATES_PASS'); q=load(root/FILES['qualification']); q['scientific_pass']=False; q['scientific_fail']=True; write_json(root/FILES['qualification'],q)
        try: inspect(root)
        except ValueError: rejected['mapping_corruption']=True
        else: rejected['mapping_corruption']=False
        root=base/'manifest'; synthetic(root,'ALL_PREDICATES_PASS'); m=load(root/FILES['manifest']); m['files'][0]['sha256']='00'*32; write_json(root/FILES['manifest'],m)
        try: inspect(root)
        except ValueError: rejected['manifest_tamper']=True
        else: rejected['manifest_tamper']=False
        root=base/'ids'; synthetic(root,'PREDICATE_FAILURES'); c=load(root/FILES['comparison']); c['failed_predicate_ids']=['REL005A-P999']; write_json(root/FILES['comparison'],c); m=load(root/FILES['manifest'])
        for ent in m['files']:
            if ent['basename']==FILES['comparison']:
                path=root/FILES['comparison']; ent['byte_length']=path.stat().st_size; ent['sha256']=sha256(path)
        write_json(root/FILES['manifest'],m)
        try: inspect(root)
        except ValueError: rejected['unknown_failed_id']=True
        else: rejected['unknown_failed_id']=False
    require(all(rejected.values()),f'self-test failures: {rejected}')
    return {'schema':'symthaea.rel.qualification-evidence-inspection-self-test.v1','authority':'OfflineQualificationEvidenceInspectionOnly','valid_pass_bundle_accepted':True,'valid_fail_bundle_accepted':True,'adversarial_mutations_rejected':len(rejected),**{k+'_rejected':v for k,v in rejected.items()},'claims':{'qualification_completed':False,'rel_005a_qualified':False,'scientific_pass':False,'scientific_fail':False}}
def main():
    ap=argparse.ArgumentParser(); ap.add_argument('evidence_dir',type=pathlib.Path,nargs='?'); ap.add_argument('--self-test',action='store_true'); a=ap.parse_args()
    if a.self_test: print(json.dumps(self_test(),indent=2,sort_keys=True)); return
    require(a.evidence_dir is not None,'evidence_dir is required'); print(json.dumps(inspect(a.evidence_dir),indent=2,sort_keys=True))
if __name__=='__main__': main()
