#!/usr/bin/env python3
"""Build the metric-free REL-005A QualificationAssemblyOnly artifact."""
from __future__ import annotations
import argparse, hashlib, json, pathlib, shutil
from typing import Any
PROJECTED={'predicate-contract-receipt.json','execution-v3-receipt.json','observation-seal-v3.json','comparison-only-qualification-receipt.json','qualification-input-manifest.json'}

def require(c:bool,m:str)->None:
    if not c: raise ValueError(m)
def load(p:pathlib.Path)->dict[str,Any]:
    v=json.loads(p.read_text()); require(isinstance(v,dict),f'{p}: expected object'); return v
def sha(p:pathlib.Path)->str:return hashlib.sha256(p.read_bytes()).hexdigest()

def main()->None:
    ap=argparse.ArgumentParser(); ap.add_argument('--source',type=pathlib.Path,required=True); ap.add_argument('--projected-dir',type=pathlib.Path,required=True); ap.add_argument('--provenance',type=pathlib.Path,required=True); ap.add_argument('--output-dir',type=pathlib.Path,required=True); a=ap.parse_args()
    s=load(a.source); p=load(a.provenance)
    require(s['schema']=='symthaea.rel.qualification-pipeline-source.v2' and s['authority']=='PipelineOrchestrationOnly','source identity'); require(p['schema']=='symthaea.rel.qualification-pipeline-provenance.v2','provenance schema')
    actual={x.relative_to(a.projected_dir).as_posix() for x in a.projected_dir.rglob('*') if x.is_file()}; require(actual==PROJECTED,f'projected census: {sorted(actual)}')
    cp=a.projected_dir/'comparison-only-qualification-receipt.json'; mp=a.projected_dir/'qualification-input-manifest.json'; c,m=load(cp),load(mp)
    require(c['schema']=='symthaea.rel.comparison-only-qualification-receipt.v1' and c['authority']=='ComparisonOnly','comparison identity'); require(c['comparison_result'] in s['allowed_comparison_results'],'comparison result'); require(m['schema']=='symthaea.rel.qualification-input-manifest.v2' and m['authority']=='EvidenceProjectionOnly','manifest identity'); require(m['comparison_result']==c['comparison_result'],'manifest result'); require(m['raw_observation_included'] is False and m['raw_execution_logs_included'] is False and m['detailed_predicate_values_included'] is False,'projection leakage flags')
    expected=s['contracts']; require(p['assembly_contract_head']==expected['assembly_head'],'assembly head'); require(p['comparison_subject_head']==s['comparison']['subject_head'] and p['comparison_source_run_id']==s['comparison']['source_run_id'],'comparison provenance'); require(p['projection_contract_head']==s['projection_contract']['subject_head'] and p['projection_contract_run_id']==s['projection_contract']['source_run_id'],'projection provenance'); require(p['full_comparison_sha256']==c['full_comparison_sha256'],'comparison hash'); require(p['transport_identity_scientific_authority'] is False and p['inner_content_commitments_verified'] is True,'transport/content semantics'); require(p['receipt_extraction_performed'] is True,'receipt extraction'); require(p['projection_raw_observation_visibility'] is False and p['projection_execution_log_visibility'] is False,'projection visibility'); require(p['source_extraction_raw_observation_output'] is False and p['source_extraction_execution_log_output'] is False,'extractor output'); require(isinstance(p['authority_extraction_receipt_sha256'],str) and len(p['authority_extraction_receipt_sha256'])==64,'extraction receipt hash'); require(isinstance(p['sealed_manifest_replay_receipt_sha256'],str) and len(p['sealed_manifest_replay_receipt_sha256'])==64,'manifest replay receipt hash')
    r={'schema':'symthaea.rel.qualification-assembly-receipt.v3','authority':'QualificationAssemblyOnly','assembly_contract_head':expected['assembly_head'],'comparison_subject_head':p['comparison_subject_head'],'comparison_source_run_id':p['comparison_source_run_id'],'comparison_source_job_id':p['comparison_source_job_id'],'comparison_artifact_id':p['comparison_artifact_id'],'comparison_artifact_name':p['comparison_artifact_name'],'comparison_artifact_digest':p['comparison_artifact_digest'],'full_comparison_sha256':c['full_comparison_sha256'],'projection_contract_head':p['projection_contract_head'],'projection_contract_run_id':p['projection_contract_run_id'],'projection_contract_source_job_id':p['projection_contract_source_job_id'],'projection_contract_artifact_id':p['projection_contract_artifact_id'],'projection_contract_artifact_name':p['projection_contract_artifact_name'],'projection_contract_artifact_digest':p['projection_contract_artifact_digest'],'projection_contract_receipt_sha256':p['projection_contract_receipt_sha256'],'predicate_source_run_id':p['predicate_source_run_id'],'predicate_artifact_id':p['predicate_artifact_id'],'predicate_artifact_digest':p['predicate_artifact_digest'],'seal_source_run_id':p['seal_source_run_id'],'seal_source_job_id':p['seal_source_job_id'],'seal_artifact_id':p['seal_artifact_id'],'seal_artifact_digest':p['seal_artifact_digest'],'predicate_receipt_sha256':p['predicate_receipt_sha256'],'execution_receipt_sha256':p['execution_receipt_sha256'],'seal_receipt_sha256':p['seal_receipt_sha256'],'authority_extraction_receipt_sha256':p['authority_extraction_receipt_sha256'],'sealed_manifest_replay_receipt_sha256':p['sealed_manifest_replay_receipt_sha256'],'transport_identity_scientific_authority':False,'inner_content_commitments_verified':True,'claims':{'receipt_extraction_performed':True,'projection_performed':True,'projection_raw_observation_visibility':False,'projection_execution_log_visibility':False,'source_extraction_raw_observation_output':False,'source_extraction_execution_log_output':False,'qualification_completed':False,'rel_005a_qualified':False,'scientific_pass':False,'scientific_fail':False}}
    a.output_dir.mkdir(parents=True,exist_ok=True)
    for n in sorted(PROJECTED): shutil.copy2(a.projected_dir/n,a.output_dir/n)
    rp=a.output_dir/'qualification-assembly-receipt.json'; rp.write_text(json.dumps(r,indent=2,sort_keys=True)+'\n')
    final={x.relative_to(a.output_dir).as_posix() for x in a.output_dir.rglob('*') if x.is_file()}; require(final==PROJECTED|{'qualification-assembly-receipt.json'},f'assembly census: {sorted(final)}')
    print(json.dumps({'schema':'symthaea.rel.qualification-assembly-build-receipt.v2','authority':'QualificationAssemblyOnly','comparison_result':c['comparison_result'],'assembly_receipt_sha256':sha(rp),'authority_extraction_receipt_sha256':p['authority_extraction_receipt_sha256'],'sealed_manifest_replay_receipt_sha256':p['sealed_manifest_replay_receipt_sha256'],'file_count':len(final),'claims':r['claims']},indent=2,sort_keys=True))
if __name__=='__main__': main()
