SYMTHAEA_QUALIFICATION_PROFILE_V1
profile=statistics-core-v1
repository=Luminous-Dynamics/symthaea
rust_channel=1.96.0
timeout_seconds=900
hash=Cargo.toml
hash=Cargo.lock
hash=rust-toolchain.toml
hash=flake.lock
hash=crates/domains/symthaea-statistics/Cargo.toml
hash=.github/workflows/statistics-core.yml
step=metadata
step=fmt-statistics
step=test-statistics
step=doc-statistics
step=clippy-statistics
step=wasm-statistics
