// Copyright (C) 2024-2026 Tristan Stoltz / Luminous Dynamics
// SPDX-License-Identifier: AGPL-3.0-or-later
// Commercial licensing: see COMMERCIAL_LICENSE.md at repository root
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Thresholds for confidence classification
 */
export type ConfidenceThresholds = { 
/**
 * Critical applications (medical, defense): 0.90+
 */
critical: number, 
/**
 * High-stakes applications (financial, legal): 0.75+
 */
high: number, 
/**
 * General knowledge: 0.60+
 */
medium: number, 
/**
 * Experimental/social data: 0.40+
 */
low: number, };
