// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Individual confidence factor scores
 */
export type ConfidenceFactors = { 
/**
 * Score from attestation count (0-1)
 */
attestation: number, 
/**
 * Score from reputation-weighted attestations (0-1)
 */
reputation: number, 
/**
 * Score from source quality (0-1)
 */
source_quality: number, 
/**
 * Score from time decay (0-1)
 */
time_decay: number, 
/**
 * Score from consistency check (0-1)
 */
consistency: number, };
