// Copyright (C) 2024-2026 Tristan Stoltz / Luminous Dynamics
// SPDX-License-Identifier: AGPL-3.0-or-later
//! Canonical authority-bearing checkpoint record bytes for lattice-QCD.
//!
//! Rust parity layer for the independently executed LQCD-021O checkpoint oracle.
//! This module deliberately does not compute SHA-256 yet: the crate does not
//! currently carry a direct hashing dependency, and that dependency/lockfile
//! transition must be generated by Cargo rather than hand-edited. Instead this
//! module freezes the exact record bytes and exact domain-separated preimages
//! that a later qualified SHA-256 layer hashes.

use crate::lattice_rng::{
    LatticeCampaignPhase, LatticeRngError, LatticeStreamCoordinatesV2, LatticeStreamPurpose,
};

pub const LQCD_CHECKPOINT_RECORD_ID: &str = "lqcd_checkpoint_record_v1";
pub const LQCD_CHECKPOINT_RECORD_TAG: &[u8] = b"symthaea.lqcd.checkpoint.record.v1\0";
pub const LQCD_CHECKPOINT_COMMITMENT_TAG: &[u8] = b"symthaea.lqcd.checkpoint.commitment.v1\0";
pub const LQCD_SEED_COMMITMENT_TAG: &[u8] = b"symthaea.lqcd.seed.commitment.v1\0";

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct LqcdCheckpointRecordV1 {
    pub campaign_subject: [u8; 32],
    pub chain_id: String,
    pub checkpoint_index: u64,
    pub update_ordinal: u64,
    pub stream_coordinates: LatticeStreamCoordinatesV2,
    pub stream_id: u64,
    pub rng_word_pos: u128,
    pub seed_commitment: [u8; 32],
    pub field_encoding_id: String,
    pub field_sha256: [u8; 32],
    pub sampler_stable_id: String,
    pub sampler_revision: String,
    pub numerical_profile_id: String,
    pub environment_profile_id: String,
    pub predecessor: Option<[u8; 32]>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum CheckpointRecordError {
    EmptyIdentifier(&'static str),
    IdentifierTooLong(&'static str),
    StreamNamespace(LatticeRngError),
    StreamIdMismatch { expected: u64, actual: u64 },
    GenesisHasPredecessor,
    SuccessorMissingPredecessor,
    WrongTag,
    Truncated,
    TrailingBytes,
    InvalidUtf8,
    InvalidPhase(u8),
    InvalidPurpose(u8),
    InvalidPredecessorTag(u8),
    AuthorityMismatch(&'static str),
}

impl From<LatticeRngError> for CheckpointRecordError {
    fn from(value: LatticeRngError) -> Self {
        Self::StreamNamespace(value)
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum CheckpointChildDisposition {
    EligibleChild,
    StaleOrSkippedIndex,
    StalePredecessor,
    NonMonotonicUpdateOrdinal,
}

#[derive(Debug, Clone, Copy)]
pub struct CheckpointRestoreExpectation<'a> {
    pub campaign_subject: [u8; 32],
    pub chain_id: &'a str,
    pub stream_coordinates: LatticeStreamCoordinatesV2,
    pub seed_commitment: [u8; 32],
    pub field_encoding_id: &'a str,
    pub field_sha256: [u8; 32],
    pub sampler_stable_id: &'a str,
    pub sampler_revision: &'a str,
    pub numerical_profile_id: &'a str,
    pub environment_profile_id: &'a str,
}

fn require_identifier(value: &str, label: &'static str) -> Result<(), CheckpointRecordError> {
    if value.is_empty() {
        return Err(CheckpointRecordError::EmptyIdentifier(label));
    }
    if u32::try_from(value.len()).is_err() {
        return Err(CheckpointRecordError::IdentifierTooLong(label));
    }
    Ok(())
}

impl LqcdCheckpointRecordV1 {
    pub fn validate(&self) -> Result<(), CheckpointRecordError> {
        require_identifier(&self.chain_id, "chain_id")?;
        require_identifier(&self.field_encoding_id, "field_encoding_id")?;
        require_identifier(&self.sampler_stable_id, "sampler_stable_id")?;
        require_identifier(&self.sampler_revision, "sampler_revision")?;
        require_identifier(&self.numerical_profile_id, "numerical_profile_id")?;
        require_identifier(&self.environment_profile_id, "environment_profile_id")?;

        let expected = self.stream_coordinates.stream_id()?;
        if self.stream_id != expected {
            return Err(CheckpointRecordError::StreamIdMismatch {
                expected,
                actual: self.stream_id,
            });
        }

        if self.checkpoint_index == 0 {
            if self.predecessor.is_some() {
                return Err(CheckpointRecordError::GenesisHasPredecessor);
            }
        } else if self.predecessor.is_none() {
            return Err(CheckpointRecordError::SuccessorMissingPredecessor);
        }
        Ok(())
    }
}

fn push_identifier(
    out: &mut Vec<u8>,
    value: &str,
    label: &'static str,
) -> Result<(), CheckpointRecordError> {
    require_identifier(value, label)?;
    let raw = value.as_bytes();
    let len = u32::try_from(raw.len())
        .map_err(|_| CheckpointRecordError::IdentifierTooLong(label))?;
    out.extend_from_slice(&len.to_be_bytes());
    out.extend_from_slice(raw);
    Ok(())
}

/// Encode the exact LQCD-021O record bytes.
///
/// Field order and integer widths are part of the scientific identity.
pub fn encode_checkpoint_record(
    record: &LqcdCheckpointRecordV1,
) -> Result<Vec<u8>, CheckpointRecordError> {
    record.validate()?;

    let mut out = Vec::new();
    out.extend_from_slice(LQCD_CHECKPOINT_RECORD_TAG);
    out.extend_from_slice(&record.campaign_subject);
    push_identifier(&mut out, &record.chain_id, "chain_id")?;
    out.extend_from_slice(&record.checkpoint_index.to_be_bytes());
    out.extend_from_slice(&record.update_ordinal.to_be_bytes());
    out.push(record.stream_coordinates.phase as u8);
    out.push(record.stream_coordinates.purpose as u8);

    let slot = record.stream_coordinates.ensemble_slot.to_be_bytes();
    out.extend_from_slice(&slot[1..]);
    out.extend_from_slice(&record.stream_coordinates.replica.to_be_bytes());
    out.extend_from_slice(&record.stream_coordinates.rank.to_be_bytes());
    out.extend_from_slice(&record.stream_id.to_be_bytes());
    out.extend_from_slice(&record.rng_word_pos.to_be_bytes());
    out.extend_from_slice(&record.seed_commitment);
    push_identifier(&mut out, &record.field_encoding_id, "field_encoding_id")?;
    out.extend_from_slice(&record.field_sha256);
    push_identifier(&mut out, &record.sampler_stable_id, "sampler_stable_id")?;
    push_identifier(&mut out, &record.sampler_revision, "sampler_revision")?;
    push_identifier(&mut out, &record.numerical_profile_id, "numerical_profile_id")?;
    push_identifier(
        &mut out,
        &record.environment_profile_id,
        "environment_profile_id",
    )?;
    match record.predecessor {
        None => out.push(0),
        Some(predecessor) => {
            out.push(1);
            out.extend_from_slice(&predecessor);
        }
    }
    Ok(out)
}

fn take<'a>(
    bytes: &'a [u8],
    cursor: &mut usize,
    count: usize,
) -> Result<&'a [u8], CheckpointRecordError> {
    let end = cursor
        .checked_add(count)
        .ok_or(CheckpointRecordError::Truncated)?;
    if end > bytes.len() {
        return Err(CheckpointRecordError::Truncated);
    }
    let result = &bytes[*cursor..end];
    *cursor = end;
    Ok(result)
}

fn read_u16(bytes: &[u8], cursor: &mut usize) -> Result<u16, CheckpointRecordError> {
    let raw: [u8; 2] = take(bytes, cursor, 2)?
        .try_into()
        .map_err(|_| CheckpointRecordError::Truncated)?;
    Ok(u16::from_be_bytes(raw))
}

fn read_u32(bytes: &[u8], cursor: &mut usize) -> Result<u32, CheckpointRecordError> {
    let raw: [u8; 4] = take(bytes, cursor, 4)?
        .try_into()
        .map_err(|_| CheckpointRecordError::Truncated)?;
    Ok(u32::from_be_bytes(raw))
}

fn read_u64(bytes: &[u8], cursor: &mut usize) -> Result<u64, CheckpointRecordError> {
    let raw: [u8; 8] = take(bytes, cursor, 8)?
        .try_into()
        .map_err(|_| CheckpointRecordError::Truncated)?;
    Ok(u64::from_be_bytes(raw))
}

fn read_u128(bytes: &[u8], cursor: &mut usize) -> Result<u128, CheckpointRecordError> {
    let raw: [u8; 16] = take(bytes, cursor, 16)?
        .try_into()
        .map_err(|_| CheckpointRecordError::Truncated)?;
    Ok(u128::from_be_bytes(raw))
}

fn read_array32(
    bytes: &[u8],
    cursor: &mut usize,
) -> Result<[u8; 32], CheckpointRecordError> {
    take(bytes, cursor, 32)?
        .try_into()
        .map_err(|_| CheckpointRecordError::Truncated)
}

fn read_identifier(
    bytes: &[u8],
    cursor: &mut usize,
    label: &'static str,
) -> Result<String, CheckpointRecordError> {
    let length = read_u32(bytes, cursor)? as usize;
    if length == 0 {
        return Err(CheckpointRecordError::EmptyIdentifier(label));
    }
    let raw = take(bytes, cursor, length)?;
    let value = std::str::from_utf8(raw).map_err(|_| CheckpointRecordError::InvalidUtf8)?;
    Ok(value.to_owned())
}

fn phase_from_byte(value: u8) -> Result<LatticeCampaignPhase, CheckpointRecordError> {
    match value {
        1 => Ok(LatticeCampaignPhase::Throughput),
        2 => Ok(LatticeCampaignPhase::Pilot),
        3 => Ok(LatticeCampaignPhase::Final),
        4 => Ok(LatticeCampaignPhase::Qualification),
        _ => Err(CheckpointRecordError::InvalidPhase(value)),
    }
}

fn purpose_from_byte(value: u8) -> Result<LatticeStreamPurpose, CheckpointRecordError> {
    match value {
        1 => Ok(LatticeStreamPurpose::GaugeTransition),
        2 => Ok(LatticeStreamPurpose::Diagnostic),
        3 => Ok(LatticeStreamPurpose::Analysis),
        4 => Ok(LatticeStreamPurpose::Bootstrap),
        _ => Err(CheckpointRecordError::InvalidPurpose(value)),
    }
}

/// Decode exact canonical bytes and reject trailing or non-canonical structure.
pub fn decode_checkpoint_record(
    bytes: &[u8],
) -> Result<LqcdCheckpointRecordV1, CheckpointRecordError> {
    if bytes.len() < LQCD_CHECKPOINT_RECORD_TAG.len() {
        return Err(CheckpointRecordError::Truncated);
    }
    if &bytes[..LQCD_CHECKPOINT_RECORD_TAG.len()] != LQCD_CHECKPOINT_RECORD_TAG {
        return Err(CheckpointRecordError::WrongTag);
    }

    let mut cursor = LQCD_CHECKPOINT_RECORD_TAG.len();
    let campaign_subject = read_array32(bytes, &mut cursor)?;
    let chain_id = read_identifier(bytes, &mut cursor, "chain_id")?;
    let checkpoint_index = read_u64(bytes, &mut cursor)?;
    let update_ordinal = read_u64(bytes, &mut cursor)?;
    let phase = phase_from_byte(take(bytes, &mut cursor, 1)?[0])?;
    let purpose = purpose_from_byte(take(bytes, &mut cursor, 1)?[0])?;

    let slot_bytes = take(bytes, &mut cursor, 3)?;
    let ensemble_slot =
        ((slot_bytes[0] as u32) << 16) | ((slot_bytes[1] as u32) << 8) | slot_bytes[2] as u32;
    let replica = read_u16(bytes, &mut cursor)?;
    let rank = read_u16(bytes, &mut cursor)?;
    let stream_id = read_u64(bytes, &mut cursor)?;
    let rng_word_pos = read_u128(bytes, &mut cursor)?;
    let seed_commitment = read_array32(bytes, &mut cursor)?;
    let field_encoding_id = read_identifier(bytes, &mut cursor, "field_encoding_id")?;
    let field_sha256 = read_array32(bytes, &mut cursor)?;
    let sampler_stable_id = read_identifier(bytes, &mut cursor, "sampler_stable_id")?;
    let sampler_revision = read_identifier(bytes, &mut cursor, "sampler_revision")?;
    let numerical_profile_id = read_identifier(bytes, &mut cursor, "numerical_profile_id")?;
    let environment_profile_id =
        read_identifier(bytes, &mut cursor, "environment_profile_id")?;

    let predecessor_tag = take(bytes, &mut cursor, 1)?[0];
    let predecessor = match predecessor_tag {
        0 => None,
        1 => Some(read_array32(bytes, &mut cursor)?),
        other => return Err(CheckpointRecordError::InvalidPredecessorTag(other)),
    };

    if cursor != bytes.len() {
        return Err(CheckpointRecordError::TrailingBytes);
    }

    let record = LqcdCheckpointRecordV1 {
        campaign_subject,
        chain_id,
        checkpoint_index,
        update_ordinal,
        stream_coordinates: LatticeStreamCoordinatesV2 {
            phase,
            purpose,
            ensemble_slot,
            replica,
            rank,
        },
        stream_id,
        rng_word_pos,
        seed_commitment,
        field_encoding_id,
        field_sha256,
        sampler_stable_id,
        sampler_revision,
        numerical_profile_id,
        environment_profile_id,
        predecessor,
    };
    record.validate()?;
    Ok(record)
}

/// Exact bytes that the future SHA-256 checkpoint commitment hashes.
pub fn checkpoint_commitment_preimage(
    record: &LqcdCheckpointRecordV1,
) -> Result<Vec<u8>, CheckpointRecordError> {
    let encoded = encode_checkpoint_record(record)?;
    let mut out = Vec::with_capacity(LQCD_CHECKPOINT_COMMITMENT_TAG.len() + encoded.len());
    out.extend_from_slice(LQCD_CHECKPOINT_COMMITMENT_TAG);
    out.extend_from_slice(&encoded);
    Ok(out)
}

/// Exact bytes that the future SHA-256 seed commitment hashes.
pub fn seed_commitment_preimage(seed: &[u8; 32]) -> Vec<u8> {
    let mut out = Vec::with_capacity(LQCD_SEED_COMMITMENT_TAG.len() + seed.len());
    out.extend_from_slice(LQCD_SEED_COMMITMENT_TAG);
    out.extend_from_slice(seed);
    out
}

/// Validate all externally computed digest/profile bindings before restore.
///
/// This function does not compute those digests; it ensures that once supplied
/// by the future qualified hashing layer, none can be silently substituted.
pub fn validate_restore_authority(
    record: &LqcdCheckpointRecordV1,
    expected: CheckpointRestoreExpectation<'_>,
) -> Result<(), CheckpointRecordError> {
    record.validate()?;
    if record.campaign_subject != expected.campaign_subject {
        return Err(CheckpointRecordError::AuthorityMismatch("campaign_subject"));
    }
    if record.chain_id != expected.chain_id {
        return Err(CheckpointRecordError::AuthorityMismatch("chain_id"));
    }
    if record.stream_coordinates != expected.stream_coordinates {
        return Err(CheckpointRecordError::AuthorityMismatch("stream_coordinates"));
    }
    if record.seed_commitment != expected.seed_commitment {
        return Err(CheckpointRecordError::AuthorityMismatch("seed_commitment"));
    }
    if record.field_encoding_id != expected.field_encoding_id {
        return Err(CheckpointRecordError::AuthorityMismatch("field_encoding_id"));
    }
    if record.field_sha256 != expected.field_sha256 {
        return Err(CheckpointRecordError::AuthorityMismatch("field_sha256"));
    }
    if record.sampler_stable_id != expected.sampler_stable_id {
        return Err(CheckpointRecordError::AuthorityMismatch("sampler_stable_id"));
    }
    if record.sampler_revision != expected.sampler_revision {
        return Err(CheckpointRecordError::AuthorityMismatch("sampler_revision"));
    }
    if record.numerical_profile_id != expected.numerical_profile_id {
        return Err(CheckpointRecordError::AuthorityMismatch("numerical_profile_id"));
    }
    if record.environment_profile_id != expected.environment_profile_id {
        return Err(CheckpointRecordError::AuthorityMismatch("environment_profile_id"));
    }
    Ok(())
}

/// Classify one proposed successor using an externally verified current-head
/// commitment. SHA-256 computation remains outside this dependency-neutral tranche.
pub fn classify_checkpoint_child(
    current: &LqcdCheckpointRecordV1,
    current_commitment: [u8; 32],
    candidate: &LqcdCheckpointRecordV1,
) -> Result<CheckpointChildDisposition, CheckpointRecordError> {
    current.validate()?;
    candidate.validate()?;

    if current.checkpoint_index.checked_add(1) != Some(candidate.checkpoint_index) {
        return Ok(CheckpointChildDisposition::StaleOrSkippedIndex);
    }
    if candidate.predecessor != Some(current_commitment) {
        return Ok(CheckpointChildDisposition::StalePredecessor);
    }
    if candidate.update_ordinal <= current.update_ordinal {
        return Ok(CheckpointChildDisposition::NonMonotonicUpdateOrdinal);
    }
    Ok(CheckpointChildDisposition::EligibleChild)
}

#[cfg(test)]
mod tests {
    use super::*;

    const CAMPAIGN_SUBJECT: [u8; 32] = [
        0x69, 0xfd, 0xe4, 0xf2, 0x16, 0x12, 0x9e, 0x45, 0xfe, 0x3b, 0x52, 0x39, 0x77, 0xea,
        0x00, 0xd9, 0x46, 0x30, 0xca, 0x68, 0x4b, 0x7e, 0xe8, 0xc5, 0x1d, 0xee, 0xc7, 0x26,
        0x43, 0x0f, 0xcb, 0xf1,
    ];
    const SEED_COMMITMENT: [u8; 32] = [
        0x48, 0xd6, 0x91, 0x93, 0xd3, 0xfa, 0x4b, 0x0e, 0x9b, 0xa5, 0x04, 0x4e, 0x09, 0x70,
        0x74, 0xd0, 0x6f, 0x95, 0x88, 0x9e, 0x21, 0x7e, 0x49, 0x20, 0xda, 0xe1, 0x0b, 0xad,
        0xb0, 0x6c, 0x19, 0xc4,
    ];
    const FIELD_DIGEST: [u8; 32] = [
        0x7b, 0xd6, 0x2c, 0xa2, 0x98, 0x33, 0xbe, 0x01, 0x71, 0xa4, 0xf3, 0x23, 0x2c, 0x03,
        0xa3, 0xed, 0xca, 0x12, 0x5a, 0xa5, 0x0b, 0x33, 0xae, 0xb1, 0x87, 0xe7, 0x02, 0xfb,
        0x1c, 0x8c, 0x99, 0x6b,
    ];
    const GENESIS_COMMITMENT: [u8; 32] = [
        0xe5, 0xb4, 0x39, 0xc4, 0x79, 0x11, 0xa6, 0x7e, 0xcb, 0x9d, 0x89, 0xcc, 0x43, 0xde,
        0xbb, 0x9d, 0x5f, 0xe9, 0x65, 0x6c, 0x47, 0x67, 0xb9, 0x00, 0x7a, 0x5f, 0x1b, 0x1e,
        0xc9, 0x8c, 0x5f, 0x3c,
    ];

    const GENESIS_HEX: &str = "73796d74686165612e6c7163642e636865636b706f696e742e7265636f72642e76310069fde4f216129e45fe3b523977ea00d94630ca684b7ee8c51deec726430fcbf10000001662657461362d66696e616c2d636861696e2d3030303700000000000000000000000000001f40030100021d000700003100021d00070000000000000000000000000000075bcd1548d69193d3fa4b0e9ba5044e097074d06f95889e217e4920dae10badb06c19c40000001c77696c736f6e5f67617567655f6669656c645f62655f6636345f76317bd62ca29833be0171a4f3232c03a3edca125aa50b33aeb187e702fb1c8c996b0000003b636d5f68656174626174685f6f725f76313a666f7263653d737461706c653a6f725f7377656570733d333a6d61785f617474656d7074733d3235360000002835366331313562343639323066633862333464616138383937303531636666353963363161306266000000236c7163645f6e756d65726963616c5f70726f66696c655f63616e6469646174655f76310000002a73796d74686165612d727573743139362d6c696e75782d7838365f36342d63616e6469646174652d763100";
    const SUCCESSOR_HEX: &str = "73796d74686165612e6c7163642e636865636b706f696e742e7265636f72642e76310069fde4f216129e45fe3b523977ea00d94630ca684b7ee8c51deec726430fcbf10000001662657461362d66696e616c2d636861696e2d3030303700000000000000010000000000001fa4030100021d000700003100021d00070000000000000000000000000000078ea59448d69193d3fa4b0e9ba5044e097074d06f95889e217e4920dae10badb06c19c40000001c77696c736f6e5f67617567655f6669656c645f62655f6636345f76317bd62ca29833be0171a4f3232c03a3edca125aa50b33aeb187e702fb1c8c996b0000003b636d5f68656174626174685f6f725f76313a666f7263653d737461706c653a6f725f7377656570733d333a6d61785f617474656d7074733d3235360000002835366331313562343639323066633862333464616138383937303531636666353963363161306266000000236c7163645f6e756d65726963616c5f70726f66696c655f63616e6469646174655f76310000002a73796d74686165612d727573743139362d6c696e75782d7838365f36342d63616e6469646174652d763101e5b439c47911a67ecb9d89cc43debb9d5fe9656c4767b9007a5f1b1ec98c5f3c";

    fn decode_hex(hex: &str) -> Vec<u8> {
        assert_eq!(hex.len() % 2, 0);
        (0..hex.len())
            .step_by(2)
            .map(|index| u8::from_str_radix(&hex[index..index + 2], 16).unwrap())
            .collect()
    }

    fn coordinates() -> LatticeStreamCoordinatesV2 {
        LatticeStreamCoordinatesV2 {
            phase: LatticeCampaignPhase::Final,
            purpose: LatticeStreamPurpose::GaugeTransition,
            ensemble_slot: 0x021d,
            replica: 7,
            rank: 0,
        }
    }

    fn genesis() -> LqcdCheckpointRecordV1 {
        LqcdCheckpointRecordV1 {
            campaign_subject: CAMPAIGN_SUBJECT,
            chain_id: "beta6-final-chain-0007".to_owned(),
            checkpoint_index: 0,
            update_ordinal: 8000,
            stream_coordinates: coordinates(),
            stream_id: 0x3100_021d_0007_0000,
            rng_word_pos: 123_456_789,
            seed_commitment: SEED_COMMITMENT,
            field_encoding_id: "wilson_gauge_field_be_f64_v1".to_owned(),
            field_sha256: FIELD_DIGEST,
            sampler_stable_id:
                "cm_heatbath_or_v1:force=staple:or_sweeps=3:max_attempts=256".to_owned(),
            sampler_revision: "56c115b46920fc8b34daa8897051cff59c61a0bf".to_owned(),
            numerical_profile_id: "lqcd_numerical_profile_candidate_v1".to_owned(),
            environment_profile_id: "symthaea-rust196-linux-x86_64-candidate-v1".to_owned(),
            predecessor: None,
        }
    }

    fn successor() -> LqcdCheckpointRecordV1 {
        LqcdCheckpointRecordV1 {
            checkpoint_index: 1,
            update_ordinal: 8100,
            rng_word_pos: 126_789_012,
            predecessor: Some(GENESIS_COMMITMENT),
            ..genesis()
        }
    }

    #[test]
    fn exact_genesis_and_successor_bytes_match_independent_oracle() {
        let genesis_bytes = encode_checkpoint_record(&genesis()).unwrap();
        let successor_bytes = encode_checkpoint_record(&successor()).unwrap();
        assert_eq!(genesis_bytes.len(), 431);
        assert_eq!(successor_bytes.len(), 463);
        assert_eq!(genesis_bytes, decode_hex(GENESIS_HEX));
        assert_eq!(successor_bytes, decode_hex(SUCCESSOR_HEX));
    }

    #[test]
    fn exact_oracle_vectors_roundtrip_without_trailing_bytes() {
        let genesis_bytes = decode_hex(GENESIS_HEX);
        let successor_bytes = decode_hex(SUCCESSOR_HEX);
        let decoded_genesis = decode_checkpoint_record(&genesis_bytes).unwrap();
        let decoded_successor = decode_checkpoint_record(&successor_bytes).unwrap();
        assert_eq!(decoded_genesis, genesis());
        assert_eq!(decoded_successor, successor());
        assert_eq!(encode_checkpoint_record(&decoded_genesis).unwrap(), genesis_bytes);
        assert_eq!(encode_checkpoint_record(&decoded_successor).unwrap(), successor_bytes);

        let mut trailing = successor_bytes.clone();
        trailing.push(0);
        assert_eq!(
            decode_checkpoint_record(&trailing),
            Err(CheckpointRecordError::TrailingBytes)
        );
        assert_eq!(
            decode_checkpoint_record(&successor_bytes[..successor_bytes.len() - 1]),
            Err(CheckpointRecordError::Truncated)
        );
    }

    #[test]
    fn preimages_are_domain_separated_without_claiming_sha256() {
        let seed: [u8; 32] = std::array::from_fn(|index| index as u8);
        let seed_preimage = seed_commitment_preimage(&seed);
        assert_eq!(
            &seed_preimage[..LQCD_SEED_COMMITMENT_TAG.len()],
            LQCD_SEED_COMMITMENT_TAG
        );
        assert_eq!(&seed_preimage[LQCD_SEED_COMMITMENT_TAG.len()..], &seed);

        let checkpoint_preimage = checkpoint_commitment_preimage(&genesis()).unwrap();
        assert_eq!(
            &checkpoint_preimage[..LQCD_CHECKPOINT_COMMITMENT_TAG.len()],
            LQCD_CHECKPOINT_COMMITMENT_TAG
        );
        assert_eq!(
            &checkpoint_preimage[LQCD_CHECKPOINT_COMMITMENT_TAG.len()..],
            decode_hex(GENESIS_HEX)
        );
    }

    #[test]
    fn restore_authority_rejects_profile_and_digest_substitution() {
        let record = successor();
        let expected = CheckpointRestoreExpectation {
            campaign_subject: CAMPAIGN_SUBJECT,
            chain_id: "beta6-final-chain-0007",
            stream_coordinates: coordinates(),
            seed_commitment: SEED_COMMITMENT,
            field_encoding_id: "wilson_gauge_field_be_f64_v1",
            field_sha256: FIELD_DIGEST,
            sampler_stable_id: "cm_heatbath_or_v1:force=staple:or_sweeps=3:max_attempts=256",
            sampler_revision: "56c115b46920fc8b34daa8897051cff59c61a0bf",
            numerical_profile_id: "lqcd_numerical_profile_candidate_v1",
            environment_profile_id: "symthaea-rust196-linux-x86_64-candidate-v1",
        };
        validate_restore_authority(&record, expected).unwrap();

        let mut wrong_field = expected;
        wrong_field.field_sha256[0] ^= 1;
        assert_eq!(
            validate_restore_authority(&record, wrong_field),
            Err(CheckpointRecordError::AuthorityMismatch("field_sha256"))
        );

        let mut wrong_profile = expected;
        wrong_profile.numerical_profile_id = "different-profile";
        assert_eq!(
            validate_restore_authority(&record, wrong_profile),
            Err(CheckpointRecordError::AuthorityMismatch("numerical_profile_id"))
        );
    }

    #[test]
    fn child_classification_matches_independent_oracle_semantics() {
        assert_eq!(
            classify_checkpoint_child(&genesis(), GENESIS_COMMITMENT, &successor()).unwrap(),
            CheckpointChildDisposition::EligibleChild
        );

        let mut stale = successor();
        stale.checkpoint_index = 2;
        stale.update_ordinal = 8200;
        stale.predecessor = Some([0; 32]);
        assert_eq!(
            classify_checkpoint_child(&successor(), [0x84; 32], &stale).unwrap(),
            CheckpointChildDisposition::StalePredecessor
        );

        let mut non_monotonic = successor();
        non_monotonic.update_ordinal = 8000;
        assert_eq!(
            classify_checkpoint_child(&genesis(), GENESIS_COMMITMENT, &non_monotonic).unwrap(),
            CheckpointChildDisposition::NonMonotonicUpdateOrdinal
        );
    }

    #[test]
    fn structural_mismatches_fail_closed() {
        let mut mismatch = successor();
        mismatch.stream_id ^= 1;
        assert!(matches!(
            encode_checkpoint_record(&mismatch),
            Err(CheckpointRecordError::StreamIdMismatch { .. })
        ));

        let mut bad_genesis = genesis();
        bad_genesis.predecessor = Some([0; 32]);
        assert_eq!(
            encode_checkpoint_record(&bad_genesis),
            Err(CheckpointRecordError::GenesisHasPredecessor)
        );

        let mut bad_successor = successor();
        bad_successor.predecessor = None;
        assert_eq!(
            encode_checkpoint_record(&bad_successor),
            Err(CheckpointRecordError::SuccessorMissingPredecessor)
        );
    }
}
