// Copyright (C) 2024-2026 Tristan Stoltz / Luminous Dynamics
// SPDX-License-Identifier: AGPL-3.0-or-later
//! Internal dense SU(3) Lie-group helpers used by lattice qualification kernels.
//!
//! This is deliberately tiny and dependency-free. It is not a general linear
//! algebra layer; it only centralizes the scaling/squaring exponential convention
//! needed by optimized flow code and its deterministic Gell-Mann fixtures.

use crate::lattice_gauge::{Su3Matrix, su3_identity, su3_mul};
use crate::symmetry_groups::{Complex, gell_mann_matrix};

const MATRIX_EXP_TERMS: usize = 50;

#[inline]
fn c_add(a: Complex, b: Complex) -> Complex {
    Complex::new(a.re + b.re, a.im + b.im)
}

#[inline]
fn c_mul(a: Complex, b: Complex) -> Complex {
    Complex::new(a.re * b.re - a.im * b.im, a.re * b.im + a.im * b.re)
}

pub(crate) fn zero_matrix() -> Su3Matrix {
    [[Complex::ZERO; 3]; 3]
}

pub(crate) fn matrix_add(a: &Su3Matrix, b: &Su3Matrix) -> Su3Matrix {
    let mut out = zero_matrix();
    for i in 0..3 {
        for j in 0..3 {
            out[i][j] = c_add(a[i][j], b[i][j]);
        }
    }
    out
}

pub(crate) fn matrix_add_assign(dst: &mut Su3Matrix, src: &Su3Matrix) {
    for i in 0..3 {
        for j in 0..3 {
            dst[i][j] = c_add(dst[i][j], src[i][j]);
        }
    }
}

pub(crate) fn matrix_scale(a: &Su3Matrix, scalar: Complex) -> Su3Matrix {
    let mut out = zero_matrix();
    for i in 0..3 {
        for j in 0..3 {
            out[i][j] = c_mul(scalar, a[i][j]);
        }
    }
    out
}

fn frobenius_norm(a: &Su3Matrix) -> f64 {
    a.iter()
        .flatten()
        .map(|value| value.norm_sq())
        .sum::<f64>()
        .sqrt()
}

/// Scaling/squaring plus a 50-term Taylor expansion.
///
/// This matches the convention frozen by LQCD-017D/017E. Callers are expected
/// to pass the small anti-Hermitian matrices generated by lattice flow code.
pub(crate) fn matrix_exp(a: &Su3Matrix) -> Su3Matrix {
    let norm = frobenius_norm(a);
    let squarings = if norm > 0.5 {
        (norm / 0.5).log2().ceil().max(0.0) as u32
    } else {
        0
    };
    let x = matrix_scale(
        a,
        Complex::new(1.0 / 2.0_f64.powi(squarings as i32), 0.0),
    );
    let mut out = su3_identity();
    let mut term = su3_identity();
    for k in 1..=MATRIX_EXP_TERMS {
        term = matrix_scale(
            &su3_mul(&term, &x),
            Complex::new(1.0 / k as f64, 0.0),
        );
        out = matrix_add(&out, &term);
    }
    for _ in 0..squarings {
        out = su3_mul(&out, &out);
    }
    out
}

pub(crate) fn generator_rotation(generator: usize, theta: f64) -> Su3Matrix {
    matrix_exp(&matrix_scale(
        &gell_mann_matrix(generator),
        Complex::new(0.0, theta),
    ))
}
