// Copyright (C) 2024-2026 Tristan Stoltz / Luminous Dynamics
// SPDX-License-Identifier: AGPL-3.0-or-later
#![cfg(target_os = "linux")]
//! Content-addressed compiled seccomp cBPF artifacts for Forge evaluator sandboxes.
//!
//! This bridge validates only structural facts that can be established directly from the compiled
//! bytes. In particular, it requires an architecture guard before syscall-number dispatch and a
//! fail-closed `SECCOMP_RET_KILL_PROCESS` architecture-mismatch branch. It deliberately does not
//! claim that the remaining syscall policy is correct, complete, least-privilege, or generated by a
//! semantically trustworthy compiler.

use serde::Serialize;
use symthaea_algorithms::ContentId;
use thiserror::Error;

const SOCK_FILTER_BYTES: usize = 8;
const MAX_BPF_INSTRUCTIONS: usize = 4096;
const MAX_COMPILER_VERSION_BYTES: usize = 128;

// Classic-BPF encodings from linux/filter.h.
const BPF_LD_W_ABS: u16 = 0x20;
const BPF_JMP_JEQ_K: u16 = 0x15;
const BPF_RET_K: u16 = 0x06;

// offsetof(struct seccomp_data, nr) and offsetof(struct seccomp_data, arch).
const SECCOMP_DATA_NR_OFFSET: u32 = 0;
const SECCOMP_DATA_ARCH_OFFSET: u32 = 4;
const SECCOMP_RET_KILL_PROCESS: u32 = 0x8000_0000;

#[derive(Debug, Error)]
pub enum CompiledSeccompFilterError {
    #[error("compiler version must be non-empty, bounded, trimmed and single-line")]
    InvalidCompilerVersion,
    #[error("compiled filter bytes must contain whole 8-byte sock_filter records")]
    InvalidRecordShape,
    #[error("compiled filter instruction count is outside the accepted bounds")]
    InvalidInstructionCount,
    #[error("compiled filter does not begin by loading seccomp_data.arch")]
    MissingArchitectureLoad,
    #[error("compiled filter does not compare the loaded architecture with the declared AUDIT_ARCH")]
    MissingArchitectureComparison,
    #[error("compiled filter architecture branch jumps outside the program")]
    ArchitectureBranchOutOfBounds,
    #[error("architecture mismatch does not branch directly to SECCOMP_RET_KILL_PROCESS")]
    ArchitectureMismatchNotFailClosed,
    #[error("matching architecture does not branch directly to a seccomp_data.nr load")]
    ArchitectureMatchDoesNotLoadSyscall,
    #[error("compiled-filter artifact identity is non-canonical")]
    ArtifactIdentityMismatch,
    #[error("architecture-guard receipt does not bind the supplied filter")]
    GuardScopeMismatch,
    #[error("architecture-guard receipt identity is non-canonical")]
    GuardIdentityMismatch,
    #[error("compiled filter target architecture does not match this process architecture")]
    CurrentProcessArchitectureMismatch,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize)]
pub enum SeccompFilterEncoding {
    SockFilterLittleEndianV1,
}

impl SeccompFilterEncoding {
    fn tag(self) -> &'static [u8] {
        match self {
            Self::SockFilterLittleEndianV1 => b"sock-filter-little-endian-v1",
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize)]
pub enum SeccompAuditArchitecture {
    X86_64,
    Aarch64,
    Riscv64,
}

impl SeccompAuditArchitecture {
    pub fn audit_arch(self) -> u32 {
        match self {
            Self::X86_64 => 0xc000_003e,
            Self::Aarch64 => 0xc000_00b7,
            Self::Riscv64 => 0xc000_00f3,
        }
    }

    pub fn rust_arch(self) -> &'static str {
        match self {
            Self::X86_64 => "x86_64",
            Self::Aarch64 => "aarch64",
            Self::Riscv64 => "riscv64",
        }
    }

    fn tag(self) -> &'static [u8] {
        match self {
            Self::X86_64 => b"audit-arch-x86-64",
            Self::Aarch64 => b"audit-arch-aarch64",
            Self::Riscv64 => b"audit-arch-riscv64",
        }
    }

    pub fn matches_current_process(self) -> bool {
        std::env::consts::ARCH == self.rust_arch()
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize)]
pub enum SeccompFilterExporter {
    LibseccompExportBpfV1,
}

impl SeccompFilterExporter {
    fn tag(self) -> &'static [u8] {
        match self {
            Self::LibseccompExportBpfV1 => b"libseccomp-export-bpf-v1",
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize)]
pub enum SeccompFilterSemanticsStatus {
    NotEstablishedV1,
}

/// Identity of the tool claimed to have produced the raw `seccomp_export_bpf` bytes.
///
/// This is provenance only. It does not establish that the compiler implementation is correct.
#[derive(Debug, Clone, PartialEq, Eq, Serialize)]
pub struct SeccompFilterCompilerIdentity {
    id: ContentId,
    implementation_artifact_id: ContentId,
    version: String,
    exporter: SeccompFilterExporter,
    semantics: SeccompFilterSemanticsStatus,
}

impl SeccompFilterCompilerIdentity {
    pub fn new(
        implementation_artifact_id: ContentId,
        version: impl Into<String>,
    ) -> Result<Self, CompiledSeccompFilterError> {
        let version = version.into();
        validate_version(&version)?;
        let exporter = SeccompFilterExporter::LibseccompExportBpfV1;
        let semantics = SeccompFilterSemanticsStatus::NotEstablishedV1;
        let id = ContentId::derive(
            "symthaea.forge-seccomp-filter-compiler-identity.v1",
            [
                implementation_artifact_id.as_str().as_bytes(),
                version.as_bytes(),
                exporter.tag(),
                b"compiler-semantics-not-established-v1",
            ],
        );
        Ok(Self {
            id,
            implementation_artifact_id,
            version,
            exporter,
            semantics,
        })
    }

    pub fn id(&self) -> &ContentId { &self.id }
    pub fn implementation_artifact_id(&self) -> &ContentId { &self.implementation_artifact_id }
    pub fn version(&self) -> &str { &self.version }
    pub fn exporter(&self) -> SeccompFilterExporter { self.exporter }
    pub fn semantics(&self) -> SeccompFilterSemanticsStatus { self.semantics }

    pub fn validate(&self) -> Result<(), CompiledSeccompFilterError> {
        if Self::new(self.implementation_artifact_id.clone(), self.version.clone())? == *self {
            Ok(())
        } else {
            Err(CompiledSeccompFilterError::ArtifactIdentityMismatch)
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
struct BpfInstruction {
    code: u16,
    jt: u8,
    jf: u8,
    k: u32,
}

impl BpfInstruction {
    fn parse(bytes: &[u8]) -> Self {
        Self {
            code: u16::from_le_bytes([bytes[0], bytes[1]]),
            jt: bytes[2],
            jf: bytes[3],
            k: u32::from_le_bytes([bytes[4], bytes[5], bytes[6], bytes[7]]),
        }
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize)]
pub struct CompiledSeccompFilterArtifact {
    id: ContentId,
    target_architecture: SeccompAuditArchitecture,
    encoding: SeccompFilterEncoding,
    compiler_id: ContentId,
    policy_contract_id: ContentId,
    instruction_count: u16,
    bytes: Vec<u8>,
    semantics: SeccompFilterSemanticsStatus,
}

impl CompiledSeccompFilterArtifact {
    pub fn freeze(
        target_architecture: SeccompAuditArchitecture,
        compiler: &SeccompFilterCompilerIdentity,
        policy_contract_id: ContentId,
        bytes: Vec<u8>,
    ) -> Result<Self, CompiledSeccompFilterError> {
        compiler.validate()?;
        let instructions = parse_program(&bytes)?;
        validate_architecture_guard(&instructions, target_architecture)?;
        let instruction_count = u16::try_from(instructions.len())
            .map_err(|_| CompiledSeccompFilterError::InvalidInstructionCount)?;
        let encoding = SeccompFilterEncoding::SockFilterLittleEndianV1;
        let semantics = SeccompFilterSemanticsStatus::NotEstablishedV1;
        let id = derive_artifact_id(
            target_architecture,
            encoding,
            compiler.id(),
            &policy_contract_id,
            instruction_count,
            &bytes,
        );
        Ok(Self {
            id,
            target_architecture,
            encoding,
            compiler_id: compiler.id().clone(),
            policy_contract_id,
            instruction_count,
            bytes,
            semantics,
        })
    }

    pub fn id(&self) -> &ContentId { &self.id }
    pub fn target_architecture(&self) -> SeccompAuditArchitecture { self.target_architecture }
    pub fn encoding(&self) -> SeccompFilterEncoding { self.encoding }
    pub fn compiler_id(&self) -> &ContentId { &self.compiler_id }
    pub fn policy_contract_id(&self) -> &ContentId { &self.policy_contract_id }
    pub fn instruction_count(&self) -> u16 { self.instruction_count }
    pub fn bytes(&self) -> &[u8] { &self.bytes }
    pub fn semantics(&self) -> SeccompFilterSemanticsStatus { self.semantics }

    pub fn validate_for(
        &self,
        compiler: &SeccompFilterCompilerIdentity,
    ) -> Result<(), CompiledSeccompFilterError> {
        compiler.validate()?;
        let instructions = parse_program(&self.bytes)?;
        validate_architecture_guard(&instructions, self.target_architecture)?;
        let count = u16::try_from(instructions.len())
            .map_err(|_| CompiledSeccompFilterError::InvalidInstructionCount)?;
        if self.encoding != SeccompFilterEncoding::SockFilterLittleEndianV1
            || self.compiler_id != *compiler.id()
            || self.instruction_count != count
            || self.semantics != SeccompFilterSemanticsStatus::NotEstablishedV1
        {
            return Err(CompiledSeccompFilterError::ArtifactIdentityMismatch);
        }
        let expected = derive_artifact_id(
            self.target_architecture,
            self.encoding,
            &self.compiler_id,
            &self.policy_contract_id,
            self.instruction_count,
            &self.bytes,
        );
        if expected == self.id {
            Ok(())
        } else {
            Err(CompiledSeccompFilterError::ArtifactIdentityMismatch)
        }
    }

    pub fn require_current_process_architecture(&self) -> Result<(), CompiledSeccompFilterError> {
        if self.target_architecture.matches_current_process() {
            Ok(())
        } else {
            Err(CompiledSeccompFilterError::CurrentProcessArchitectureMismatch)
        }
    }
}

/// Static proof that the compiled bytes have a fail-closed architecture dispatch before syscall
/// number handling. This is not a proof of the remaining syscall-policy semantics.
#[derive(Debug, Clone, PartialEq, Eq, Serialize)]
pub struct SeccompArchitectureGuardReceipt {
    id: ContentId,
    filter_artifact_id: ContentId,
    target_architecture: SeccompAuditArchitecture,
    audit_arch: u32,
    architecture_compare_index: u16,
    architecture_match_target: u16,
    architecture_mismatch_target: u16,
    semantics: SeccompFilterSemanticsStatus,
}

impl SeccompArchitectureGuardReceipt {
    pub fn issue(
        artifact: &CompiledSeccompFilterArtifact,
        compiler: &SeccompFilterCompilerIdentity,
    ) -> Result<Self, CompiledSeccompFilterError> {
        artifact.validate_for(compiler)?;
        let instructions = parse_program(artifact.bytes())?;
        let (match_target, mismatch_target) =
            validate_architecture_guard(&instructions, artifact.target_architecture())?;
        let architecture_compare_index = 1u16;
        let architecture_match_target = u16::try_from(match_target)
            .map_err(|_| CompiledSeccompFilterError::ArchitectureBranchOutOfBounds)?;
        let architecture_mismatch_target = u16::try_from(mismatch_target)
            .map_err(|_| CompiledSeccompFilterError::ArchitectureBranchOutOfBounds)?;
        let semantics = SeccompFilterSemanticsStatus::NotEstablishedV1;
        let id = derive_guard_id(
            artifact.id(),
            artifact.target_architecture(),
            artifact.target_architecture().audit_arch(),
            architecture_compare_index,
            architecture_match_target,
            architecture_mismatch_target,
        );
        Ok(Self {
            id,
            filter_artifact_id: artifact.id().clone(),
            target_architecture: artifact.target_architecture(),
            audit_arch: artifact.target_architecture().audit_arch(),
            architecture_compare_index,
            architecture_match_target,
            architecture_mismatch_target,
            semantics,
        })
    }

    pub fn id(&self) -> &ContentId { &self.id }
    pub fn filter_artifact_id(&self) -> &ContentId { &self.filter_artifact_id }
    pub fn target_architecture(&self) -> SeccompAuditArchitecture { self.target_architecture }
    pub fn audit_arch(&self) -> u32 { self.audit_arch }
    pub fn semantics(&self) -> SeccompFilterSemanticsStatus { self.semantics }

    pub fn validate_for(
        &self,
        artifact: &CompiledSeccompFilterArtifact,
        compiler: &SeccompFilterCompilerIdentity,
    ) -> Result<(), CompiledSeccompFilterError> {
        let rebuilt = Self::issue(artifact, compiler)?;
        if self.filter_artifact_id != *artifact.id()
            || self.target_architecture != artifact.target_architecture()
            || self.audit_arch != artifact.target_architecture().audit_arch()
            || self.semantics != SeccompFilterSemanticsStatus::NotEstablishedV1
        {
            return Err(CompiledSeccompFilterError::GuardScopeMismatch);
        }
        if rebuilt == *self {
            Ok(())
        } else {
            Err(CompiledSeccompFilterError::GuardIdentityMismatch)
        }
    }
}

fn validate_version(version: &str) -> Result<(), CompiledSeccompFilterError> {
    if version.is_empty()
        || version.len() > MAX_COMPILER_VERSION_BYTES
        || version.trim() != version
        || version.chars().any(|ch| ch.is_control())
    {
        return Err(CompiledSeccompFilterError::InvalidCompilerVersion);
    }
    Ok(())
}

fn parse_program(bytes: &[u8]) -> Result<Vec<BpfInstruction>, CompiledSeccompFilterError> {
    if bytes.len() % SOCK_FILTER_BYTES != 0 {
        return Err(CompiledSeccompFilterError::InvalidRecordShape);
    }
    let count = bytes.len() / SOCK_FILTER_BYTES;
    if count < 4 || count > MAX_BPF_INSTRUCTIONS {
        return Err(CompiledSeccompFilterError::InvalidInstructionCount);
    }
    Ok(bytes
        .chunks_exact(SOCK_FILTER_BYTES)
        .map(BpfInstruction::parse)
        .collect())
}

fn validate_architecture_guard(
    instructions: &[BpfInstruction],
    target: SeccompAuditArchitecture,
) -> Result<(usize, usize), CompiledSeccompFilterError> {
    let load_arch = instructions[0];
    if load_arch.code != BPF_LD_W_ABS
        || load_arch.jt != 0
        || load_arch.jf != 0
        || load_arch.k != SECCOMP_DATA_ARCH_OFFSET
    {
        return Err(CompiledSeccompFilterError::MissingArchitectureLoad);
    }

    let compare = instructions[1];
    if compare.code != BPF_JMP_JEQ_K || compare.k != target.audit_arch() {
        return Err(CompiledSeccompFilterError::MissingArchitectureComparison);
    }
    let match_target = 2usize
        .checked_add(compare.jt as usize)
        .ok_or(CompiledSeccompFilterError::ArchitectureBranchOutOfBounds)?;
    let mismatch_target = 2usize
        .checked_add(compare.jf as usize)
        .ok_or(CompiledSeccompFilterError::ArchitectureBranchOutOfBounds)?;
    let Some(on_match) = instructions.get(match_target) else {
        return Err(CompiledSeccompFilterError::ArchitectureBranchOutOfBounds);
    };
    let Some(on_mismatch) = instructions.get(mismatch_target) else {
        return Err(CompiledSeccompFilterError::ArchitectureBranchOutOfBounds);
    };
    if on_mismatch.code != BPF_RET_K
        || on_mismatch.jt != 0
        || on_mismatch.jf != 0
        || on_mismatch.k != SECCOMP_RET_KILL_PROCESS
    {
        return Err(CompiledSeccompFilterError::ArchitectureMismatchNotFailClosed);
    }
    if on_match.code != BPF_LD_W_ABS
        || on_match.jt != 0
        || on_match.jf != 0
        || on_match.k != SECCOMP_DATA_NR_OFFSET
    {
        return Err(CompiledSeccompFilterError::ArchitectureMatchDoesNotLoadSyscall);
    }
    Ok((match_target, mismatch_target))
}

fn derive_artifact_id(
    target: SeccompAuditArchitecture,
    encoding: SeccompFilterEncoding,
    compiler_id: &ContentId,
    policy_contract_id: &ContentId,
    instruction_count: u16,
    bytes: &[u8],
) -> ContentId {
    ContentId::derive(
        "symthaea.forge-compiled-seccomp-filter-artifact.v1",
        [
            target.tag(),
            target.audit_arch().to_be_bytes().as_slice(),
            encoding.tag(),
            compiler_id.as_str().as_bytes(),
            policy_contract_id.as_str().as_bytes(),
            instruction_count.to_be_bytes().as_slice(),
            (bytes.len() as u64).to_be_bytes().as_slice(),
            bytes,
            b"syscall-policy-semantics-not-established-v1",
        ],
    )
}

fn derive_guard_id(
    artifact_id: &ContentId,
    target: SeccompAuditArchitecture,
    audit_arch: u32,
    compare_index: u16,
    match_target: u16,
    mismatch_target: u16,
) -> ContentId {
    ContentId::derive(
        "symthaea.forge-seccomp-architecture-guard-receipt.v1",
        [
            artifact_id.as_str().as_bytes(),
            target.tag(),
            audit_arch.to_be_bytes().as_slice(),
            compare_index.to_be_bytes().as_slice(),
            match_target.to_be_bytes().as_slice(),
            mismatch_target.to_be_bytes().as_slice(),
            b"architecture-mismatch-kill-process;policy-semantics-not-established-v1",
        ],
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    fn instruction(code: u16, jt: u8, jf: u8, k: u32) -> [u8; 8] {
        let mut out = [0u8; 8];
        out[..2].copy_from_slice(&code.to_le_bytes());
        out[2] = jt;
        out[3] = jf;
        out[4..].copy_from_slice(&k.to_le_bytes());
        out
    }

    fn canonical_program(target: SeccompAuditArchitecture) -> Vec<u8> {
        [
            instruction(BPF_LD_W_ABS, 0, 0, SECCOMP_DATA_ARCH_OFFSET),
            instruction(BPF_JMP_JEQ_K, 1, 0, target.audit_arch()),
            instruction(BPF_RET_K, 0, 0, SECCOMP_RET_KILL_PROCESS),
            instruction(BPF_LD_W_ABS, 0, 0, SECCOMP_DATA_NR_OFFSET),
            instruction(BPF_RET_K, 0, 0, 0x7fff_0000),
        ]
        .into_iter()
        .flatten()
        .collect()
    }

    fn compiler() -> SeccompFilterCompilerIdentity {
        SeccompFilterCompilerIdentity::new(
            ContentId::derive("test-libseccomp", [b"bytes".as_slice()]),
            "libseccomp-test",
        )
        .unwrap()
    }

    #[test]
    fn accepts_fail_closed_architecture_prefix() {
        for target in [
            SeccompAuditArchitecture::X86_64,
            SeccompAuditArchitecture::Aarch64,
            SeccompAuditArchitecture::Riscv64,
        ] {
            let artifact = CompiledSeccompFilterArtifact::freeze(
                target,
                &compiler(),
                ContentId::derive("test-policy", [target.tag()]),
                canonical_program(target),
            )
            .unwrap();
            let guard = SeccompArchitectureGuardReceipt::issue(&artifact, &compiler()).unwrap();
            guard.validate_for(&artifact, &compiler()).unwrap();
        }
    }

    #[test]
    fn rejects_wrong_declared_architecture() {
        let bytes = canonical_program(SeccompAuditArchitecture::X86_64);
        let result = CompiledSeccompFilterArtifact::freeze(
            SeccompAuditArchitecture::Aarch64,
            &compiler(),
            ContentId::derive("test-policy", [b"policy".as_slice()]),
            bytes,
        );
        assert!(matches!(
            result,
            Err(CompiledSeccompFilterError::MissingArchitectureComparison)
        ));
    }

    #[test]
    fn rejects_non_killing_architecture_mismatch() {
        let target = SeccompAuditArchitecture::X86_64;
        let mut bytes = canonical_program(target);
        bytes[2 * SOCK_FILTER_BYTES + 4..2 * SOCK_FILTER_BYTES + 8]
            .copy_from_slice(&0x7fff_0000u32.to_le_bytes());
        let result = CompiledSeccompFilterArtifact::freeze(
            target,
            &compiler(),
            ContentId::derive("test-policy", [b"policy".as_slice()]),
            bytes,
        );
        assert!(matches!(
            result,
            Err(CompiledSeccompFilterError::ArchitectureMismatchNotFailClosed)
        ));
    }

    #[test]
    fn rejects_partial_record_and_empty_program() {
        let target = SeccompAuditArchitecture::X86_64;
        let policy = ContentId::derive("test-policy", [b"policy".as_slice()]);
        assert!(matches!(
            CompiledSeccompFilterArtifact::freeze(target, &compiler(), policy.clone(), vec![0; 9]),
            Err(CompiledSeccompFilterError::InvalidRecordShape)
        ));
        assert!(matches!(
            CompiledSeccompFilterArtifact::freeze(target, &compiler(), policy, Vec::new()),
            Err(CompiledSeccompFilterError::InvalidInstructionCount)
        ));
    }
}
