#!/usr/bin/env ts-node

// Copyright (C) 2024-2026 Tristan Stoltz / Luminous Dynamics
// SPDX-License-Identifier: AGPL-3.0-or-later
// Commercial licensing: see COMMERCIAL_LICENSE.md at repository root
/**
 * Mycelix Knowledge Graph — Claims Seeder
 *
 * Seeds the Claims zome from JSON files in seed-data/claims/.
 * Follows the idempotent pattern from mycelix-commons/scripts/seed-support-knowledge.ts:
 *   - Fetches existing claims for dedup (by content hash → claim ID)
 *   - Skips claims that already exist
 *   - Reports progress with [SEED]/[SKIP]/[ERROR] prefixes
 *
 * Usage:
 *   npx ts-node scripts/seed-claims.ts [conductor-url] [--dry-run] [--file FILE]
 *
 * Arguments:
 *   conductor-url   WebSocket URL of the Holochain conductor
 *                   (default: ws://localhost:8888)
 *   --dry-run       Validate and count claims without submitting
 *   --file FILE     Seed only a specific JSON file (default: all files)
 *
 * Requires:
 *   - Holochain conductor running with mycelix-knowledge hApp installed
 *   - Seed data JSON files generated by the importers
 */

import * as fs from 'fs';
import * as path from 'path';

// SDK imports — ClaimsClient provides type-safe zome calls
import {
  ClaimsClient,
  createKnowledgeClients,
  type Claim,
} from '../../mycelix-workspace/sdk-ts/src/knowledge/index';

// ---------------------------------------------------------------------------
// Configuration
// ---------------------------------------------------------------------------

const CONDUCTOR_URL = (() => {
  for (const arg of process.argv.slice(2)) {
    if (arg.startsWith('ws://') || arg.startsWith('wss://')) return arg;
  }
  return 'ws://localhost:8888';
})();

const DRY_RUN = process.argv.includes('--dry-run');

const SINGLE_FILE = (() => {
  const idx = process.argv.indexOf('--file');
  return idx !== -1 ? process.argv[idx + 1] : null;
})();

const SEED_DATA_DIR = path.resolve(__dirname, '..', 'seed-data', 'claims');
const KNOWLEDGE_ROLE = 'knowledge';
const BATCH_SIZE = 50; // Submit in batches to avoid conductor pressure

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function discoverSeedFiles(): string[] {
  if (SINGLE_FILE) {
    const fullPath = path.isAbsolute(SINGLE_FILE)
      ? SINGLE_FILE
      : path.join(SEED_DATA_DIR, SINGLE_FILE);
    if (!fs.existsSync(fullPath)) {
      console.error(`File not found: ${fullPath}`);
      process.exit(1);
    }
    return [fullPath];
  }

  if (!fs.existsSync(SEED_DATA_DIR)) {
    console.error(`Seed data directory not found: ${SEED_DATA_DIR}`);
    console.error('Run the importers first to generate seed data.');
    process.exit(1);
  }

  return fs
    .readdirSync(SEED_DATA_DIR)
    .filter((f) => f.endsWith('.json') && f !== 'README.md')
    .sort()
    .map((f) => path.join(SEED_DATA_DIR, f));
}

function loadClaimsFile(filepath: string): Claim[] {
  const raw = fs.readFileSync(filepath, 'utf-8');
  const claims: Claim[] = JSON.parse(raw);
  return claims;
}

async function sleep(ms: number): Promise<void> {
  return new Promise((r) => setTimeout(r, ms));
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

async function main() {
  console.log('=== Mycelix Knowledge Graph — Claims Seeder ===');
  console.log(`Conductor URL: ${CONDUCTOR_URL}`);
  console.log(`Seed data dir: ${SEED_DATA_DIR}`);
  if (DRY_RUN) console.log('Mode: DRY RUN (no submissions)');
  console.log();

  // Discover seed files
  const seedFiles = discoverSeedFiles();
  console.log(`Found ${seedFiles.length} seed file(s):`);
  for (const f of seedFiles) {
    console.log(`  ${path.basename(f)}`);
  }
  console.log();

  // Count total claims for progress
  let totalClaims = 0;
  const fileData: Array<{ path: string; claims: Claim[] }> = [];
  for (const f of seedFiles) {
    try {
      const claims = loadClaimsFile(f);
      fileData.push({ path: f, claims });
      totalClaims += claims.length;
      console.log(`  ${path.basename(f)}: ${claims.length} claims`);
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err);
      console.error(`  [ERROR] Failed to load ${path.basename(f)}: ${msg}`);
    }
  }
  console.log(`Total: ${totalClaims} claims to seed`);
  console.log();

  if (DRY_RUN) {
    console.log('=== Dry run complete. No claims were submitted. ===');
    return;
  }

  // Connect to conductor
  console.log('Connecting to Holochain conductor...');
  let claimsClient: ClaimsClient;

  try {
    const clients = await createKnowledgeClients({
      url: CONDUCTOR_URL,
      roleName: KNOWLEDGE_ROLE,
    });
    claimsClient = clients.claims;
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err);
    console.error(`Failed to connect to conductor at ${CONDUCTOR_URL}`);
    console.error(msg);
    console.error();
    console.error('Make sure the Holochain conductor is running and the');
    console.error('mycelix-knowledge hApp is installed.');
    process.exit(1);
  }

  console.log('Connected.');
  console.log();

  // Fetch existing claim IDs for deduplication
  console.log('Fetching existing claims for deduplication...');
  const existingIds = new Set<string>();

  // We can't fetch all claims at once, so we'll rely on the anchor-based
  // get_claim lookup to check each ID. Build the set as we go.
  // For efficiency, try to get claims by tag (if supported), otherwise
  // just submit and let the conductor handle duplicates via ID anchor.

  console.log('(Using ID-based dedup — duplicates will be caught by anchor index)');
  console.log();

  // Seed each file
  let totalSeeded = 0;
  let totalSkipped = 0;
  let totalErrors = 0;

  for (const { path: filePath, claims } of fileData) {
    const filename = path.basename(filePath);
    console.log(`--- ${filename} (${claims.length} claims) ---`);

    for (let i = 0; i < claims.length; i += BATCH_SIZE) {
      const batch = claims.slice(i, i + BATCH_SIZE);

      for (const claim of batch) {
        // Check if we've already seen this ID in this run
        if (existingIds.has(claim.id)) {
          console.log(`  [SKIP] "${claim.content.slice(0, 60)}..." (duplicate ID)`);
          totalSkipped++;
          continue;
        }

        try {
          // Try to get existing claim by ID first
          const existing = await claimsClient.getClaim(claim.id);
          if (existing) {
            console.log(`  [SKIP] "${claim.content.slice(0, 60)}..." (already exists)`);
            existingIds.add(claim.id);
            totalSkipped++;
            continue;
          }
        } catch {
          // getClaim throws if not found — that's expected
        }

        try {
          await claimsClient.submitClaim(claim);
          existingIds.add(claim.id);
          totalSeeded++;

          if (totalSeeded % 100 === 0) {
            console.log(`  [PROGRESS] ${totalSeeded} seeded, ${totalSkipped} skipped, ${totalErrors} errors`);
          }
        } catch (err) {
          const msg = err instanceof Error ? err.message : String(err);
          console.error(`  [ERROR] "${claim.content.slice(0, 60)}...": ${msg}`);
          totalErrors++;
        }
      }

      // Brief pause between batches
      if (i + BATCH_SIZE < claims.length) {
        await sleep(100);
      }
    }

    console.log();
  }

  // Summary
  console.log('=== Summary ===');
  console.log(`  Seeded:  ${totalSeeded}`);
  console.log(`  Skipped: ${totalSkipped} (already existed or duplicate)`);
  console.log(`  Errors:  ${totalErrors}`);
  console.log();

  if (totalErrors > 0) {
    console.log('Some claims failed to seed. Check the errors above.');
    process.exit(1);
  }

  console.log('Done.');
}

main().catch((err) => {
  console.error('Unexpected error:', err);
  process.exit(1);
});
