// SPDX-License-Identifier: AGPL-3.0-or-later
//! Convenience imports for maritime platform adapters.

pub use crate::{
    AuthorityContext, AuthorityLease, BayBoundary, BayBoundaryDecision, BayBoundaryGateContext,
    BayBoundaryRefusal, BayMediumState, BayOccupancy, BayPressureQualification, BoundaryPosition,
    CapabilityViability, ComponentHealth, DependencyGovernance, DependencyState, DockingObservation,
    DockingPhase, FailureObservation, FleetAssuranceReport, FleetMemberReport, HealthSeverity,
    MaintenanceDisposition, MaintenanceRecord, MaintenanceStage, MaritimeBayObservation,
    MaritimeCapability, MaritimeOperatingMode, MaritimePlatformKind, MaritimeResourceEnvelope,
    MaritimeResourceRequest, MaritimeServiceContract, MaritimeServiceKind, MaritimeState,
    NavigationQuality, OperatingEnvelope, OperatingModeContext, OperatingModeDecision,
    OperatingModeRefusal, OperationalLimitAssessment, OperationalLimitStatus, PlatformHealth,
    ProgressiveFailureTrace, ProgressiveFailureViolation, RegenerativeAssumptionChangeSetV1,
    RegenerativeBootstrapReserveAssessmentV1, RegenerativeBootstrapReserveDeficitV1,
    RegenerativeBootstrapReserveError, RegenerativeBootstrapReserveObservationV1,
    RegenerativeBootstrapReservePolicyV1, RegenerativeBootstrapReserveQuantityV1,
    RegenerativeBootstrapReserveRequirementV1, RegenerativeCapability, RegenerativeClosureError,
    RegenerativeClosureModel, RegenerativeClosureReport, RegenerativeDependency,
    RegenerativeDependencyKind, RegenerativeEpochExternalAdmissionQualificationV1,
    RegenerativeEpochHandoffError, RegenerativeEpochHandoffEvidenceV1,
    RegenerativeEpochHandoffQualificationReportV1, RegenerativeEpochTransferQualificationV1,
    RegenerativeFlowKindV1, RegenerativeFlowSupportClaimV1, RegenerativeFlowSupportError,
    RegenerativeFlowSupportV1, RegenerativeGenerationCountV1,
    RegenerativeGenerationPolicyError, RegenerativeGenerationPolicyProjectionV1,
    RegenerativeGenomeError, RegenerativeGenomeRequirementSupportability,
    RegenerativeGenomeRequirementV1, RegenerativeGenomeSupportabilityReport,
    RegenerativeGenomeSupportedError, RegenerativeGenomeSupportedReport,
    RegenerativeGenomeSupportedRequirementReport, RegenerativeGenomeV1, RegenerativeHorizon,
    RegenerativeLineageEvidenceEnvelopeV1, RegenerativeLineageRoleReportV1,
    RegenerativeLineageRoleV1, RegenerativeLineageViabilityError,
    RegenerativeLineageViabilityProfileV1, RegenerativeLineageViabilityReportV1,
    RegenerativePolicyNormalizedLineageError, RegenerativePolicyNormalizedLineageProfileV1,
    RegenerativeRoleAssumptionAssessmentV1, RegenerativeRoleAssumptionScopeError,
    RegenerativeRoleAssumptionScopeV1, RegenerativeSubstitutionError,
    RegenerativeSubstitutionEvidenceV1, RegenerativeSupportedClosureError,
    RegenerativeSupportedClosureReport, RegenerativeSupportedDependencyReport,
    RegenerativeViabilityCalibrationClassV1, RegenerativeViabilityCalibrationError,
    RegenerativeViabilityCalibrationReportV1, RegenerativeViabilityDynamicObservationV1,
    RegenerativeViabilityRoleCalibrationV1, ReleaseDecision, ReleaseGateContext, ReleaseRefusal,
    ResidualUtilitySnapshot, ResourceAllocationProjection, ResourceDecision, ResourceGateContext,
    ResourcePriority, ResourceRefusal, ReturnToServiceDecision, ReturnToServiceGateContext,
    ReturnToServiceRefusal, ServiceGateContext, ServiceStartDecision, ServiceStartRefusal,
    UtilityAvailability, assess_regenerative_bootstrap_reserve,
    assess_regenerative_role_assumption_changes, baseline_envelope,
    calibrate_regenerative_viability_role, calibrate_regenerative_viability_roles,
    derive_regenerative_role_assumption_scopes, evaluate_bay_boundary_open,
    evaluate_genome_supported_closure, evaluate_operating_mode,
    evaluate_policy_normalized_lineage_profile, evaluate_regenerative_lineage_evidence,
    evaluate_regenerative_lineage_viability, evaluate_release, evaluate_resource_request,
    evaluate_return_to_service, evaluate_service_start, evaluate_supported_closure,
    project_regenerative_generation_policy, qualify_regenerative_epoch_handoff,
    validate_regenerative_bootstrap_reserve_policy, validate_regenerative_lineage_successor,
};
