// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Normative Axis (N): Who agrees with the claim
 *
 * From narrowest to broadest agreement:
 * - N0: Personal (self only)
 * - N1: Communal (local DAO)
 * - N2: Network (global consensus)
 * - N3: Axiomatic (constitutional/mathematical)
 */
export type NormativeLevel = "N0Personal" | "N1Communal" | "N2Network" | "N3Axiomatic";
