[package]
name = "enforcement"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]
name = "enforcement"

[dependencies]
getrandom.workspace = true
hdk.workspace = true
serde.workspace = true
serde_json.workspace = true
mycelix_justice_integrity.workspace = true
