// Copyright (C) 2024-2026 Tristan Stoltz / Luminous Dynamics
// SPDX-License-Identifier: AGPL-3.0-or-later
// Commercial licensing: see COMMERCIAL_LICENSE.md at repository root
/**
 * Mycelix Contract Deployment Script
 *
 * Deploys all Mycelix contracts to the specified network.
 * Run with: npx hardhat run scripts/deploy.ts --network <network>
 */

import { ethers, network } from "hardhat";
import { writeFileSync, mkdirSync, existsSync } from "fs";
import { join } from "path";

interface DeploymentInfo {
  network: string;
  chainId: number;
  deployer: string;
  timestamp: string;
  contracts: {
    SoulRegistry: string;
    ProofOfPresence: string;
    PatronageRegistry?: string;
    SporeToken?: string;
    NutrientFlow?: string;
  };
  blockNumbers: {
    SoulRegistry: number;
    ProofOfPresence: number;
    PatronageRegistry?: number;
    SporeToken?: number;
    NutrientFlow?: number;
  };
}

async function main() {
  console.log("\n🍄 Mycelix Contract Deployment\n");
  console.log("═".repeat(50));

  // Get deployer
  const [deployer] = await ethers.getSigners();
  console.log("\n📍 Network: " + network.name);
  console.log("👤 Deployer: " + deployer.address);

  const balance = await ethers.provider.getBalance(deployer.address);
  console.log("💰 Balance: " + ethers.formatEther(balance) + " ETH\n");

  if (balance === 0n) {
    throw new Error("Deployer has no funds!");
  }

  const chainId = (await ethers.provider.getNetwork()).chainId;

  // Base URI for metadata (update for production)
  const baseUri = process.env.METADATA_BASE_URI ||
    "https://api.mycelix.io/metadata/" + chainId + "/";

  const deploymentInfo: DeploymentInfo = {
    network: network.name,
    chainId: Number(chainId),
    deployer: deployer.address,
    timestamp: new Date().toISOString(),
    contracts: {} as any,
    blockNumbers: {} as any,
  };

  // ========================================================================
  // Deploy SoulRegistry
  // ========================================================================

  console.log("📜 Deploying SoulRegistry...");
  const SoulRegistry = await ethers.getContractFactory("SoulRegistry");
  const soulRegistry = await SoulRegistry.deploy();
  await soulRegistry.waitForDeployment();

  const soulRegistryAddress = await soulRegistry.getAddress();
  const soulRegistryReceipt = await soulRegistry.deploymentTransaction()?.wait();

  deploymentInfo.contracts.SoulRegistry = soulRegistryAddress;
  deploymentInfo.blockNumbers.SoulRegistry = soulRegistryReceipt?.blockNumber || 0;

  console.log("   ✅ SoulRegistry: " + soulRegistryAddress);
  console.log("      Block: " + soulRegistryReceipt?.blockNumber);

  // ========================================================================
  // Deploy ProofOfPresence
  // ========================================================================

  console.log("\n📜 Deploying ProofOfPresence...");
  const ProofOfPresence = await ethers.getContractFactory("ProofOfPresence");
  const proofOfPresence = await ProofOfPresence.deploy(baseUri);
  await proofOfPresence.waitForDeployment();

  const proofOfPresenceAddress = await proofOfPresence.getAddress();
  const proofOfPresenceReceipt = await proofOfPresence.deploymentTransaction()?.wait();

  deploymentInfo.contracts.ProofOfPresence = proofOfPresenceAddress;
  deploymentInfo.blockNumbers.ProofOfPresence = proofOfPresenceReceipt?.blockNumber || 0;

  console.log("   ✅ ProofOfPresence: " + proofOfPresenceAddress);
  console.log("      Block: " + proofOfPresenceReceipt?.blockNumber);

  // ========================================================================
  // Grant Roles
  // ========================================================================

  console.log("\n🔑 Setting up roles...");

  // SoulRegistry: Grant RESONANCE_MANAGER_ROLE to ProofOfPresence
  const RESONANCE_MANAGER_ROLE = ethers.keccak256(ethers.toUtf8Bytes("RESONANCE_MANAGER_ROLE"));
  await soulRegistry.grantRole(RESONANCE_MANAGER_ROLE, proofOfPresenceAddress);
  console.log("   ✅ Granted RESONANCE_MANAGER_ROLE to ProofOfPresence");

  // ========================================================================
  // Save Deployment Info
  // ========================================================================

  console.log("\n💾 Saving deployment info...");

  // Save to deployments directory
  const deploymentsDir = join(__dirname, "..", "deployments", network.name);
  if (!existsSync(deploymentsDir)) {
    mkdirSync(deploymentsDir, { recursive: true });
  }

  writeFileSync(
    join(deploymentsDir, "deployment.json"),
    JSON.stringify(deploymentInfo, null, 2)
  );

  // Generate TypeScript constants for frontend
  const frontendConstants = [
    "// Auto-generated by deploy.ts",
    "// Network: " + network.name + " (" + chainId + ")",
    "// Deployed: " + deploymentInfo.timestamp,
    "",
    "export const MYCELIX_CONTRACTS = {",
    "  chainId: " + chainId + ",",
    '  network: "' + network.name + '",',
    "",
    '  SoulRegistry: "' + soulRegistryAddress + '" as const,',
    '  ProofOfPresence: "' + proofOfPresenceAddress + '" as const,',
    "} as const;",
    "",
    "export type MycelixContracts = typeof MYCELIX_CONTRACTS;",
  ].join("\n");

  writeFileSync(
    join(deploymentsDir, "contracts.ts"),
    frontendConstants
  );

  // Also save to apps/web for easy import
  const webContractsDir = join(__dirname, "..", "..", "..", "apps", "web", "src", "contracts");
  if (!existsSync(webContractsDir)) {
    mkdirSync(webContractsDir, { recursive: true });
  }

  writeFileSync(
    join(webContractsDir, network.name + ".ts"),
    frontendConstants
  );

  console.log("   ✅ Saved to deployments/" + network.name + "/");
  console.log("   ✅ Saved to apps/web/src/contracts/" + network.name + ".ts");

  // ========================================================================
  // Summary
  // ========================================================================

  console.log("\n" + "═".repeat(50));
  console.log("🎉 Deployment Complete!\n");
  console.log("Contract Addresses:");
  console.log("  SoulRegistry:      " + soulRegistryAddress);
  console.log("  ProofOfPresence:   " + proofOfPresenceAddress);

  if (network.name !== "hardhat" && network.name !== "localhost") {
    console.log("\n📋 Verification Commands:");
    console.log("  npx hardhat verify --network " + network.name + " " + soulRegistryAddress);
    console.log("  npx hardhat verify --network " + network.name + " " + proofOfPresenceAddress + ' "' + baseUri + '"');
  }

  console.log("\n" + "═".repeat(50) + "\n");

  return deploymentInfo;
}

main()
  .then((info) => {
    console.log("Deployment info:", JSON.stringify(info, null, 2));
    process.exit(0);
  })
  .catch((error) => {
    console.error("Deployment failed:", error);
    process.exit(1);
  });
