[package]
name = "transfer"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "rlib"]
name = "transfer"

[dependencies]
getrandom = { workspace = true }
holochain_serialized_bytes = { workspace = true }
hdk = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
transfer_integrity = { path = "../integrity" }
