//! Structure-aware classical baselines for the HDQF pilot.
//!
//! Exhaustive search supports exact and noisy minimum-Hamming objectives. The
//! meet-in-the-middle implementation is intentionally exact-only: using it on a
//! noisy target returns `NotApplicable` instead of silently changing the task.

use std::collections::BTreeMap;

use crate::classical_hdc::BinaryHypervector;
use crate::errors::{QuantumCompError, Result};
use crate::hdqf_problem::{HdqfProblemInstance, enumerate_indices};

/// Classical baseline algorithm represented by a report.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum HdqfBaselineMethod {
    /// Complete lexicographic enumeration.
    Exhaustive,
    /// Balanced exact XOR meet-in-the-middle.
    MeetInTheMiddleExact,
}

/// Why a baseline did not produce a completed result.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum HdqfBaselineDisposition {
    /// The search completed under its declared budget.
    Completed,
    /// The method does not solve this objective.
    NotApplicable,
    /// A preregistered resource ceiling prevented execution.
    ResourceCensored,
    /// A bounded heuristic completed its budget without finding a solution.
    NonConverged,
}

/// Explicit work ceiling applied before a baseline allocates or enumerates.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct HdqfSearchBudget {
    /// Maximum full candidate products for exhaustive search.
    pub max_candidate_products: usize,
    /// Maximum partial tuples stored by meet-in-the-middle.
    pub max_stored_partial_tuples: usize,
}

impl HdqfSearchBudget {
    /// No practical ceiling. Suitable only for already bounded test fixtures.
    pub const fn unlimited() -> Self {
        Self {
            max_candidate_products: usize::MAX,
            max_stored_partial_tuples: usize::MAX,
        }
    }
}

/// Algorithm-independent logical work counters.
#[derive(Debug, Clone, Copy, Default, PartialEq, Eq)]
pub struct HdqfBaselineMetrics {
    /// Complete products evaluated against the observed target.
    pub candidate_products_evaluated: usize,
    /// Partial products generated by a structure-aware method.
    pub partial_products_generated: usize,
    /// Complement lookups performed.
    pub lookup_operations: usize,
    /// Individual codeword reads.
    pub codebook_accesses: usize,
    /// Packed-word XOR operations.
    pub binding_word_xors: usize,
    /// Packed-word Hamming comparisons.
    pub hamming_word_comparisons: usize,
    /// Partial tuples inserted before collision aggregation.
    pub stored_partial_tuples: usize,
    /// Maximum distinct partial-product map entries.
    pub peak_stored_partial_entries: usize,
    /// Complete candidates conventionally computed and checked.
    pub solution_candidates_verified: usize,
}

/// Result of one classical factorization baseline.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct HdqfBaselineReport {
    /// Algorithm used.
    pub method: HdqfBaselineMethod,
    /// Completion or censoring status.
    pub disposition: HdqfBaselineDisposition,
    /// Stable explanation when not completed.
    pub reason: Option<&'static str>,
    /// Globally minimal Hamming distance when completed.
    pub best_hamming_distance: Option<usize>,
    /// Number of tuples attaining the optimum when known.
    pub optimal_count: Option<usize>,
    /// First optimal tuple in lexicographic order.
    pub returned_indices: Option<Vec<usize>>,
    /// Whether the returned tuple equals the planted tuple.
    pub returned_planted: Option<bool>,
    /// Logical work counters independent of wall-clock timing.
    pub metrics: HdqfBaselineMetrics,
}

impl HdqfBaselineReport {
    fn incomplete(
        method: HdqfBaselineMethod,
        disposition: HdqfBaselineDisposition,
        reason: &'static str,
    ) -> Self {
        Self {
            method,
            disposition,
            reason: Some(reason),
            best_hamming_distance: None,
            optimal_count: None,
            returned_indices: None,
            returned_planted: None,
            metrics: HdqfBaselineMetrics::default(),
        }
    }
}

/// Exhaustively solves exact or minimum-Hamming factorization.
pub fn exhaustive_factorization(
    instance: &HdqfProblemInstance,
    budget: HdqfSearchBudget,
) -> Result<HdqfBaselineReport> {
    validate_instance_shape(instance)?;
    let candidates = candidate_count(instance)?;
    if candidates > budget.max_candidate_products {
        return Ok(HdqfBaselineReport::incomplete(
            HdqfBaselineMethod::Exhaustive,
            HdqfBaselineDisposition::ResourceCensored,
            "candidate-product ceiling exceeded",
        ));
    }

    let words = instance.target.word_len();
    let factors = instance.factor_count();
    let mut metrics = HdqfBaselineMetrics::default();
    let mut best_distance = usize::MAX;
    let mut optimal_count = 0usize;
    let mut returned_indices = None;
    let mut indices = vec![0; factors];

    enumerate_indices(
        instance.codebook_size(),
        0,
        &mut indices,
        &mut |candidate| {
            let product = instance.product_for_indices(candidate)?;
            let distance = product.hamming_distance(&instance.target)?;
            metrics.candidate_products_evaluated += 1;
            metrics.codebook_accesses += factors;
            metrics.binding_word_xors += factors * words;
            metrics.hamming_word_comparisons += words;
            metrics.solution_candidates_verified += 1;

            if distance < best_distance {
                best_distance = distance;
                optimal_count = 1;
                returned_indices = Some(candidate.to_vec());
            } else if distance == best_distance {
                optimal_count += 1;
            }
            Ok(true)
        },
    )?;

    let returned_planted = returned_indices
        .as_ref()
        .map(|indices| indices == &instance.planted_indices);
    Ok(HdqfBaselineReport {
        method: HdqfBaselineMethod::Exhaustive,
        disposition: HdqfBaselineDisposition::Completed,
        reason: None,
        best_hamming_distance: Some(best_distance),
        optimal_count: Some(optimal_count),
        returned_indices,
        returned_planted,
        metrics,
    })
}

#[derive(Debug, Clone)]
struct PartialBucket {
    count: usize,
    first_indices: Vec<usize>,
}

/// Solves exact XOR factorization using a balanced codebook split.
///
/// The smaller, right-hand factor set is stored. For odd `F`, this yields
/// `N^floor(F/2)` stored tuples and `N^ceil(F/2)` complement lookups.
pub fn meet_in_the_middle_exact(
    instance: &HdqfProblemInstance,
    budget: HdqfSearchBudget,
) -> Result<HdqfBaselineReport> {
    validate_instance_shape(instance)?;
    if instance.is_noisy() {
        return Ok(HdqfBaselineReport::incomplete(
            HdqfBaselineMethod::MeetInTheMiddleExact,
            HdqfBaselineDisposition::NotApplicable,
            "exact meet-in-the-middle is not a minimum-distance algorithm",
        ));
    }

    let right_factors = instance.factor_count() / 2;
    let left_factors = instance.factor_count() - right_factors;
    let right_tuples = instance
        .codebook_size()
        .checked_pow(right_factors as u32)
        .ok_or(QuantumCompError::InvalidConfig(
            "meet-in-the-middle partial count overflows usize",
        ))?;
    if right_tuples > budget.max_stored_partial_tuples {
        return Ok(HdqfBaselineReport::incomplete(
            HdqfBaselineMethod::MeetInTheMiddleExact,
            HdqfBaselineDisposition::ResourceCensored,
            "stored-partial ceiling exceeded",
        ));
    }

    let words = instance.target.word_len();
    let mut metrics = HdqfBaselineMetrics::default();
    let mut right_map: BTreeMap<Vec<u64>, PartialBucket> = BTreeMap::new();
    let mut right_indices = vec![0; right_factors];
    enumerate_indices(
        instance.codebook_size(),
        0,
        &mut right_indices,
        &mut |indices| {
            let product = subset_product(instance, left_factors, indices)?;
            metrics.partial_products_generated += 1;
            metrics.codebook_accesses += right_factors;
            metrics.binding_word_xors += right_factors * words;
            metrics.stored_partial_tuples += 1;
            right_map
                .entry(product.words().to_vec())
                .and_modify(|bucket| bucket.count += 1)
                .or_insert_with(|| PartialBucket {
                    count: 1,
                    first_indices: indices.to_vec(),
                });
            Ok(true)
        },
    )?;
    metrics.peak_stored_partial_entries = right_map.len();

    let mut optimal_count = 0usize;
    let mut returned_indices = None;
    let mut left_indices = vec![0; left_factors];
    enumerate_indices(
        instance.codebook_size(),
        0,
        &mut left_indices,
        &mut |indices| {
            let product = subset_product(instance, 0, indices)?;
            let complement = product.bind_xor(&instance.target)?;
            metrics.partial_products_generated += 1;
            metrics.lookup_operations += 1;
            metrics.codebook_accesses += left_factors;
            metrics.binding_word_xors += left_factors * words + words;
            if let Some(bucket) = right_map.get(complement.words()) {
                optimal_count = optimal_count.checked_add(bucket.count).ok_or(
                    QuantumCompError::InvalidConfig("HDQF solution count overflows usize"),
                )?;
                if returned_indices.is_none() {
                    let mut full = indices.to_vec();
                    full.extend_from_slice(&bucket.first_indices);
                    returned_indices = Some(full);
                }
            }
            Ok(true)
        },
    )?;

    let best_hamming_distance = if optimal_count > 0 { Some(0) } else { None };
    if let Some(indices) = &returned_indices {
        let product = instance.product_for_indices(indices)?;
        let distance = product.hamming_distance(&instance.target)?;
        metrics.codebook_accesses += instance.factor_count();
        metrics.binding_word_xors += instance.factor_count() * words;
        metrics.hamming_word_comparisons += words;
        metrics.solution_candidates_verified += 1;
        if distance != 0 {
            return Err(QuantumCompError::InvalidConfig(
                "meet-in-the-middle returned an invalid exact factorization",
            ));
        }
    }

    let returned_planted = returned_indices
        .as_ref()
        .map(|indices| indices == &instance.planted_indices);
    Ok(HdqfBaselineReport {
        method: HdqfBaselineMethod::MeetInTheMiddleExact,
        disposition: HdqfBaselineDisposition::Completed,
        reason: None,
        best_hamming_distance,
        optimal_count: Some(optimal_count),
        returned_indices,
        returned_planted,
        metrics,
    })
}

fn subset_product(
    instance: &HdqfProblemInstance,
    factor_start: usize,
    indices: &[usize],
) -> Result<BinaryHypervector> {
    let mut product = BinaryHypervector::zeros(instance.dimension())?;
    for (offset, &index) in indices.iter().enumerate() {
        let factor = factor_start + offset;
        let codebook = instance
            .codebooks
            .get(factor)
            .ok_or(QuantumCompError::InvalidConfig(
                "partial factor range exceeds codebooks",
            ))?;
        let vector = codebook.get(index).ok_or(QuantumCompError::InvalidConfig(
            "partial factor index exceeds codebook",
        ))?;
        product = product.bind_xor(vector)?;
    }
    Ok(product)
}

fn candidate_count(instance: &HdqfProblemInstance) -> Result<usize> {
    if instance.factor_count() > u32::MAX as usize {
        return Err(QuantumCompError::InvalidConfig(
            "HDQF factor count exceeds exponent representation",
        ));
    }
    instance
        .codebook_size()
        .checked_pow(instance.factor_count() as u32)
        .ok_or(QuantumCompError::InvalidConfig(
            "HDQF candidate count overflows usize",
        ))
}

fn validate_instance_shape(instance: &HdqfProblemInstance) -> Result<()> {
    if instance.factor_count() < 2 || instance.codebook_size() < 2 {
        return Err(QuantumCompError::InvalidConfig(
            "HDQF instance requires at least two nonempty codebooks",
        ));
    }
    let dimension = instance.dimension();
    let size = instance.codebook_size();
    for codebook in &instance.codebooks {
        if codebook.len() != size {
            return Err(QuantumCompError::DimensionMismatch {
                expected: size,
                actual: codebook.len(),
            });
        }
        for vector in codebook {
            if vector.dimension() != dimension {
                return Err(QuantumCompError::DimensionMismatch {
                    expected: dimension,
                    actual: vector.dimension(),
                });
            }
        }
    }
    Ok(())
}
