// Copyright (C) 2024-2026 Tristan Stoltz / Luminous Dynamics
// SPDX-License-Identifier: AGPL-3.0-or-later
// Commercial licensing: see COMMERCIAL_LICENSE.md at repository root
//! Actor Bridge — NixOS State → Symthaea Actor Messages
//!
//! Translates NixOS system state and mind output into a form the main Symthaea
//! actor system can consume. Since symthaea-nix cannot depend on the main
//! symthaea crate (which depends on us), this module defines:
//!
//! - `NixActorState`: a self-contained snapshot of the Nix mind's state
//! - `NixActorMessage`: domain-specific messages the actor system can route
//! - `NixActorBridge`: the bridge that produces these from the Nix mind
//!
//! The main crate's actor system instantiates actors and wires them using these
//! types as the interchange format.

use std::collections::HashMap;
use symthaea_core::hdc::ContinuousHV;

use crate::encoding::NixCodebook;
use crate::mind::{
    ActionCategory, ActionPlan, CausalEdge, EpisodeOutcome, NixActiveInference, SystemEpisode,
};

// =============================================================================
// ACTOR MESSAGE TYPES
// =============================================================================

/// NixOS-specific message types for the actor system.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum NixMessageKind {
    /// System state observation (Sensor → Processor).
    StateObservation,
    /// Action plan generated by active inference (Processor → Decider).
    ActionPlan,
    /// Action outcome feedback (Effector → Memory).
    ActionOutcome,
    /// Causal insight discovered (Processor → Memory).
    CausalInsight,
    /// Free energy alarm (Evaluator → Coordinator).
    SurpriseAlert,
    /// Request for episodic memory recall (Decider → Memory).
    MemoryRecall,
    /// Episodic memory response (Memory → Decider).
    MemoryResponse,
    /// Goal state update from user input (Sensor → Processor).
    GoalUpdate,
}

/// A message produced by the NixOS actor bridge for the main actor system.
#[derive(Debug, Clone)]
pub struct NixActorMessage {
    /// What kind of message this is.
    pub kind: NixMessageKind,
    /// HDC-encoded content vector.
    pub content: ContinuousHV,
    /// Human-readable summary.
    pub summary: String,
    /// Suggested sender role name.
    pub from_role: &'static str,
    /// Suggested receiver role name.
    pub to_role: &'static str,
    /// Priority (higher = process first).
    pub priority: f32,
    /// Arbitrary metadata.
    pub metadata: HashMap<String, String>,
}

// =============================================================================
// ACTOR STATE SNAPSHOT
// =============================================================================

/// Complete snapshot of the Nix mind's state.
#[derive(Debug, Clone)]
pub struct NixActorState {
    /// Current system state vector.
    pub system_state: ContinuousHV,
    /// Current free energy (prediction error from goal).
    pub free_energy: f64,
    /// Current consciousness metrics.
    pub phi: f64,
    /// Confidence in current goal interpretation.
    pub confidence: f64,
    /// Number of episodes in memory.
    pub episode_count: usize,
    /// Number of learned action transitions.
    pub learned_actions: usize,
    /// Total system observations.
    pub total_observations: usize,
    /// Recent failure count.
    pub failure_count: usize,
    /// Whether the prediction hierarchy is surprised.
    pub is_surprised: bool,
}

/// Recommended actor roles for NixOS subsystems.
pub struct NixActorRoles;

impl NixActorRoles {
    pub const SENSOR: &'static str = "nix.sensor";
    pub const PROCESSOR: &'static str = "nix.processor";
    pub const DECIDER: &'static str = "nix.decider";
    pub const EFFECTOR: &'static str = "nix.effector";
    pub const MEMORY: &'static str = "nix.memory";
    pub const EVALUATOR: &'static str = "nix.evaluator";
    pub const COORDINATOR: &'static str = "nix.coordinator";

    /// All role IDs, for batch spawning.
    pub fn all() -> &'static [&'static str] {
        &[
            Self::SENSOR,
            Self::PROCESSOR,
            Self::DECIDER,
            Self::EFFECTOR,
            Self::MEMORY,
            Self::EVALUATOR,
            Self::COORDINATOR,
        ]
    }
}

// =============================================================================
// THE BRIDGE
// =============================================================================

/// Bridge between the NixOS mind and the Symthaea actor system.
pub struct NixActorBridge {
    codebook: NixCodebook,
    surprise_threshold: f64,
}

impl NixActorBridge {
    /// Create a new actor bridge.
    pub fn new() -> Self {
        Self {
            codebook: NixCodebook::new(),
            surprise_threshold: 0.3,
        }
    }

    /// Set the surprise threshold for generating alert messages.
    pub fn with_surprise_threshold(mut self, threshold: f64) -> Self {
        self.surprise_threshold = threshold;
        self
    }

    /// Take a snapshot of the Nix mind's current state.
    pub fn snapshot(&self, engine: &NixActiveInference) -> NixActorState {
        let wm = engine.world_model();
        let hierarchy = wm.prediction_hierarchy();

        NixActorState {
            system_state: wm.system_state().clone(),
            free_energy: wm.free_energy(),
            phi: 0.0,
            confidence: 0.0,
            episode_count: engine.episode_count(),
            learned_actions: wm.learned_action_count(),
            total_observations: wm.total_observations(),
            failure_count: engine.episodic_memory().failure_count(),
            is_surprised: hierarchy.is_surprised(),
        }
    }

    /// Generate actor messages from a system observation.
    pub fn observe_system(&mut self, engine: &mut NixActiveInference) -> Vec<NixActorMessage> {
        let mut messages = Vec::new();

        if let Ok(snapshot) = crate::observe::SystemObserver::snapshot() {
            let mut encoder = crate::encoding::SystemStateEncoder::new(&mut self.codebook);
            let state_hv = encoder.encode_snapshot(&snapshot);

            engine.observe_state(state_hv.clone());

            let mut meta = HashMap::new();
            meta.insert("services".into(), snapshot.services.len().to_string());
            if let Some(r#gen) = snapshot.generation {
                meta.insert("generation".into(), r#gen.to_string());
            }

            messages.push(NixActorMessage {
                kind: NixMessageKind::StateObservation,
                content: state_hv,
                summary: format!(
                    "System snapshot: {} services, r#gen {:?}",
                    snapshot.services.len(),
                    snapshot.generation,
                ),
                from_role: NixActorRoles::SENSOR,
                to_role: NixActorRoles::PROCESSOR,
                priority: 0.5,
                metadata: meta,
            });

            let fe = engine.world_model().free_energy();
            if fe > self.surprise_threshold {
                messages.push(NixActorMessage {
                    kind: NixMessageKind::SurpriseAlert,
                    content: engine.world_model().system_state().clone(),
                    summary: format!("High prediction error: FE={fe:.3}"),
                    from_role: NixActorRoles::EVALUATOR,
                    to_role: NixActorRoles::COORDINATOR,
                    priority: 0.9,
                    metadata: HashMap::new(),
                });
            }
        }

        messages
    }

    /// Generate messages from a user input event.
    pub fn process_input(
        &self,
        engine: &mut NixActiveInference,
        input: &str,
    ) -> (ActionPlan, Vec<NixActorMessage>) {
        let plan = engine.process_input(input);
        let mut messages = Vec::new();

        let goal_hv = engine.goal_inference().current_goal();
        let mut goal_meta = HashMap::new();
        goal_meta.insert("input".into(), input.to_string());
        goal_meta.insert("confidence".into(), format!("{:.3}", plan.goal.confidence));

        messages.push(NixActorMessage {
            kind: NixMessageKind::GoalUpdate,
            content: goal_hv,
            summary: format!(
                "Goal: {} (conf={:.2})",
                plan.goal.description, plan.goal.confidence
            ),
            from_role: NixActorRoles::SENSOR,
            to_role: NixActorRoles::PROCESSOR,
            priority: 0.8,
            metadata: goal_meta,
        });

        if let Some(best) = plan.actions.first() {
            let mut plan_meta = HashMap::new();
            plan_meta.insert("action".into(), format!("{:?}", best.action));
            plan_meta.insert("efe".into(), format!("{:.3}", best.expected_free_energy));
            plan_meta.insert("pragmatic".into(), format!("{:.3}", best.pragmatic_value));
            plan_meta.insert("epistemic".into(), format!("{:.3}", best.epistemic_value));
            plan_meta.insert(
                "needs_clarification".into(),
                plan.needs_clarification.to_string(),
            );

            messages.push(NixActorMessage {
                kind: NixMessageKind::ActionPlan,
                content: engine.world_model().system_state().clone(),
                summary: format!(
                    "Plan: {:?} (EFE={:.3}, {} candidates)",
                    best.action,
                    best.expected_free_energy,
                    plan.actions.len(),
                ),
                from_role: NixActorRoles::PROCESSOR,
                to_role: NixActorRoles::DECIDER,
                priority: 0.7,
                metadata: plan_meta,
            });
        }

        (plan, messages)
    }

    /// Generate a message for an action outcome (success/failure).
    pub fn report_outcome(
        &self,
        engine: &mut NixActiveInference,
        action: &str,
        outcome: EpisodeOutcome,
        state_after: ContinuousHV,
    ) -> Vec<NixActorMessage> {
        let mut messages = Vec::new();

        let valence = match &outcome {
            EpisodeOutcome::Success => 1.0,
            EpisodeOutcome::PartialSuccess(_) => 0.3,
            EpisodeOutcome::Failure(_) => -1.0,
            EpisodeOutcome::RolledBack(_) => -0.5,
        };

        // Learn from the outcome
        let state_before = engine.world_model().system_state().clone();
        let action_cat = ActionCategory::from_command(action);
        engine.learn_from_outcome(
            &state_before,
            action_cat,
            &state_after,
            outcome.clone(),
            0.5,
        );

        // Outcome message: Effector → Memory
        let mut meta = HashMap::new();
        meta.insert("action".into(), action.to_string());
        meta.insert("valence".into(), format!("{valence:.2}"));
        let outcome_str = match &outcome {
            EpisodeOutcome::Success => "success".to_string(),
            EpisodeOutcome::Failure(r) => format!("failure: {r}"),
            EpisodeOutcome::PartialSuccess(r) => format!("partial: {r}"),
            EpisodeOutcome::RolledBack(r) => format!("rollback: {r}"),
        };
        meta.insert("outcome".into(), outcome_str.clone());

        messages.push(NixActorMessage {
            kind: NixMessageKind::ActionOutcome,
            content: state_after,
            summary: format!("Outcome of '{action}': {outcome_str}"),
            from_role: NixActorRoles::EFFECTOR,
            to_role: NixActorRoles::MEMORY,
            priority: 0.6,
            metadata: meta,
        });

        messages
    }

    /// Generate messages from causal discovery.
    pub fn report_causal_edges(&self, edges: &[CausalEdge]) -> Vec<NixActorMessage> {
        if edges.is_empty() {
            return Vec::new();
        }

        let summary = format!(
            "Discovered {} causal edges (strongest: {} → {} @ {:.2})",
            edges.len(),
            edges.first().map(|e| e.from.as_str()).unwrap_or("?"),
            edges.first().map(|e| e.to.as_str()).unwrap_or("?"),
            edges.first().map(|e| e.confidence).unwrap_or(0.0),
        );

        let dim = 128;
        let content = ContinuousHV::random(dim, 42);

        let mut meta = HashMap::new();
        meta.insert("edge_count".into(), edges.len().to_string());
        for (i, edge) in edges.iter().take(10).enumerate() {
            meta.insert(
                format!("edge_{i}"),
                format!("{} → {} ({:.2})", edge.from, edge.to, edge.confidence),
            );
        }

        vec![NixActorMessage {
            kind: NixMessageKind::CausalInsight,
            content,
            summary,
            from_role: NixActorRoles::PROCESSOR,
            to_role: NixActorRoles::MEMORY,
            priority: 0.4,
            metadata: meta,
        }]
    }
}

impl Default for NixActorBridge {
    fn default() -> Self {
        Self::new()
    }
}

// =============================================================================
// HIPPOCAMPUS BRIDGE TRAIT
// =============================================================================

/// Trait for bridging NixOS episodic memory into the main Symthaea hippocampus.
///
/// The main crate implements this trait to wire `NixEpisodicMemory` episodes
/// into the `HippocampusActor`.
pub trait HippocampusBridge: Send + Sync {
    /// Store a NixOS episode as a hippocampal memory trace.
    fn store_episode(&self, episode: &SystemEpisode) -> Result<u64, String>;

    /// Recall episodes similar to a query state.
    fn recall_similar(&self, query: &ContinuousHV, top_k: usize) -> Vec<SystemEpisode>;

    /// Trigger memory consolidation.
    fn consolidate(&self) -> usize;
}

// =============================================================================
// CAUSAL MIND BRIDGE
// =============================================================================

/// Bridge between NixOS causal graph and symthaea-core's CausalMind.
pub struct CausalMindBridge;

impl CausalMindBridge {
    /// Seed a CausalMind with NixOS causal patterns.
    pub fn seed_from_patterns(mind: &mut symthaea_core::hdc::causal_mind::CausalMind) {
        for (cause, effect, _relationship) in
            crate::mind::causal_graph::NixOSCausalPatterns::known_patterns()
        {
            mind.add_causal_link(cause, effect, 0.8);
        }
    }

    /// Sync discovered causal edges into the CausalMind.
    pub fn sync_edges(
        mind: &mut symthaea_core::hdc::causal_mind::CausalMind,
        edges: &[CausalEdge],
    ) {
        for edge in edges {
            mind.add_causal_link(&edge.from, &edge.to, edge.confidence);
        }
    }

    /// Seed a CausalMind with edges derived from NixOS option schemas.
    pub fn seed_from_schemas(
        mind: &mut symthaea_core::hdc::causal_mind::CausalMind,
        schemas: &[crate::parser::option_schema::NixOptionSchema],
    ) {
        // Build a temporary causal graph and bootstrap from schemas
        let mut graph = crate::mind::causal_graph::NixCausalGraph::new(42);
        graph.bootstrap_from_schemas(schemas);
        // The structural edges are in the graph; predict side effects
        // to enumerate them and sync into CausalMind
        for schema in schemas {
            if schema.is_enable_option() {
                let effects = graph.predict_side_effects(&schema.name);
                for effect in effects {
                    mind.add_causal_link(
                        &schema.name,
                        &effect.affected_variable,
                        effect.confidence,
                    );
                }
            }
        }
    }

    /// Query the CausalMind for causal explanations.
    pub fn query_why(
        mind: &symthaea_core::hdc::causal_mind::CausalMind,
        symptom: &str,
    ) -> Vec<(String, f64)> {
        mind.query_why(symptom)
            .into_iter()
            .map(|e| (e.explanation.clone(), e.strength))
            .collect()
    }

    /// Query the CausalMind for predicted effects.
    pub fn query_what_if(
        mind: &symthaea_core::hdc::causal_mind::CausalMind,
        change: &str,
    ) -> Vec<(String, f64)> {
        mind.query_what_if(change)
            .into_iter()
            .map(|p| (p.prediction.clone(), p.probability))
            .collect()
    }
}

// =============================================================================
// TESTS
// =============================================================================

#[cfg(test)]
mod tests {
    use super::*;
    use crate::traits::CausalDirection;

    #[test]
    fn test_actor_roles() {
        let roles = NixActorRoles::all();
        assert_eq!(roles.len(), 7);
        assert!(roles.contains(&"nix.sensor"));
        assert!(roles.contains(&"nix.effector"));
    }

    #[test]
    fn test_bridge_creation() {
        let bridge = NixActorBridge::new();
        assert!((bridge.surprise_threshold - 0.3).abs() < f64::EPSILON);

        let bridge2 = NixActorBridge::new().with_surprise_threshold(0.5);
        assert!((bridge2.surprise_threshold - 0.5).abs() < f64::EPSILON);
    }

    #[test]
    fn test_snapshot() {
        let bridge = NixActorBridge::new();
        let engine = NixActiveInference::new();
        let state = bridge.snapshot(&engine);

        assert_eq!(state.episode_count, 0);
        assert_eq!(state.failure_count, 0);
        assert!(!state.is_surprised);
    }

    #[test]
    fn test_process_input_messages() {
        let bridge = NixActorBridge::new();
        let mut engine = NixActiveInference::new();

        let (plan, messages) = bridge.process_input(&mut engine, "install firefox");
        assert!(
            messages
                .iter()
                .any(|m| m.kind == NixMessageKind::GoalUpdate)
        );
        assert!(!plan.goal.description.is_empty());
    }

    #[test]
    fn test_outcome_messages() {
        let bridge = NixActorBridge::new();
        let mut engine = NixActiveInference::new();
        let dim = engine.world_model().system_state().dim();
        let state_after = ContinuousHV::random(dim, 99);

        let messages = bridge.report_outcome(
            &mut engine,
            "install firefox",
            EpisodeOutcome::Success,
            state_after,
        );

        assert_eq!(messages.len(), 1);
        assert_eq!(messages[0].kind, NixMessageKind::ActionOutcome);
        assert!(messages[0].metadata.get("valence").unwrap().contains("1.0"));
    }

    #[test]
    fn test_causal_edge_messages() {
        let bridge = NixActorBridge::new();
        let edges = vec![CausalEdge {
            from: "services.xserver.enable".into(),
            to: "hardware.nvidia.package".into(),
            direction: CausalDirection::Forward,
            confidence: 0.85,
        }];

        let messages = bridge.report_causal_edges(&edges);
        assert_eq!(messages.len(), 1);
        assert_eq!(messages[0].kind, NixMessageKind::CausalInsight);
    }

    #[test]
    fn test_empty_causal_edges() {
        let bridge = NixActorBridge::new();
        let messages = bridge.report_causal_edges(&[]);
        assert!(messages.is_empty());
    }

    #[test]
    fn test_causal_mind_bridge_seed() {
        let mut mind = symthaea_core::hdc::causal_mind::CausalMind::new();
        CausalMindBridge::seed_from_patterns(&mut mind);
        assert!(mind.link_count() > 0);
    }

    #[test]
    fn test_causal_mind_bridge_sync() {
        let mut mind = symthaea_core::hdc::causal_mind::CausalMind::new();
        let edges = vec![CausalEdge {
            from: "boot.loader.grub.enable".into(),
            to: "boot.loader.systemd-boot.enable".into(),
            direction: CausalDirection::Forward,
            confidence: 0.9,
        }];
        CausalMindBridge::sync_edges(&mut mind, &edges);
        assert!(mind.link_count() > 0);
    }

    #[test]
    fn test_outcome_failure_valence() {
        let bridge = NixActorBridge::new();
        let mut engine = NixActiveInference::new();
        let dim = engine.world_model().system_state().dim();
        let state_after = ContinuousHV::random(dim, 42);

        let messages = bridge.report_outcome(
            &mut engine,
            "install broken-pkg",
            EpisodeOutcome::Failure("build failed".into()),
            state_after,
        );

        assert_eq!(messages.len(), 1);
        assert_eq!(messages[0].kind, NixMessageKind::ActionOutcome);
        assert!(messages[0].metadata["valence"].contains("-1.0"));
        assert!(messages[0].metadata["outcome"].contains("failure"));
    }

    #[test]
    fn test_outcome_partial_success_valence() {
        let bridge = NixActorBridge::new();
        let mut engine = NixActiveInference::new();
        let dim = engine.world_model().system_state().dim();

        let messages = bridge.report_outcome(
            &mut engine,
            "rebuild",
            EpisodeOutcome::PartialSuccess("warnings".into()),
            ContinuousHV::random(dim, 1),
        );

        assert_eq!(messages[0].metadata["valence"], "0.30");
        assert!(messages[0].metadata["outcome"].contains("partial"));
    }

    #[test]
    fn test_outcome_rollback_valence() {
        let bridge = NixActorBridge::new();
        let mut engine = NixActiveInference::new();
        let dim = engine.world_model().system_state().dim();

        let messages = bridge.report_outcome(
            &mut engine,
            "upgrade",
            EpisodeOutcome::RolledBack("reverted".into()),
            ContinuousHV::random(dim, 1),
        );

        assert!(messages[0].metadata["valence"].contains("-0.5"));
        assert!(messages[0].metadata["outcome"].contains("rollback"));
    }

    #[test]
    fn test_causal_edge_metadata_populated() {
        let bridge = NixActorBridge::new();
        let edges = vec![
            CausalEdge {
                from: "a".into(),
                to: "b".into(),
                direction: CausalDirection::Forward,
                confidence: 0.9,
            },
            CausalEdge {
                from: "c".into(),
                to: "d".into(),
                direction: CausalDirection::Forward,
                confidence: 0.5,
            },
        ];

        let messages = bridge.report_causal_edges(&edges);
        assert_eq!(messages.len(), 1);
        assert_eq!(messages[0].metadata["edge_count"], "2");
        assert!(messages[0].metadata.contains_key("edge_0"));
        assert!(messages[0].metadata.contains_key("edge_1"));
        assert!(messages[0].summary.contains("2 causal edges"));
    }

    #[test]
    fn test_process_input_goal_metadata() {
        let bridge = NixActorBridge::new();
        let mut engine = NixActiveInference::new();

        let (_plan, messages) = bridge.process_input(&mut engine, "remove firefox");
        let goal_msg = messages
            .iter()
            .find(|m| m.kind == NixMessageKind::GoalUpdate)
            .expect("Should have GoalUpdate message");

        assert_eq!(goal_msg.metadata["input"], "remove firefox");
        assert!(goal_msg.metadata.contains_key("confidence"));
        assert_eq!(goal_msg.from_role, NixActorRoles::SENSOR);
        assert_eq!(goal_msg.to_role, NixActorRoles::PROCESSOR);
    }

    #[test]
    fn test_process_input_produces_action_plan() {
        let bridge = NixActorBridge::new();
        let mut engine = NixActiveInference::new();

        let (_plan, messages) = bridge.process_input(&mut engine, "install nginx");
        let plan_msg = messages
            .iter()
            .find(|m| m.kind == NixMessageKind::ActionPlan);
        assert!(
            plan_msg.is_some(),
            "Should produce ActionPlan message for actionable input"
        );
        if let Some(pm) = plan_msg {
            assert!(pm.metadata.contains_key("action"));
            assert!(pm.metadata.contains_key("efe"));
            assert!(pm.metadata.contains_key("needs_clarification"));
        }
    }

    #[test]
    fn test_snapshot_after_learning() {
        let bridge = NixActorBridge::new();
        let mut engine = NixActiveInference::new();
        let dim = engine.world_model().system_state().dim();

        // Learn some transitions
        bridge.report_outcome(
            &mut engine,
            "install vim",
            EpisodeOutcome::Success,
            ContinuousHV::random(dim, 1),
        );

        let state = bridge.snapshot(&engine);
        assert_eq!(state.episode_count, 1);
        assert!(state.learned_actions > 0);
    }

    #[test]
    fn test_causal_mind_bridge_query_why() {
        let mut mind = symthaea_core::hdc::causal_mind::CausalMind::new();
        CausalMindBridge::seed_from_patterns(&mut mind);

        let explanations = CausalMindBridge::query_why(&mind, "services.xserver.enable");
        // May or may not find explanations depending on seeded patterns
        for (explanation, strength) in &explanations {
            assert!(!explanation.is_empty());
            assert!(strength.is_finite());
        }
    }

    #[test]
    fn test_causal_mind_bridge_query_what_if() {
        let mut mind = symthaea_core::hdc::causal_mind::CausalMind::new();
        CausalMindBridge::seed_from_patterns(&mut mind);

        let predictions = CausalMindBridge::query_what_if(&mind, "services.nginx.enable");
        for (prediction, prob) in &predictions {
            assert!(!prediction.is_empty());
            assert!(prob.is_finite());
        }
    }
}
