[package]
name = "legal_did"
version = "0.1.0"
edition = "2021"
license = "AGPL-3.0-or-later"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
getrandom_03 = { workspace = true }
holochain_serialized_bytes = { workspace = true }
hdk = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
legal_did_integrity = { path = "../integrity" }
base64 = { workspace = true }
