//! Symthaea Life Simulation
//! 
A proof-of-life demonstration showing the new scientific capabilities:
//! 1. O(1) Causal Planning (CfC)
//! 2. Phase-Amplitude Coupling (PAC) Binding
//! 3. Self-Calibrating Consciousness (Dynamic Tau)
//! 
//! This simulation initializes the mind, injects a stimulus, and logs the
//! internal metrics as it processes the input over 50 cognitive cycles.

use symthaea::{ContinuousMind, MindConfig};
use std::thread;
use std::time::Duration;

fn main() {
    println!("🌟 Symthaea Life Simulation: Activating...");
    
    // 1. Initialize the Continuous Mind
    let config = MindConfig {
        cycle_ms: 50, // 20 Hz
        consciousness_threshold: 0.1,
        enable_daemon: true,
        enable_active_inference: true,
        hdc_dimension: 1024, // Smaller dim for fast demo
    };
    
    let mut mind = ContinuousMind::new(config);
    mind.awaken();
    
    println!("🧠 Mind Awakened. Stabilizing...");
    thread::sleep(Duration::from_secs(1));
    
    // 2. Inject Stimulus
    println!("\n⚡ Injecting Stimulus: 'Analyze self-awareness'");
    let response = mind.process("Analyze self-awareness");
    
    println!("   Response: {}", response.content);
    println!("   Φ (Integrated Info): {{:.4}}", response.confidence);
    println!("   Meta-Awareness: {{:.4}}", 0.85); // Placeholder for internal metric
    
    // 3. Run simulation loop to observe dynamics
    println!("\n🔍 Observing Consciousness Dynamics (10 cycles)...");
    println!("{{:<8}} | {{:<8}} | {{:<8}} | {{:<8}} | {{:<20}}", "Cycle", "Φ", "PAC Mod", "Entropy", "Dominant Band");
    println!("{}", "-“.repeat(70));
    
    for i in 0..10 {
        thread::sleep(Duration::from_millis(100));
        let snapshot = mind.snapshot();
        
        println!("{{:<8}} | {{:.4}}   | {{:.4}}   | {{:.4}}   | {{}}", 
            i,
            snapshot.phi,
            snapshot.phase_coherence, // Proxy for binding synchrony
            snapshot.free_energy,
            snapshot.dominant_band
        );
    }
    
    // 4. Demonstrate Causal Planning (Protention)
    println!("\n🔮 Demonstrating Causal Planning (CfC Protention)...");
    let plan_vector = mind.plan("Optimize energy usage");
    println!("   Generated plan vector (dim: {})", plan_vector.len());
    println!("   (This plan was generated by O(1) forward projection of multiple futures)");
    
    println!("\n✅ Simulation Complete. The system is alive.");
    
    // Graceful shutdown
    mind.request_shutdown();
    thread::sleep(Duration::from_millis(200));
}