#!/bin/bash
# Generate TypeScript types from Rust SDK using ts-rs
#
# Usage: ./scripts/generate-types.sh
#
# This script:
# 1. Builds the SDK with ts-export feature to trigger ts-rs type generation
# 2. Copies generated .ts files to the TypeScript SDK
# 3. Runs TypeScript type checking to validate
#
# Prerequisites:
# - Rust toolchain
# - ts-rs added to types with #[derive(TS)] #[ts(export)]
# - pnpm or npm for TypeScript validation

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SDK_DIR="$(dirname "$SCRIPT_DIR")"
TS_SDK_DIR="$(dirname "$SDK_DIR")/sdk-ts"
BINDINGS_DIR="$SDK_DIR/bindings"
GENERATED_DIR="$TS_SDK_DIR/src/generated"

echo "=== Mycelix Type Generation Pipeline ==="
echo "SDK Directory: $SDK_DIR"
echo "TS SDK Directory: $TS_SDK_DIR"
echo ""

# Step 1: Build with ts-export feature
echo "[1/4] Building Rust SDK with ts-export feature..."
cd "$SDK_DIR"
cargo build --features ts-export --release

# Step 2: Run tests to trigger ts-rs export (ts-rs generates on test run)
echo "[2/4] Running type export tests..."
cargo test export_bindings --features ts-export -- --nocapture 2>/dev/null || true

# Step 3: Copy generated types
echo "[3/4] Copying generated types to TypeScript SDK..."
mkdir -p "$GENERATED_DIR"

if [ -d "$BINDINGS_DIR" ] && [ "$(ls -A "$BINDINGS_DIR" 2>/dev/null)" ]; then
    cp "$BINDINGS_DIR"/*.ts "$GENERATED_DIR/" 2>/dev/null || true
    echo "Copied $(ls -1 "$BINDINGS_DIR"/*.ts 2>/dev/null | wc -l) type files"
else
    echo "No bindings found in $BINDINGS_DIR"
    echo "Make sure Rust types have #[derive(TS)] and #[ts(export)] annotations"
fi

# Step 4: Generate index file
echo "[4/4] Generating index file..."
cat > "$GENERATED_DIR/index.ts" << 'EOF'
/**
 * Auto-generated TypeScript types from Rust SDK
 *
 * DO NOT EDIT MANUALLY - These types are generated by ts-rs from Rust structs
 * Run `pnpm generate-types` to regenerate
 *
 * @generated
 */

// Re-export all generated types
export * from './matl';
export * from './epistemic';
export * from './dkg';
export * from './fl';
export * from './bridge';
export * from './economics';
EOF

echo ""
echo "=== Type Generation Complete ==="
echo ""
echo "Next steps:"
echo "1. Review generated types in $GENERATED_DIR"
echo "2. Run 'pnpm typecheck' in sdk-ts to validate"
echo "3. Import types from '@mycelix/sdk/generated'"
