// Copyright (C) 2024-2026 Tristan Stoltz / Luminous Dynamics
// SPDX-License-Identifier: AGPL-3.0-or-later

//! Mock data for Knowledge cluster — 52 curated claims from plexus-ingest.

use knowledge_leptos_types::*;

/// All 52 curated claims mapped from plexus-ingest/src/curated.rs.
pub fn claims() -> Vec<ClaimView> {
    vec![
        // ── Consciousness (1-4) ──
        ClaimView {
            id: "CLM-001".into(),
            content: "Integrated Information Theory proposes that consciousness corresponds to integrated information called Phi".into(),
            classification: EpistemicClassificationView { empirical: EmpiricalLevel::E3, normative: NormativeLevel::N2, materiality: MaterialityLevel::M2, confidence: 0.80 },
            author: "did:mycelix:curated".into(),
            sources: vec!["Tononi 2004".into()],
            tags: vec!["consciousness".into(), "iit".into()],
            claim_type: ClaimType::Hypothesis,
            created: 1704067200,
            version: 1,
        },
        ClaimView {
            id: "CLM-002".into(),
            content: "The hard problem of consciousness refers to explaining why subjective experience exists".into(),
            classification: EpistemicClassificationView { empirical: EmpiricalLevel::E4, normative: NormativeLevel::N3, materiality: MaterialityLevel::M2, confidence: 0.95 },
            author: "did:mycelix:curated".into(),
            sources: vec!["Chalmers 1995".into()],
            tags: vec!["consciousness".into(), "philosophy".into()],
            claim_type: ClaimType::Hypothesis,
            created: 1704153600,
            version: 1,
        },
        ClaimView {
            id: "CLM-003".into(),
            content: "Global Workspace Theory proposes consciousness arises from information broadcast across brain regions".into(),
            classification: EpistemicClassificationView { empirical: EmpiricalLevel::E3, normative: NormativeLevel::N2, materiality: MaterialityLevel::M2, confidence: 0.80 },
            author: "did:mycelix:curated".into(),
            sources: vec!["Baars 1988".into()],
            tags: vec!["consciousness".into(), "gwt".into()],
            claim_type: ClaimType::Hypothesis,
            created: 1704240000,
            version: 1,
        },
        ClaimView {
            id: "CLM-004".into(),
            content: "Neural correlates of consciousness are the minimal neuronal mechanisms sufficient for any specific conscious experience".into(),
            classification: EpistemicClassificationView { empirical: EmpiricalLevel::E3, normative: NormativeLevel::N2, materiality: MaterialityLevel::M2, confidence: 0.80 },
            author: "did:mycelix:curated".into(),
            sources: vec!["Koch 2004".into()],
            tags: vec!["consciousness".into(), "neuroscience".into()],
            claim_type: ClaimType::Hypothesis,
            created: 1704326400,
            version: 1,
        },

        // ── Programming (5-12) ──
        ClaimView {
            id: "CLM-005".into(),
            content: "Rust is a memory-safe systems programming language that prevents data races at compile time".into(),
            classification: EpistemicClassificationView { empirical: EmpiricalLevel::E4, normative: NormativeLevel::N3, materiality: MaterialityLevel::M2, confidence: 0.95 },
            author: "did:mycelix:curated".into(),
            sources: vec!["rust-lang.org".into()],
            tags: vec!["programming".into(), "rust".into()],
            claim_type: ClaimType::Fact,
            created: 1704412800,
            version: 1,
        },
        ClaimView {
            id: "CLM-006".into(),
            content: "Rust uses an ownership system with borrowing rules instead of garbage collection for memory management".into(),
            classification: EpistemicClassificationView { empirical: EmpiricalLevel::E4, normative: NormativeLevel::N3, materiality: MaterialityLevel::M2, confidence: 0.95 },
            author: "did:mycelix:curated".into(),
            sources: vec!["rust-lang.org".into()],
            tags: vec!["programming".into(), "rust".into()],
            claim_type: ClaimType::Fact,
            created: 1704499200,
            version: 1,
        },
        ClaimView {
            id: "CLM-007".into(),
            content: "WebAssembly is a binary instruction format designed as a portable compilation target for high-level languages".into(),
            classification: EpistemicClassificationView { empirical: EmpiricalLevel::E4, normative: NormativeLevel::N3, materiality: MaterialityLevel::M2, confidence: 0.95 },
            author: "did:mycelix:curated".into(),
            sources: vec!["webassembly.org".into()],
            tags: vec!["programming".into(), "wasm".into()],
            claim_type: ClaimType::Fact,
            created: 1704585600,
            version: 1,
        },
        ClaimView {
            id: "CLM-008".into(),
            content: "Git was created by Linus Torvalds in 2005 for Linux kernel development".into(),
            classification: EpistemicClassificationView { empirical: EmpiricalLevel::E4, normative: NormativeLevel::N3, materiality: MaterialityLevel::M2, confidence: 0.95 },
            author: "did:mycelix:curated".into(),
            sources: vec!["git-scm.com".into()],
            tags: vec!["programming".into(), "git".into()],
            claim_type: ClaimType::Historical,
            created: 1704672000,
            version: 1,
        },
        ClaimView {
            id: "CLM-009".into(),
            content: "JavaScript was created in 10 days by Brendan Eich at Netscape in 1995".into(),
            classification: EpistemicClassificationView { empirical: EmpiricalLevel::E4, normative: NormativeLevel::N3, materiality: MaterialityLevel::M2, confidence: 0.95 },
            author: "did:mycelix:curated".into(),
            sources: vec!["MDN".into()],
            tags: vec!["programming".into(), "javascript".into()],
            claim_type: ClaimType::Historical,
            created: 1704758400,
            version: 1,
        },
        ClaimView {
            id: "CLM-010".into(),
            content: "The first web browser was called WorldWideWeb later renamed Nexus created by Tim Berners-Lee".into(),
            classification: EpistemicClassificationView { empirical: EmpiricalLevel::E4, normative: NormativeLevel::N3, materiality: MaterialityLevel::M2, confidence: 0.95 },
            author: "did:mycelix:curated".into(),
            sources: vec!["CERN".into()],
            tags: vec!["web".into(), "browser".into()],
            claim_type: ClaimType::Historical,
            created: 1704844800,
            version: 1,
        },
        ClaimView {
            id: "CLM-011".into(),
            content: "SQLite is the most widely deployed database engine in the world".into(),
            classification: EpistemicClassificationView { empirical: EmpiricalLevel::E4, normative: NormativeLevel::N3, materiality: MaterialityLevel::M2, confidence: 0.95 },
            author: "did:mycelix:curated".into(),
            sources: vec!["sqlite.org".into()],
            tags: vec!["database".into(), "sqlite".into()],
            claim_type: ClaimType::Fact,
            created: 1704931200,
            version: 1,
        },
        ClaimView {
            id: "CLM-012".into(),
            content: "TCP/IP is the foundational protocol suite of the internet standardized in 1983".into(),
            classification: EpistemicClassificationView { empirical: EmpiricalLevel::E4, normative: NormativeLevel::N3, materiality: MaterialityLevel::M2, confidence: 0.95 },
            author: "did:mycelix:curated".into(),
            sources: vec!["IETF".into()],
            tags: vec!["networking".into(), "internet".into()],
            claim_type: ClaimType::Fact,
            created: 1705017600,
            version: 1,
        },

        // ── Physics (13-18) ──
        ClaimView {
            id: "CLM-013".into(),
            content: "Quantum entanglement allows particles to share states instantaneously regardless of distance".into(),
            classification: EpistemicClassificationView { empirical: EmpiricalLevel::E4, normative: NormativeLevel::N3, materiality: MaterialityLevel::M1, confidence: 0.95 },
            author: "did:mycelix:curated".into(),
            sources: vec!["Physics Review".into()],
            tags: vec!["physics".into(), "quantum".into()],
            claim_type: ClaimType::Fact,
            created: 1705104000,
            version: 1,
        },
        ClaimView {
            id: "CLM-014".into(),
            content: "The speed of light in vacuum is approximately 299792458 meters per second".into(),
            classification: EpistemicClassificationView { empirical: EmpiricalLevel::E4, normative: NormativeLevel::N3, materiality: MaterialityLevel::M1, confidence: 0.95 },
            author: "did:mycelix:curated".into(),
            sources: vec!["NIST".into()],
            tags: vec!["physics".into(), "light".into()],
            claim_type: ClaimType::Fact,
            created: 1705190400,
            version: 1,
        },
        ClaimView {
            id: "CLM-015".into(),
            content: "The Heisenberg uncertainty principle states position and momentum cannot both be precisely measured simultaneously".into(),
            classification: EpistemicClassificationView { empirical: EmpiricalLevel::E4, normative: NormativeLevel::N3, materiality: MaterialityLevel::M1, confidence: 0.95 },
            author: "did:mycelix:curated".into(),
            sources: vec!["Heisenberg 1927".into()],
            tags: vec!["physics".into(), "quantum".into()],
            claim_type: ClaimType::Fact,
            created: 1705276800,
            version: 1,
        },
        ClaimView {
            id: "CLM-016".into(),
            content: "Dark matter constitutes approximately 27 percent of the total mass-energy of the universe".into(),
            classification: EpistemicClassificationView { empirical: EmpiricalLevel::E3, normative: NormativeLevel::N2, materiality: MaterialityLevel::M1, confidence: 0.80 },
            author: "did:mycelix:curated".into(),
            sources: vec!["Planck".into()],
            tags: vec!["physics".into(), "cosmology".into()],
            claim_type: ClaimType::Fact,
            created: 1705363200,
            version: 1,
        },
        ClaimView {
            id: "CLM-017".into(),
            content: "The observable universe has a diameter of approximately 93 billion light-years".into(),
            classification: EpistemicClassificationView { empirical: EmpiricalLevel::E3, normative: NormativeLevel::N2, materiality: MaterialityLevel::M1, confidence: 0.80 },
            author: "did:mycelix:curated".into(),
            sources: vec!["NASA".into()],
            tags: vec!["physics".into(), "cosmology".into()],
            claim_type: ClaimType::Fact,
            created: 1705449600,
            version: 1,
        },
        ClaimView {
            id: "CLM-018".into(),
            content: "General relativity predicts that gravity bends the path of light".into(),
            classification: EpistemicClassificationView { empirical: EmpiricalLevel::E4, normative: NormativeLevel::N3, materiality: MaterialityLevel::M1, confidence: 0.95 },
            author: "did:mycelix:curated".into(),
            sources: vec!["Einstein 1915".into()],
            tags: vec!["physics".into(), "relativity".into()],
            claim_type: ClaimType::Fact,
            created: 1705536000,
            version: 1,
        },

        // ── Biology (19-24) ──
        ClaimView {
            id: "CLM-019".into(),
            content: "DNA consists of two complementary strands forming a double helix structure".into(),
            classification: EpistemicClassificationView { empirical: EmpiricalLevel::E4, normative: NormativeLevel::N3, materiality: MaterialityLevel::M2, confidence: 0.95 },
            author: "did:mycelix:curated".into(),
            sources: vec!["Watson Crick 1953".into()],
            tags: vec!["biology".into(), "genetics".into()],
            claim_type: ClaimType::Fact,
            created: 1705622400,
            version: 1,
        },
        ClaimView {
            id: "CLM-020".into(),
            content: "The human brain contains approximately 86 billion neurons".into(),
            classification: EpistemicClassificationView { empirical: EmpiricalLevel::E4, normative: NormativeLevel::N3, materiality: MaterialityLevel::M2, confidence: 0.95 },
            author: "did:mycelix:curated".into(),
            sources: vec!["Azevedo 2009".into()],
            tags: vec!["biology".into(), "neuroscience".into()],
            claim_type: ClaimType::Fact,
            created: 1705708800,
            version: 1,
        },
        ClaimView {
            id: "CLM-021".into(),
            content: "CRISPR-Cas9 enables precise editing of DNA sequences in living organisms".into(),
            classification: EpistemicClassificationView { empirical: EmpiricalLevel::E4, normative: NormativeLevel::N3, materiality: MaterialityLevel::M2, confidence: 0.95 },
            author: "did:mycelix:curated".into(),
            sources: vec!["Doudna 2012".into()],
            tags: vec!["biology".into(), "genetics".into()],
            claim_type: ClaimType::Fact,
            created: 1705795200,
            version: 1,
        },
        ClaimView {
            id: "CLM-022".into(),
            content: "The human genome contains approximately 3 billion base pairs and 20000 to 25000 protein-coding genes".into(),
            classification: EpistemicClassificationView { empirical: EmpiricalLevel::E4, normative: NormativeLevel::N3, materiality: MaterialityLevel::M2, confidence: 0.95 },
            author: "did:mycelix:curated".into(),
            sources: vec!["Human Genome Project".into()],
            tags: vec!["biology".into(), "genetics".into()],
            claim_type: ClaimType::Fact,
            created: 1705881600,
            version: 1,
        },
        ClaimView {
            id: "CLM-023".into(),
            content: "Photosynthesis converts carbon dioxide and water into glucose and oxygen using sunlight".into(),
            classification: EpistemicClassificationView { empirical: EmpiricalLevel::E4, normative: NormativeLevel::N3, materiality: MaterialityLevel::M2, confidence: 0.95 },
            author: "did:mycelix:curated".into(),
            sources: vec!["Biology".into()],
            tags: vec!["biology".into(), "photosynthesis".into()],
            claim_type: ClaimType::Fact,
            created: 1705968000,
            version: 1,
        },
        ClaimView {
            id: "CLM-024".into(),
            content: "Neurons communicate through electrochemical signals called action potentials".into(),
            classification: EpistemicClassificationView { empirical: EmpiricalLevel::E4, normative: NormativeLevel::N3, materiality: MaterialityLevel::M2, confidence: 0.95 },
            author: "did:mycelix:curated".into(),
            sources: vec!["Neuroscience".into()],
            tags: vec!["biology".into(), "neuroscience".into()],
            claim_type: ClaimType::Fact,
            created: 1706054400,
            version: 1,
        },

        // ── Climate (25-29) ──
        ClaimView {
            id: "CLM-025".into(),
            content: "Ocean acidification is caused by absorption of atmospheric carbon dioxide by seawater lowering pH levels".into(),
            classification: EpistemicClassificationView { empirical: EmpiricalLevel::E4, normative: NormativeLevel::N3, materiality: MaterialityLevel::M3, confidence: 0.95 },
            author: "did:mycelix:curated".into(),
            sources: vec!["NOAA".into()],
            tags: vec!["climate".into(), "ocean".into()],
            claim_type: ClaimType::Fact,
            created: 1706140800,
            version: 1,
        },
        ClaimView {
            id: "CLM-026".into(),
            content: "Global average sea level has risen approximately 8 to 9 inches since 1880".into(),
            classification: EpistemicClassificationView { empirical: EmpiricalLevel::E4, normative: NormativeLevel::N3, materiality: MaterialityLevel::M3, confidence: 0.95 },
            author: "did:mycelix:curated".into(),
            sources: vec!["NASA".into()],
            tags: vec!["climate".into(), "sea-level".into()],
            claim_type: ClaimType::Fact,
            created: 1706227200,
            version: 1,
        },
        ClaimView {
            id: "CLM-027".into(),
            content: "The Arctic sea ice extent has declined approximately 13 percent per decade since 1979".into(),
            classification: EpistemicClassificationView { empirical: EmpiricalLevel::E4, normative: NormativeLevel::N3, materiality: MaterialityLevel::M3, confidence: 0.95 },
            author: "did:mycelix:curated".into(),
            sources: vec!["NASA".into()],
            tags: vec!["climate".into(), "arctic".into()],
            claim_type: ClaimType::Fact,
            created: 1706313600,
            version: 1,
        },
        ClaimView {
            id: "CLM-028".into(),
            content: "Methane is approximately 80 times more potent than CO2 as a greenhouse gas over a 20 year period".into(),
            classification: EpistemicClassificationView { empirical: EmpiricalLevel::E4, normative: NormativeLevel::N3, materiality: MaterialityLevel::M3, confidence: 0.95 },
            author: "did:mycelix:curated".into(),
            sources: vec!["IPCC".into()],
            tags: vec!["climate".into(), "greenhouse".into()],
            claim_type: ClaimType::Fact,
            created: 1706400000,
            version: 1,
        },
        ClaimView {
            id: "CLM-029".into(),
            content: "The ocean absorbs approximately 30 percent of anthropogenic CO2 emissions".into(),
            classification: EpistemicClassificationView { empirical: EmpiricalLevel::E4, normative: NormativeLevel::N3, materiality: MaterialityLevel::M3, confidence: 0.95 },
            author: "did:mycelix:curated".into(),
            sources: vec!["NOAA".into()],
            tags: vec!["climate".into(), "ocean".into()],
            claim_type: ClaimType::Fact,
            created: 1706486400,
            version: 1,
        },

        // ── Geography (30-33) ──
        ClaimView {
            id: "CLM-030".into(),
            content: "The Mariana Trench is the deepest known point in the ocean at approximately 36000 feet".into(),
            classification: EpistemicClassificationView { empirical: EmpiricalLevel::E4, normative: NormativeLevel::N3, materiality: MaterialityLevel::M2, confidence: 0.95 },
            author: "did:mycelix:curated".into(),
            sources: vec!["NOAA".into()],
            tags: vec!["geography".into(), "ocean".into()],
            claim_type: ClaimType::Fact,
            created: 1706572800,
            version: 1,
        },
        ClaimView {
            id: "CLM-031".into(),
            content: "Mount Everest is the highest point on Earth at 8849 meters above sea level".into(),
            classification: EpistemicClassificationView { empirical: EmpiricalLevel::E4, normative: NormativeLevel::N3, materiality: MaterialityLevel::M2, confidence: 0.95 },
            author: "did:mycelix:curated".into(),
            sources: vec!["Nepal Survey".into()],
            tags: vec!["geography".into(), "mountains".into()],
            claim_type: ClaimType::Fact,
            created: 1706659200,
            version: 1,
        },
        ClaimView {
            id: "CLM-032".into(),
            content: "Antarctica contains approximately 70 percent of the worlds fresh water frozen in its ice sheet".into(),
            classification: EpistemicClassificationView { empirical: EmpiricalLevel::E4, normative: NormativeLevel::N3, materiality: MaterialityLevel::M2, confidence: 0.95 },
            author: "did:mycelix:curated".into(),
            sources: vec!["NASA".into()],
            tags: vec!["geography".into(), "antarctica".into()],
            claim_type: ClaimType::Fact,
            created: 1706745600,
            version: 1,
        },
        ClaimView {
            id: "CLM-033".into(),
            content: "The Amazon River carries more water than any other river system on Earth".into(),
            classification: EpistemicClassificationView { empirical: EmpiricalLevel::E4, normative: NormativeLevel::N3, materiality: MaterialityLevel::M2, confidence: 0.95 },
            author: "did:mycelix:curated".into(),
            sources: vec!["USGS".into()],
            tags: vec!["geography".into(), "rivers".into()],
            claim_type: ClaimType::Fact,
            created: 1706832000,
            version: 1,
        },

        // ── Energy (34-35) ──
        ClaimView {
            id: "CLM-034".into(),
            content: "Solar photovoltaic costs have declined approximately 90 percent since 2010".into(),
            classification: EpistemicClassificationView { empirical: EmpiricalLevel::E4, normative: NormativeLevel::N3, materiality: MaterialityLevel::M3, confidence: 0.95 },
            author: "did:mycelix:curated".into(),
            sources: vec!["IRENA".into()],
            tags: vec!["energy".into(), "solar".into()],
            claim_type: ClaimType::Fact,
            created: 1706918400,
            version: 1,
        },
        ClaimView {
            id: "CLM-035".into(),
            content: "Nuclear fission produces energy by splitting heavy atomic nuclei like uranium-235".into(),
            classification: EpistemicClassificationView { empirical: EmpiricalLevel::E4, normative: NormativeLevel::N3, materiality: MaterialityLevel::M3, confidence: 0.95 },
            author: "did:mycelix:curated".into(),
            sources: vec!["Physics".into()],
            tags: vec!["energy".into(), "nuclear".into()],
            claim_type: ClaimType::Fact,
            created: 1707004800,
            version: 1,
        },

        // ── Decentralization (36-40) ──
        ClaimView {
            id: "CLM-036".into(),
            content: "Holochain is a framework for building peer-to-peer applications using agent-centric distributed hash tables".into(),
            classification: EpistemicClassificationView { empirical: EmpiricalLevel::E3, normative: NormativeLevel::N2, materiality: MaterialityLevel::M2, confidence: 0.80 },
            author: "did:mycelix:curated".into(),
            sources: vec!["holochain.org".into()],
            tags: vec!["decentralization".into(), "holochain".into()],
            claim_type: ClaimType::Definition,
            created: 1707091200,
            version: 1,
        },
        ClaimView {
            id: "CLM-037".into(),
            content: "Distributed hash tables enable decentralized key-value storage across a peer-to-peer network".into(),
            classification: EpistemicClassificationView { empirical: EmpiricalLevel::E4, normative: NormativeLevel::N3, materiality: MaterialityLevel::M2, confidence: 0.95 },
            author: "did:mycelix:curated".into(),
            sources: vec!["Computer Science".into()],
            tags: vec!["decentralization".into(), "dht".into()],
            claim_type: ClaimType::Definition,
            created: 1707177600,
            version: 1,
        },
        ClaimView {
            id: "CLM-038".into(),
            content: "Zero-knowledge proofs allow proving knowledge of information without revealing the information itself".into(),
            classification: EpistemicClassificationView { empirical: EmpiricalLevel::E4, normative: NormativeLevel::N3, materiality: MaterialityLevel::M2, confidence: 0.95 },
            author: "did:mycelix:curated".into(),
            sources: vec!["Goldwasser 1985".into()],
            tags: vec!["cryptography".into(), "zkp".into()],
            claim_type: ClaimType::Definition,
            created: 1707264000,
            version: 1,
        },
        ClaimView {
            id: "CLM-039".into(),
            content: "Post-quantum cryptography develops algorithms resistant to quantum computer attacks".into(),
            classification: EpistemicClassificationView { empirical: EmpiricalLevel::E3, normative: NormativeLevel::N2, materiality: MaterialityLevel::M2, confidence: 0.80 },
            author: "did:mycelix:curated".into(),
            sources: vec!["NIST".into()],
            tags: vec!["cryptography".into(), "quantum".into()],
            claim_type: ClaimType::Definition,
            created: 1707350400,
            version: 1,
        },
        ClaimView {
            id: "CLM-040".into(),
            content: "Public key cryptography uses mathematically related key pairs for encryption and digital signatures".into(),
            classification: EpistemicClassificationView { empirical: EmpiricalLevel::E4, normative: NormativeLevel::N3, materiality: MaterialityLevel::M2, confidence: 0.95 },
            author: "did:mycelix:curated".into(),
            sources: vec!["Diffie-Hellman 1976".into()],
            tags: vec!["cryptography".into(), "pki".into()],
            claim_type: ClaimType::Definition,
            created: 1707436800,
            version: 1,
        },

        // ── Mathematics (41-43) ──
        ClaimView {
            id: "CLM-041".into(),
            content: "The Pythagorean theorem states in a right triangle a squared plus b squared equals c squared".into(),
            classification: EpistemicClassificationView { empirical: EmpiricalLevel::E4, normative: NormativeLevel::N3, materiality: MaterialityLevel::M1, confidence: 0.95 },
            author: "did:mycelix:curated".into(),
            sources: vec!["Euclid".into()],
            tags: vec!["mathematics".into(), "geometry".into()],
            claim_type: ClaimType::Fact,
            created: 1707523200,
            version: 1,
        },
        ClaimView {
            id: "CLM-042".into(),
            content: "Euler identity links five fundamental constants e to the power of i times pi plus 1 equals 0".into(),
            classification: EpistemicClassificationView { empirical: EmpiricalLevel::E4, normative: NormativeLevel::N3, materiality: MaterialityLevel::M1, confidence: 0.95 },
            author: "did:mycelix:curated".into(),
            sources: vec!["Euler 1748".into()],
            tags: vec!["mathematics".into(), "constants".into()],
            claim_type: ClaimType::Fact,
            created: 1707609600,
            version: 1,
        },
        ClaimView {
            id: "CLM-043".into(),
            content: "Pi is an irrational number approximately equal to 3.14159265".into(),
            classification: EpistemicClassificationView { empirical: EmpiricalLevel::E4, normative: NormativeLevel::N3, materiality: MaterialityLevel::M1, confidence: 0.95 },
            author: "did:mycelix:curated".into(),
            sources: vec!["Mathematics".into()],
            tags: vec!["mathematics".into(), "constants".into()],
            claim_type: ClaimType::Fact,
            created: 1707696000,
            version: 1,
        },

        // ── Health (44-46) ──
        ClaimView {
            id: "CLM-044".into(),
            content: "Vaccines work by training the immune system to recognize specific pathogens".into(),
            classification: EpistemicClassificationView { empirical: EmpiricalLevel::E4, normative: NormativeLevel::N3, materiality: MaterialityLevel::M2, confidence: 0.95 },
            author: "did:mycelix:curated".into(),
            sources: vec!["WHO".into()],
            tags: vec!["health".into(), "vaccines".into()],
            claim_type: ClaimType::Fact,
            created: 1707782400,
            version: 1,
        },
        ClaimView {
            id: "CLM-045".into(),
            content: "Antibiotics do not work against viral infections".into(),
            classification: EpistemicClassificationView { empirical: EmpiricalLevel::E4, normative: NormativeLevel::N3, materiality: MaterialityLevel::M2, confidence: 0.95 },
            author: "did:mycelix:curated".into(),
            sources: vec!["WHO".into()],
            tags: vec!["health".into(), "antibiotics".into()],
            claim_type: ClaimType::Fact,
            created: 1707868800,
            version: 1,
        },
        ClaimView {
            id: "CLM-046".into(),
            content: "The WHO recommends adults engage in at least 150 minutes of moderate physical activity per week".into(),
            classification: EpistemicClassificationView { empirical: EmpiricalLevel::E4, normative: NormativeLevel::N3, materiality: MaterialityLevel::M2, confidence: 0.95 },
            author: "did:mycelix:curated".into(),
            sources: vec!["WHO".into()],
            tags: vec!["health".into(), "exercise".into()],
            claim_type: ClaimType::Fact,
            created: 1707955200,
            version: 1,
        },

        // ── Ecology (47-49) ──
        ClaimView {
            id: "CLM-047".into(),
            content: "Biodiversity loss is occurring at 100 to 1000 times the natural background extinction rate".into(),
            classification: EpistemicClassificationView { empirical: EmpiricalLevel::E3, normative: NormativeLevel::N2, materiality: MaterialityLevel::M3, confidence: 0.80 },
            author: "did:mycelix:curated".into(),
            sources: vec!["IPBES".into()],
            tags: vec!["ecology".into(), "biodiversity".into()],
            claim_type: ClaimType::Fact,
            created: 1708041600,
            version: 1,
        },
        ClaimView {
            id: "CLM-048".into(),
            content: "Pollinators are responsible for approximately 75 percent of food crop production worldwide".into(),
            classification: EpistemicClassificationView { empirical: EmpiricalLevel::E3, normative: NormativeLevel::N2, materiality: MaterialityLevel::M3, confidence: 0.80 },
            author: "did:mycelix:curated".into(),
            sources: vec!["IPBES".into()],
            tags: vec!["ecology".into(), "pollinators".into()],
            claim_type: ClaimType::Fact,
            created: 1708128000,
            version: 1,
        },
        ClaimView {
            id: "CLM-049".into(),
            content: "Forests cover approximately 31 percent of the global land area".into(),
            classification: EpistemicClassificationView { empirical: EmpiricalLevel::E4, normative: NormativeLevel::N3, materiality: MaterialityLevel::M3, confidence: 0.95 },
            author: "did:mycelix:curated".into(),
            sources: vec!["FAO".into()],
            tags: vec!["ecology".into(), "forests".into()],
            claim_type: ClaimType::Fact,
            created: 1708214400,
            version: 1,
        },

        // ── History (50-52) ──
        ClaimView {
            id: "CLM-050".into(),
            content: "The printing press was invented by Johannes Gutenberg around 1440".into(),
            classification: EpistemicClassificationView { empirical: EmpiricalLevel::E4, normative: NormativeLevel::N3, materiality: MaterialityLevel::M2, confidence: 0.95 },
            author: "did:mycelix:curated".into(),
            sources: vec!["Historical records".into()],
            tags: vec!["history".into(), "technology".into()],
            claim_type: ClaimType::Historical,
            created: 1708300800,
            version: 1,
        },
        ClaimView {
            id: "CLM-051".into(),
            content: "The internet originated from ARPANET first connected in 1969".into(),
            classification: EpistemicClassificationView { empirical: EmpiricalLevel::E4, normative: NormativeLevel::N3, materiality: MaterialityLevel::M2, confidence: 0.95 },
            author: "did:mycelix:curated".into(),
            sources: vec!["DARPA".into()],
            tags: vec!["history".into(), "internet".into()],
            claim_type: ClaimType::Historical,
            created: 1708387200,
            version: 1,
        },
        ClaimView {
            id: "CLM-052".into(),
            content: "The Universal Declaration of Human Rights was adopted by the United Nations in 1948".into(),
            classification: EpistemicClassificationView { empirical: EmpiricalLevel::E4, normative: NormativeLevel::N3, materiality: MaterialityLevel::M2, confidence: 0.95 },
            author: "did:mycelix:curated".into(),
            sources: vec!["UN".into()],
            tags: vec!["history".into(), "rights".into()],
            claim_type: ClaimType::Historical,
            created: 1708473600,
            version: 1,
        },
    ]
}

/// Fact-check results: 15 for E4 claims (True) + 3 for E3 claims (MostlyTrue).
pub fn fact_checks() -> Vec<FactCheckResultView> {
    vec![
        // E4 claims — verdict: True, confidence: 0.95
        FactCheckResultView { id: "FC-001".into(), statement: "Rust prevents data races at compile time".into(), verdict: FactCheckVerdict::True, verdict_confidence: 0.95, credibility_score: 0.96, evidence_count: 12 },
        FactCheckResultView { id: "FC-002".into(), statement: "Speed of light is approximately 299792458 m/s".into(), verdict: FactCheckVerdict::True, verdict_confidence: 0.95, credibility_score: 0.99, evidence_count: 20 },
        FactCheckResultView { id: "FC-003".into(), statement: "DNA forms a double helix structure".into(), verdict: FactCheckVerdict::True, verdict_confidence: 0.95, credibility_score: 0.99, evidence_count: 18 },
        FactCheckResultView { id: "FC-004".into(), statement: "Human brain contains approximately 86 billion neurons".into(), verdict: FactCheckVerdict::True, verdict_confidence: 0.95, credibility_score: 0.93, evidence_count: 8 },
        FactCheckResultView { id: "FC-005".into(), statement: "CRISPR-Cas9 enables precise DNA editing".into(), verdict: FactCheckVerdict::True, verdict_confidence: 0.95, credibility_score: 0.97, evidence_count: 15 },
        FactCheckResultView { id: "FC-006".into(), statement: "Ocean acidification caused by CO2 absorption".into(), verdict: FactCheckVerdict::True, verdict_confidence: 0.95, credibility_score: 0.96, evidence_count: 14 },
        FactCheckResultView { id: "FC-007".into(), statement: "Sea level risen 8-9 inches since 1880".into(), verdict: FactCheckVerdict::True, verdict_confidence: 0.95, credibility_score: 0.94, evidence_count: 11 },
        FactCheckResultView { id: "FC-008".into(), statement: "Arctic ice declining 13% per decade since 1979".into(), verdict: FactCheckVerdict::True, verdict_confidence: 0.95, credibility_score: 0.95, evidence_count: 10 },
        FactCheckResultView { id: "FC-009".into(), statement: "Solar PV costs declined 90% since 2010".into(), verdict: FactCheckVerdict::True, verdict_confidence: 0.95, credibility_score: 0.94, evidence_count: 9 },
        FactCheckResultView { id: "FC-010".into(), statement: "Pythagorean theorem: a^2 + b^2 = c^2".into(), verdict: FactCheckVerdict::True, verdict_confidence: 0.95, credibility_score: 0.99, evidence_count: 25 },
        FactCheckResultView { id: "FC-011".into(), statement: "Vaccines train immune system to recognize pathogens".into(), verdict: FactCheckVerdict::True, verdict_confidence: 0.95, credibility_score: 0.97, evidence_count: 16 },
        FactCheckResultView { id: "FC-012".into(), statement: "Antibiotics do not work against viruses".into(), verdict: FactCheckVerdict::True, verdict_confidence: 0.95, credibility_score: 0.98, evidence_count: 13 },
        FactCheckResultView { id: "FC-013".into(), statement: "Git created by Torvalds in 2005".into(), verdict: FactCheckVerdict::True, verdict_confidence: 0.95, credibility_score: 0.98, evidence_count: 10 },
        FactCheckResultView { id: "FC-014".into(), statement: "Printing press invented by Gutenberg around 1440".into(), verdict: FactCheckVerdict::True, verdict_confidence: 0.95, credibility_score: 0.93, evidence_count: 7 },
        FactCheckResultView { id: "FC-015".into(), statement: "ARPANET first connected in 1969".into(), verdict: FactCheckVerdict::True, verdict_confidence: 0.95, credibility_score: 0.97, evidence_count: 9 },

        // E3 claims — verdict: MostlyTrue, confidence: 0.80
        FactCheckResultView { id: "FC-016".into(), statement: "IIT: consciousness corresponds to integrated information Phi".into(), verdict: FactCheckVerdict::MostlyTrue, verdict_confidence: 0.80, credibility_score: 0.74, evidence_count: 6 },
        FactCheckResultView { id: "FC-017".into(), statement: "Dark matter is ~27% of mass-energy of universe".into(), verdict: FactCheckVerdict::MostlyTrue, verdict_confidence: 0.80, credibility_score: 0.78, evidence_count: 8 },
        FactCheckResultView { id: "FC-018".into(), statement: "Biodiversity loss 100-1000x background extinction rate".into(), verdict: FactCheckVerdict::MostlyTrue, verdict_confidence: 0.80, credibility_score: 0.76, evidence_count: 5 },
    ]
}

/// Inferences drawn from the curated claim graph.
pub fn inferences() -> Vec<InferenceView> {
    vec![
        InferenceView {
            id: "INF-001".into(),
            inference_type: InferenceType::Pattern,
            source_claims: vec!["CLM-025".into(), "CLM-026".into(), "CLM-027".into(), "CLM-028".into(), "CLM-029".into()],
            conclusion: "Climate change evidence converging from multiple independent data sources".into(),
            confidence: 0.92,
            reasoning: "Ocean acidification, sea level rise, Arctic ice decline, methane potency, and CO2 absorption data all independently confirm accelerating climate disruption".into(),
            verified: true,
        },
        InferenceView {
            id: "INF-002".into(),
            inference_type: InferenceType::Similarity,
            source_claims: vec!["CLM-001".into(), "CLM-013".into()],
            conclusion: "Quantum mechanics and consciousness share information integration properties".into(),
            confidence: 0.55,
            reasoning: "IIT's integrated information and quantum entanglement both describe non-decomposable information states across subsystems".into(),
            verified: false,
        },
        InferenceView {
            id: "INF-003".into(),
            inference_type: InferenceType::Synthesis,
            source_claims: vec!["CLM-036".into(), "CLM-037".into(), "CLM-038".into(), "CLM-040".into()],
            conclusion: "Decentralized knowledge infrastructure requires convergence of DHTs, ZKPs, and public-key cryptography".into(),
            confidence: 0.82,
            reasoning: "Agent-centric DHTs (Holochain) provide storage, ZKPs enable privacy-preserving verification, and PKI anchors identity — together forming a complete decentralized knowledge stack".into(),
            verified: true,
        },
        InferenceView {
            id: "INF-004".into(),
            inference_type: InferenceType::Pattern,
            source_claims: vec!["CLM-019".into(), "CLM-021".into(), "CLM-022".into()],
            conclusion: "Genomic sciences accelerating from structural understanding to precise engineering".into(),
            confidence: 0.88,
            reasoning: "The progression from DNA structure discovery to genome sequencing to CRISPR editing shows a clear trajectory of increasing capability in genetic engineering".into(),
            verified: true,
        },
    ]
}

/// Graph statistics for the 52-claim knowledge graph.
pub fn graph_stats() -> GraphStatsView {
    GraphStatsView { relationship_count: 156 }
}
