-- Auto-generated by symthaea-lean-bridge::fol_ext_bridge
-- SMT fragment: LRA
-- Mathlib tactic: linarith
-- Requires `import Mathlib.Tactic` + a Lake project with Mathlib resolved.
-- See lean-proofs/phase2/README.md for setup.

import Mathlib.Tactic

theorem pos_implies_nonneg : (∀ x : ℝ, (((0) < x) → ((0) ≤ x))) := by
  try intros
  first
    | (rfl; done)
    | (norm_num; done)
    | (ring; done)
    | (omega; done)
    | (linarith; done)
    | (nlinarith [sq_nonneg _, sq_nonneg (_ - _), sq_nonneg (_ + _), mul_self_nonneg _]; done)
    | (positivity; done)
    | (rcases lt_trichotomy _ _ with h | h | h <;> tauto; done)
    | (rcases le_total _ _ with h | h <;> first | linarith | tauto; done)
    | (tauto; done)
    | (polyrith; done)
