-- Auto-generated by symthaea-lean-bridge::fol_ext_bridge
-- SMT fragment: LRA
-- Mathlib tactic: linarith
-- Requires `import Mathlib.Tactic` + a Lake project with Mathlib resolved.
-- See lean-proofs/phase2/README.md for setup.

import Mathlib.Tactic

theorem pos_implies_nonneg : (∀ x : ℝ, (((0) < x) → ((0) ≤ x))) := by
  linarith
