-- Auto-generated by symthaea-lean-bridge::fol_ext_bridge
-- SMT fragment: LIA
-- Mathlib tactic: omega
-- Requires `import Mathlib.Tactic` + a Lake project with Mathlib resolved.
-- See lean-proofs/phase2/README.md for setup.

import Mathlib.Tactic

theorem refl_int : (∀ n : ℤ, (n = n)) := by
  omega
