-- Auto-generated by symthaea-lean-bridge::fol_ext_bridge
-- SMT fragment: NRA
-- Mathlib tactic: nlinarith
-- Requires `import Mathlib.Tactic` + a Lake project with Mathlib resolved.
-- See lean-proofs/phase2/README.md for setup.

import Mathlib.Tactic

theorem sum_of_squares_nonneg : (∀ a : ℝ, (∀ b : ℝ, ((0) ≤ ((a ^ 2) + (b ^ 2))))) := by
  nlinarith
