-- Auto-generated by symthaea-lean-bridge::fol_ext_bridge
-- SMT fragment: QF_LRA
-- Mathlib tactic: linarith
-- Requires `import Mathlib.Tactic` + a Lake project with Mathlib resolved.
-- See lean-proofs/phase2/README.md for setup.

import Mathlib.Tactic

theorem three_times_third_eq_one : (((3) * ((1 : ℝ) / (3 : ℝ))) = (1)) := by
  linarith
