-- Auto-generated by symthaea-lean-bridge::fol_ext_bridge
-- SMT fragment: LRA
-- Mathlib tactic: linarith
-- Requires `import Mathlib.Tactic` + a Lake project with Mathlib resolved.
-- See lean-proofs/phase2/README.md for setup.

import Mathlib.Tactic

theorem trichotomy_real : (∀ x : ℝ, (∀ y : ℝ, (((x = y) ∨ (x < y)) ∨ (y < x)))) := by
  linarith
