-- Auto-generated by symthaea-lean-bridge::fol_ext_bridge
-- SMT fragment: LRA
-- Mathlib tactic: linarith
-- Requires `import Mathlib.Tactic` + a Lake project with Mathlib resolved.
-- See lean-proofs/phase2/README.md for setup.

import Mathlib.Tactic

theorem trichotomy_real : (∀ x : ℝ, (∀ y : ℝ, (((x = y) ∨ (x < y)) ∨ (y < x)))) := by
  intro x y
  try intros
  first
    | (rfl; done)
    | (norm_num; done)
    | (ring; done)
    | (omega; done)
    | (linarith; done)
    | (nlinarith [sq_nonneg x, mul_self_nonneg x, sq_nonneg (x - 1), sq_nonneg (x + 1), sq_nonneg y, mul_self_nonneg y, sq_nonneg (y - 1), sq_nonneg (y + 1), sq_nonneg (x - y), sq_nonneg (x + y)]; done)
    | (positivity; done)
    | (rcases lt_trichotomy x y with h | h | h <;> tauto; done)
    | (rcases le_total _ _ with h | h <;> first | linarith | tauto; done)
    | (tauto; done)
    | (polyrith; done)
