// Copyright (C) 2024-2026 Tristan Stoltz / Luminous Dynamics
// SPDX-License-Identifier: AGPL-3.0-or-later
// Commercial licensing: see COMMERCIAL_LICENSE.md at repository root
//! Vorbis/OGG encoding and decoding

use crate::{CodecError, Decoder, Encoder, EncoderConfig, Result};
use bytes::Bytes;

/// Vorbis encoder
pub struct VorbisEncoder {
    config: EncoderConfig,
    sample_buffer: Vec<f32>,
    frame_size: usize,
    granule_position: u64,
    sequence_number: u32,
    // In production, this would hold vorbis_info, vorbis_dsp_state, etc.
}

impl VorbisEncoder {
    pub fn new(config: EncoderConfig) -> Result<Self> {
        if config.channels > 255 {
            return Err(CodecError::InvalidChannels(config.channels));
        }

        let valid_rates = [8000, 11025, 16000, 22050, 32000, 44100, 48000];
        if !valid_rates.contains(&config.sample_rate) {
            return Err(CodecError::InvalidSampleRate(config.sample_rate));
        }

        // Vorbis typically uses 4096 sample blocks
        let frame_size = 4096 * config.channels as usize;

        Ok(Self {
            config,
            sample_buffer: Vec::with_capacity(frame_size * 2),
            frame_size,
            granule_position: 0,
            sequence_number: 0,
        })
    }

    /// Create OGG page header
    fn create_ogg_page(&mut self, data: &[u8], is_header: bool, is_eos: bool) -> Vec<u8> {
        let mut page = Vec::with_capacity(data.len() + 27 + 255);

        // OGG capture pattern
        page.extend_from_slice(b"OggS");

        // Stream structure version
        page.push(0);

        // Header type flag
        let mut flags = 0u8;
        if self.sequence_number == 0 {
            flags |= 0x02; // BOS (beginning of stream)
        }
        if is_eos {
            flags |= 0x04; // EOS (end of stream)
        }
        page.push(flags);

        // Granule position (8 bytes, little-endian)
        let granule = if is_header { 0 } else { self.granule_position };
        page.extend_from_slice(&granule.to_le_bytes());

        // Bitstream serial number (4 bytes)
        page.extend_from_slice(&0x12345678u32.to_le_bytes());

        // Page sequence number (4 bytes)
        page.extend_from_slice(&self.sequence_number.to_le_bytes());
        self.sequence_number += 1;

        // CRC checksum placeholder (4 bytes) - would be calculated in production
        page.extend_from_slice(&[0u8; 4]);

        // Number of segments
        let segments = (data.len() + 254) / 255;
        page.push(segments as u8);

        // Segment table
        let mut remaining = data.len();
        for _ in 0..segments {
            let segment_size = remaining.min(255);
            page.push(segment_size as u8);
            remaining -= segment_size;
        }

        // Segment data
        page.extend_from_slice(data);

        page
    }

    fn create_vorbis_headers(&mut self) -> Vec<u8> {
        let mut output = Vec::new();

        // Identification header
        let mut id_header = Vec::new();
        id_header.push(1); // Packet type: identification
        id_header.extend_from_slice(b"vorbis");
        id_header.extend_from_slice(&0u32.to_le_bytes()); // Version
        id_header.push(self.config.channels);
        id_header.extend_from_slice(&self.config.sample_rate.to_le_bytes());
        id_header.extend_from_slice(&0i32.to_le_bytes()); // Bitrate maximum
        id_header
            .extend_from_slice(&(self.config.effective_bitrate() as i32 * 1000).to_le_bytes());
        id_header.extend_from_slice(&0i32.to_le_bytes()); // Bitrate minimum
        id_header.push(0xB8); // Block sizes
        id_header.push(1); // Framing flag

        output.extend(self.create_ogg_page(&id_header, true, false));

        // Comment header (simplified)
        let mut comment_header = Vec::new();
        comment_header.push(3); // Packet type: comment
        comment_header.extend_from_slice(b"vorbis");
        comment_header.extend_from_slice(&7u32.to_le_bytes()); // Vendor length
        comment_header.extend_from_slice(b"mycelix");
        comment_header.extend_from_slice(&0u32.to_le_bytes()); // Comment count
        comment_header.push(1); // Framing flag

        // Setup header (placeholder - would be generated by libvorbis)
        let mut setup_header = Vec::new();
        setup_header.push(5); // Packet type: setup
        setup_header.extend_from_slice(b"vorbis");
        // In production, this would contain codebooks and floor/residue configs
        setup_header.resize(256, 0);
        setup_header.push(1); // Framing flag

        // Combine comment and setup on same page
        let mut headers = comment_header;
        headers.extend(setup_header);
        output.extend(self.create_ogg_page(&headers, true, false));

        output
    }

    fn encode_audio_packet(&mut self, samples: &[f32]) -> Vec<u8> {
        // In production, this would:
        // 1. Apply MDCT
        // 2. Floor curve fitting
        // 3. Residue encoding
        // 4. Entropy coding

        // Update granule position
        self.granule_position += (samples.len() / self.config.channels as usize) as u64;

        // Estimate packet size based on bitrate
        let duration_s =
            samples.len() as f64 / self.config.channels as f64 / self.config.sample_rate as f64;
        let packet_size = (self.config.effective_bitrate() as f64 * duration_s * 1000.0 / 8.0) as usize;

        // Create audio packet placeholder
        let mut packet = vec![0u8; packet_size.max(32)];

        // Audio packet type (0 for audio data)
        packet[0] = 0;

        packet
    }
}

impl Encoder for VorbisEncoder {
    fn encode(&mut self, samples: &[f32]) -> Result<Bytes> {
        let mut output = Vec::new();

        // Output headers on first call
        if self.sequence_number == 0 {
            output.extend(self.create_vorbis_headers());
        }

        self.sample_buffer.extend_from_slice(samples);

        while self.sample_buffer.len() >= self.frame_size {
            let frame: Vec<f32> = self.sample_buffer.drain(..self.frame_size).collect();
            let packet = self.encode_audio_packet(&frame);
            output.extend(self.create_ogg_page(&packet, false, false));
        }

        Ok(Bytes::from(output))
    }

    fn flush(&mut self) -> Result<Bytes> {
        let mut output = Vec::new();

        if !self.sample_buffer.is_empty() {
            // Pad and encode remaining samples
            self.sample_buffer.resize(self.frame_size, 0.0);
            let buffer_copy = self.sample_buffer.clone();
            let packet = self.encode_audio_packet(&buffer_copy);
            output.extend(self.create_ogg_page(&packet, false, true));
            self.sample_buffer.clear();
        } else {
            // Empty EOS page
            output.extend(self.create_ogg_page(&[], false, true));
        }

        Ok(Bytes::from(output))
    }

    fn config(&self) -> &EncoderConfig {
        &self.config
    }
}

/// Vorbis decoder using lewton
pub struct VorbisDecoder {
    sample_rate: u32,
    channels: u8,
    finished: bool,
    headers_parsed: bool,
    // In production, would hold OggStreamReader
}

impl VorbisDecoder {
    pub fn new() -> Result<Self> {
        Ok(Self {
            sample_rate: 44100,
            channels: 2,
            finished: false,
            headers_parsed: false,
        })
    }

    fn parse_ogg_page(&mut self, data: &[u8]) -> Option<(Vec<u8>, bool)> {
        if data.len() < 27 || &data[0..4] != b"OggS" {
            return None;
        }

        let flags = data[5];
        let is_eos = (flags & 0x04) != 0;

        let num_segments = data[26] as usize;
        if data.len() < 27 + num_segments {
            return None;
        }

        let segment_table = &data[27..27 + num_segments];
        let data_start = 27 + num_segments;

        let data_len: usize = segment_table.iter().map(|&s| s as usize).sum();
        if data.len() < data_start + data_len {
            return None;
        }

        let packet_data = data[data_start..data_start + data_len].to_vec();
        Some((packet_data, is_eos))
    }

    fn parse_identification_header(&mut self, data: &[u8]) -> bool {
        if data.len() < 30 || data[0] != 1 || &data[1..7] != b"vorbis" {
            return false;
        }

        self.channels = data[11];

        let sr_bytes: [u8; 4] = data[12..16].try_into().unwrap_or([0; 4]);
        self.sample_rate = u32::from_le_bytes(sr_bytes);

        true
    }
}

impl Decoder for VorbisDecoder {
    fn decode(&mut self, data: &[u8]) -> Result<Vec<f32>> {
        if data.is_empty() {
            self.finished = true;
            return Ok(Vec::new());
        }

        // Parse OGG container
        let (packet_data, is_eos) = match self.parse_ogg_page(data) {
            Some(p) => p,
            None => return Err(CodecError::DecodingError("Invalid OGG page".to_string())),
        };

        if is_eos {
            self.finished = true;
        }

        // Parse headers if not done yet
        if !self.headers_parsed && !packet_data.is_empty() {
            if packet_data[0] == 1 {
                self.parse_identification_header(&packet_data);
                return Ok(Vec::new()); // Headers don't produce audio
            } else if packet_data[0] == 3 || packet_data[0] == 5 {
                // Comment or setup header
                if packet_data[0] == 5 {
                    self.headers_parsed = true;
                }
                return Ok(Vec::new());
            }
        }

        // Decode audio packet
        // In production, this would use lewton to decode
        // Estimate output samples
        let estimated_samples = 4096 * self.channels as usize;
        Ok(vec![0.0f32; estimated_samples])
    }

    fn sample_rate(&self) -> u32 {
        self.sample_rate
    }

    fn channels(&self) -> u8 {
        self.channels
    }

    fn is_finished(&self) -> bool {
        self.finished
    }
}

impl Default for VorbisDecoder {
    fn default() -> Self {
        Self::new().unwrap()
    }
}

/// OGG stream muxer for multiple Vorbis streams
pub struct OggMuxer {
    streams: Vec<OggStream>,
}

struct OggStream {
    serial: u32,
    granule: u64,
    sequence: u32,
}

impl OggMuxer {
    pub fn new() -> Self {
        Self {
            streams: Vec::new(),
        }
    }

    pub fn add_stream(&mut self) -> u32 {
        let serial = self.streams.len() as u32 + 1;
        self.streams.push(OggStream {
            serial,
            granule: 0,
            sequence: 0,
        });
        serial
    }

    pub fn write_packet(&mut self, _stream_id: u32, _data: &[u8], _granule: u64) -> Vec<u8> {
        // In production, would create proper OGG page with CRC
        Vec::new()
    }
}

impl Default for OggMuxer {
    fn default() -> Self {
        Self::new()
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::QualityPreset;

    #[test]
    fn test_vorbis_encoder_creation() {
        let config = EncoderConfig::vorbis(QualityPreset::High);
        let encoder = VorbisEncoder::new(config);
        assert!(encoder.is_ok());
    }

    #[test]
    fn test_vorbis_decoder_creation() {
        let decoder = VorbisDecoder::new();
        assert!(decoder.is_ok());
    }

    #[test]
    fn test_ogg_muxer() {
        let mut muxer = OggMuxer::new();
        let stream = muxer.add_stream();
        assert_eq!(stream, 1);
    }
}
