// Copyright (C) 2024-2026 Tristan Stoltz / Luminous Dynamics
// SPDX-License-Identifier: AGPL-3.0-or-later
// Commercial licensing: see COMMERCIAL_LICENSE.md at repository root
//! Holographic Scorer - HDC-based Language Model
//!
//! This module implements the "infinite n-gram" using Hyperdimensional Computing.
//! Instead of storing massive lookup tables for n-gram probabilities, we use:
//!
//! 1. **Phoneme Basis**: Random hypervectors for each phoneme (quasi-orthogonal)
//! 2. **Context State**: Rolling history encoded via permutation binding
//! 3. **Grammar Memory**: Superposition of valid sequences (learned from corpus)
//!
//! The key insight: HDC compresses sequence information into a fixed-size vector
//! using permutation: H_t = Π(H_{t-1}) ⊕ Φ_current
//!
//! This allows "soft matching" - similar sequences have similar resonance scores,
//! unlike traditional n-grams which return 0 for unseen sequences.

use crate::hdc::{HDC_DIM, HDC_WORDS, HV16, bundle};
use std::collections::HashMap;
use std::fs::File;
use std::io::{BufReader, Read};
use std::path::Path;

/// Phoneme identifier
pub type Phoneme = String;

/// The Holographic Scorer implements an HDC-based language model
/// that can capture arbitrarily long sequence dependencies.
pub struct HolographicScorer {
    /// Random hypervectors for each phoneme (static basis)
    phoneme_basis: HashMap<Phoneme, HV16>,

    /// Grammar memory: superposition of valid transitions
    /// This is learned from a corpus and represents "what sounds right"
    grammar_memory: HV16,

    /// Current context state: rolling history of the hypothesis
    context_state: HV16,

    /// Fast 3-gram phonotactic constraints (local system)
    /// Maps (prev2, prev1) -> set of valid next phonemes
    trigram_constraints: HashMap<(Phoneme, Phoneme), Vec<Phoneme>>,

    /// Weight for HDC score vs trigram score
    hdc_weight: f32,

    /// History depth for context (how many permutations to apply)
    #[allow(dead_code)]
    history_depth: usize,
}

impl HolographicScorer {
    /// Create a new Holographic Scorer with random phoneme basis
    pub fn new() -> Self {
        let mut phoneme_basis = HashMap::new();

        // Generate random basis vectors for all phonemes using string seeds
        let phonemes = [
            "AA", "AE", "AH", "AO", "AW", "AY", "B", "CH", "D", "DH", "EH", "ER", "EY", "F", "G",
            "HH", "IH", "IY", "JH", "K", "L", "M", "N", "NG", "OW", "OY", "P", "R", "S", "SH", "T",
            "TH", "UH", "UW", "V", "W", "Y", "Z", "ZH", "SIL", "UNK",
        ];

        for phoneme in phonemes.iter() {
            // Use phoneme name as seed for deterministic basis vectors
            let seed = format!("phoneme_basis_{phoneme}");
            let hv = HV16::random(&seed);
            phoneme_basis.insert(phoneme.to_string(), hv);
        }

        Self {
            phoneme_basis,
            grammar_memory: HV16::random("grammar_memory_init"),
            context_state: HV16::zero(),
            trigram_constraints: HashMap::new(),
            hdc_weight: 0.7,
            history_depth: 10,
        }
    }

    /// Load phoneme basis from binary file (generated by train_omni.py)
    pub fn load_basis(path: &Path) -> std::io::Result<HashMap<Phoneme, HV16>> {
        let file = File::open(path)?;
        let mut reader = BufReader::new(file);

        // Read header
        let mut buf4 = [0u8; 4];
        reader.read_exact(&mut buf4)?;
        let dim = u32::from_le_bytes(buf4) as usize;
        reader.read_exact(&mut buf4)?;
        let count = u32::from_le_bytes(buf4) as usize;

        if dim != HDC_DIM {
            return Err(std::io::Error::new(
                std::io::ErrorKind::InvalidData,
                format!("Dimension mismatch: file has {dim}, expected {HDC_DIM}"),
            ));
        }

        let mut basis = HashMap::new();

        for _ in 0..count {
            // Read phoneme name
            reader.read_exact(&mut buf4)?;
            let name_len = u32::from_le_bytes(buf4) as usize;
            let mut name_bytes = vec![0u8; name_len];
            reader.read_exact(&mut name_bytes)?;
            let name = String::from_utf8_lossy(&name_bytes).to_string();

            // Read vector (dim bits = dim/8 bytes = 256 bytes for 2048 bits)
            let num_bytes = dim / 8;
            let mut vec_bytes = vec![0u8; num_bytes];
            reader.read_exact(&mut vec_bytes)?;

            // Convert to HV16 using from_bytes
            let mut bytes_arr = [0u8; 256];
            bytes_arr[..num_bytes.min(256)].copy_from_slice(&vec_bytes[..num_bytes.min(256)]);
            let hv = HV16::from_bytes(&bytes_arr);

            basis.insert(name, hv);
        }

        Ok(basis)
    }

    /// Load grammar memory from file (trained on corpus)
    pub fn load_grammar(&mut self, path: &Path) -> std::io::Result<()> {
        let file = File::open(path)?;
        let mut reader = BufReader::new(file);

        let mut bytes = [0u8; 256];
        reader.read_exact(&mut bytes)?;

        self.grammar_memory = HV16::from_bytes(&bytes);
        Ok(())
    }

    /// Save grammar memory to file
    pub fn save_grammar(&self, path: &Path) -> std::io::Result<()> {
        use std::io::Write;
        let mut file = File::create(path)?;
        let bytes = self.grammar_memory.to_bytes();
        file.write_all(&bytes)?;
        Ok(())
    }

    /// Get reference to phoneme basis (for external training)
    pub fn phoneme_basis(&self) -> &HashMap<Phoneme, HV16> {
        &self.phoneme_basis
    }

    /// Set phoneme basis (for loading trained basis)
    pub fn set_phoneme_basis(&mut self, basis: HashMap<Phoneme, HV16>) {
        self.phoneme_basis = basis;
    }

    /// Reset context state (start of new sequence)
    pub fn reset(&mut self) {
        self.context_state = HV16::zero();
    }

    /// Permute a hypervector (rotate bits by 1 position)
    /// This encodes temporal order in the sequence
    fn permute(hv: &HV16) -> HV16 {
        let mut new_words = [0u128; HDC_WORDS];

        // Rotate all bits by 1 position across the entire vector
        for i in 0..HDC_WORDS {
            let next_i = (i + 1) % HDC_WORDS;
            // Take high bit from current word, combine with shifted next word
            let high_bit = (hv.words[i] >> 127) & 1;
            new_words[next_i] = (hv.words[next_i] << 1) | high_bit;
        }

        // Handle wrap-around: last word's high bit goes to first word's low bit
        let last_high = (hv.words[HDC_WORDS - 1] >> 127) & 1;
        new_words[0] = (new_words[0] & !1) | last_high;

        HV16 { words: new_words }
    }

    /// Update context with new phoneme and return resonance score
    pub fn score(&mut self, phoneme: &Phoneme) -> f32 {
        // Get phoneme vector (or unknown if not found)
        let phoneme_hv = self.phoneme_basis.get(phoneme).cloned().unwrap_or_else(|| {
            self.phoneme_basis
                .get("UNK")
                .cloned()
                .unwrap_or_else(|| HV16::random("unknown_phoneme"))
        });

        // Update context: shift history and bind new phoneme
        // H_t = Π(H_{t-1}) ⊕ Φ_current
        let shifted = Self::permute(&self.context_state);
        let next_state = shifted.bind(&phoneme_hv);

        // Compute resonance with grammar memory
        let resonance = self.grammar_memory.similarity(&next_state);

        // Update state
        self.context_state = next_state;

        resonance
    }

    /// Score a phoneme without updating state (for beam search)
    pub fn score_candidate(&self, phoneme: &Phoneme) -> f32 {
        let phoneme_hv = self.phoneme_basis.get(phoneme).cloned().unwrap_or_else(|| {
            self.phoneme_basis
                .get("UNK")
                .cloned()
                .unwrap_or_else(|| HV16::random("unknown_phoneme"))
        });

        let shifted = Self::permute(&self.context_state);
        let candidate_state = shifted.bind(&phoneme_hv);

        self.grammar_memory.similarity(&candidate_state)
    }

    /// Train grammar memory from a corpus of phoneme sequences
    pub fn train_grammar(&mut self, sequences: &[Vec<Phoneme>]) {
        println!(
            "Training grammar memory on {} sequences...",
            sequences.len()
        );

        let mut grammar_accumulator = HV16::zero();
        let mut count = 0;

        for sequence in sequences {
            // Encode each sequence as a holographic vector
            let mut seq_state = HV16::zero();

            for phoneme in sequence {
                if let Some(phoneme_hv) = self.phoneme_basis.get(phoneme) {
                    let shifted = Self::permute(&seq_state);
                    seq_state = shifted.bind(phoneme_hv);
                }
            }

            // Add to grammar memory (bundle/superposition)
            grammar_accumulator = bundle(&[grammar_accumulator, seq_state]);
            count += 1;
        }

        self.grammar_memory = grammar_accumulator;
        println!("Grammar memory trained on {count} sequences");
    }

    /// Build trigram constraints from corpus (fast local system)
    pub fn build_trigram_constraints(&mut self, sequences: &[Vec<Phoneme>]) {
        println!("Building trigram constraints...");

        for sequence in sequences {
            for window in sequence.windows(3) {
                let key = (window[0].clone(), window[1].clone());
                let next = window[2].clone();

                self.trigram_constraints.entry(key).or_default().push(next);
            }
        }

        // Deduplicate
        for (_, nexts) in self.trigram_constraints.iter_mut() {
            nexts.sort();
            nexts.dedup();
        }

        println!(
            "Built {} trigram constraints",
            self.trigram_constraints.len()
        );
    }

    /// Check if a phoneme is valid given the previous two
    pub fn is_valid_trigram(&self, prev2: &Phoneme, prev1: &Phoneme, candidate: &Phoneme) -> bool {
        let key = (prev2.clone(), prev1.clone());
        match self.trigram_constraints.get(&key) {
            Some(valid) => valid.contains(candidate),
            None => true, // If unseen, allow it
        }
    }

    /// Combined scoring: HDC resonance + trigram validity
    pub fn combined_score(&self, prev2: &Phoneme, prev1: &Phoneme, candidate: &Phoneme) -> f32 {
        let hdc_score = self.score_candidate(candidate);

        // Trigram validity as a binary gate
        let trigram_valid = if self.is_valid_trigram(prev2, prev1, candidate) {
            1.0
        } else {
            0.1 // Penalty but don't zero out
        };

        // Combined score
        self.hdc_weight * hdc_score + (1.0 - self.hdc_weight) * trigram_valid
    }

    /// Get context state (for saving/restoring during beam search)
    pub fn get_state(&self) -> HV16 {
        self.context_state
    }

    /// Set context state
    pub fn set_state(&mut self, state: HV16) {
        self.context_state = state;
    }
}

impl Default for HolographicScorer {
    fn default() -> Self {
        Self::new()
    }
}

/// Trait for any language model scorer
pub trait Scorer {
    /// Score a candidate phoneme given current context
    fn score(&mut self, phoneme: &str) -> f32;

    /// Reset scorer state
    fn reset(&mut self);
}

impl Scorer for HolographicScorer {
    fn score(&mut self, phoneme: &str) -> f32 {
        HolographicScorer::score(self, &phoneme.to_string())
    }

    fn reset(&mut self) {
        HolographicScorer::reset(self);
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_holographic_scorer_basic() {
        let mut scorer = HolographicScorer::new();

        // Score some phonemes
        let s1 = scorer.score(&"T".to_string());
        let s2 = scorer.score(&"IY".to_string());
        let s3 = scorer.score(&"M".to_string());

        println!("Scores: T={:.3}, IY={:.3}, M={:.3}", s1, s2, s3);

        // Context should be different now
        scorer.reset();
        let s1_reset = scorer.score(&"T".to_string());

        // After reset, same phoneme should give different score
        // (because context history is different)
        println!("After reset, T={:.3}", s1_reset);
    }

    #[test]
    fn test_grammar_training() {
        let mut scorer = HolographicScorer::new();

        // Train on some simple sequences
        let sequences = vec![
            vec!["HH", "EH", "L", "OW"]
                .iter()
                .map(|s| s.to_string())
                .collect(),
            vec!["W", "ER", "L", "D"]
                .iter()
                .map(|s| s.to_string())
                .collect(),
            vec!["T", "IY", "M"].iter().map(|s| s.to_string()).collect(),
        ];

        scorer.train_grammar(&sequences);

        // Now score a similar sequence
        scorer.reset();
        let _ = scorer.score(&"HH".to_string());
        let _ = scorer.score(&"EH".to_string());
        let s_l = scorer.score_candidate(&"L".to_string()); // Should resonate
        let s_x = scorer.score_candidate(&"K".to_string()); // Should not resonate as much

        println!("After HH-EH: L score={:.3}, K score={:.3}", s_l, s_x);
        // L should score higher than K in this context
    }

    #[test]
    fn test_trigram_constraints() {
        let mut scorer = HolographicScorer::new();

        let sequences = vec![
            vec!["T", "IY", "M"].iter().map(|s| s.to_string()).collect(),
            vec!["T", "IY", "CH"]
                .iter()
                .map(|s| s.to_string())
                .collect(),
            vec!["S", "T", "R"].iter().map(|s| s.to_string()).collect(),
        ];

        scorer.build_trigram_constraints(&sequences);

        // T-IY should allow M and CH
        assert!(scorer.is_valid_trigram(&"T".to_string(), &"IY".to_string(), &"M".to_string()));
        assert!(scorer.is_valid_trigram(&"T".to_string(), &"IY".to_string(), &"CH".to_string()));

        // S-T should allow R
        assert!(scorer.is_valid_trigram(&"S".to_string(), &"T".to_string(), &"R".to_string()));
    }
}
