[workspace]
exclude = ["apps/leptos"]
members = [
    "zomes/professional-graph/integrity",
    "zomes/professional-graph/coordinator",
    "zomes/job-postings/integrity",
    "zomes/job-postings/coordinator",
    "zomes/work-history/integrity",
    "zomes/work-history/coordinator",
    "zomes/connection-graph/integrity",
    "zomes/connection-graph/coordinator",
    "zomes/applications/integrity",
    "zomes/applications/coordinator",
]

resolver = "2"

[workspace.dependencies]
hdk = "0.6.0"
hdi = "0.7.0"
holochain_serialized_bytes = "0.0.56"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
getrandom_03 = { package = "getrandom", version = "=0.3.2" }

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
strip = true

[workspace.lints.clippy]
dbg_macro = "deny"
todo = "deny"
unimplemented = "deny"
eq_op = "deny"
cast_ptr_alignment = "deny"

