-- Auto-generated by symthaea-lean-bridge
-- from ProofResult { valid = true, phi = 0.500 }

variable (P : Prop)
variable (Q : Prop)
variable (R : Prop)

theorem and_associative_right : (((P ∧ Q) ∧ R) → (P ∧ (Q ∧ R))) := by
  exact (fun h0 => ⟨h0.1.1, ⟨h0.1.2, h0.2⟩⟩)
