-- Auto-generated by symthaea-lean-bridge
-- from ProofResult { valid = true, phi = 0.500 }

variable (P : Prop)
variable (Q : Prop)
variable (R : Prop)

theorem and_implies_to_impl : (((P ∧ Q) → R) → (P → (Q → R))) := by
  exact (fun h0 => (fun h1 => (fun h2 => (h0 ⟨h1, h2⟩))))
