-- Auto-generated by symthaea-lean-bridge
-- from ProofResult { valid = true, phi = 0.500 }

variable (P : Prop)
variable (Q : Prop)

theorem and_intro : (P → (Q → (P ∧ Q))) := by
  exact (fun h0 => (fun h1 => ⟨h0, h1⟩))
