-- Auto-generated by symthaea-lean-bridge
-- from ProofResult { valid = true, phi = 0.500 }

variable (P : Prop)
variable (Q : Prop)

theorem and_elim_right : ((P ∧ Q) → Q) := by
  exact (fun h0 => h0.2)
