-- Auto-generated by symthaea-lean-bridge
-- from ProofResult { valid = true, phi = 0.500 }

variable (P : Prop)

theorem double_negation_intro : (P → (¬ (¬ P))) := by
  exact (fun h0 => (fun h1 => (h1 h0)))
