-- Auto-generated by symthaea-lean-bridge
-- from ProofResult { valid = true, phi = 0.500 }

variable (P : Prop)
variable (Q : Prop)
variable (R : Prop)

theorem hypothetical_syllogism : ((P → Q) → ((Q → R) → (P → R))) := by
  exact (fun h0 => (fun h1 => (fun h2 => (h1 (h0 h2)))))
