-- Auto-generated by symthaea-lean-bridge
-- from ProofResult { valid = true, phi = 0.500 }

variable (P : Prop)
variable (Q : Prop)
variable (R : Prop)

theorem impl_to_and_implies : ((P → (Q → R)) → ((P ∧ Q) → R)) := by
  exact (fun h0 => (fun h1 => ((h0 h1.1) h1.2)))
