-- Auto-generated by symthaea-lean-bridge
-- from ProofResult { valid = true, phi = 0.500 }

variable (P : Prop)
variable (Q : Prop)

theorem or_intro_right : (Q → (P ∨ Q)) := by
  exact (fun h0 => Or.inr h0)
