//! Support Tickets Integrity Zome
//! Entry types and validation for community support ticket management.
//!
//! Manages support tickets, comments, autonomous actions, undo operations,
//! and preemptive alerts for Symthaea-assisted community support.

use hdi::prelude::*;
use support_types::{
    SupportCategory, TicketPriority, TicketStatus, AutonomyLevel,
    ActionType as SupportActionType, EpistemicStatus,
};

// ============================================================================
// ANCHOR
// ============================================================================

/// Anchor entry for deterministic link bases
#[hdk_entry_helper]
#[derive(Clone, PartialEq)]
pub struct Anchor(pub String);

// ============================================================================
// SUPPORT TICKET
// ============================================================================

/// A community support ticket with optional Symthaea autonomy
#[hdk_entry_helper]
#[derive(Clone, PartialEq)]
pub struct SupportTicket {
    pub title: String,
    pub description: String,
    pub category: SupportCategory,
    pub priority: TicketPriority,
    pub status: TicketStatus,
    pub requester: AgentPubKey,
    pub assignee: Option<AgentPubKey>,
    pub autonomy_level: AutonomyLevel,
    pub system_info: Option<String>,
    pub is_preemptive: bool,
    pub prediction_confidence: Option<f32>,
    pub created_at: Timestamp,
    pub updated_at: Timestamp,
}

// ============================================================================
// TICKET COMMENT
// ============================================================================

/// A comment on a support ticket (human or Symthaea-generated)
#[hdk_entry_helper]
#[derive(Clone, PartialEq)]
pub struct TicketComment {
    pub ticket_hash: ActionHash,
    pub author: AgentPubKey,
    pub content: String,
    pub is_symthaea_response: bool,
    pub confidence: Option<f32>,
    pub epistemic_status: Option<EpistemicStatus>,
}

// ============================================================================
// AUTONOMOUS ACTION
// ============================================================================

/// An autonomous action proposed or taken by Symthaea on a ticket
#[hdk_entry_helper]
#[derive(Clone, PartialEq)]
pub struct AutonomousAction {
    pub ticket_hash: ActionHash,
    pub action_type: SupportActionType,
    pub description: String,
    pub approved: bool,
    pub executed: bool,
    pub result: Option<String>,
    pub success: Option<bool>,
    pub rollback_steps: Option<Vec<String>>,
    pub rollback_state: Option<String>,
    pub rolled_back: bool,
    pub created_at: Timestamp,
}

// ============================================================================
// UNDO ACTION
// ============================================================================

/// Record of an undone autonomous action with rollback result
#[hdk_entry_helper]
#[derive(Clone, PartialEq)]
pub struct UndoAction {
    pub original_action_hash: ActionHash,
    pub reason: String,
    pub rollback_result: String,
    pub created_at: Timestamp,
}

// ============================================================================
// PREEMPTIVE ALERT
// ============================================================================

/// A preemptive alert generated by Symthaea's predictive subsystem
#[hdk_entry_helper]
#[derive(Clone, PartialEq)]
pub struct PreemptiveAlert {
    pub predicted_failure: String,
    pub expected_time_to_failure: Option<String>,
    pub free_energy: f64,
    pub recommended_action: String,
    pub auto_generated_ticket: Option<ActionHash>,
    pub created_at: Timestamp,
}

// ============================================================================
// ENTRY & LINK TYPE REGISTRATION
// ============================================================================

#[hdk_entry_types]
#[unit_enum(UnitEntryTypes)]
pub enum EntryTypes {
    Anchor(Anchor),
    SupportTicket(SupportTicket),
    TicketComment(TicketComment),
    AutonomousAction(AutonomousAction),
    UndoAction(UndoAction),
    PreemptiveAlert(PreemptiveAlert),
}

#[hdk_link_types]
pub enum LinkTypes {
    ShardedTickets,
    AgentToTicket,
    StatusToTicket,
    CategoryToTicket,
    TicketToComment,
    TicketToAction,
    ActionToUndo,
    AgentToAlert,
}

// ============================================================================
// VALIDATION
// ============================================================================

#[hdk_extern]
pub fn validate(op: Op) -> ExternResult<ValidateCallbackResult> {
    match op.flattened::<EntryTypes, LinkTypes>()? {
        FlatOp::StoreEntry(store_entry) => match store_entry {
            OpEntry::CreateEntry { app_entry, .. } => match app_entry {
                EntryTypes::Anchor(_) => Ok(ValidateCallbackResult::Valid),
                EntryTypes::SupportTicket(ticket) => validate_support_ticket(ticket),
                EntryTypes::TicketComment(comment) => validate_ticket_comment(comment),
                EntryTypes::AutonomousAction(_) => Ok(ValidateCallbackResult::Valid),
                EntryTypes::UndoAction(undo) => validate_undo_action(undo),
                EntryTypes::PreemptiveAlert(alert) => validate_preemptive_alert(alert),
            },
            OpEntry::UpdateEntry { app_entry, .. } => match app_entry {
                EntryTypes::SupportTicket(ticket) => validate_support_ticket(ticket),
                EntryTypes::TicketComment(comment) => validate_ticket_comment(comment),
                EntryTypes::UndoAction(undo) => validate_undo_action(undo),
                EntryTypes::PreemptiveAlert(alert) => validate_preemptive_alert(alert),
                _ => Ok(ValidateCallbackResult::Valid),
            },
            _ => Ok(ValidateCallbackResult::Valid),
        },
        FlatOp::RegisterCreateLink { link_type, tag, .. } => {
            match link_type {
                LinkTypes::ShardedTickets => {
                    if tag.0.len() > 256 {
                        return Ok(ValidateCallbackResult::Invalid(
                            "ShardedTickets link tag too long (max 256 bytes)".into(),
                        ));
                    }
                    Ok(ValidateCallbackResult::Valid)
                }
                LinkTypes::AgentToTicket => {
                    if tag.0.len() > 256 {
                        return Ok(ValidateCallbackResult::Invalid(
                            "AgentToTicket link tag too long (max 256 bytes)".into(),
                        ));
                    }
                    Ok(ValidateCallbackResult::Valid)
                }
                LinkTypes::StatusToTicket => {
                    if tag.0.len() > 256 {
                        return Ok(ValidateCallbackResult::Invalid(
                            "StatusToTicket link tag too long (max 256 bytes)".into(),
                        ));
                    }
                    Ok(ValidateCallbackResult::Valid)
                }
                LinkTypes::CategoryToTicket => {
                    if tag.0.len() > 256 {
                        return Ok(ValidateCallbackResult::Invalid(
                            "CategoryToTicket link tag too long (max 256 bytes)".into(),
                        ));
                    }
                    Ok(ValidateCallbackResult::Valid)
                }
                LinkTypes::TicketToComment => {
                    if tag.0.len() > 256 {
                        return Ok(ValidateCallbackResult::Invalid(
                            "TicketToComment link tag too long (max 256 bytes)".into(),
                        ));
                    }
                    Ok(ValidateCallbackResult::Valid)
                }
                LinkTypes::TicketToAction => {
                    if tag.0.len() > 256 {
                        return Ok(ValidateCallbackResult::Invalid(
                            "TicketToAction link tag too long (max 256 bytes)".into(),
                        ));
                    }
                    Ok(ValidateCallbackResult::Valid)
                }
                LinkTypes::ActionToUndo => {
                    if tag.0.len() > 256 {
                        return Ok(ValidateCallbackResult::Invalid(
                            "ActionToUndo link tag too long (max 256 bytes)".into(),
                        ));
                    }
                    Ok(ValidateCallbackResult::Valid)
                }
                LinkTypes::AgentToAlert => {
                    if tag.0.len() > 256 {
                        return Ok(ValidateCallbackResult::Invalid(
                            "AgentToAlert link tag too long (max 256 bytes)".into(),
                        ));
                    }
                    Ok(ValidateCallbackResult::Valid)
                }
            }
        }
        FlatOp::RegisterDeleteLink { .. } => Ok(ValidateCallbackResult::Valid),
        FlatOp::StoreRecord(_) => Ok(ValidateCallbackResult::Valid),
        FlatOp::RegisterAgentActivity(_) => Ok(ValidateCallbackResult::Valid),
        FlatOp::RegisterUpdate(_) => Ok(ValidateCallbackResult::Valid),
        FlatOp::RegisterDelete(_) => Ok(ValidateCallbackResult::Valid),
    }
}

fn validate_support_ticket(ticket: SupportTicket) -> ExternResult<ValidateCallbackResult> {
    if ticket.title.trim().is_empty() {
        return Ok(ValidateCallbackResult::Invalid(
            "Support ticket title cannot be empty".into(),
        ));
    }
    if ticket.description.trim().is_empty() {
        return Ok(ValidateCallbackResult::Invalid(
            "Support ticket description cannot be empty".into(),
        ));
    }
    Ok(ValidateCallbackResult::Valid)
}

fn validate_ticket_comment(comment: TicketComment) -> ExternResult<ValidateCallbackResult> {
    if comment.content.trim().is_empty() {
        return Ok(ValidateCallbackResult::Invalid(
            "Ticket comment content cannot be empty".into(),
        ));
    }
    Ok(ValidateCallbackResult::Valid)
}

fn validate_preemptive_alert(alert: PreemptiveAlert) -> ExternResult<ValidateCallbackResult> {
    if !alert.free_energy.is_finite() {
        return Ok(ValidateCallbackResult::Invalid(
            "PreemptiveAlert free_energy must be finite".into(),
        ));
    }
    if !(alert.free_energy > 0.0) {
        return Ok(ValidateCallbackResult::Invalid(
            "PreemptiveAlert free_energy must be positive".into(),
        ));
    }
    Ok(ValidateCallbackResult::Valid)
}

fn validate_undo_action(undo: UndoAction) -> ExternResult<ValidateCallbackResult> {
    if undo.reason.trim().is_empty() {
        return Ok(ValidateCallbackResult::Invalid(
            "UndoAction reason cannot be empty".into(),
        ));
    }
    if undo.rollback_result.trim().is_empty() {
        return Ok(ValidateCallbackResult::Invalid(
            "UndoAction rollback_result cannot be empty".into(),
        ));
    }
    Ok(ValidateCallbackResult::Valid)
}

// ============================================================================
// TESTS
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    // -- Helpers --------------------------------------------------------------

    fn fake_agent() -> AgentPubKey {
        AgentPubKey::from_raw_36(vec![0xab; 36])
    }

    fn fake_action_hash() -> ActionHash {
        ActionHash::from_raw_36(vec![0xdb; 36])
    }

    fn fake_timestamp() -> Timestamp {
        Timestamp::from_micros(1_700_000_000_000_000)
    }

    fn valid_support_ticket() -> SupportTicket {
        SupportTicket {
            title: "Network issue".into(),
            description: "Cannot connect to DHT peers".into(),
            category: SupportCategory::Network,
            priority: TicketPriority::High,
            status: TicketStatus::Open,
            requester: fake_agent(),
            assignee: None,
            autonomy_level: AutonomyLevel::Advisory,
            system_info: None,
            is_preemptive: false,
            prediction_confidence: None,
            created_at: fake_timestamp(),
            updated_at: fake_timestamp(),
        }
    }

    fn valid_ticket_comment() -> TicketComment {
        TicketComment {
            ticket_hash: fake_action_hash(),
            author: fake_agent(),
            content: "Have you tried restarting the conductor?".into(),
            is_symthaea_response: false,
            confidence: None,
            epistemic_status: None,
        }
    }

    fn valid_autonomous_action() -> AutonomousAction {
        AutonomousAction {
            ticket_hash: fake_action_hash(),
            action_type: SupportActionType::RestartService,
            description: "Restart holochain conductor".into(),
            approved: false,
            executed: false,
            result: None,
            success: None,
            rollback_steps: Some(vec!["Stop conductor".into(), "Restore state".into()]),
            rollback_state: None,
            rolled_back: false,
            created_at: fake_timestamp(),
        }
    }

    fn valid_undo_action() -> UndoAction {
        UndoAction {
            original_action_hash: fake_action_hash(),
            reason: "Action made things worse".into(),
            rollback_result: "Successfully reverted to previous state".into(),
            created_at: fake_timestamp(),
        }
    }

    fn valid_preemptive_alert() -> PreemptiveAlert {
        PreemptiveAlert {
            predicted_failure: "Disk space critically low".into(),
            expected_time_to_failure: Some("2 hours".into()),
            free_energy: 42.5,
            recommended_action: "Clear old DHT data".into(),
            auto_generated_ticket: None,
            created_at: fake_timestamp(),
        }
    }

    fn assert_valid(result: ExternResult<ValidateCallbackResult>) {
        match result {
            Ok(ValidateCallbackResult::Valid) => {}
            Ok(ValidateCallbackResult::Invalid(msg)) => {
                panic!("Expected Valid, got Invalid: {msg}")
            }
            other => panic!("Expected Valid, got {other:?}"),
        }
    }

    fn assert_invalid(result: ExternResult<ValidateCallbackResult>, expected_substr: &str) {
        match result {
            Ok(ValidateCallbackResult::Invalid(msg)) => {
                assert!(
                    msg.contains(expected_substr),
                    "Expected Invalid containing '{expected_substr}', got: '{msg}'"
                );
            }
            Ok(ValidateCallbackResult::Valid) => {
                panic!("Expected Invalid containing '{expected_substr}', got Valid")
            }
            other => panic!("Expected Invalid, got {other:?}"),
        }
    }

    // -- Serde roundtrip: entry types -----------------------------------------

    #[test]
    fn serde_roundtrip_anchor() {
        let a = Anchor("support:tickets:2026:02".to_string());
        let json = serde_json::to_string(&a).unwrap();
        let back: Anchor = serde_json::from_str(&json).unwrap();
        assert_eq!(back, a);
    }

    #[test]
    fn serde_roundtrip_support_ticket() {
        let t = valid_support_ticket();
        let json = serde_json::to_string(&t).unwrap();
        let back: SupportTicket = serde_json::from_str(&json).unwrap();
        assert_eq!(back, t);
    }

    #[test]
    fn serde_roundtrip_support_ticket_with_all_optionals() {
        let mut t = valid_support_ticket();
        t.assignee = Some(fake_agent());
        t.system_info = Some(r#"{"os":"NixOS","version":"25.11"}"#.into());
        t.is_preemptive = true;
        t.prediction_confidence = Some(0.87);
        let json = serde_json::to_string(&t).unwrap();
        let back: SupportTicket = serde_json::from_str(&json).unwrap();
        assert_eq!(back, t);
    }

    #[test]
    fn serde_roundtrip_ticket_comment() {
        let c = valid_ticket_comment();
        let json = serde_json::to_string(&c).unwrap();
        let back: TicketComment = serde_json::from_str(&json).unwrap();
        assert_eq!(back, c);
    }

    #[test]
    fn serde_roundtrip_ticket_comment_symthaea() {
        let mut c = valid_ticket_comment();
        c.is_symthaea_response = true;
        c.confidence = Some(0.92);
        c.epistemic_status = Some(EpistemicStatus::Probable);
        let json = serde_json::to_string(&c).unwrap();
        let back: TicketComment = serde_json::from_str(&json).unwrap();
        assert_eq!(back, c);
    }

    #[test]
    fn serde_roundtrip_autonomous_action() {
        let a = valid_autonomous_action();
        let json = serde_json::to_string(&a).unwrap();
        let back: AutonomousAction = serde_json::from_str(&json).unwrap();
        assert_eq!(back, a);
    }

    #[test]
    fn serde_roundtrip_autonomous_action_executed() {
        let mut a = valid_autonomous_action();
        a.approved = true;
        a.executed = true;
        a.result = Some("Conductor restarted successfully".into());
        a.success = Some(true);
        let json = serde_json::to_string(&a).unwrap();
        let back: AutonomousAction = serde_json::from_str(&json).unwrap();
        assert_eq!(back, a);
    }

    #[test]
    fn serde_roundtrip_undo_action() {
        let u = valid_undo_action();
        let json = serde_json::to_string(&u).unwrap();
        let back: UndoAction = serde_json::from_str(&json).unwrap();
        assert_eq!(back, u);
    }

    #[test]
    fn serde_roundtrip_preemptive_alert() {
        let a = valid_preemptive_alert();
        let json = serde_json::to_string(&a).unwrap();
        let back: PreemptiveAlert = serde_json::from_str(&json).unwrap();
        assert_eq!(back, a);
    }

    #[test]
    fn serde_roundtrip_preemptive_alert_with_ticket() {
        let mut a = valid_preemptive_alert();
        a.auto_generated_ticket = Some(fake_action_hash());
        let json = serde_json::to_string(&a).unwrap();
        let back: PreemptiveAlert = serde_json::from_str(&json).unwrap();
        assert_eq!(back, a);
    }

    // -- Serde roundtrip: shared enums ----------------------------------------

    #[test]
    fn serde_roundtrip_support_category() {
        let variants = vec![
            SupportCategory::Network, SupportCategory::Hardware,
            SupportCategory::Software, SupportCategory::Holochain,
            SupportCategory::Mycelix, SupportCategory::Security,
            SupportCategory::General,
        ];
        for v in &variants {
            let json = serde_json::to_string(v).unwrap();
            let back: SupportCategory = serde_json::from_str(&json).unwrap();
            assert_eq!(&back, v);
        }
    }

    #[test]
    fn serde_roundtrip_ticket_priority() {
        let variants = vec![
            TicketPriority::Low, TicketPriority::Medium,
            TicketPriority::High, TicketPriority::Critical,
        ];
        for v in &variants {
            let json = serde_json::to_string(v).unwrap();
            let back: TicketPriority = serde_json::from_str(&json).unwrap();
            assert_eq!(&back, v);
        }
    }

    #[test]
    fn serde_roundtrip_ticket_status() {
        let variants = vec![
            TicketStatus::Open, TicketStatus::InProgress,
            TicketStatus::AwaitingUser, TicketStatus::Resolved,
            TicketStatus::Closed,
        ];
        for v in &variants {
            let json = serde_json::to_string(v).unwrap();
            let back: TicketStatus = serde_json::from_str(&json).unwrap();
            assert_eq!(&back, v);
        }
    }

    #[test]
    fn serde_roundtrip_autonomy_level() {
        let variants = vec![
            AutonomyLevel::Advisory, AutonomyLevel::SemiAutonomous,
            AutonomyLevel::FullAutonomous,
        ];
        for v in &variants {
            let json = serde_json::to_string(v).unwrap();
            let back: AutonomyLevel = serde_json::from_str(&json).unwrap();
            assert_eq!(&back, v);
        }
    }

    #[test]
    fn serde_roundtrip_action_type() {
        let variants = vec![
            SupportActionType::RestartService, SupportActionType::ClearCache,
            SupportActionType::UpdateConfig, SupportActionType::RunDiagnostic,
            SupportActionType::Custom("patch-apply".to_string()),
        ];
        for v in &variants {
            let json = serde_json::to_string(v).unwrap();
            let back: SupportActionType = serde_json::from_str(&json).unwrap();
            assert_eq!(&back, v);
        }
    }

    #[test]
    fn serde_roundtrip_epistemic_status() {
        let variants = vec![
            EpistemicStatus::Certain, EpistemicStatus::Probable,
            EpistemicStatus::Uncertain, EpistemicStatus::Unknown,
            EpistemicStatus::OutOfDomain,
        ];
        for v in &variants {
            let json = serde_json::to_string(v).unwrap();
            let back: EpistemicStatus = serde_json::from_str(&json).unwrap();
            assert_eq!(&back, v);
        }
    }

    // -- validate_support_ticket ----------------------------------------------

    #[test]
    fn valid_ticket_passes() {
        assert_valid(validate_support_ticket(valid_support_ticket()));
    }

    #[test]
    fn ticket_empty_title_rejected() {
        let mut t = valid_support_ticket();
        t.title = String::new();
        assert_invalid(validate_support_ticket(t), "title cannot be empty");
    }

    #[test]
    fn ticket_whitespace_title_rejected() {
        let mut t = valid_support_ticket();
        t.title = "   ".into();
        assert_invalid(validate_support_ticket(t), "title cannot be empty");
    }

    #[test]
    fn ticket_empty_description_rejected() {
        let mut t = valid_support_ticket();
        t.description = String::new();
        assert_invalid(validate_support_ticket(t), "description cannot be empty");
    }

    #[test]
    fn ticket_whitespace_description_rejected() {
        let mut t = valid_support_ticket();
        t.description = " \t\n ".into();
        assert_invalid(validate_support_ticket(t), "description cannot be empty");
    }

    #[test]
    fn ticket_empty_title_rejects_before_empty_description() {
        let mut t = valid_support_ticket();
        t.title = String::new();
        t.description = String::new();
        assert_invalid(validate_support_ticket(t), "title cannot be empty");
    }

    #[test]
    fn ticket_all_categories_valid() {
        for cat in [
            SupportCategory::Network, SupportCategory::Hardware,
            SupportCategory::Software, SupportCategory::Holochain,
            SupportCategory::Mycelix, SupportCategory::Security,
            SupportCategory::General,
        ] {
            let mut t = valid_support_ticket();
            t.category = cat;
            assert_valid(validate_support_ticket(t));
        }
    }

    #[test]
    fn ticket_all_priorities_valid() {
        for pri in [
            TicketPriority::Low, TicketPriority::Medium,
            TicketPriority::High, TicketPriority::Critical,
        ] {
            let mut t = valid_support_ticket();
            t.priority = pri;
            assert_valid(validate_support_ticket(t));
        }
    }

    #[test]
    fn ticket_all_statuses_valid() {
        for status in [
            TicketStatus::Open, TicketStatus::InProgress,
            TicketStatus::AwaitingUser, TicketStatus::Resolved,
            TicketStatus::Closed,
        ] {
            let mut t = valid_support_ticket();
            t.status = status;
            assert_valid(validate_support_ticket(t));
        }
    }

    #[test]
    fn ticket_all_autonomy_levels_valid() {
        for level in [
            AutonomyLevel::Advisory, AutonomyLevel::SemiAutonomous,
            AutonomyLevel::FullAutonomous,
        ] {
            let mut t = valid_support_ticket();
            t.autonomy_level = level;
            assert_valid(validate_support_ticket(t));
        }
    }

    // -- validate_ticket_comment ----------------------------------------------

    #[test]
    fn valid_comment_passes() {
        assert_valid(validate_ticket_comment(valid_ticket_comment()));
    }

    #[test]
    fn comment_empty_content_rejected() {
        let mut c = valid_ticket_comment();
        c.content = String::new();
        assert_invalid(validate_ticket_comment(c), "content cannot be empty");
    }

    #[test]
    fn comment_whitespace_content_rejected() {
        let mut c = valid_ticket_comment();
        c.content = "   ".into();
        assert_invalid(validate_ticket_comment(c), "content cannot be empty");
    }

    // -- validate_preemptive_alert --------------------------------------------

    #[test]
    fn valid_alert_passes() {
        assert_valid(validate_preemptive_alert(valid_preemptive_alert()));
    }

    #[test]
    fn alert_zero_free_energy_rejected() {
        let mut a = valid_preemptive_alert();
        a.free_energy = 0.0;
        assert_invalid(validate_preemptive_alert(a), "free_energy must be positive");
    }

    #[test]
    fn alert_negative_free_energy_rejected() {
        let mut a = valid_preemptive_alert();
        a.free_energy = -1.0;
        assert_invalid(validate_preemptive_alert(a), "free_energy must be positive");
    }

    #[test]
    fn alert_nan_free_energy_rejected() {
        let mut a = valid_preemptive_alert();
        a.free_energy = f64::NAN;
        assert_invalid(validate_preemptive_alert(a), "free_energy must be finite");
    }

    #[test]
    fn alert_inf_free_energy_rejected() {
        let mut a = valid_preemptive_alert();
        a.free_energy = f64::INFINITY;
        assert_invalid(validate_preemptive_alert(a), "free_energy must be finite");
    }

    #[test]
    fn alert_neg_inf_free_energy_rejected() {
        let mut a = valid_preemptive_alert();
        a.free_energy = f64::NEG_INFINITY;
        assert_invalid(validate_preemptive_alert(a), "free_energy must be finite");
    }

    #[test]
    fn alert_barely_positive_free_energy_valid() {
        let mut a = valid_preemptive_alert();
        a.free_energy = 0.001;
        assert_valid(validate_preemptive_alert(a));
    }

    #[test]
    fn alert_large_free_energy_valid() {
        let mut a = valid_preemptive_alert();
        a.free_energy = 999999.0;
        assert_valid(validate_preemptive_alert(a));
    }

    // -- validate_undo_action -------------------------------------------------

    #[test]
    fn valid_undo_passes() {
        assert_valid(validate_undo_action(valid_undo_action()));
    }

    #[test]
    fn undo_empty_reason_rejected() {
        let mut u = valid_undo_action();
        u.reason = String::new();
        assert_invalid(validate_undo_action(u), "reason cannot be empty");
    }

    #[test]
    fn undo_whitespace_reason_rejected() {
        let mut u = valid_undo_action();
        u.reason = "  ".into();
        assert_invalid(validate_undo_action(u), "reason cannot be empty");
    }

    #[test]
    fn undo_empty_rollback_result_rejected() {
        let mut u = valid_undo_action();
        u.rollback_result = String::new();
        assert_invalid(validate_undo_action(u), "rollback_result cannot be empty");
    }

    #[test]
    fn undo_whitespace_rollback_result_rejected() {
        let mut u = valid_undo_action();
        u.rollback_result = " \t ".into();
        assert_invalid(validate_undo_action(u), "rollback_result cannot be empty");
    }

    #[test]
    fn undo_empty_reason_rejects_before_empty_rollback() {
        let mut u = valid_undo_action();
        u.reason = String::new();
        u.rollback_result = String::new();
        assert_invalid(validate_undo_action(u), "reason cannot be empty");
    }

    // -- Link tag boundary tests ----------------------------------------------

    fn validate_link_tag(link_type: &LinkTypes, tag_len: usize) -> ValidateCallbackResult {
        let tag = LinkTag(vec![0u8; tag_len]);
        let max = 256;
        let name = match link_type {
            LinkTypes::ShardedTickets => "ShardedTickets",
            LinkTypes::AgentToTicket => "AgentToTicket",
            LinkTypes::StatusToTicket => "StatusToTicket",
            LinkTypes::CategoryToTicket => "CategoryToTicket",
            LinkTypes::TicketToComment => "TicketToComment",
            LinkTypes::TicketToAction => "TicketToAction",
            LinkTypes::ActionToUndo => "ActionToUndo",
            LinkTypes::AgentToAlert => "AgentToAlert",
        };
        if tag.0.len() > max {
            ValidateCallbackResult::Invalid(
                format!("{} link tag too long (max {} bytes)", name, max),
            )
        } else {
            ValidateCallbackResult::Valid
        }
    }

    #[test]
    fn link_sharded_tickets_tag_at_max_accepted() {
        let result = validate_link_tag(&LinkTypes::ShardedTickets, 256);
        assert_eq!(result, ValidateCallbackResult::Valid);
    }

    #[test]
    fn link_sharded_tickets_tag_over_max_rejected() {
        let result = validate_link_tag(&LinkTypes::ShardedTickets, 257);
        assert!(matches!(result, ValidateCallbackResult::Invalid(_)));
    }

    #[test]
    fn link_agent_to_ticket_tag_at_max_accepted() {
        let result = validate_link_tag(&LinkTypes::AgentToTicket, 256);
        assert_eq!(result, ValidateCallbackResult::Valid);
    }

    #[test]
    fn link_agent_to_ticket_tag_over_max_rejected() {
        let result = validate_link_tag(&LinkTypes::AgentToTicket, 257);
        assert!(matches!(result, ValidateCallbackResult::Invalid(_)));
    }

    #[test]
    fn link_status_to_ticket_tag_at_max_accepted() {
        let result = validate_link_tag(&LinkTypes::StatusToTicket, 256);
        assert_eq!(result, ValidateCallbackResult::Valid);
    }

    #[test]
    fn link_status_to_ticket_tag_over_max_rejected() {
        let result = validate_link_tag(&LinkTypes::StatusToTicket, 257);
        assert!(matches!(result, ValidateCallbackResult::Invalid(_)));
    }

    #[test]
    fn link_category_to_ticket_tag_at_max_accepted() {
        let result = validate_link_tag(&LinkTypes::CategoryToTicket, 256);
        assert_eq!(result, ValidateCallbackResult::Valid);
    }

    #[test]
    fn link_category_to_ticket_tag_over_max_rejected() {
        let result = validate_link_tag(&LinkTypes::CategoryToTicket, 257);
        assert!(matches!(result, ValidateCallbackResult::Invalid(_)));
    }

    #[test]
    fn link_ticket_to_comment_tag_at_max_accepted() {
        let result = validate_link_tag(&LinkTypes::TicketToComment, 256);
        assert_eq!(result, ValidateCallbackResult::Valid);
    }

    #[test]
    fn link_ticket_to_comment_tag_over_max_rejected() {
        let result = validate_link_tag(&LinkTypes::TicketToComment, 257);
        assert!(matches!(result, ValidateCallbackResult::Invalid(_)));
    }

    #[test]
    fn link_ticket_to_action_tag_at_max_accepted() {
        let result = validate_link_tag(&LinkTypes::TicketToAction, 256);
        assert_eq!(result, ValidateCallbackResult::Valid);
    }

    #[test]
    fn link_ticket_to_action_tag_over_max_rejected() {
        let result = validate_link_tag(&LinkTypes::TicketToAction, 257);
        assert!(matches!(result, ValidateCallbackResult::Invalid(_)));
    }

    #[test]
    fn link_action_to_undo_tag_at_max_accepted() {
        let result = validate_link_tag(&LinkTypes::ActionToUndo, 256);
        assert_eq!(result, ValidateCallbackResult::Valid);
    }

    #[test]
    fn link_action_to_undo_tag_over_max_rejected() {
        let result = validate_link_tag(&LinkTypes::ActionToUndo, 257);
        assert!(matches!(result, ValidateCallbackResult::Invalid(_)));
    }

    #[test]
    fn link_agent_to_alert_tag_at_max_accepted() {
        let result = validate_link_tag(&LinkTypes::AgentToAlert, 256);
        assert_eq!(result, ValidateCallbackResult::Valid);
    }

    #[test]
    fn link_agent_to_alert_tag_over_max_rejected() {
        let result = validate_link_tag(&LinkTypes::AgentToAlert, 257);
        assert!(matches!(result, ValidateCallbackResult::Invalid(_)));
    }
}
