// Copyright (C) 2024-2026 Tristan Stoltz / Luminous Dynamics
// SPDX-License-Identifier: AGPL-3.0-or-later
//! Exact NARMA10 v1 scientific subject.
//!
//! Recurrence:
//!
//! `y[t+1] = 0.3*y[t] + 0.05*y[t]*sum(y[t-i], i=0..9)
//!           + 1.5*u[t]*u[t-9] + 0.1`
//!
//! Inputs are generated by the versioned SplitMix64 stream below and mapped to
//! `[0, 0.5)` using the top 53 bits. The target aligned with frame `t` is
//! `y[t+1]`. Prehistory is exactly zero. There is no retry, clipping, tanh,
//! sequence replacement, or hidden normalization.

use symthaea_physical_experiment::SeedPlan;
use symthaea_physical_fixtures::{
    FixtureSuite, MetadataEntry, ScalarChannel, SeedFixture,
};

/// Stable workload family.
pub const FAMILY: &str = "temporal:narma10";
/// Exact workload-definition version.
pub const VERSION: &str = "atiya-parlos-u05-v1";
/// Domain separation mixed into the input RNG state.
pub const RNG_DOMAIN_XOR: u64 = 0x4e41_524d_4131_3031;
/// Maximum frame count accepted by this generator.
pub const MAX_FRAMES: usize = 1_000_000;

const INPUT_SCALE: f64 = 0.5;
const UNIT_53: f64 = 1.0 / 9_007_199_254_740_992.0;

/// Exact NARMA10 fixture-generation parameters.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Narma10Spec {
    /// Number of causal input/target frames generated per seed.
    pub frames: usize,
}

impl Narma10Spec {
    /// Validate a bounded, non-empty frame count.
    pub fn validate(self) -> Result<(), Narma10Error> {
        if self.frames == 0 || self.frames > MAX_FRAMES {
            return Err(Narma10Error::InvalidFrameCount(self.frames));
        }
        Ok(())
    }
}

/// Generate the exact multi-seed PHYS-006 fixture suite.
pub fn generate_suite(
    seed_plan: &SeedPlan,
    spec: Narma10Spec,
) -> Result<FixtureSuite, Narma10Error> {
    spec.validate()?;
    seed_plan
        .validate()
        .map_err(|error| Narma10Error::SeedPlan(error.to_string()))?;

    let mut records = Vec::with_capacity(seed_plan.seeds.len());
    for &seed in &seed_plan.seeds {
        records.push(generate_seed_fixture(seed, spec.frames)?);
    }

    let suite = FixtureSuite {
        schema_version: 1,
        family: FAMILY.to_string(),
        version: VERSION.to_string(),
        metadata: vec![
            MetadataEntry {
                key: "alignment".to_string(),
                value: "frame-t:drive_voltage=u[t];target=y[t+1]".to_string(),
            },
            MetadataEntry {
                key: "definition".to_string(),
                value: "y[t+1]=0.3*y[t]+0.05*y[t]*sum(y[t-i],i=0..9)+1.5*u[t]*u[t-9]+0.1"
                    .to_string(),
            },
            MetadataEntry {
                key: "input_distribution".to_string(),
                value: "splitmix64-top53-uniform-[0,0.5)".to_string(),
            },
            MetadataEntry {
                key: "prehistory".to_string(),
                value: "y[0],y[-1]..y[-9]=0;u[t<0]=0".to_string(),
            },
            MetadataEntry {
                key: "retry_policy".to_string(),
                value: "none".to_string(),
            },
            MetadataEntry {
                key: "rng_domain_xor".to_string(),
                value: format!("0x{RNG_DOMAIN_XOR:016x}"),
            },
        ],
        records,
    };
    suite
        .validate_against_seed_plan(seed_plan)
        .map_err(|error| Narma10Error::Fixture(error.to_string()))?;
    Ok(suite)
}

fn generate_seed_fixture(seed: u64, frames: usize) -> Result<SeedFixture, Narma10Error> {
    let mut rng = SplitMix64::new(seed ^ RNG_DOMAIN_XOR);
    let mut inputs = Vec::with_capacity(frames);
    for _ in 0..frames {
        inputs.push(rng.next_unit_f64() * INPUT_SCALE);
    }

    let mut history = [0.0f64; 10];
    let mut targets = Vec::with_capacity(frames);
    for (frame, &input) in inputs.iter().enumerate() {
        let y_t = history[0];
        let history_sum = history.iter().copied().sum::<f64>();
        let delayed_input = if frame >= 9 { inputs[frame - 9] } else { 0.0 };
        let next = 0.3 * y_t
            + 0.05 * y_t * history_sum
            + 1.5 * input * delayed_input
            + 0.1;
        if !next.is_finite() {
            return Err(Narma10Error::NonFiniteTarget { seed, frame });
        }
        targets.push(next);
        history.copy_within(0..9, 1);
        history[0] = next;
    }

    Ok(SeedFixture {
        seed,
        scalar_channels: vec![
            ScalarChannel {
                name: "drive_voltage".to_string(),
                values: inputs,
            },
            ScalarChannel {
                name: "target".to_string(),
                values: targets,
            },
        ],
        binary_channels: vec![],
    })
}

#[derive(Debug, Clone, Copy)]
struct SplitMix64 {
    state: u64,
}

impl SplitMix64 {
    fn new(state: u64) -> Self {
        Self { state }
    }

    fn next_u64(&mut self) -> u64 {
        self.state = self.state.wrapping_add(0x9e37_79b9_7f4a_7c15);
        let mut value = self.state;
        value = (value ^ (value >> 30)).wrapping_mul(0xbf58_476d_1ce4_e5b9);
        value = (value ^ (value >> 27)).wrapping_mul(0x94d0_49bb_1331_11eb);
        value ^ (value >> 31)
    }

    fn next_unit_f64(&mut self) -> f64 {
        ((self.next_u64() >> 11) as f64) * UNIT_53
    }
}

/// Exact fixture-generation failures.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum Narma10Error {
    /// Frame count was zero or exceeded the bounded generator limit.
    InvalidFrameCount(usize),
    /// PHYS-002 seed plan was invalid.
    SeedPlan(String),
    /// PHYS-006 fixture validation failed.
    Fixture(String),
    /// Standard recurrence produced a non-finite target; no retry is performed.
    NonFiniteTarget {
        /// Seed whose target diverged.
        seed: u64,
        /// Frame at which the non-finite target appeared.
        frame: usize,
    },
}

impl std::fmt::Display for Narma10Error {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{self:?}")
    }
}

impl std::error::Error for Narma10Error {}

#[cfg(test)]
mod tests {
    use super::*;

    const GOLDEN_INPUT_BITS: [u64; 16] = [
        0x3fdf_37d9_7dca_ca3a,
        0x3fc7_440f_8918_8d66,
        0x3fd8_e426_8e2b_2bbd,
        0x3faa_0fed_2a2c_0d80,
        0x3fca_5151_f068_2822,
        0x3fde_7b69_92a1_2871,
        0x3fc2_8c8c_1145_cfdc,
        0x3fd7_c5c5_5613_366b,
        0x3fd7_9efc_b0bd_db34,
        0x3f9e_d323_f462_d930,
        0x3f9d_0e5b_2b85_3870,
        0x3fb5_db3c_1112_9574,
        0x3fc2_4adc_87fa_59fc,
        0x3fc6_7f8f_1700_f9fe,
        0x3fdc_ca8d_b975_da08,
        0x3fd9_2320_4b97_d133,
    ];

    const GOLDEN_TARGET_BITS: [u64; 16] = [
        0x3fb9_9999_9999_999a,
        0x3fc0_b439_5810_624e,
        0x3fc2_00f3_5fde_8ce9,
        0x3fc2_8904_4882_b924,
        0x3fc2_d6b7_9177_6b00,
        0x3fc3_1385_8006_6e2a,
        0x3fc3_4c2b_5409_75fe,
        0x3fc3_84b4_15aa_a1a5,
        0x3fc3_be7b_7a87_bf86,
        0x3fc6_cbbd_9cbf_eae8,
        0x3fc6_4777_6888_be26,
        0x3fcb_8deb_0eb0_6b75,
        0x3fc8_ad2b_1ef2_9626,
        0x3fcd_302d_3b68_a179,
        0x3fe0_4f29_fe57_5c1a,
        0x3fd9_14f1_bf2f_8218,
    ];

    fn channels(record: &SeedFixture) -> (&[f64], &[f64]) {
        let input = record
            .scalar_channels
            .iter()
            .find(|channel| channel.name == "drive_voltage")
            .unwrap();
        let target = record
            .scalar_channels
            .iter()
            .find(|channel| channel.name == "target")
            .unwrap();
        (&input.values, &target.values)
    }

    #[test]
    fn seed_one_prefix_is_bit_exact() {
        let plan = SeedPlan { seeds: vec![1] };
        let suite = generate_suite(&plan, Narma10Spec { frames: 16 }).unwrap();
        let (input, target) = channels(&suite.records[0]);
        let input_bits = input.iter().map(|value| value.to_bits()).collect::<Vec<_>>();
        let target_bits = target.iter().map(|value| value.to_bits()).collect::<Vec<_>>();
        assert_eq!(input_bits, GOLDEN_INPUT_BITS);
        assert_eq!(target_bits, GOLDEN_TARGET_BITS);
    }

    #[test]
    fn exact_definition_has_expected_identity_and_metadata() {
        let plan = SeedPlan { seeds: vec![3] };
        let suite = generate_suite(&plan, Narma10Spec { frames: 32 }).unwrap();
        assert_eq!(suite.family, FAMILY);
        assert_eq!(suite.version, VERSION);
        assert!(suite
            .metadata
            .iter()
            .any(|entry| entry.key == "retry_policy" && entry.value == "none"));
        assert_eq!(suite.records[0].scalar_channels.len(), 2);
        assert!(suite.records[0].binary_channels.is_empty());
    }

    #[test]
    fn inputs_are_in_standard_half_open_range() {
        let plan = SeedPlan {
            seeds: vec![1, 2, 3],
        };
        let suite = generate_suite(&plan, Narma10Spec { frames: 1024 }).unwrap();
        for record in &suite.records {
            let (input, _) = channels(record);
            assert!(input.iter().all(|value| (0.0..0.5).contains(value)));
        }
    }

    #[test]
    fn same_seed_replays_exactly_and_different_seed_changes_stream() {
        let a = generate_seed_fixture(42, 64).unwrap();
        let b = generate_seed_fixture(42, 64).unwrap();
        let c = generate_seed_fixture(43, 64).unwrap();
        assert_eq!(a, b);
        assert_ne!(a, c);
    }

    #[test]
    fn recurrence_and_causal_alignment_hold() {
        let record = generate_seed_fixture(7, 64).unwrap();
        let (input, target) = channels(&record);
        let mut history = [0.0f64; 10];
        for frame in 0..64 {
            let delayed = if frame >= 9 { input[frame - 9] } else { 0.0 };
            let expected = 0.3 * history[0]
                + 0.05 * history[0] * history.iter().copied().sum::<f64>()
                + 1.5 * input[frame] * delayed
                + 0.1;
            assert_eq!(target[frame].to_bits(), expected.to_bits());
            history.copy_within(0..9, 1);
            history[0] = expected;
        }
    }

    #[test]
    fn aurum002_fixed_seed_subject_constructs_without_retry_or_replacement() {
        let plan = SeedPlan {
            seeds: vec![1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, 233, 377, 610, 987, 1597],
        };
        let suite = generate_suite(&plan, Narma10Spec { frames: 3840 }).unwrap();
        suite.validate_against_seed_plan(&plan).unwrap();
        assert_eq!(suite.records.len(), plan.seeds.len());
        for record in &suite.records {
            let (input, target) = channels(record);
            assert_eq!(input.len(), 3840);
            assert_eq!(target.len(), 3840);
            assert!(target.iter().all(|value| value.is_finite()));
        }
    }

    #[test]
    fn invalid_frame_counts_fail_before_allocation() {
        let plan = SeedPlan { seeds: vec![1] };
        assert_eq!(
            generate_suite(&plan, Narma10Spec { frames: 0 }),
            Err(Narma10Error::InvalidFrameCount(0))
        );
        assert_eq!(
            generate_suite(
                &plan,
                Narma10Spec {
                    frames: MAX_FRAMES + 1,
                },
            ),
            Err(Narma10Error::InvalidFrameCount(MAX_FRAMES + 1))
        );
    }
}
