// Copyright (C) 2024-2026 Tristan Stoltz / Luminous Dynamics
// SPDX-License-Identifier: AGPL-3.0-or-later
// Commercial licensing: see COMMERCIAL_LICENSE.md at repository root
//! # DID Registry Integration Tests
//!
//! Comprehensive tests for the Mycelix Identity DID Registry zome.
//!
//! These tests use the pre-built .happ bundle instead of linking zome crates
//! directly, avoiding duplicate symbol errors from multiple integrity zomes.
//!
//! ## Running Tests
//!
//! ```bash
//! # Build the hApp first
//! cd mycelix-identity && hc app pack .
//!
//! # Run tests (excluded by default, require conductor)
//! cargo test --test did_registry_test -- --ignored
//! ```

use holochain::sweettest::*;
use holochain::prelude::*;
use std::path::PathBuf;


// ============================================================================
// Mirror types for deserialization (avoids importing zome crates)
// ============================================================================

/// Mirror of did_registry_integrity::DidDocument
#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct DidDocument {
    pub id: String,
    pub controller: AgentPubKey,
    #[serde(rename = "verificationMethod", alias = "verification_method")]
    pub verification_method: Vec<VerificationMethod>,
    pub authentication: Vec<String>,
    #[serde(rename = "keyAgreement", alias = "key_agreement", default)]
    pub key_agreement: Vec<String>,
    pub service: Vec<ServiceEndpoint>,
    pub created: Timestamp,
    pub updated: Timestamp,
    pub version: u32,
}

/// Mirror of did_registry_integrity::VerificationMethod
#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct VerificationMethod {
    pub id: String,
    #[serde(rename = "type", alias = "type_")]
    pub type_: String,
    pub controller: String,
    #[serde(rename = "publicKeyMultibase", alias = "public_key_multibase")]
    pub public_key_multibase: String,
    #[serde(default)]
    pub algorithm: Option<u16>,
}

/// Mirror of did_registry_integrity::ServiceEndpoint
#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ServiceEndpoint {
    pub id: String,
    #[serde(rename = "type", alias = "type_")]
    pub type_: String,
    #[serde(rename = "serviceEndpoint", alias = "service_endpoint")]
    pub service_endpoint: String,
}

/// Mirror of did_registry_integrity::DidDeactivation
#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct DidDeactivation {
    pub did: String,
    pub reason: String,
    pub deactivated_at: Timestamp,
}

// ============================================================================
// Test Utilities
// ============================================================================

mod test_helpers {
    pub const TEST_DID_PREFIX: &str = "did:mycelix:test:";

    pub fn test_did(suffix: &str) -> String {
        format!("{}{}", TEST_DID_PREFIX, suffix)
    }

    pub fn unique_test_did(prefix: &str) -> String {
        let timestamp = chrono::Utc::now().timestamp_micros();
        format!("{}{}:{}", TEST_DID_PREFIX, prefix, timestamp)
    }

    pub fn is_valid_mycelix_did(did: &str) -> bool {
        did.starts_with("did:mycelix:")
    }
}

use test_helpers::*;

/// Path to the pre-built DNA bundle
fn dna_path() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("..")
        .join("dna")
        .join("mycelix_identity_dna.dna")
}

async fn load_dna() -> DnaFile {
    SweetDnaFile::from_bundle(&dna_path())
        .await
        .expect("Failed to load DNA bundle")
}

/// Decode an entry from a Record into a concrete type via MessagePack deserialization.
/// Replaces `to_app_option()` which requires `TryFrom<SerializedBytes>` (generated by `#[hdk_entry_helper]`).
fn decode_entry<T: serde::de::DeserializeOwned>(record: &Record) -> Option<T> {
    match record.entry().as_option()? {
        Entry::App(bytes) => {
            let sb = SerializedBytes::from(bytes.to_owned());
            rmp_serde::from_slice(sb.bytes()).ok()
        }
        _ => None,
    }
}

// ============================================================================
// Section 1: DID Creation Tests
// ============================================================================

#[cfg(test)]
mod did_creation {
    use super::*;

    #[tokio::test(flavor = "multi_thread")]
    #[ignore] // Requires hApp bundle
    async fn test_create_did_success() {
        println!("Test 1.1: Basic DID Creation");

        let mut conductor = SweetConductor::from_standard_config().await;
        let dna = load_dna().await;
        let app = conductor
            .setup_app("test-app", &[dna.clone()])
            .await
            .unwrap();
        let cell = app.cells()[0].clone();
        let agent = app.agent().clone();

        let did_record: Record = conductor
            .call(&cell.zome("did_registry"), "create_did", ())
            .await;

        let did_doc: DidDocument = decode_entry(&did_record).expect("Failed to decode entry");

        assert!(
            did_doc.id.starts_with("did:mycelix:"),
            "DID should start with 'did:mycelix:'"
        );
        assert_eq!(
            did_doc.controller, agent,
            "Controller should be the creating agent"
        );
        assert!(
            !did_doc.verification_method.is_empty(),
            "Should have at least one verification method"
        );
        assert_eq!(did_doc.version, 1, "Initial version should be 1");
        assert!(
            !did_doc.authentication.is_empty(),
            "Should have authentication method"
        );

        println!("  - DID ID: {}", did_doc.id);
        println!("  - Controller: {}", did_doc.controller);
        println!("  - Version: {}", did_doc.version);
        println!("Test 1.1 PASSED");
    }

    #[tokio::test(flavor = "multi_thread")]
    #[ignore]
    async fn test_did_verification_method_structure() {
        println!("Test 1.2: DID Verification Method Structure");

        let mut conductor = SweetConductor::from_standard_config().await;
        let dna = load_dna().await;
        let app = conductor
            .setup_app("test-app", &[dna.clone()])
            .await
            .unwrap();
        let cell = app.cells()[0].clone();

        let did_record: Record = conductor
            .call(&cell.zome("did_registry"), "create_did", ())
            .await;

        let did_doc: DidDocument = decode_entry(&did_record).expect("No entry");

        let vm = &did_doc.verification_method[0];
        assert!(vm.id.starts_with(&did_doc.id), "VM ID should reference DID");
        assert_eq!(vm.type_, "Ed25519VerificationKey2020", "Should use Ed25519 key type");
        assert!(vm.public_key_multibase.starts_with("z"), "Key should be multibase encoded");

        println!("  - VM ID: {}", vm.id);
        println!("Test 1.2 PASSED");
    }

    #[tokio::test(flavor = "multi_thread")]
    #[ignore]
    async fn test_unique_dids_per_agent() {
        println!("Test 1.3: Unique DIDs Per Agent");

        let mut conductor = SweetConductor::from_standard_config().await;
        let dna = load_dna().await;

        let mut dids = Vec::new();
        for _ in 0..3 {
            let app = conductor
                .setup_app(&format!("test-app-{}", dids.len()), &[dna.clone()])
                .await
                .unwrap();
            let cell = app.cells()[0].clone();

            let did_record: Record = conductor
                .call(&cell.zome("did_registry"), "create_did", ())
                .await;

            let did_doc: DidDocument = decode_entry(&did_record).expect("No entry");

            dids.push(did_doc.id.clone());
            println!("  - Agent {}: {}", dids.len() - 1, did_doc.id);
        }

        let unique_dids: std::collections::HashSet<_> = dids.iter().collect();
        assert_eq!(unique_dids.len(), dids.len(), "All agents should have unique DIDs");

        println!("Test 1.3 PASSED");
    }
}

// ============================================================================
// Section 2: DID Resolution Tests
// ============================================================================

#[cfg(test)]
mod did_resolution {
    use super::*;

    #[tokio::test(flavor = "multi_thread")]
    #[ignore]
    async fn test_resolve_did_by_string() {
        println!("Test 2.1: Resolve DID by String");

        let mut conductor = SweetConductor::from_standard_config().await;
        let dna = load_dna().await;
        let app = conductor
            .setup_app("test-app", &[dna.clone()])
            .await
            .unwrap();
        let cell = app.cells()[0].clone();

        let created_record: Record = conductor
            .call(&cell.zome("did_registry"), "create_did", ())
            .await;

        let created_did: DidDocument = decode_entry(&created_record).expect("No entry");

        let resolved: Option<Record> = conductor
            .call(
                &cell.zome("did_registry"),
                "resolve_did",
                created_did.id.clone(),
            )
            .await;

        assert!(resolved.is_some(), "Should resolve created DID");

        let resolved_did: DidDocument = decode_entry(&resolved.unwrap()).expect("No entry");

        assert_eq!(resolved_did.id, created_did.id, "Resolved DID should match");

        println!("  - Resolved DID: {}", resolved_did.id);
        println!("Test 2.1 PASSED");
    }

    #[tokio::test(flavor = "multi_thread")]
    #[ignore]
    async fn test_resolve_did_by_agent_key() {
        println!("Test 2.2: Resolve DID by Agent Pub Key");

        let mut conductor = SweetConductor::from_standard_config().await;
        let dna = load_dna().await;
        let app = conductor
            .setup_app("test-app", &[dna.clone()])
            .await
            .unwrap();
        let cell = app.cells()[0].clone();
        let agent = app.agent().clone();

        let _: Record = conductor
            .call(&cell.zome("did_registry"), "create_did", ())
            .await;

        let resolved: Option<Record> = conductor
            .call(
                &cell.zome("did_registry"),
                "get_did_document",
                agent.clone(),
            )
            .await;

        assert!(resolved.is_some(), "Should find DID for agent");

        println!("Test 2.2 PASSED");
    }

    #[tokio::test(flavor = "multi_thread")]
    #[ignore]
    async fn test_get_my_did() {
        println!("Test 2.3: Get My DID");

        let mut conductor = SweetConductor::from_standard_config().await;
        let dna = load_dna().await;
        let app = conductor
            .setup_app("test-app", &[dna.clone()])
            .await
            .unwrap();
        let cell = app.cells()[0].clone();

        let _: Record = conductor
            .call(&cell.zome("did_registry"), "create_did", ())
            .await;

        let my_did: Option<Record> = conductor
            .call(&cell.zome("did_registry"), "get_my_did", ())
            .await;

        assert!(my_did.is_some(), "Should return my DID");

        println!("Test 2.3 PASSED");
    }

    #[tokio::test(flavor = "multi_thread")]
    #[ignore]
    async fn test_resolve_nonexistent_did() {
        println!("Test 2.4: Resolve Non-existent DID");

        let mut conductor = SweetConductor::from_standard_config().await;
        let dna = load_dna().await;
        // Install two apps so we have a second agent
        let app1 = conductor
            .setup_app("test-app-1", &[dna.clone()])
            .await
            .unwrap();
        let app2 = conductor
            .setup_app("test-app-2", &[dna.clone()])
            .await
            .unwrap();
        let cell1 = app1.cells()[0].clone();
        let agent2 = app2.agent().clone();

        // Don't create a DID for agent2, try to look it up via agent1's cell
        let bob_did: Option<Record> = conductor
            .call(
                &cell1.zome("did_registry"),
                "get_did_document",
                agent2,
            )
            .await;

        assert!(bob_did.is_none(), "Should return None for non-existent DID");

        println!("Test 2.4 PASSED");
    }
}

// ============================================================================
// Section 3: Invalid DID Rejection Tests
// ============================================================================

#[cfg(test)]
mod invalid_did_rejection {
    use super::*;

    #[tokio::test(flavor = "multi_thread")]
    #[ignore]
    async fn test_reject_invalid_did_format() {
        println!("Test 3.1: Reject Invalid DID Format");

        let mut conductor = SweetConductor::from_standard_config().await;
        let dna = load_dna().await;
        let app = conductor
            .setup_app("test-app", &[dna.clone()])
            .await
            .unwrap();
        let cell = app.cells()[0].clone();

        let invalid_dids = vec![
            "did:example:12345",
            "invalid:string",
            "did:mycelix",
            "mycelix:12345",
            "DID:MYCELIX:test",
        ];

        for invalid_did in invalid_dids {
            let result: Result<Option<Record>, _> = conductor
                .call_fallible(
                    &cell.zome("did_registry"),
                    "resolve_did",
                    invalid_did.to_string(),
                )
                .await;

            match result {
                Err(_) => println!("  - '{}': Rejected with error", invalid_did),
                Ok(None) => println!("  - '{}': Returned None", invalid_did),
                Ok(Some(_)) => panic!("Should not resolve invalid DID: {}", invalid_did),
            }
        }

        println!("Test 3.1 PASSED");
    }

    #[tokio::test(flavor = "multi_thread")]
    #[ignore]
    async fn test_reject_invalid_agent_key_in_did() {
        println!("Test 3.2: Reject Invalid Agent Key in DID");

        let mut conductor = SweetConductor::from_standard_config().await;
        let dna = load_dna().await;
        let app = conductor
            .setup_app("test-app", &[dna.clone()])
            .await
            .unwrap();
        let cell = app.cells()[0].clone();

        let invalid_did = "did:mycelix:not_a_valid_agent_pub_key";

        let result: Result<Option<Record>, _> = conductor
            .call_fallible(
                &cell.zome("did_registry"),
                "resolve_did",
                invalid_did.to_string(),
            )
            .await;

        match result {
            Err(e) => println!("  - Error (expected): {:?}", e),
            Ok(None) => println!("  - Returned None for invalid agent key"),
            Ok(Some(_)) => panic!("Should not resolve DID with invalid agent key"),
        }

        println!("Test 3.2 PASSED");
    }
}

// ============================================================================
// Section 4: DID Deactivation Tests
// ============================================================================

#[cfg(test)]
mod did_deactivation {
    use super::*;

    #[tokio::test(flavor = "multi_thread")]
    #[ignore]
    async fn test_deactivate_own_did() {
        println!("Test 4.1: Deactivate Own DID");

        let mut conductor = SweetConductor::from_standard_config().await;
        let dna = load_dna().await;
        let app = conductor
            .setup_app("test-app", &[dna.clone()])
            .await
            .unwrap();
        let cell = app.cells()[0].clone();

        let created_record: Record = conductor
            .call(&cell.zome("did_registry"), "create_did", ())
            .await;

        let created_did: DidDocument = decode_entry(&created_record).expect("No entry");

        println!("  - Created DID: {}", created_did.id);

        let deactivation_record: Record = conductor
            .call(
                &cell.zome("did_registry"),
                "deactivate_did",
                "Key compromise suspected".to_string(),
            )
            .await;

        let deactivation: DidDeactivation = decode_entry(&deactivation_record).expect("No entry");

        assert_eq!(deactivation.did, created_did.id);
        assert_eq!(deactivation.reason, "Key compromise suspected");

        println!("Test 4.1 PASSED");
    }

    #[tokio::test(flavor = "multi_thread")]
    #[ignore]
    async fn test_check_did_active_status() {
        println!("Test 4.2: Check DID Active Status");

        let mut conductor = SweetConductor::from_standard_config().await;
        let dna = load_dna().await;
        let app = conductor
            .setup_app("test-app", &[dna.clone()])
            .await
            .unwrap();
        let cell = app.cells()[0].clone();

        let created_record: Record = conductor
            .call(&cell.zome("did_registry"), "create_did", ())
            .await;

        let created_did: DidDocument = decode_entry(&created_record).expect("No entry");

        let is_active_before: bool = conductor
            .call(
                &cell.zome("did_registry"),
                "is_did_active",
                created_did.id.clone(),
            )
            .await;

        assert!(is_active_before, "DID should be active before deactivation");

        println!("Test 4.2 PASSED");
    }

    #[tokio::test(flavor = "multi_thread")]
    #[ignore]
    async fn test_cannot_deactivate_nonexistent_did() {
        println!("Test 4.3: Cannot Deactivate Non-existent DID");

        let mut conductor = SweetConductor::from_standard_config().await;
        let dna = load_dna().await;
        let app = conductor
            .setup_app("test-app", &[dna.clone()])
            .await
            .unwrap();
        let cell = app.cells()[0].clone();

        let result: Result<Record, _> = conductor
            .call_fallible(
                &cell.zome("did_registry"),
                "deactivate_did",
                "Trying to deactivate non-existent DID".to_string(),
            )
            .await;

        assert!(result.is_err(), "Should not be able to deactivate non-existent DID");

        println!("Test 4.3 PASSED");
    }
}

// ============================================================================
// Section 5: DID Update Tests
// ============================================================================

#[cfg(test)]
mod did_updates {
    use super::*;

    #[tokio::test(flavor = "multi_thread")]
    #[ignore]
    async fn test_add_service_endpoint() {
        println!("Test 5.1: Add Service Endpoint");

        let mut conductor = SweetConductor::from_standard_config().await;
        let dna = load_dna().await;
        let app = conductor
            .setup_app("test-app", &[dna.clone()])
            .await
            .unwrap();
        let cell = app.cells()[0].clone();

        let created_record: Record = conductor
            .call(&cell.zome("did_registry"), "create_did", ())
            .await;

        let created_did: DidDocument = decode_entry(&created_record).expect("No entry");

        assert!(created_did.service.is_empty(), "Initial DID should have no services");

        let service = ServiceEndpoint {
            id: format!("{}#messaging", created_did.id),
            type_: "MessagingService".to_string(),
            service_endpoint: "https://messaging.example.com/alice".to_string(),
        };

        let updated_record: Record = conductor
            .call(
                &cell.zome("did_registry"),
                "add_service_endpoint",
                service.clone(),
            )
            .await;

        let updated_did: DidDocument = decode_entry(&updated_record).expect("No entry");

        assert_eq!(updated_did.service.len(), 1, "Should have one service");
        assert_eq!(updated_did.version, 2, "Version should be incremented");

        println!("Test 5.1 PASSED");
    }

    #[tokio::test(flavor = "multi_thread")]
    #[ignore]
    async fn test_remove_service_endpoint() {
        println!("Test 5.2: Remove Service Endpoint");

        let mut conductor = SweetConductor::from_standard_config().await;
        let dna = load_dna().await;
        let app = conductor
            .setup_app("test-app", &[dna.clone()])
            .await
            .unwrap();
        let cell = app.cells()[0].clone();

        let created_record: Record = conductor
            .call(&cell.zome("did_registry"), "create_did", ())
            .await;

        let created_did: DidDocument = decode_entry(&created_record).expect("No entry");

        let service_id = format!("{}#messaging", created_did.id);
        let service = ServiceEndpoint {
            id: service_id.clone(),
            type_: "MessagingService".to_string(),
            service_endpoint: "https://messaging.example.com/alice".to_string(),
        };

        let _: Record = conductor
            .call(
                &cell.zome("did_registry"),
                "add_service_endpoint",
                service,
            )
            .await;

        let removed_record: Record = conductor
            .call(
                &cell.zome("did_registry"),
                "remove_service_endpoint",
                service_id,
            )
            .await;

        let removed_did: DidDocument = decode_entry(&removed_record).expect("No entry");

        assert!(removed_did.service.is_empty(), "Should have no services after removal");
        assert_eq!(removed_did.version, 3, "Version should be 3 after two updates");

        println!("Test 5.2 PASSED");
    }

    #[tokio::test(flavor = "multi_thread")]
    #[ignore]
    async fn test_add_verification_method() {
        println!("Test 5.3: Add Verification Method");

        let mut conductor = SweetConductor::from_standard_config().await;
        let dna = load_dna().await;
        let app = conductor
            .setup_app("test-app", &[dna.clone()])
            .await
            .unwrap();
        let cell = app.cells()[0].clone();

        let created_record: Record = conductor
            .call(&cell.zome("did_registry"), "create_did", ())
            .await;

        let created_did: DidDocument = decode_entry(&created_record).expect("No entry");

        let initial_vm_count = created_did.verification_method.len();

        let new_vm = VerificationMethod {
            id: format!("{}#keys-2", created_did.id),
            type_: "Ed25519VerificationKey2020".to_string(),
            controller: created_did.id.clone(),
            public_key_multibase: "z6MkeXBLjYiSvqnhFb6D7sHm8yKm4jV45wwBFRaatf1cfZ76".to_string(),
            algorithm: None,
        };

        let updated_record: Record = conductor
            .call(
                &cell.zome("did_registry"),
                "add_verification_method",
                new_vm.clone(),
            )
            .await;

        let updated_did: DidDocument = decode_entry(&updated_record).expect("No entry");

        assert_eq!(
            updated_did.verification_method.len(),
            initial_vm_count + 1,
        );

        println!("Test 5.3 PASSED");
    }

    #[tokio::test(flavor = "multi_thread")]
    #[ignore]
    async fn test_version_increments() {
        println!("Test 5.4: Version Increments");

        let mut conductor = SweetConductor::from_standard_config().await;
        let dna = load_dna().await;
        let app = conductor
            .setup_app("test-app", &[dna.clone()])
            .await
            .unwrap();
        let cell = app.cells()[0].clone();

        let created_record: Record = conductor
            .call(&cell.zome("did_registry"), "create_did", ())
            .await;

        let did_v1: DidDocument = decode_entry(&created_record).expect("No entry");

        assert_eq!(did_v1.version, 1);

        let service1 = ServiceEndpoint {
            id: format!("{}#service1", did_v1.id),
            type_: "Service1".to_string(),
            service_endpoint: "https://service1.example.com".to_string(),
        };

        let updated1: Record = conductor
            .call(&cell.zome("did_registry"), "add_service_endpoint", service1)
            .await;

        let did_v2: DidDocument = decode_entry(&updated1).expect("No entry");

        assert_eq!(did_v2.version, 2);

        let service2 = ServiceEndpoint {
            id: format!("{}#service2", did_v1.id),
            type_: "Service2".to_string(),
            service_endpoint: "https://service2.example.com".to_string(),
        };

        let updated2: Record = conductor
            .call(&cell.zome("did_registry"), "add_service_endpoint", service2)
            .await;

        let did_v3: DidDocument = decode_entry(&updated2).expect("No entry");

        assert_eq!(did_v3.version, 3);

        println!("Test 5.4 PASSED");
    }
}

// ============================================================================
// Section 6: Duplicate DID Prevention Tests
// ============================================================================

#[cfg(test)]
mod duplicate_prevention {
    use super::*;

    #[tokio::test(flavor = "multi_thread")]
    #[ignore]
    async fn test_agent_did_management() {
        println!("Test 6.1: Agent DID Management");

        let mut conductor = SweetConductor::from_standard_config().await;
        let dna = load_dna().await;
        let app = conductor
            .setup_app("test-app", &[dna.clone()])
            .await
            .unwrap();
        let cell = app.cells()[0].clone();
        let agent = app.agent().clone();

        let first_record: Record = conductor
            .call(&cell.zome("did_registry"), "create_did", ())
            .await;

        let first_did: DidDocument = decode_entry(&first_record).expect("No entry");

        // Second create_did should fail — agents can only have one DID
        let second_result: Result<Record, _> = conductor
            .call_fallible(&cell.zome("did_registry"), "create_did", ())
            .await;

        assert!(
            second_result.is_err(),
            "Creating a second DID for the same agent should fail"
        );
        let err_msg = format!("{:?}", second_result.unwrap_err());
        assert!(
            err_msg.contains("already has a DID"),
            "Error should mention duplicate DID: {}", err_msg
        );

        let resolved: Option<Record> = conductor
            .call(
                &cell.zome("did_registry"),
                "get_did_document",
                agent,
            )
            .await;

        assert!(resolved.is_some(), "Should resolve agent's DID");

        println!("Test 6.1 PASSED");
    }

    #[tokio::test(flavor = "multi_thread")]
    #[ignore]
    async fn test_did_id_deterministic() {
        println!("Test 6.2: DID ID is Deterministic");

        let mut conductor = SweetConductor::from_standard_config().await;
        let dna = load_dna().await;
        let app = conductor
            .setup_app("test-app", &[dna.clone()])
            .await
            .unwrap();
        let cell = app.cells()[0].clone();
        let agent = app.agent().clone();

        let record: Record = conductor
            .call(&cell.zome("did_registry"), "create_did", ())
            .await;

        let did: DidDocument = decode_entry(&record).expect("No entry");

        let expected_did = format!("did:mycelix:{}", agent);
        assert_eq!(did.id, expected_did, "DID should be deterministic");

        println!("Test 6.2 PASSED");
    }
}

// ============================================================================
// Unit Tests (No Conductor Required)
// ============================================================================

#[cfg(test)]
mod unit_tests {
    use super::*;

    #[test]
    fn test_did_format_validation() {
        assert!(is_valid_mycelix_did("did:mycelix:abc123"));
        assert!(is_valid_mycelix_did("did:mycelix:uhCAk_test_key"));
        assert!(!is_valid_mycelix_did("did:example:abc123"));
        assert!(!is_valid_mycelix_did("not_a_did"));
    }

    #[test]
    fn test_test_did_helper() {
        let did = test_did("alice");
        assert!(did.starts_with("did:mycelix:test:"));
        assert!(did.ends_with("alice"));
    }

    #[test]
    fn test_unique_test_did_helper() {
        let did1 = unique_test_did("user");
        let did2 = unique_test_did("user");
        assert_ne!(did1, did2, "Unique DIDs should be different");
    }

    #[test]
    fn test_verification_method_serialization() {
        let vm = VerificationMethod {
            id: "did:mycelix:test#keys-1".to_string(),
            type_: "Ed25519VerificationKey2020".to_string(),
            controller: "did:mycelix:test".to_string(),
            public_key_multibase: "zABC123".to_string(),
            algorithm: None,
        };

        let json = serde_json::to_string(&vm).expect("Serialize failed");
        let deserialized: VerificationMethod = serde_json::from_str(&json).expect("Deserialize failed");

        assert_eq!(vm.id, deserialized.id);
        assert_eq!(vm.type_, deserialized.type_);
    }

    #[test]
    fn test_service_endpoint_serialization() {
        let service = ServiceEndpoint {
            id: "did:mycelix:test#messaging".to_string(),
            type_: "MessagingService".to_string(),
            service_endpoint: "https://example.com/msg".to_string(),
        };

        let json = serde_json::to_string(&service).expect("Serialize failed");
        let deserialized: ServiceEndpoint = serde_json::from_str(&json).expect("Deserialize failed");

        assert_eq!(service.id, deserialized.id);
    }
}
