[package]
name = "membership"
version = "0.1.0"
edition = "2024"
description = "Housing membership coordinator zome"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
hdk = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
membership_integrity = { path = "../integrity" }
