[target.x86_64-unknown-linux-gnu]
rustflags = ["-C", "link-arg=-fuse-ld=mold"]

[env]
RUST_TEST_THREADS = "8"

[profile.dev]
# "packed" = single .dwp file vs "unpacked" = thousands of .dwo files (~80GB savings)
split-debuginfo = "packed"
