[package]
name = "grid"
version = "0.1.0"
edition = "2024"
license.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]
name = "grid"

[dependencies]
mycelix-bridge-common = { workspace = true }
holochain_serialized_bytes = { workspace = true }
hdk = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
grid_integrity = { path = "../integrity" }
mycelix_energy_shared = { path = "../../shared" }
mycelix-bridge-proc = { path = "../../../../crates/mycelix-bridge-proc" }
mycelix-zome-helpers = { path = "../../../../crates/mycelix-zome-helpers" }
