[package]
name = "verification_coordinator"
version = "0.1.0"
edition = "2021"

[dependencies]
mycelix-zome-helpers = { workspace = true }
hdk.workspace = true
serde.workspace = true
serde_json.workspace = true
verification_integrity = { path = "../integrity" }
claims_integrity = { path = "../../claims/integrity" }

[lib]
crate-type = ["cdylib", "rlib"]
