[package]
name = "purity"
version = "0.1.0"
edition = "2024"
description = "Water quality monitoring coordinator zome"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
hdk = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
purity_integrity = { path = "../integrity" }
