// Copyright (C) 2024-2026 Tristan Stoltz / Luminous Dynamics
// SPDX-License-Identifier: AGPL-3.0-or-later
// Commercial licensing: see COMMERCIAL_LICENSE.md at repository root
//! # Provenance Tagging for Information Source Tracking
//!
//! Tracks the causal origin of information within the cognitive pipeline.
//! Every `StructuredThought` can carry a `ProvenanceTag` indicating whether
//! its content came from perception, memory, reasoning, simulation, or
//! external sources. This enables:
//!
//! - Reality monitoring (PRM): distinguishing observed from imagined
//! - Epistemic gating: simulated content capped at E0 (opinion)
//! - Audit trails: which subsystems contributed to each output
//!
//! Science: Goldman (1986) — reliabilism requires causal connection to
//! truth-makers. Anderson (1983) — source monitoring errors increase
//! with information integration.

use serde::{Deserialize, Serialize};

/// Confidence decay factor when merging provenance from multiple sources.
/// Each merge reduces attribution confidence by 10%.
/// Science: Anderson (1983) — source monitoring accuracy decreases
/// with the number of sources integrated.
pub const PROVENANCE_MERGE_DECAY: f32 = 0.9;

/// Source of information within Symthaea's cognitive pipeline.
///
/// Ordered roughly by "groundedness" — how directly the information
/// connects to external reality.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum InformationSource {
    /// Direct user input (perception phase)
    UserInput,
    /// Retrieved from verified knowledge graph facts
    KnowledgeGraph,
    /// Retrieved from episodic memory (experienced events)
    EpisodicMemory,
    /// Generated by reasoning engine (causal inference, planning)
    ReasoningEngine,
    /// Generated by CfC temporal prediction (forward model)
    CfCPrediction,
    /// Generated by Broca language pipeline
    BrocaGeneration,
    /// Received from external swarm/mesh peer
    SwarmPeer,
    /// From soul/value system (core values, self-assessment)
    SoulAlignment,
    /// Simulated or hypothetical (not grounded in observed data)
    Simulated,
    /// Source unknown or not tracked
    Unknown,
}

impl InformationSource {
    /// Whether this source is grounded in external reality.
    ///
    /// Grounded sources have a causal connection to events outside
    /// the system's own inference processes.
    pub fn is_externally_grounded(&self) -> bool {
        matches!(
            self,
            InformationSource::UserInput
                | InformationSource::KnowledgeGraph
                | InformationSource::SwarmPeer
                | InformationSource::EpisodicMemory
        )
    }

    /// Human-readable name for telemetry.
    pub fn as_str(&self) -> &'static str {
        match self {
            Self::UserInput => "user_input",
            Self::KnowledgeGraph => "knowledge_graph",
            Self::EpisodicMemory => "episodic_memory",
            Self::ReasoningEngine => "reasoning_engine",
            Self::CfCPrediction => "cfc_prediction",
            Self::BrocaGeneration => "broca_generation",
            Self::SwarmPeer => "swarm_peer",
            Self::SoulAlignment => "soul_alignment",
            Self::Simulated => "simulated",
            Self::Unknown => "unknown",
        }
    }
}

impl Default for InformationSource {
    fn default() -> Self {
        Self::Unknown
    }
}

impl std::fmt::Display for InformationSource {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}", self.as_str())
    }
}

/// Provenance tag for a piece of information in the cognitive pipeline.
///
/// Tracks which subsystem(s) produced the information and how confident
/// we are in the attribution. Carried on `StructuredThought` and optionally
/// on `ActivatedConcept`.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ProvenanceTag {
    /// Primary source that produced this information
    pub source: InformationSource,

    /// Secondary sources that contributed (e.g., KnowledgeGraph + ReasoningEngine)
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub contributing_sources: Vec<InformationSource>,

    /// Cycle at which this information was produced
    pub produced_at_cycle: u64,

    /// Confidence in the source attribution (0.0-1.0).
    /// Decays with each merge (PROVENANCE_MERGE_DECAY).
    pub attribution_confidence: f32,

    /// Whether this information is grounded in external reality
    /// (vs. internally generated/inferred).
    pub is_grounded: bool,
}

impl ProvenanceTag {
    /// Create a tag for direct user input.
    pub fn user_input(cycle: u64) -> Self {
        Self {
            source: InformationSource::UserInput,
            contributing_sources: Vec::new(),
            produced_at_cycle: cycle,
            attribution_confidence: 1.0,
            is_grounded: true,
        }
    }

    /// Create a tag for knowledge-graph-retrieved information.
    pub fn from_knowledge(cycle: u64, confidence: f32) -> Self {
        Self {
            source: InformationSource::KnowledgeGraph,
            contributing_sources: Vec::new(),
            produced_at_cycle: cycle,
            attribution_confidence: confidence.clamp(0.0, 1.0),
            is_grounded: true,
        }
    }

    /// Create a tag for episodic memory retrieval.
    pub fn from_episodic(cycle: u64, confidence: f32) -> Self {
        Self {
            source: InformationSource::EpisodicMemory,
            contributing_sources: Vec::new(),
            produced_at_cycle: cycle,
            attribution_confidence: confidence.clamp(0.0, 1.0),
            is_grounded: true,
        }
    }

    /// Create a tag for reasoning-engine-generated content.
    pub fn from_reasoning(cycle: u64, contributing: Vec<InformationSource>) -> Self {
        Self {
            source: InformationSource::ReasoningEngine,
            contributing_sources: contributing,
            produced_at_cycle: cycle,
            attribution_confidence: 0.8,
            is_grounded: false,
        }
    }

    /// Create a tag for CfC temporal prediction.
    pub fn from_prediction(cycle: u64) -> Self {
        Self {
            source: InformationSource::CfCPrediction,
            contributing_sources: Vec::new(),
            produced_at_cycle: cycle,
            attribution_confidence: 0.7,
            is_grounded: false,
        }
    }

    /// Create a tag for Broca language generation.
    pub fn from_broca(cycle: u64, input_provenance: Option<&ProvenanceTag>) -> Self {
        let mut contributing = vec![InformationSource::BrocaGeneration];
        if let Some(input) = input_provenance {
            contributing.push(input.source);
            contributing.extend_from_slice(&input.contributing_sources);
        }
        Self {
            source: InformationSource::BrocaGeneration,
            contributing_sources: contributing,
            produced_at_cycle: cycle,
            attribution_confidence: input_provenance
                .map(|p| p.attribution_confidence * PROVENANCE_MERGE_DECAY)
                .unwrap_or(0.5),
            is_grounded: false,
        }
    }

    /// Create a tag for simulated/hypothetical content.
    pub fn simulated(cycle: u64) -> Self {
        Self {
            source: InformationSource::Simulated,
            contributing_sources: Vec::new(),
            produced_at_cycle: cycle,
            attribution_confidence: 1.0, // we're confident it's simulated
            is_grounded: false,
        }
    }

    /// Merge two provenance tags when information from multiple sources combines.
    ///
    /// The primary source is taken from `self`; the other's sources become
    /// contributing. Attribution confidence decays per Anderson (1983).
    pub fn merge(&self, other: &ProvenanceTag) -> ProvenanceTag {
        let mut contributing = self.contributing_sources.clone();
        contributing.push(other.source);
        contributing.extend_from_slice(&other.contributing_sources);
        // Deduplicate
        contributing.sort_by_key(|s| *s as u8);
        contributing.dedup();

        let merged_confidence = (self.attribution_confidence * PROVENANCE_MERGE_DECAY)
            .min(other.attribution_confidence * PROVENANCE_MERGE_DECAY);

        ProvenanceTag {
            source: self.source,
            contributing_sources: contributing,
            produced_at_cycle: self.produced_at_cycle.max(other.produced_at_cycle),
            attribution_confidence: merged_confidence.clamp(0.0, 1.0),
            is_grounded: self.is_grounded || other.is_grounded,
        }
    }

    /// Whether the primary source is grounded in external reality.
    pub fn is_externally_grounded(&self) -> bool {
        self.source.is_externally_grounded()
    }
}

impl Default for ProvenanceTag {
    fn default() -> Self {
        Self {
            source: InformationSource::Unknown,
            contributing_sources: Vec::new(),
            produced_at_cycle: 0,
            attribution_confidence: 0.0,
            is_grounded: false,
        }
    }
}

// ============================================================================
// Tests
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_user_input_is_grounded() {
        let tag = ProvenanceTag::user_input(100);
        assert!(tag.is_grounded);
        assert!(tag.is_externally_grounded());
        assert_eq!(tag.attribution_confidence, 1.0);
        assert_eq!(tag.source, InformationSource::UserInput);
    }

    #[test]
    fn test_simulated_is_not_grounded() {
        let tag = ProvenanceTag::simulated(200);
        assert!(!tag.is_grounded);
        assert!(!tag.is_externally_grounded());
        assert_eq!(tag.source, InformationSource::Simulated);
    }

    #[test]
    fn test_merge_decays_confidence() {
        let a = ProvenanceTag::user_input(100);
        let b = ProvenanceTag::from_knowledge(100, 0.9);
        let merged = a.merge(&b);

        assert_eq!(merged.source, InformationSource::UserInput);
        assert!(merged.attribution_confidence < 1.0);
        assert!(merged.attribution_confidence <= PROVENANCE_MERGE_DECAY);
        assert!(merged.is_grounded); // either source grounded → merged is grounded
    }

    #[test]
    fn test_merge_collects_contributing_sources() {
        let a = ProvenanceTag::from_reasoning(100, vec![InformationSource::KnowledgeGraph]);
        let b = ProvenanceTag::from_episodic(100, 0.8);
        let merged = a.merge(&b);

        assert!(
            merged
                .contributing_sources
                .contains(&InformationSource::EpisodicMemory)
        );
        assert!(
            merged
                .contributing_sources
                .contains(&InformationSource::KnowledgeGraph)
        );
    }

    #[test]
    fn test_default_is_unknown_and_ungrounded() {
        let tag = ProvenanceTag::default();
        assert_eq!(tag.source, InformationSource::Unknown);
        assert!(!tag.is_grounded);
        assert_eq!(tag.attribution_confidence, 0.0);
    }

    #[test]
    fn test_serde_roundtrip() {
        let tag = ProvenanceTag::from_reasoning(
            42,
            vec![
                InformationSource::KnowledgeGraph,
                InformationSource::EpisodicMemory,
            ],
        );
        let json = serde_json::to_string(&tag).unwrap();
        let restored: ProvenanceTag = serde_json::from_str(&json).unwrap();
        assert_eq!(restored.source, tag.source);
        assert_eq!(
            restored.contributing_sources.len(),
            tag.contributing_sources.len()
        );
        assert_eq!(restored.produced_at_cycle, 42);
    }

    #[test]
    fn test_information_source_display() {
        assert_eq!(InformationSource::UserInput.as_str(), "user_input");
        assert_eq!(InformationSource::Simulated.as_str(), "simulated");
        assert_eq!(InformationSource::Unknown.as_str(), "unknown");
    }

    #[test]
    fn test_broca_provenance_inherits_input() {
        let input = ProvenanceTag::user_input(100);
        let broca = ProvenanceTag::from_broca(101, Some(&input));
        assert_eq!(broca.source, InformationSource::BrocaGeneration);
        assert!(
            broca
                .contributing_sources
                .contains(&InformationSource::UserInput)
        );
        assert!(broca.attribution_confidence < 1.0); // decayed
    }

    #[test]
    fn test_confidence_always_bounded() {
        let tag = ProvenanceTag::from_knowledge(100, 5.0); // out of range
        assert!(tag.attribution_confidence <= 1.0);
        assert!(tag.attribution_confidence >= 0.0);

        let tag2 = ProvenanceTag::from_knowledge(100, -1.0); // out of range
        assert!(tag2.attribution_confidence >= 0.0);
    }
}
