"""Type stubs for zk_tax Python bindings."""

from enum import IntEnum
from typing import List, Tuple

class Jurisdiction(IntEnum):
    """Tax jurisdiction (country)."""
    US = ...
    UK = ...
    DE = ...
    FR = ...
    CA = ...
    AU = ...
    JP = ...
    CN = ...
    IN = ...
    BR = ...
    MX = ...
    KR = ...
    IT = ...
    RU = ...
    TR = ...
    AR = ...
    ID = ...
    SA = ...
    ZA = ...
    CL = ...
    CO = ...
    PE = ...
    EC = ...
    UY = ...
    ES = ...
    NL = ...
    BE = ...
    AT = ...
    PT = ...
    IE = ...
    PL = ...
    SE = ...
    DK = ...
    FI = ...
    NO = ...
    CH = ...
    CZ = ...
    GR = ...
    HU = ...
    RO = ...
    UA = ...
    NZ = ...
    SG = ...
    HK = ...
    TW = ...
    MY = ...
    TH = ...
    VN = ...
    PH = ...
    PK = ...
    AE = ...
    IL = ...
    EG = ...
    QA = ...
    NG = ...
    KE = ...
    MA = ...
    GH = ...

class FilingStatus(IntEnum):
    """Tax filing status."""
    SINGLE = ...
    MARRIED_FILING_JOINTLY = ...
    MARRIED_FILING_SEPARATELY = ...
    HEAD_OF_HOUSEHOLD = ...

class TaxBracket:
    """A tax bracket with rate and bounds."""

    @property
    def index(self) -> int:
        """Bracket index (0-based)."""
        ...

    @property
    def rate_bps(self) -> int:
        """Marginal tax rate in basis points (e.g., 2200 = 22%)."""
        ...

    @property
    def rate_percent(self) -> float:
        """Tax rate as a percentage (e.g., 22.0 for 22%)."""
        ...

    @property
    def lower(self) -> int:
        """Lower bound of the bracket (inclusive)."""
        ...

    @property
    def upper(self) -> int:
        """Upper bound of the bracket (exclusive)."""
        ...

    def contains(self, income: int) -> bool:
        """Check if an income falls within this bracket."""
        ...

class TaxBracketProof:
    """A zero-knowledge proof of tax bracket membership."""

    @property
    def jurisdiction(self) -> Jurisdiction:
        """The jurisdiction this proof is for."""
        ...

    @property
    def filing_status(self) -> FilingStatus:
        """The filing status used."""
        ...

    @property
    def tax_year(self) -> int:
        """The tax year."""
        ...

    @property
    def bracket_index(self) -> int:
        """The bracket index (0-based)."""
        ...

    @property
    def rate_bps(self) -> int:
        """The marginal tax rate in basis points."""
        ...

    @property
    def rate_percent(self) -> float:
        """The tax rate as a percentage."""
        ...

    @property
    def bracket_lower(self) -> int:
        """Lower bound of the bracket."""
        ...

    @property
    def bracket_upper(self) -> int:
        """Upper bound of the bracket."""
        ...

    @property
    def commitment(self) -> str:
        """The cryptographic commitment (hex string)."""
        ...

    def verify(self) -> bool:
        """Verify this proof. Returns True if valid, raises ValueError if invalid."""
        ...

    def to_json(self) -> str:
        """Serialize to JSON string."""
        ...

    @staticmethod
    def from_json(json: str) -> "TaxBracketProof":
        """Deserialize from JSON string."""
        ...

def find_bracket(
    income: int,
    jurisdiction: Jurisdiction,
    year: int,
    filing_status: FilingStatus,
) -> TaxBracket:
    """Find the tax bracket for a given income.

    Args:
        income: Annual income in the jurisdiction's currency
        jurisdiction: Tax jurisdiction (country)
        year: Tax year (2020-2025)
        filing_status: Filing status

    Returns:
        TaxBracket for the given income

    Raises:
        ValueError: If jurisdiction/year/status combination is unsupported
    """
    ...

def get_brackets(
    jurisdiction: Jurisdiction,
    year: int,
    filing_status: FilingStatus,
) -> List[TaxBracket]:
    """Get all tax brackets for a jurisdiction.

    Args:
        jurisdiction: Tax jurisdiction (country)
        year: Tax year (2020-2025)
        filing_status: Filing status

    Returns:
        List of TaxBracket objects, sorted by lower bound

    Raises:
        ValueError: If jurisdiction/year/status combination is unsupported
    """
    ...

def list_jurisdictions() -> List[Tuple[str, str]]:
    """List all supported jurisdictions.

    Returns:
        List of (code, name) tuples for all supported jurisdictions
    """
    ...

def version() -> str:
    """Get the SDK version."""
    ...
