[package]
name = "cases"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]
name = "cases"

[dependencies]
getrandom.workspace = true
getrandom_03.workspace = true
hdk.workspace = true
holochain_zome_types.workspace = true
holochain_integrity_types.workspace = true
holo_hash.workspace = true
hdk_derive.workspace = true
serde.workspace = true
serde_json.workspace = true
mycelix_justice_integrity.workspace = true
