use symthaea_quantum_comp::{
    ExperimentManifest, ExperimentProtocol, ResearchArtifactReceipt, RunEnvironment,
    SubstrateProfile,
};

fn main() {
    let manifest = ExperimentManifest::local_simulation(
        "alpha6-local-receipt-demo",
        ExperimentProtocol::NoiseSweep,
        0xA16A_0006,
        256,
        8,
        SubstrateProfile::quantum_inspired(),
    );
    let environment = RunEnvironment::local_unknown();
    let report_text = "placeholder report body generated by a local alpha.6 run";
    let receipt = ResearchArtifactReceipt::from_manifest_report_and_environment(
        &manifest,
        report_text,
        &environment,
        Some("local-researcher".to_string()),
    );
    println!("{}", receipt.to_text());
}
