[package]
name = "credit_scoring"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "rlib"]
name = "credit_scoring"

[dependencies]
getrandom = { workspace = true }
getrandom_03 = { workspace = true }
holochain_serialized_bytes = { workspace = true }
hdk = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
credit_scoring_integrity = { path = "../integrity" }
mycelix_finance_shared = { path = "../../shared" }
