// Copyright (C) 2024-2026 Tristan Stoltz / Luminous Dynamics
// SPDX-License-Identifier: AGPL-3.0-or-later

use symthaea_core::double_integrator_reachability::{
    BoundedDoubleIntegrator1D, DoubleIntegratorQuery1D,
    DoubleIntegratorReachabilityResult1D, DoubleIntegratorState1D,
    MAX_DOUBLE_INTEGRATOR_REPLAY_SEGMENTS, TimedAccelerationSegment1D,
    TimedAccelerationTrajectory1D, replay_double_integrator_trajectory,
    solve_double_integrator_analytic,
};
use symthaea_core::kinodynamic_reachability::{
    ControlInterval1D, DynamicsReplayPolicy1D, KinodynamicError, PlantTimeProfile,
};
use symthaea_core::reachability::UnknownReason;

fn state(position: f64, velocity: f64) -> DoubleIntegratorState1D {
    DoubleIntegratorState1D::new(position, velocity).unwrap()
}

#[test]
fn raw_feasible_witness_replays_when_canonical_switch_reconstruction_is_ambiguous() {
    // This exact finite-arithmetic fixture sits on the lower conditional-position
    // boundary. The target is raw-feasible and is generated by a valid two-phase
    // control history, but reconstructing the canonical switch from the terminal
    // state produces a switch time about 5e-17 s later than the latest legal
    // switch. The solver must therefore abstain rather than clamp, while replay of
    // the independently supplied dynamics-valid witness must still succeed.
    let u_min = -0.04089868460418858;
    let u_max = 0.029701791047250306;
    let horizon = 0.30438845531035996;
    let switch = 0.056754525799264016;

    let model = BoundedDoubleIntegrator1D::new(
        ControlInterval1D::new(u_min, u_max).unwrap(),
    );
    let initial = state(0.0017813097996452144, -0.09248954988286343);
    let intermediate = state(-0.0035337596351124054, -0.09481073533338781);
    let target = state(-0.026101419608531944, -0.08745556410283972);
    let query = DoubleIntegratorQuery1D::new(
        &model,
        initial,
        target,
        PlantTimeProfile::new(horizon).unwrap(),
        DynamicsReplayPolicy1D::reference_v1(),
    );

    assert!(matches!(
        solve_double_integrator_analytic(&model, &query).unwrap(),
        DoubleIntegratorReachabilityResult1D::Unknown {
            reason: UnknownReason::NumericalFailure,
            ..
        }
    ));

    let trajectory = TimedAccelerationTrajectory1D::new(
        &model,
        &query,
        vec![
            TimedAccelerationSegment1D::new(
                0.0,
                switch,
                u_min,
                initial,
                intermediate,
            ),
            TimedAccelerationSegment1D::new(
                switch,
                horizon,
                u_max,
                intermediate,
                target,
            ),
        ],
    )
    .unwrap();

    let replay = replay_double_integrator_trajectory(&model, &query, &trajectory).unwrap();
    assert_eq!(replay.segment_count(), 2);
    assert_eq!(replay.final_state(), target);
    assert!(
        replay.maximum_position_residual()
            <= query.replay_policy().absolute_state_tolerance()
    );
    assert!(
        replay.maximum_velocity_residual()
            <= query.replay_policy().absolute_state_tolerance()
    );
}

#[test]
fn replay_rejects_sub_tolerance_drift_accumulation_across_segments() {
    let model = BoundedDoubleIntegrator1D::new(
        ControlInterval1D::new(-1.0, 1.0).unwrap(),
    );
    let policy = DynamicsReplayPolicy1D::reference_v1();
    let step = 0.5 * policy.absolute_state_tolerance();
    let segment_count = 128_usize;
    let horizon = 2.0_f64;
    let dt = horizon / segment_count as f64;

    let mut declared_target_position = 0.0_f64;
    for _ in 0..segment_count {
        declared_target_position += step;
    }
    let query = DoubleIntegratorQuery1D::new(
        &model,
        state(0.0, 0.0),
        state(declared_target_position, 0.0),
        PlantTimeProfile::new(horizon).unwrap(),
        policy,
    );

    let mut segments = Vec::with_capacity(segment_count);
    let mut declared_position = 0.0_f64;
    for index in 0..segment_count {
        let next_position = declared_position + step;
        segments.push(TimedAccelerationSegment1D::new(
            index as f64 * dt,
            (index + 1) as f64 * dt,
            0.0,
            state(declared_position, 0.0),
            state(next_position, 0.0),
        ));
        declared_position = next_position;
    }
    let trajectory = TimedAccelerationTrajectory1D::new(&model, &query, segments).unwrap();

    // A verifier that restarts integration from every declared segment start would
    // accept each local half-tolerance position jump and eventually accept the
    // fabricated terminal displacement. Global replay must keep its own state at x=0.
    assert!(matches!(
        replay_double_integrator_trajectory(&model, &query, &trajectory),
        Err(KinodynamicError::InvalidTrajectory { .. })
    ));
}

#[test]
fn trajectory_segment_budget_fails_closed() {
    let model = BoundedDoubleIntegrator1D::new(
        ControlInterval1D::new(-1.0, 1.0).unwrap(),
    );
    let query = DoubleIntegratorQuery1D::new(
        &model,
        state(0.0, 0.0),
        state(0.0, 0.0),
        PlantTimeProfile::new(2.0).unwrap(),
        DynamicsReplayPolicy1D::reference_v1(),
    );
    let segment = TimedAccelerationSegment1D::new(
        0.0,
        2.0,
        0.0,
        state(0.0, 0.0),
        state(0.0, 0.0),
    );

    assert!(matches!(
        TimedAccelerationTrajectory1D::new(
            &model,
            &query,
            vec![segment; MAX_DOUBLE_INTEGRATOR_REPLAY_SEGMENTS + 1],
        ),
        Err(KinodynamicError::InvalidTrajectory { .. })
    ));
}
