[package]
name = "legacy_probate_integrity"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]
name = "legacy_probate_integrity"

[dependencies]
hdi = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
holochain_serialized_bytes = { workspace = true }
legacy-types = { workspace = true }
