// Copyright (C) 2024-2026 Tristan Stoltz / Luminous Dynamics
// SPDX-License-Identifier: AGPL-3.0-or-later

//! Finite groups represented by a Cayley (multiplication) table over elements
//! `0..n`, with the constructions for cyclic (`Zₙ`) and symmetric (`Sₙ`) groups.

use crate::permutation::Permutation;
use std::collections::HashMap;

/// A finite group given by its Cayley table: `table[a][b] = a · b`.
#[derive(Debug, Clone)]
pub struct CayleyGroup {
    table: Vec<Vec<usize>>,
}

impl CayleyGroup {
    /// Build from a Cayley table, checking it is a Latin square (each row and
    /// column is a permutation of `0..n` — the group cancellation law).
    pub fn from_table(table: Vec<Vec<usize>>) -> Result<CayleyGroup, String> {
        let n = table.len();
        if n == 0 || table.iter().any(|r| r.len() != n) {
            return Err("table must be square and non-empty".to_string());
        }
        for i in 0..n {
            let mut row_seen = vec![false; n];
            let mut col_seen = vec![false; n];
            for j in 0..n {
                let (r, c) = (table[i][j], table[j][i]);
                if r >= n || c >= n || row_seen[r] || col_seen[c] {
                    return Err("not a Latin square (cancellation fails)".to_string());
                }
                row_seen[r] = true;
                col_seen[c] = true;
            }
        }
        Ok(CayleyGroup { table })
    }

    /// The group order (number of elements).
    pub fn order(&self) -> usize {
        self.table.len()
    }

    /// The product `a · b`.
    pub fn op(&self, a: usize, b: usize) -> usize {
        self.table[a][b]
    }

    /// The identity element `e` (the `e` with `e·x = x` for all `x`).
    pub fn identity(&self) -> usize {
        let n = self.order();
        (0..n)
            .find(|&e| (0..n).all(|x| self.table[e][x] == x))
            .expect("a valid group has an identity")
    }

    /// The inverse of `a`, if it exists.
    pub fn inverse(&self, a: usize) -> Option<usize> {
        let e = self.identity();
        (0..self.order()).find(|&b| self.op(a, b) == e)
    }

    /// The order of an element: the least `k ≥ 1` with `a^k = e`.
    pub fn element_order(&self, a: usize) -> usize {
        let e = self.identity();
        let mut x = a;
        let mut k = 1;
        while x != e {
            x = self.op(x, a);
            k += 1;
        }
        k
    }

    /// The cyclic subgroup generated by `a` (its distinct powers), ascending.
    pub fn subgroup_generated(&self, a: usize) -> Vec<usize> {
        let e = self.identity();
        let mut set = vec![e];
        let mut x = a;
        while x != e {
            set.push(x);
            x = self.op(x, a);
        }
        set.sort_unstable();
        set.dedup();
        set
    }

    /// Whether the group is abelian (commutative): the table is symmetric.
    pub fn is_abelian(&self) -> bool {
        let n = self.order();
        (0..n).all(|a| (0..n).all(|b| self.table[a][b] == self.table[b][a]))
    }

    /// A direct check of Lagrange's theorem's consequence: every element's order
    /// divides the group order.
    pub fn lagrange_holds(&self) -> bool {
        let n = self.order();
        (0..n).all(|a| n % self.element_order(a) == 0)
    }

    /// The cyclic group `Zₙ` under addition mod `n`.
    pub fn cyclic(n: usize) -> CayleyGroup {
        let table = (0..n)
            .map(|a| (0..n).map(|b| (a + b) % n).collect())
            .collect();
        CayleyGroup { table }
    }

    /// The symmetric group `Sₙ` (all permutations of `n` points under
    /// composition). `n!` elements, so keep `n` small.
    pub fn symmetric(n: usize) -> CayleyGroup {
        let perms = all_permutations(n);
        let index: HashMap<Permutation, usize> = perms
            .iter()
            .enumerate()
            .map(|(i, p)| (p.clone(), i))
            .collect();
        let table = perms
            .iter()
            .map(|a| perms.iter().map(|b| index[&a.compose(b)]).collect())
            .collect();
        CayleyGroup { table }
    }
}

/// Every permutation of `0..n`, in lexicographic order.
fn all_permutations(n: usize) -> Vec<Permutation> {
    let mut result = Vec::new();
    let mut cur: Vec<usize> = (0..n).collect();
    permute(&mut cur, 0, &mut result);
    result
}

fn permute(cur: &mut Vec<usize>, k: usize, out: &mut Vec<Permutation>) {
    if k == cur.len() {
        out.push(Permutation::from_one_line(cur.clone()).unwrap());
        return;
    }
    for i in k..cur.len() {
        cur.swap(k, i);
        permute(cur, k + 1, out);
        cur.swap(k, i);
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn cyclic_group_structure() {
        let z6 = CayleyGroup::cyclic(6);
        assert_eq!(z6.order(), 6);
        assert_eq!(z6.identity(), 0);
        assert!(z6.is_abelian());
        // Element 2 has order 3 (2+2+2 = 0 mod 6); 1 generates the whole group.
        assert_eq!(z6.element_order(2), 3);
        assert_eq!(z6.element_order(1), 6);
        // ⟨2⟩ = {0, 2, 4}.
        assert_eq!(z6.subgroup_generated(2), vec![0, 2, 4]);
        assert!(z6.lagrange_holds());
    }

    #[test]
    fn symmetric_group_s3_is_nonabelian() {
        let s3 = CayleyGroup::symmetric(3);
        assert_eq!(s3.order(), 6);
        assert!(!s3.is_abelian());
        assert!(s3.lagrange_holds());
        // S3 has elements of order 1, 2, and 3 only.
        let orders: std::collections::BTreeSet<usize> =
            (0..6).map(|a| s3.element_order(a)).collect();
        assert_eq!(orders, [1, 2, 3].into_iter().collect());
        // Every element has an inverse.
        assert!((0..6).all(|a| s3.inverse(a).is_some()));
    }

    #[test]
    fn latin_square_validation() {
        // Z3 table is a valid group.
        assert!(CayleyGroup::from_table(vec![vec![0, 1, 2], vec![1, 2, 0], vec![2, 0, 1]]).is_ok());
        // A non-Latin-square is rejected.
        assert!(CayleyGroup::from_table(vec![vec![0, 0], vec![1, 1]]).is_err());
    }
}
