// Copyright (C) 2024-2026 Tristan Stoltz / Luminous Dynamics
// SPDX-License-Identifier: AGPL-3.0-or-later
// Commercial licensing: see COMMERCIAL_LICENSE.md at repository root
//! Cortical Activation Map — per-region activation tracking for neural validation.
//!
//! Provides explicit per-region activation vectors that can be compared against
//! external neuroscience ground-truth (e.g., TRIBE v2 fMRI predictions from Meta FAIR).
//!
//! Each cognitive cycle produces a `CorticalActivationMap` with normalized [0,1]
//! activation levels for each of the 12 `CorticalRegion` variants. These maps
//! can then be compared via cosine similarity, Pearson correlation, or rank
//! correlation against externally predicted or observed fMRI activation patterns.
//!
//! # References
//!
//! - Glasser et al. (2016). A multi-modal parcellation of human cerebral cortex.
//!   *Nature*, 536, 171-178. doi:10.1038/nature18933
//! - TRIBE v2 (Meta FAIR, 2026). Tri-modal brain encoding for fMRI prediction.

use serde::{Deserialize, Serialize};
use std::collections::HashMap;

use super::substrate_independence::CorticalRegion;

/// Source of the activation data.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum ActivationSource {
    /// Generated by Symthaea's cognitive loop (simulated dynamics).
    Simulated,
    /// Predicted by an external brain encoding model (e.g., TRIBE v2).
    FmriPredicted,
    /// Observed from actual fMRI recordings.
    FmriObserved,
    /// Observed from EEG recordings.
    EegObserved,
}

/// Per-region activation snapshot from a single cognitive cycle or time window.
///
/// Activations are normalized to [0.0, 1.0] where 0 = baseline and 1 = maximal
/// activation for that region.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CorticalActivationMap {
    /// Normalized activation level per region.
    pub activations: HashMap<CorticalRegion, f32>,
    /// Cycle number (for simulated) or time index (for fMRI).
    pub timestamp_cycles: u64,
    /// Where this data came from.
    pub source: ActivationSource,
    /// Optional stimulus identifier for cross-system comparison.
    pub stimulus_id: Option<String>,
}

impl CorticalActivationMap {
    /// Create a new activation map with all regions at zero.
    pub fn zeros(source: ActivationSource, timestamp_cycles: u64) -> Self {
        let activations = CorticalRegion::ALL.iter().map(|r| (*r, 0.0)).collect();
        Self {
            activations,
            timestamp_cycles,
            source,
            stimulus_id: None,
        }
    }

    /// Create from a pre-built hashmap.
    pub fn from_map(
        activations: HashMap<CorticalRegion, f32>,
        source: ActivationSource,
        timestamp_cycles: u64,
    ) -> Self {
        Self {
            activations,
            timestamp_cycles,
            source,
            stimulus_id: None,
        }
    }

    /// Set a region's activation level, clamping to [0, 1].
    pub fn set(&mut self, region: CorticalRegion, value: f32) {
        self.activations.insert(region, value.clamp(0.0, 1.0));
    }

    /// Get a region's activation (0.0 if absent).
    pub fn get(&self, region: CorticalRegion) -> f32 {
        self.activations.get(&region).copied().unwrap_or(0.0)
    }

    /// Convert to a 12-element vector in `CorticalRegion::ALL` order.
    pub fn to_vec(&self) -> Vec<f32> {
        CorticalRegion::ALL.iter().map(|r| self.get(*r)).collect()
    }

    /// Cosine similarity with another activation map.
    ///
    /// Returns a value in [-1, 1] (though typically [0, 1] since activations
    /// are non-negative). Returns 0.0 if either vector is zero.
    pub fn cosine_similarity(&self, other: &Self) -> f64 {
        let a = self.to_vec();
        let b = other.to_vec();

        let dot: f64 = a
            .iter()
            .zip(b.iter())
            .map(|(x, y)| *x as f64 * *y as f64)
            .sum();
        let mag_a: f64 = a.iter().map(|x| (*x as f64).powi(2)).sum::<f64>().sqrt();
        let mag_b: f64 = b.iter().map(|x| (*x as f64).powi(2)).sum::<f64>().sqrt();

        if mag_a < 1e-12 || mag_b < 1e-12 {
            return 0.0;
        }
        dot / (mag_a * mag_b)
    }

    /// Pearson correlation with another activation map.
    ///
    /// Returns r in [-1, 1]. Returns 0.0 if either has zero variance.
    pub fn pearson_correlation(&self, other: &Self) -> f64 {
        let a = self.to_vec();
        let b = other.to_vec();
        let n = a.len() as f64;

        let mean_a: f64 = a.iter().map(|x| *x as f64).sum::<f64>() / n;
        let mean_b: f64 = b.iter().map(|x| *x as f64).sum::<f64>() / n;

        let mut cov = 0.0;
        let mut var_a = 0.0;
        let mut var_b = 0.0;
        for (x, y) in a.iter().zip(b.iter()) {
            let da = *x as f64 - mean_a;
            let db = *y as f64 - mean_b;
            cov += da * db;
            var_a += da * da;
            var_b += db * db;
        }

        let denom = (var_a * var_b).sqrt();
        if denom < 1e-12 {
            return 0.0;
        }
        cov / denom
    }

    /// Spearman rank correlation with another activation map.
    ///
    /// Converts activations to ranks, then computes Pearson on ranks.
    pub fn spearman_rank_correlation(&self, other: &Self) -> f64 {
        let ranks_a = to_ranks(&self.to_vec());
        let ranks_b = to_ranks(&other.to_vec());
        pearson_on_ranks(&ranks_a, &ranks_b)
    }

    /// Per-region absolute difference (useful for identifying which regions
    /// diverge most between simulated and predicted).
    pub fn per_region_difference(&self, other: &Self) -> HashMap<CorticalRegion, f32> {
        CorticalRegion::ALL
            .iter()
            .map(|r| (*r, (self.get(*r) - other.get(*r)).abs()))
            .collect()
    }
}

/// Timeseries of cortical activations (for HRF convolution and temporal analysis).
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CorticalActivationTimeseries {
    /// Ordered sequence of activation maps.
    pub maps: Vec<CorticalActivationMap>,
    /// Sample rate in Hz (e.g., 31.0 for Symthaea's cognitive loop).
    pub sample_rate_hz: f32,
}

impl CorticalActivationTimeseries {
    pub fn new(sample_rate_hz: f32) -> Self {
        Self {
            maps: Vec::new(),
            sample_rate_hz,
        }
    }

    pub fn push(&mut self, map: CorticalActivationMap) {
        self.maps.push(map);
    }

    /// Extract a single region's timeseries as a Vec<f32>.
    pub fn region_timeseries(&self, region: CorticalRegion) -> Vec<f32> {
        self.maps.iter().map(|m| m.get(region)).collect()
    }

    /// Duration in seconds.
    pub fn duration_secs(&self) -> f32 {
        if self.sample_rate_hz <= 0.0 || self.maps.is_empty() {
            return 0.0;
        }
        self.maps.len() as f32 / self.sample_rate_hz
    }
}

// ============================================================================
// EEG Power Spectrum (for EEG temporal validation)
// ============================================================================

/// EEG frequency bands with standard clinical ranges.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum EegBand {
    /// Delta: 0.5-4 Hz (deep sleep, unconscious processing)
    Delta,
    /// Theta: 4-8 Hz (memory encoding, drowsiness)
    Theta,
    /// Alpha: 8-13 Hz (relaxed wakefulness, visual cortex idle)
    Alpha,
    /// Beta: 13-30 Hz (active thinking, focus, motor planning)
    Beta,
    /// Gamma: 30-100 Hz (consciousness binding, attention, perception)
    Gamma,
}

impl EegBand {
    pub const ALL: [EegBand; 5] = [
        EegBand::Delta,
        EegBand::Theta,
        EegBand::Alpha,
        EegBand::Beta,
        EegBand::Gamma,
    ];

    pub fn as_str(&self) -> &'static str {
        match self {
            EegBand::Delta => "delta",
            EegBand::Theta => "theta",
            EegBand::Alpha => "alpha",
            EegBand::Beta => "beta",
            EegBand::Gamma => "gamma",
        }
    }

    /// Frequency range in Hz.
    pub fn range_hz(&self) -> (f32, f32) {
        match self {
            EegBand::Delta => (0.5, 4.0),
            EegBand::Theta => (4.0, 8.0),
            EegBand::Alpha => (8.0, 13.0),
            EegBand::Beta => (13.0, 30.0),
            EegBand::Gamma => (30.0, 100.0),
        }
    }
}

/// Per-region EEG power spectrum snapshot.
///
/// Maps each CorticalRegion × EegBand to a power value (μV²/Hz).
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EegPowerMap {
    /// Power per region per band.
    pub powers: HashMap<CorticalRegion, HashMap<EegBand, f32>>,
    /// Timestamp (cycle number or milliseconds).
    pub timestamp: u64,
    /// Source of the data.
    pub source: ActivationSource,
}

impl EegPowerMap {
    /// Create with all bands at zero for all regions.
    pub fn zeros(source: ActivationSource, timestamp: u64) -> Self {
        let powers = CorticalRegion::ALL
            .iter()
            .map(|r| {
                let bands: HashMap<EegBand, f32> = EegBand::ALL.iter().map(|b| (*b, 0.0)).collect();
                (*r, bands)
            })
            .collect();
        Self {
            powers,
            timestamp,
            source,
        }
    }

    /// Set power for a specific region and band.
    pub fn set(&mut self, region: CorticalRegion, band: EegBand, value: f32) {
        self.powers
            .entry(region)
            .or_default()
            .insert(band, value.max(0.0));
    }

    /// Get power for a specific region and band.
    pub fn get(&self, region: CorticalRegion, band: EegBand) -> f32 {
        self.powers
            .get(&region)
            .and_then(|m| m.get(&band))
            .copied()
            .unwrap_or(0.0)
    }

    /// Get total power across all bands for a region.
    pub fn total_power(&self, region: CorticalRegion) -> f32 {
        self.powers
            .get(&region)
            .map(|m| m.values().sum())
            .unwrap_or(0.0)
    }

    /// Compute correlation of band power profiles between two EEG maps.
    /// Flattens all (region, band) pairs into a vector, computes Pearson r.
    pub fn correlation(&self, other: &Self) -> f64 {
        let mut a = Vec::new();
        let mut b = Vec::new();
        for region in CorticalRegion::ALL {
            for band in EegBand::ALL {
                a.push(self.get(region, band) as f64);
                b.push(other.get(region, band) as f64);
            }
        }
        pearson_f64(&a, &b)
    }
}

/// Simulated EEG power from cortical activations.
///
/// Maps activation levels to plausible EEG band powers based on
/// neuroscience priors (e.g., high visual activation → high gamma in Visual).
pub fn activations_to_eeg(map: &CorticalActivationMap) -> EegPowerMap {
    let mut eeg = EegPowerMap::zeros(map.source, map.timestamp_cycles);

    for region in CorticalRegion::ALL {
        let activation = map.get(region) as f64;

        // Base power distribution (resting state, eyes open).
        // Alpha dominant, beta moderate, gamma low.
        let delta_base = 0.3;
        let theta_base = 0.2;
        let alpha_base = 0.5;
        let beta_base = 0.3;
        let gamma_base = 0.1;

        // Activation modulates: ↑activation → ↑beta/gamma, ↓alpha (desynchronization).
        // This is the standard ERD/ERS pattern (Pfurtscheller & Lopes da Silva 1999).
        let alpha = (alpha_base * (1.0 - 0.6 * activation)).max(0.05) as f32;
        let beta = (beta_base + 0.4 * activation) as f32;
        let gamma = (gamma_base + 0.5 * activation) as f32;
        let theta = (theta_base + 0.15 * activation) as f32;
        let delta = (delta_base * (1.0 - 0.3 * activation)).max(0.1) as f32;

        eeg.set(region, EegBand::Delta, delta);
        eeg.set(region, EegBand::Theta, theta);
        eeg.set(region, EegBand::Alpha, alpha);
        eeg.set(region, EegBand::Beta, beta);
        eeg.set(region, EegBand::Gamma, gamma);
    }

    eeg
}

/// Pearson correlation on f64 slices.
pub fn pearson_f64(a: &[f64], b: &[f64]) -> f64 {
    let n = a.len() as f64;
    if n < 2.0 {
        return 0.0;
    }
    let mean_a: f64 = a.iter().sum::<f64>() / n;
    let mean_b: f64 = b.iter().sum::<f64>() / n;
    let mut cov = 0.0;
    let mut var_a = 0.0;
    let mut var_b = 0.0;
    for (x, y) in a.iter().zip(b.iter()) {
        let da = x - mean_a;
        let db = y - mean_b;
        cov += da * db;
        var_a += da * da;
        var_b += db * db;
    }
    let denom = (var_a * var_b).sqrt();
    if denom < 1e-12 {
        return 0.0;
    }
    cov / denom
}

// ============================================================================
// Internal helpers
// ============================================================================

/// Convert values to fractional ranks (1-based, averaged for ties).
fn to_ranks(values: &[f32]) -> Vec<f64> {
    let n = values.len();
    let mut indexed: Vec<(usize, f32)> = values.iter().copied().enumerate().collect();
    indexed.sort_by(|a, b| a.1.partial_cmp(&b.1).unwrap_or(std::cmp::Ordering::Equal));

    let mut ranks = vec![0.0f64; n];
    let mut i = 0;
    while i < n {
        let mut j = i;
        // Find extent of tied values.
        while j < n && (indexed[j].1 - indexed[i].1).abs() < 1e-10 {
            j += 1;
        }
        // Average rank for tied group.
        let avg_rank = (i + j + 1) as f64 / 2.0; // 1-based midpoint
        for item in indexed.iter().take(j).skip(i) {
            ranks[item.0] = avg_rank;
        }
        i = j;
    }
    ranks
}

/// Pearson correlation on pre-computed rank vectors.
fn pearson_on_ranks(a: &[f64], b: &[f64]) -> f64 {
    let n = a.len() as f64;
    let mean_a: f64 = a.iter().sum::<f64>() / n;
    let mean_b: f64 = b.iter().sum::<f64>() / n;

    let mut cov = 0.0;
    let mut var_a = 0.0;
    let mut var_b = 0.0;
    for (x, y) in a.iter().zip(b.iter()) {
        let da = x - mean_a;
        let db = y - mean_b;
        cov += da * db;
        var_a += da * da;
        var_b += db * db;
    }

    let denom = (var_a * var_b).sqrt();
    if denom < 1e-12 {
        return 0.0;
    }
    cov / denom
}

// ============================================================================
// Tests
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_zeros_map() {
        let map = CorticalActivationMap::zeros(ActivationSource::Simulated, 0);
        assert_eq!(map.activations.len(), 12);
        for r in CorticalRegion::ALL {
            assert_eq!(map.get(r), 0.0);
        }
    }

    #[test]
    fn test_set_clamps() {
        let mut map = CorticalActivationMap::zeros(ActivationSource::Simulated, 0);
        map.set(CorticalRegion::Visual, 1.5);
        assert_eq!(map.get(CorticalRegion::Visual), 1.0);
        map.set(CorticalRegion::Motor, -0.3);
        assert_eq!(map.get(CorticalRegion::Motor), 0.0);
    }

    #[test]
    fn test_to_vec_order() {
        let mut map = CorticalActivationMap::zeros(ActivationSource::Simulated, 0);
        map.set(CorticalRegion::Prefrontal, 0.9);
        map.set(CorticalRegion::Integration, 0.1);
        let v = map.to_vec();
        assert_eq!(v.len(), 12);
        assert_eq!(v[0], 0.9); // Prefrontal is first in ALL
        assert_eq!(v[11], 0.1); // Integration is last in ALL
    }

    #[test]
    fn test_cosine_identical() {
        let mut a = CorticalActivationMap::zeros(ActivationSource::Simulated, 0);
        a.set(CorticalRegion::Visual, 0.8);
        a.set(CorticalRegion::Auditory, 0.4);
        let b = a.clone();
        let sim = a.cosine_similarity(&b);
        assert!(
            (sim - 1.0).abs() < 1e-6,
            "identical maps should have cosine=1, got {sim}"
        );
    }

    #[test]
    fn test_cosine_orthogonal() {
        let mut a = CorticalActivationMap::zeros(ActivationSource::Simulated, 0);
        a.set(CorticalRegion::Visual, 1.0);
        let mut b = CorticalActivationMap::zeros(ActivationSource::FmriPredicted, 0);
        b.set(CorticalRegion::Auditory, 1.0);
        let sim = a.cosine_similarity(&b);
        assert!(
            sim.abs() < 1e-6,
            "orthogonal maps should have cosine=0, got {sim}"
        );
    }

    #[test]
    fn test_cosine_zero_vector() {
        let a = CorticalActivationMap::zeros(ActivationSource::Simulated, 0);
        let mut b = CorticalActivationMap::zeros(ActivationSource::FmriPredicted, 0);
        b.set(CorticalRegion::Visual, 0.5);
        assert_eq!(a.cosine_similarity(&b), 0.0);
    }

    #[test]
    fn test_pearson_perfect() {
        let mut a = CorticalActivationMap::zeros(ActivationSource::Simulated, 0);
        let mut b = CorticalActivationMap::zeros(ActivationSource::FmriPredicted, 0);
        // Set matching pattern: a and b have same rank order with linear scaling
        // that stays within [0, 1] (set() clamps).
        for (i, r) in CorticalRegion::ALL.iter().enumerate() {
            let v = (i as f32 + 1.0) / 24.0; // max = 0.5
            a.set(*r, v);
            b.set(*r, v * 2.0); // max = 1.0, still within clamp range
        }
        let r = a.pearson_correlation(&b);
        assert!(
            (r - 1.0).abs() < 1e-6,
            "perfectly correlated should give r=1, got {r}"
        );
    }

    #[test]
    fn test_pearson_anti_correlated() {
        let mut a = CorticalActivationMap::zeros(ActivationSource::Simulated, 0);
        let mut b = CorticalActivationMap::zeros(ActivationSource::FmriPredicted, 0);
        for (i, r) in CorticalRegion::ALL.iter().enumerate() {
            a.set(*r, (i as f32 + 1.0) / 12.0);
            b.set(*r, 1.0 - (i as f32 + 1.0) / 12.0);
        }
        let r = a.pearson_correlation(&b);
        assert!(
            (r - (-1.0)).abs() < 1e-6,
            "anti-correlated should give r=-1, got {r}"
        );
    }

    #[test]
    fn test_spearman_rank() {
        let mut a = CorticalActivationMap::zeros(ActivationSource::Simulated, 0);
        let mut b = CorticalActivationMap::zeros(ActivationSource::FmriPredicted, 0);
        // Same rank order but different magnitudes.
        for (i, r) in CorticalRegion::ALL.iter().enumerate() {
            a.set(*r, (i as f32 + 1.0) / 12.0);
            b.set(*r, ((i as f32 + 1.0) / 12.0).powi(2));
        }
        let rho = a.spearman_rank_correlation(&b);
        assert!(
            (rho - 1.0).abs() < 1e-6,
            "same rank order should give rho=1, got {rho}"
        );
    }

    #[test]
    fn test_per_region_difference() {
        let mut a = CorticalActivationMap::zeros(ActivationSource::Simulated, 0);
        let mut b = CorticalActivationMap::zeros(ActivationSource::FmriPredicted, 0);
        a.set(CorticalRegion::Visual, 0.8);
        b.set(CorticalRegion::Visual, 0.3);
        let diff = a.per_region_difference(&b);
        assert!((diff[&CorticalRegion::Visual] - 0.5).abs() < 1e-6);
        assert!((diff[&CorticalRegion::Motor] - 0.0).abs() < 1e-6);
    }

    #[test]
    fn test_timeseries_region_extraction() {
        let mut ts = CorticalActivationTimeseries::new(31.0);
        for i in 0..5 {
            let mut map = CorticalActivationMap::zeros(ActivationSource::Simulated, i);
            map.set(CorticalRegion::Visual, i as f32 * 0.1);
            ts.push(map);
        }
        let visual_ts = ts.region_timeseries(CorticalRegion::Visual);
        assert_eq!(visual_ts, vec![0.0, 0.1, 0.2, 0.3, 0.4]);
    }

    #[test]
    fn test_timeseries_duration() {
        let mut ts = CorticalActivationTimeseries::new(31.0);
        for i in 0..62 {
            ts.push(CorticalActivationMap::zeros(ActivationSource::Simulated, i));
        }
        assert!((ts.duration_secs() - 2.0).abs() < 0.01);
    }

    #[test]
    fn test_ranks_with_ties() {
        let ranks = to_ranks(&[0.5, 0.3, 0.5, 0.1]);
        // Sorted: 0.1(idx3)=rank1, 0.3(idx1)=rank2, 0.5(idx0,2)=rank3.5
        assert!((ranks[3] - 1.0).abs() < 1e-6);
        assert!((ranks[1] - 2.0).abs() < 1e-6);
        assert!((ranks[0] - 3.5).abs() < 1e-6);
        assert!((ranks[2] - 3.5).abs() < 1e-6);
    }

    // ── EEG tests ──

    #[test]
    fn test_eeg_zeros() {
        let eeg = EegPowerMap::zeros(ActivationSource::Simulated, 0);
        for region in CorticalRegion::ALL {
            for band in EegBand::ALL {
                assert_eq!(eeg.get(region, band), 0.0);
            }
        }
    }

    #[test]
    fn test_eeg_set_get() {
        let mut eeg = EegPowerMap::zeros(ActivationSource::Simulated, 0);
        eeg.set(CorticalRegion::Visual, EegBand::Gamma, 0.8);
        assert!((eeg.get(CorticalRegion::Visual, EegBand::Gamma) - 0.8).abs() < 1e-6);
        assert_eq!(eeg.get(CorticalRegion::Visual, EegBand::Alpha), 0.0);
    }

    #[test]
    fn test_eeg_total_power() {
        let mut eeg = EegPowerMap::zeros(ActivationSource::Simulated, 0);
        eeg.set(CorticalRegion::Visual, EegBand::Alpha, 0.5);
        eeg.set(CorticalRegion::Visual, EegBand::Gamma, 0.3);
        let total = eeg.total_power(CorticalRegion::Visual);
        assert!((total - 0.8).abs() < 1e-6);
    }

    #[test]
    fn test_eeg_correlation_identical() {
        let mut eeg = EegPowerMap::zeros(ActivationSource::Simulated, 0);
        eeg.set(CorticalRegion::Visual, EegBand::Gamma, 0.8);
        eeg.set(CorticalRegion::Auditory, EegBand::Alpha, 0.5);
        let r = eeg.correlation(&eeg);
        assert!((r - 1.0).abs() < 1e-6);
    }

    #[test]
    fn test_activations_to_eeg_desynchronization() {
        // High visual activation → alpha should decrease (ERD), gamma should increase (ERS).
        let mut low = CorticalActivationMap::zeros(ActivationSource::Simulated, 0);
        low.set(CorticalRegion::Visual, 0.1);
        let mut high = CorticalActivationMap::zeros(ActivationSource::Simulated, 1);
        high.set(CorticalRegion::Visual, 0.9);

        let eeg_low = activations_to_eeg(&low);
        let eeg_high = activations_to_eeg(&high);

        // Alpha should decrease with activation (ERD).
        assert!(
            eeg_high.get(CorticalRegion::Visual, EegBand::Alpha)
                < eeg_low.get(CorticalRegion::Visual, EegBand::Alpha),
            "Alpha should decrease with activation (event-related desynchronization)"
        );
        // Gamma should increase with activation (ERS).
        assert!(
            eeg_high.get(CorticalRegion::Visual, EegBand::Gamma)
                > eeg_low.get(CorticalRegion::Visual, EegBand::Gamma),
            "Gamma should increase with activation (event-related synchronization)"
        );
    }

    #[test]
    fn test_eeg_band_ranges() {
        assert_eq!(EegBand::Alpha.range_hz(), (8.0, 13.0));
        assert_eq!(EegBand::Gamma.range_hz(), (30.0, 100.0));
        assert_eq!(EegBand::ALL.len(), 5);
    }
}
